### ISSUE TITLE
Clean up remaining tests

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#101]
@crisptrutski it would be great to get the unit tests cleaned up like the manual ones as I've done if possible.

For any jspm dependencies used in the process, rather set up a separate package.json for jspm installs within the test folder itself, instead of sharing the package.json of builder.

Apologies for anything I've broken with the recent PR!

**Comment by crisptrutski** [comment]
@guybedford so they're running again, and didn't introduce a new `package.json` or anything. 

Not exactly "clean", but enough to close this?
