### ISSUE TITLE
Build just necessary runtime for Babel

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#106]
In https://github.com/systemjs/builder/blob/master/lib/compile.js#L103 we can rather generate just the Babel runtime needed.

This can be done using http://babeljs.io/docs/usage/external-helpers/#selective-builds, and adding the used helpers to the `output` object during compilation, and managing the reduction of that `externalHelpers` option through the pipeline in https://github.com/systemjs/builder/blob/master/lib/output.js#L53.

**Comment by sebmck** [comment]
I've made some recent `runtime` transformer changes that I've detailed [here](https://github.com/babel/ember-cli-babel/issues/24#issuecomment-77698781) which might be sufficient.

**Comment by guybedford** [comment]
@sebmck thanks so much for letting me know. In that case it is time to start treating Babel and Traceur as actual packages in jspm to manage this.

Would it be possible to confirm that the output will stay as `babel-runtime` (the package name will have to be hardcoded into jspm)? I thought you were calling it `babel-helpers` and have hardcoded this currently.

**Comment by guybedford** [comment]
I've made the adjustments to move towards package-based loaders. So the direction this is going is to align with the self-contained style output rather, which is being tracked in https://github.com/systemjs/builder/issues/55.

**Comment by sebmck** [comment]
@guybedford Yeah it'll stay as `babel-runtime` and if it ever changes (I doubt it) it'll happen in a major. The runtime transformer (used to be called `selfContained`) has gone under a lot of churn and it's finally in a stable state after I've gotten a lot of feedback.
