### ISSUE TITLE
Multiple entry points for SFX bundles

### ISSUE THREAD

**Issue by Shepless** [systemjs/builder#108]
Firstly, I'd like to thank you for all of the work and effort you have put into this project. JSPM is new to me so I'm still learning, so apologies of this is already do-able and is not a valid question.

I am trying to create two separate bundles - core.js and vendors.js. Core has a dependency on vendors and I am using the subtract tree functionality in my gulp build task as follows:

```js
builder.trace('core')
            .then(function(coreTrace) {
                return builder.trace('vendors').then(function (vendorsTrace) {
                    return builder.subtractTrees(coreTrace.tree, vendorsTrace.tree)
                });
            })
            .then(function(coreMinusVendorsTrace) {
                return builder.buildSFX(coreMinusVendorsTrace, './.build/core.min.js', {
                    minify: true,
                    sourceMaps: true
                }).then(function () {
                    cb();
                }).catch(function (e) {
                    cb(e);
                });
            });
```

The issue I am facing is that the ```buildSFX()``` method only seems to accept a string and not a trace so the builder throws the following exception:

```
Potentially unhandled rejection [1] TypeError: Object #<Object> has no method 'indexOf'
```

Is it possible to split bundles and run them through ```buildSFX()```? If so how is this achieved as I have looked through the docs and source but can't see how. Also I would ask if this is even best practice? Should I perhaps be looking at a different approach? Essentially, I don't want one huge, monolithic JavaScript file that takes a long time to download as the web page is solely aimed at mobile browsers and would prefer to break them up so they are concurrent requests.

Any help is greatly appreciated, thanks.

**Comment by guybedford** [comment]
Thanks. Yes `buildSFX` is designed to represent a single execution thread and not layered bundles.

Currently the way to support layered bundles is to include SystemJS in production and use normal bundles.

This is a feature though that a lot of users have requested and we're considering support for it.

**Comment by guybedford** [comment]
Implemented in https://github.com/systemjs/builder/commit/cf68c92059ab9f2c9df9f4ca318fe3b59d9673f9.

**Comment by Shepless** [comment]
Thanks @guybedford

**Comment by AlicanC** [comment]
@guybedford, let's say I build my `vendors.js` with:
```
builder.build('./app/main.js - [./app/**/*]', outDir + 'vendor.js');
```
Since I can't subtract in `buildSFX()`, how are we supposed make this work?

**Comment by guybedford** [comment]
@AlicanC you can use normal bundles, including the SystemJS loader in production. Alternatively use stub modules to sub out dependencies like in https://github.com/systemjs/builder#adapter-modules.

In future sfx bundles will likely support custom dependency definitions as if they were their own modules.
