### ISSUE TITLE
Test uglify dead_code removal option

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#116]
This is the `compress.dead_code` option.

**Comment by guybedford** [comment]
Actually we may as well always turn this on for all bundles?

**Comment by jannisg** [comment]
I think turning this on by default makes sense.

Please also ensure there is a way to set the `global_defs: {}` options (see [here](http://lisperator.net/uglifyjs/compress)) to setup the triggers for `dead_code` removal using `if (DEBUG) { … }`.
