### ISSUE TITLE
Building css

### ISSUE THREAD

**Issue by whitecolor** [systemjs/builder#12]
Is it possible to get outfile.css for css moudles as for js? (and shared css modules as well)

**Comment by martinmicunda** [comment]
+1

**Comment by katrotz** [comment]
Only today bumped into "**SystemJS Builder - Plugin for "..." does not support sfx builds**".

Just checking whether is there a plan to support it in the near future?

**Comment by douglasduteil** [comment]
@guybedford  just a little question.
Do you think that the builder must inline all it can by default ?
So if you import a css in a script (`import 'my/style.css!'`) the content of the file will be inlined  and added by the css plugin on the head tag at run time ?

**Comment by guybedford** [comment]
@katrotz the implementations need to be plugin-specific. SFX support for the CSS plugin can certainly be added.

**Comment by guybedford** [comment]
@douglasduteil there are two styles of inlining - inlining the CSS in the JS file and injecting into the head, or to create a separate CSS file to go alongside the bundle file of JS.

**Comment by djindjic** [comment]
@guybedford @douglasduteil I'm not sure is it directly related to bundling, but can be.
I have had a problem to System.import some package before some others. System.import(...).then is called after js files of first package is loaded but styles continues to load async with second package. Concretely, I want to load all of angular material (scripts and styles) to show page layout before rest of app is loaded.

**Comment by guybedford** [comment]
@djindjic to clarify - you are loading a package which depends on CSS, and then after that importing another package. You then bundling the first package, and load it from the bundle, but the CSS isn't loaded by the time the System.import for that package has finished? Can you share a test project for this at all?

**Comment by djindjic** [comment]
I'm outdoor so I have made few commits from my phone, but I think this is right example. Something like [this](https://github.com/djindjic/jspm-sample.tk/blob/master/www/index.html#L25). You can try http://jspm-samle.tk (deployed by travis, is that awesome? :-D), I don't have dev tool right now but it was same situation as I have described above. All except angular material are bundled together but material is loaded just before it. Material css in not garanted to be loaded before bundle?

**Comment by guybedford** [comment]
Angular material depends on angular, which is loaded from the bundle, which then also contains app. Thus angular-material is always loading last.

**Comment by djindjic** [comment]
Hmmm ok, but, hypothetically, if I make two bundels with jspm arithmetics and load angular+ang-material first, will material css be loaded before app's bundle?

**Comment by guybedford** [comment]
Yes, if you have included app in a separate bundle. Note that trying to ensure css order is not a good idea. Rather use CSS specificity - https://github.com/guybedford/require-css/#modular-css.

**Comment by djindjic** [comment]
I think I don't understand last advice. I mean, its ok to override css by more specific identifier, but how this is related with css files/bundles loading order? Basically, I am looking for some optimization of page first load. Maybe I could mock and inline all needed classes (as google page insights recommend) to show initial screen before real css is loaded, but its seems a little messy for me at this moment.

**Comment by guybedford** [comment]
Right, ok my point on CSS was irrelevant then. Rather you just need to create a bundle that has a minimal dependency graph. The point is though that if your application code is dependent on angular and angular-material, then there's no way to have a minimal page load less than that - you need to design your dependency tree from the beginning around the minimal page load if this is what you're after (this is not importing angular or angular material in the bootstrapper code).

**Comment by jamiewinder** [comment]
On the subject of css inlining, I wrote such a plugin a few weeks ago which does this:
https://github.com/jamiewinder/systemjs-plugins/blob/master/css-inline.js

Admittedly I've not actually used or throughly tested this, but it's there if anyone is interested. There is also a pair of Handlebars loaders in the same repo.

**Comment by guybedford** [comment]
Thanks - yes this is the approach we'll be using in the css plugin!

**Comment by guybedford** [comment]
This is now working on SystemJS builder master, against the builder branch of the CSS plugin -https://github.com/systemjs/plugin-css/tree/builder. Release to follow this week!

**Comment by guybedford** [comment]
I've described the feature for those interested in https://github.com/systemjs/plugin-css/pull/6. Docs will follow on release.

**Comment by andreasgrimm** [comment]
@guybedford awesome!! .. can't wait to test it :)

@djindjic maybe you wanna take a look into my angular-jspm example app (https://github.com/ng-next/ng-next-example) how I got around the problem to override angular-material styles (admittedly depending on css load order).

(In https://github.com/ng-next/ng-next-example/blob/master/front/main/bootstrap.js) I'm bootstrapping like this:
```javascript
System.import( 'main' )
.then( function () {
  System.import( 'app.css!' );
})
.catch( console.error.bind( console ));
```

**Comment by andreasgrimm** [comment]
@guybedford in https://github.com/guybedford/require-css/#modular-css it says "Reset and global styles are a repeated dependency of all modular styles that build on top of them". Does that mean that every module that imports `my-module.css!` (which overrides/refines e.g. `angular-material.css`) should import `angular-material/angular-material.css!` as well?

**Comment by guybedford** [comment]
@andreasgrimm yes, you should never use globals and always import angular wherever it is used. You may get sporadic builder issues otherwise. For material the same idea applies, including for the material CSS dependency.

**Comment by guybedford** [comment]
Published in SystemJS Builder 0.7.3, plugin-css@0.1.1.

**Comment by guybedford** [comment]
Note this also needs npm@0.18.3.

**Comment by amcdnl** [comment]
Off topic but - @andreasgrimm you might be interested in https://github.com/amcdnl/systemjs-test build system ... similar to yours but automatic bundling based on deps

**Comment by andreasgrimm** [comment]
Thanks @amcdnl for mentioning your project. I'll try to take a deeper look soon.

**Comment by whitecolor** [comment]
Can you advice how to require node `less` module in system less plugin for builder?

```javascript
var less = require('less');
````
requires systemjs `less` plugin not node, little bit confused, how the whole stuff works.

**Comment by guybedford** [comment]
@whitecolor I've posted https://github.com/jspm/registry/issues/221 on the registry to trouble shoot working out whether to load from GitHub or npm and the exact override to use.
