### ISSUE TITLE
system-builder mistakenly attributes rx.all.js to System.register format

### ISSUE THREAD

**Issue by rkirov** [systemjs/builder#123]
See for the repo setup
https://gist.github.com/rkirov/946312ee958dc12f8718

In the output file `build.js` first line is `"format register"`. Moreover the bundle is broken because due to the wrong wrapping there are errors thrown (`this` is expected to be non-undefined).

**Comment by robwormald** [comment]
few more details:
- we're using the systemjs/builder tool here, pulling from npm (not jspm) installed rx (npm install rx)
- attempting to use https://github.com/Reactive-Extensions/RxJS/blob/master/dist/rx.all.js

**Comment by guybedford** [comment]
You can try running `rx` as a different module format and skipping the auto-detection.

The way to do this would be with meta config:

```javascript
new Builder({
  meta: {
    'rx/dist/rx.all': {
      format: 'amd' // or try global
    }
  }
});
```

The format interpretations are described more clearly at https://github.com/systemjs/systemjs/wiki/Module-Format-Support.

Let me know if you need more help with it at all.

**Comment by rkirov** [comment]
Thanks @guybedford, that works for us with both `format cjs` and `format global`. The auto-detected format actually is `format amd`; that is different than what I initially thought, but still broken. 

You can close the issue unless you want to track that detection issue. I am not sure if it is trully issue with auto-detection of `rx.js` UMD implementation.
