### ISSUE TITLE
compileLoad API

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#126]
For separate file builds, it would be useful to have the ability to compile files individually.

`builder.compileFile` or something like that.

**Comment by origin1tech** [comment]
Per conversation on #135 

The rub with Gulp and the single file output is handling it in the flow of how gulp works as you know. wrestled with that w/ traceur. 

Off the top of my head somehow you have to be aware of the tree (or whatever the resolved imports are called, I believe its tree for systemjs-builder) or you'll have issues concatenating. That said it this might be best tackled in two stages.

First solve the single compile task then a method etc for use within a gulp pipe. May be simple as returning the output with the entire tree on the first file or something like that. what I mean is the output object becomes.

    var output = { source: 'the compiled source', sourceMap: 'the sourcemap', tree: 'the built up tree' }

Again speaking out loud here haven't dug enough into the source yet but at first blush those are my thoughts.

Anyway any thoughts on that let me know.

**Comment by guybedford** [comment]
The key option for a single-file compile is whether the file should be "anonymous" or "named". Anonymous can be used for individual file compilation, while named is what is used to construct bundles.

In both cases I don't think the tree is important as an output?

An example API might be:

```javascript
builder.compileModule('unnormalizedModuleName' [, outFile], options).then(function(output) {
  output.source, output.sourceMap
});
```

where `options.namedModule` is set to default as false.

It may also be useful to allow a custom load record to be input in place of the unnormalized module name allowing for workflows like:

```javascript
builder.trace('some/module')
.then(function(tree) {
  return builder.compileModule(tree.anotherModule, 'outbundle.js', { namedModule: true })
});
```

**Comment by origin1tech** [comment]
Ok I see. Check back in a day or two and I'll have this in the works.
