### ISSUE TITLE
Bundling only the contents of a directory subtree

### ISSUE THREAD

**Issue by jamiewinder** [systemjs/builder#133]
I have what I assume is a pretty atypical scenario, and I'm not sure it's supported at the moment. 

I basically want to bundle together the entire contents of a subtree, but without bundling the dependencies of those files. For example, if a module in there depends on a module that isn't in this subtree, it won't be in the bundle. If another module is defined in a file, but isn't referenced anywhere, it will still be included. 

I think there are two ways I can approach this - either have the builder convert each file to the System.register format and then just concatenate the files, or somehow configure the builder to follow this logic. Are either of these feasible?

**Comment by guybedford** [comment]
There is syntax to build a module without its dependencies - `builder.build('[app]')` will bundle just the module app without any of its dependencies. `builder.build('[app/**/*]')` will build every module in the app folder, and none of their dependencies outside of that folder.

**Comment by jamiewinder** [comment]
Absolutely perfect! I must have missed this somewhere. Thanks, Guy.

**Comment by guybedford** [comment]
Sure, thanks for the feedback. It's not actually documented, still experimenting to see how useful it is.

**Comment by jamiewinder** [comment]
Well certainly in my case, it's absolutely invaluable! Please don't remove it! :)  Thanks again.

**Comment by guilhermeaiolfi** [comment]
Nice, good feature :+1: . It should be definitely documented somewhere, even if is experimental. Just put a note saying so.

**Comment by guilhermeaiolfi** [comment]
So, I was experimenting with it and it includes just .js as it seems. How to include .jsx or .ract(my case) that uses plugins to translate the code?

I tried those cmds too:
```
bundle [app/**/*] + app/**/* dist/app.js // includes everything even dependencies outside app/
bundle [app/**/*] + app/**/*.ract dist/app.js // doesn't included the .ract files at all
```

**Comment by guybedford** [comment]
Something like `bundle app/**/* + app/**/*.ract!` would bundle everything.

**Comment by guilhermeaiolfi** [comment]
After trying a lot of combinations, that's what worked for me:

```
     bundle [app/**/*] + [app/**/*.EXTENSION!PLUGIN_NAME]
```

**Comment by guybedford** [comment]
Thanks, I've documented this now.
