### ISSUE TITLE
.build & .buildSFX support options object as second arg.

### ISSUE THREAD

**Issue by origin1tech** [systemjs/builder#135]
Would be nice to support the options object as the second arg as opposed to 

    builder.build('app/app', null, {/* my options */}

This is helpful when you only want to return the "output" so as to access the source and sourceMap properties of the output object.

Primary reason would be for tasks within gulp allowing file to be pushed and ultimately writing using gulp.dest.

Let me know if I'm missing anything here and yes I get this is somewhat trivial, happy to create a PR.

**Comment by guybedford** [comment]
We should already support this I believe.

**Comment by origin1tech** [comment]
getting an error looks as though (haven't peeked at source) its calling path.resolve on that arguments as its giving me that sort of error.

sent u a tweet earlier please ignore (different issue).

**Comment by guybedford** [comment]
Sure that check is actually supposed to be happening for both bundle and bundleSFX. A PR would be welcome.

**Comment by origin1tech** [comment]
k, I'll do that also may be able to take a crack at issue #126 as well if u wish. May be useful for gulp I'm thinking.

**Comment by guybedford** [comment]
Sure, that's a good point, and would be great. Please do them as separate PRs if you can. Ah right, you mentioned Gulp on Twitter - there's nothing out there, would definitely be very useful and can be added to the SystemJS & jspm wikis.

**Comment by origin1tech** [comment]
I'll do that (sep PR's). I'll do the first above fix tomorrow (2 am here...I'm spent). The other in a few days.

**Comment by origin1tech** [comment]
Is this done? just getting to it this am as well as other issue we discussed.

**Comment by guybedford** [comment]
No work has been done here yet, feel free to take it on.

**Comment by origin1tech** [comment]
k doing it right now this is easy one be just a min or two.

**Comment by origin1tech** [comment]
done, u should see PR.

**Comment by crisptrutski** [comment]
Thanks @origin1tech!
