### ISSUE TITLE
Sourcemap fixtures are brittle

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#136]
Patch updates in Babel or Traceur can cause these to break, which is not ideal.

**Comment by guybedford** [comment]
Perhaps this could be due to the differences of newlines between Windows and Mac, if the expectation is including them.

**Comment by crisptrutski** [comment]
Not sure I'm looking at the right error - I see 
```
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    ... long stack not containing anything related to source maps or their tests...
```

Can dig into this later today.

**Comment by crisptrutski** [comment]
Ran quickly and getting different results to you - perhaps symlinks or stale npm modules in the mix?

**Comment by guybedford** [comment]
I've got a checked-out version of Traceur at exactly the 0.0.87 tag. It may be due to a transitive dependency of Traceur, will try updating its dependencies.

**Comment by crisptrutski** [comment]
Still failing after my update, but the source map diff is very small and localized. Perhaps we've found the case to scrap "acceptance" map tests.

**Comment by guybedford** [comment]
I updated Traceur's dependencies and am still getting the same issue unfortunately. Sounds like it could be the case.

**Comment by crisptrutski** [comment]
Diff if you're curious https://gist.github.com/crisptrutski/73d079bcf0695b054505

**Comment by guybedford** [comment]
Lazy fix included in https://github.com/systemjs/builder/commit/25c2d1970209655360e25135274acd48945faa59.
