### ISSUE TITLE
Dynamic import prefetched in bundle

### ISSUE THREAD

**Issue by circlingthesun** [systemjs/builder#137]
I'm using a library which does a conditional import of ```xmlhttprequest``` if it detects the code is being run via node. In jspm I need to remove the ```xmlhttprequest``` dependency via an override the to avoid issues. In the build config I set ```meta["xmlhttprequest"] = {"build": false}``` so that the builder does not attempt to include the library. However when I load the bundle an attempt is made to prefetch ```xmlhttprequest``` despite the conditional import never executing. This results in an unhandled exception. I'm currently working around this by replacing ```["xmlhttprequest"]``` with ```[""]``` after the bundle is built. Is there a better way to avoid this issue?

**Comment by guybedford** [comment]
A good method here is to map the module to `@empty`, which can also be added into the override for the library too so the fix can be general.

```json
map: {
  'xmlhttprequest': '@empty'
}
```

**Comment by circlingthesun** [comment]
Awesome! Works like a charm :+1:  Thanks :)
