### ISSUE TITLE
Unable to build the simplest possible aurelia app as bundleSFX

### ISSUE THREAD

**Issue by capaj** [systemjs/builder#144]
Hi, I have [this](https://gist.github.com/capaj/cd2c27e5a87c672760e3) little script I just put together to package my simplest possible aurelia app.

My package.json looks like:
```
  "jspm": {
    "directories": {
      "baseURL": "public",
      "dist": "built"
    },
    "dependencies": {
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.11.0",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.6.0",
      "aurelia-framework": "github:aurelia/framework@^0.10.0"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.0.12",
      "babel-runtime": "npm:babel-runtime@^5.0.12",
      "core-js": "npm:core-js@^0.8.1"
    }
  }
```

My index.html looks like:
```html
<!doctype html>
<html>
<head>
	<title>Aurelia asteroids</title>
</head>
<body aurelia-app>
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>

<script>
	System.import('aurelia-bootstrapper').catch(console.error.bind(console));
</script>
</body>
</html>
```

Now when I run the script, it outputs:
```
packages aurelia-bootstrapper + aurelia-dependency-injection + aurelia-framework + core-js + github:aurelia/binding@0.5.0 + github:aurelia/bootstrapper@0.11.0 + github:aurelia/dependency-injection@0.6.0 + github:aurelia/framework@0.10.0 + github:aurelia/history-browser@0.3.0 + github:aurelia/loader-default@0.6.0 + github:aurelia/loader@0.5.0 + github:aurelia/metadata@0.4.0 + github:aurelia/route-recognizer@0.3.0 + github:aurelia/router@0.7.2 + github:aurelia/templating-binding@0.10.0 + github:aurelia/templating-resources@0.10.0 + github:aurelia/templating-router@0.11.0 + github:aurelia/templating@0.10.3 + github:jspm/nodelibs-process@0.1.1 + npm:core-js@0.8.3
done
```

That is all fine and dandy. When running my app, I have just 14 requests instead of 200+. Size and time to DOMcontentloaded is still the same, because it still has to transpile.

Now I wanted to take it a step further by using bundleSFX instead of bundle method on the builder.
And I wasn't able to make that work. Does inject option work for bundleSFX as well as for bundle?

From the API I got the feeling that these two methods should really be mutually exchangeable-I expected that if it works with bundle, it should work with bundleSFX as well.

Could you give me some advice, how I could use bundleSFX to package my app?

**Comment by guybedford** [comment]
Aurelia uses dynamic `System.import` statements internally which needs the full loader present in production to work. SFX bundles only apply to code that does not call the dynamic `System.import` require.

Bundling does transpile ES6 to ES5 though fine - are you sure you are seeing untranspiled ES6 in your bundle?

**Comment by capaj** [comment]
@guybedford right, I knew that Aurelia uses `System.import`, but I did not realise, that it is not included when you do SFX bundle.

I may have got that wrong. I just assumed, because the time to run the app stayed constant(around 2s).

So in order to have a good packaging(get rid of the Babel(1.5MB)/traceur(1.2MB) transpiler) pipeline for aurelia apps, one will have to bundle all the app resources as well. Then any `System.import()` should resolve from the already bundled and transpiled resource. Is that right?

**Comment by guybedford** [comment]
Yes exactly, in future tooling to better capture bundles from these System.imports is planned.

**Comment by capaj** [comment]
@guybedford awesome, I think we can close it for now. I still wasn't able to build and run it with buildSFX, but regular build is good enough packagin of my apps. I don't really mind two other request for systemjs and config.js.
I got the aurelia hello world app from 2.3MB/216 request/4.34s to 628KB/8 requests/2.2s. That is good enough for me to use [Aurelia](console.log('packages', packages);
) in production.

**Comment by dredzone** [comment]
Any plans in a near future to capture System.import when using bundle-sfx?

**Comment by guybedford** [comment]
@dredzone not this is not planned. Rather the inclusion of a separate System loader allows SFX code to dynamically import.
