### ISSUE TITLE
systemjs-builder fails when using system-json

### ISSUE THREAD

**Issue by mntnoe** [systemjs/builder#145]
When importing json-files using the system-json plugin, the builder fails with the following error message:

    Error: Unknown format json
        at /.../node_modules/systemjs-builder/lib/compile.js:32:13
        at lib$rsvp$$internal$$tryCatch (/.../node_modules/rsvp/dist/rsvp.js:489:16)
        at lib$rsvp$$internal$$invokeCallback (/.../node_modules/rsvp/dist/rsvp.js:501:17)
        at /.../node_modules/rsvp/dist/rsvp.js:1095:13
        at lib$rsvp$asap$$flush (/.../node_modules/rsvp/dist/rsvp.js:1290:9)
        at process._tickDomainCallback (node.js:381:11)

I've made a quick workaround by "converting" the module to CommonJS as follows:

    // compile.js:15
    function compileLoad(loader, load, opts, compilers) {
      return Promise.resolve()
        .then(function() {
          var format = load.metadata.format;
          if (format === 'json') { format = 'cjs'; load.source = 'module.exports = ' + load.source + ';'}
          // ...

I'm not sure about the best approach to fix this. Perhaps system-json could can be made aware that the output is supposed to be bundled, or we could add a compiler for json.

Let me know what you think,
Mads

**Comment by guybedford** [comment]
@mntnoe which json plugin are you using?

**Comment by mntnoe** [comment]
The one obtained by `npm install system-json`. Are there alternatives?

**Comment by guybedford** [comment]
Yeah this one will build in SystemJS builder - https://github.com/systemjs/plugin-json/blob/master/json.js.

**Comment by mntnoe** [comment]
Ok, thank you. Is it available on npm?

**Comment by mntnoe** [comment]
$ npm install systemjs/plugin-json
    npm ERR! addLocal Could not install /tmp/npm-13070-8989395e/git-cache-b9e720062f4a/476c01034237dfec4dec8c94a59e3bd0750bdf03
    npm ERR! addLocal Could not install /tmp/npm-13070-8989395e/git-cache-2f579c377675/476c01034237dfec4dec8c94a59e3bd0750bdf03
    npm ERR! Linux 3.13.0-49-generic
    npm ERR! argv "/home/mntnoe/.local/bin/node" "/home/mntnoe/.local/bin/npm" "install" "systemjs/plugin-json"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1

    npm ERR! No name provided in package.json
