### ISSUE TITLE
Including bundles in bundles

### ISSUE THREAD

**Issue by guilhermeaiolfi** [systemjs/builder#146]
Hi,

sorry if that's a dumb question but I couldn't find nowhere the answer for it. So, I created I library using systemjs-builder and it outputs a file using ```System.register```. 

This library/file is consumed by my project. But when I try to create a bundle for my project that includes this library bundle I get:

```
err  Source file: lib/flx.js is contained in a bundle. Ensure that bundle configuration is disabled before bundling. If this really is a valid use case, please post an issue to github.com/systemjs/builder.
```

That's reasonable and it's solvable by including my library using ```jspm install my_library```. But what if I want to create simple file to others to use without SystemJS. Systemjs-builder doesn't seem to support outputting it to other formats and using buildSFX seems overkill filesize-wise.

What should I do here?

Thanks

**Comment by guybedford** [comment]
@guilhermeaiolfi it would help to understand the use case a little better. Am I right in thinking you're creating a bundle, and then installing and loading that bundle via `jspm install`?

If so, is there a reason you need to distribute the bundle at all in the first place? Can you not just install your package as separate files?

**Comment by guilhermeaiolfi** [comment]
At the moment I'm getting the bundle file built and copying it to my
project lib folder.

I'm starting to think I would need a different tool for creating the
distributable files.

I mean, it works if I install via jspm install. But it would be nice to
consume it without it.
Em 18/04/2015 19:35, "Guy Bedford" <notifications@github.com> escreveu:

**Comment by guybedford** [comment]
@guilhermeaiolfi specifically why do you need to install distributable files at all? The standard workflow with jspm is the same as npm - deliver library code as separate modules in a package, not a pre-built single file.

If you want to provide a pre-built single file, this is what sfx bundles are for though.

**Comment by guilhermeaiolfi** [comment]
Let me try to be more clear. I don't want those files in my install. I just want to distribute my library as in (not releated to jspm/npm install):

http://cdn.ractivejs.org/latest/ractive.js
https://code.jquery.com/jquery-2.1.3.js

If they are using npm/jspm it's ok as it is. But I want to deliver the whole thing as a single files just like jquery as ractive do. And people using those libraries that way don't want a copy of systemjs bundle together (sfx). 

Is it possible?

**Comment by guybedford** [comment]
@guilhermeaiolfi this is a good use case for sfx bundles.

**Comment by guilhermeaiolfi** [comment]
Al'right. I thought that maybe I could do something else besides sfx because my 500 lines doubles in size using sfx. But that's ok, I guess. Thanks for your patience.
