### ISSUE TITLE
port new global handling code

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#152]

**Comment by AutoSponge** [comment]
https://github.com/systemjs/builder/pull/138 closed the PR that had the right approach. Can this get resubmitted?

**Comment by AutoSponge** [comment]
I think I see the issue with the builds:

builder.js

```
Builder.prototype.reset = function() {
  var loader = this.loader = new System.constructor();
  loader.baseURL = System.baseURL;
...
```

Calls into this (es6-module-loader):

```
  // 26.3.1.1
  function Loader(options) {
    if (typeof options != 'object')
      throw new TypeError('Options must be an object');
...
```

It's invoking the constructor without an options object and it throws.

**Comment by guybedford** [comment]
Note #138 is a separate branch upgrade, running against SystemJS 0.17 and ESML 0.17 branches.

The current branch doesn't call that.

**Comment by AutoSponge** [comment]
Ok cool. I'll try upgrading to the unreleased ESML and see if it will compile.

**Comment by guybedford** [comment]
I wouldn't advise that - it's not a stable branch. Can you explain what compile error you are getting?

**Comment by guybedford** [comment]
Btw if you want to take a look at it, it is updating this code - https://github.com/systemjs/builder/blob/master/compilers/global.js#L116 to reflect this code - https://github.com/systemjs/systemjs/blob/master/lib/extension-global.js#L64.

**Comment by AutoSponge** [comment]
When we compile, the old version of the global-helper code is hard-coded so even though IE8 fixes are in, it will still break after being compiled.

**Comment by guybedford** [comment]
Right then it is exactly as above.

**Comment by AutoSponge** [comment]
I'm going to try a minor change to the global compiler using Object.prototype.hasOwnProperty.call for IE8. If that works can I submit it as a patch to the current release?

**Comment by AutoSponge** [comment]
I submitted https://github.com/systemjs/builder/pull/153
