### ISSUE TITLE
Bundle arithmetic expressions broken

### ISSUE THREAD

**Issue by circlingthesun** [systemjs/builder#156]
Bundle arithmetic expressions seem to be broken when using ```builder.build``` in the latest version.  I get the following error after upgrading:

```
Error on app/app Error: Error loading "app/app - shared" at file:/home/me/project/app - shared.js
ENOENT, open '/home/me/project/app - shared.js'
```

The expression used is ```app/app - shared```.

**Comment by guybedford** [comment]
Check you're not perhaps running an old version of builder?

**Comment by circlingthesun** [comment]
You are right, I was on 0.9.x. It works now.
