### ISSUE TITLE
Check sourceMap doesn't contain file: URLs

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#157]
@lookfirst mentioned `file:` URLs were turning up int he source map, we should check that isn't from builder here.

**Comment by lookfirst** [comment]
Thanks. Yes, it is from the [systemjs-route-bundler](https://github.com/Swimlane/systemjs-route-bundler) which has been updated to use the latest systemjs/builder code now. 

I disabled it with sourceMaps: false.

**Comment by crisptrutski** [comment]
Bit swamped at the moment, but will try look into this tomorrow

**Comment by crisptrutski** [comment]
@lookfirst thanks for linking me to that test suite, made my life much easier :)

Looked into this, and was able to resolve with some changes to both `builder` and `systemjs-route-bundler`. The issue basically boils down to absolute vs relative paths (`builder` assumes `baseURL` is an absolute path), and the informal `file:/` specification (which node's `path` does not understand, but `builder` assumes `baseURL` is using).

@guybedford  

Can send a PR for `builder` to be more agnostic around absolute file paths (in `sources` and `baseURL`), and to reject or at least not treat-as-if-it-were-absolute relative paths.

Don't think that `builder` should be deciding how to interpret relative paths though, in the context of normalizing the absolute paths that come back from loaders. Using `process.cwd()` matching "first occurance" or "last occurance" of the relative path in loaded file paths would work in many cases, but seem too opinionated.

In my testing I just modified the route-bundler to expand the path before calling builder, [just like jspm does](https://github.com/jspm/jspm-cli/blob/cd751a5408e40f5f134c613a246a462f891d643f/lib/bundle.js#L37), and believe this is the correct solution.
