### ISSUE TITLE
What is the better approach?

### ISSUE THREAD

**Issue by VictorQueiroz** [systemjs/builder#159]
I have alot of dependencies and a big directory structure, I'm trying to build the dependencies and the application itself in different files, but I really don't know how to do that. It's okay for me to block the build of dependencies using `System.meta.angular.build = false` but, what if I want to build a bunch of packages and not just one like `builder.build(['angular', 'angular-animate'])`. How is that so? Can someone help me, please?

**Comment by guybedford** [comment]
https://github.com/systemjs/builder#example---common-bundles is a good example of building the application and dependency bundles separately.

**Comment by VictorQueiroz** [comment]
What if I don't want to use `require('angular-animate')` at the top of my modules, which will use this dependency? In RequireJS we have `deps` key:

```js
requirejs({
  deps: ['angular-animate', 'angular-resource']
})
```

What is the equivalent for SystemJS?

**Comment by guybedford** [comment]
SystemJS doesn't have this feature, as we try to encourage full modularity over conveniences.
