### ISSUE TITLE
How to handle pre-minified, large source files during bundling?

### ISSUE THREAD

**Issue by nkoterba** [systemjs/builder#160]
So I've encountered an "annoying" situation.  I'm trying to include Kendo UI in my web application.

Kendo UI comes as a **minified** JS file at ~2.1MB, `kendo.all.min.js`.

I'm using it in my application via an import statement:
```javascript
import kendo from 'kendo';
```

And creating a standalone bundle using `builder`:
```javascript
gulp.task('bundle', 'Create JS production bundle', ['ngconstant'], function (cb) {
	var builder = new Builder();

	builder.loadConfig(snap.paths.systemjsconfig)
		.then(function () {
			builder.buildSFX(snap.paths.app.entry,
				snap.paths.tmp.scripts + 'build.js',
				{
					// See: https://github.com/systemjs/builder#minfication--source-maps
					sourceMaps: true,
					lowResSourceMaps: true,

					// Minifying kendo.all.min.js causes build to take MINUTES
					// TODO: Re-enable minification once situation has a workaround
					//minify: true,
					//mangle: false,
					config: {
						sourceRoot: snap.paths.tmp.scripts
					}
				})
				.then(function () {
					return cb();
				})
				.catch(function (ex) {
					log(COLORS.red(ex));
					cb(new Error(ex));
				});
		})
		.catch(function (ex) {
			log(COLORS.red(ex));
			cb(new Error(ex));
		})
});
```

Unfortunately, when I enable minification as part of the `buildSFX` settings, the building process takes **minutes** to complete =(

I've tried running uglify-js (uglify2) which I believe builder is using internally on the file and it too suffers from the same fate.  So I do not believe this is per-say an issue with systemjs/builder.  However, since I can't control how or what systemjs/builder minifies in creating a single bundle, I'm pretty much forced to disable minification on my entire application...which is not desirable.

So how do I work around this situation:
a) Maybe suggest a builder feature to only minify specific files (but internally it looks as if builder is generating a single source file and THEN minifying that file vs minifying individual files and concatenating or joining them together)
b) Split my application into **TWO** bundles (perhaps one as vendor.js and app.js) and only minify the app.js one? (Following guidance perhaps in #108)
c) Separate kendo UI from all bundling and just include it from a `<script>` tag on in my `index.html`.

My question if I do (c) however, is how I can then do `import kendo from 'kendo';` when kendo is now managed OUTSIDE of the systemjs/jspm/es6to5 bundling/transpiling process?

Has anybody else encountered a similar issue and found a suitable workaround?

**Comment by guybedford** [comment]
@nkoterba you should just be able to build a bundle without `kendo.all.min`, and then create a bundle of `kendo.all.min` with minification and sourcemaps disabled as a separate step. That way `kendo.all.min` becomes a base bundle that everything else excludes.
