### ISSUE TITLE
Build from a list of root module filenames?

### ISSUE THREAD

**Issue by johnjbarton** [systemjs/builder#162]
I'm unable extrapolate from the `arithmetic` examples to determine if there is way to supply list of module files which will be recursively imported to build a bundle.

I wonder if it might be possible to create a SFX file for traceur?

**Comment by guybedford** [comment]
Yes all modules passed into the build function have their dependencies traced in turn.

It may well be possible to do an SFX bundle for Traceur. Note that the runtime errors in SFX bundles are not debug-friendly, so it is advisable to start by doing a normal load through SystemJS.

**Comment by guybedford** [comment]
Closing for now, just let me know if you want to discuss this further at all.
