### ISSUE TITLE
Allow bundles themselves to be supported in addition

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#163]
And avoid this error - 

TypeError: "init" was defined via a bundle, so can only be used for subtraction or union operations.

**Comment by ohjames** [comment]
Thanks so much for opening this ticket.

I've just finished a new asset pipeline and I want to bring incremental building using multiple CPUs to my `jspm` work-flow.

Essentially in this system I pre-compile the assets server side as the project is *massive* with many many `babel` dependencies. Having to wait on each load for babel to compile them all causes big delays to testing.

So instead I compile only the files that change using a build system that watches all the source files meaning the act of compiling ES6 modules is only performed once and in parallel.

With this support I can use ES6 modules all the way, currently I have to use intermediary AMD compiled resources and these come with many disadvantages (e.g. having to maintain dependency order when many modules are bundled into a single file).

**Comment by ohjames** [comment]
Hey @guybedford I'd like to work on this issue and submit a PR, would that be okay? If you have the time would be great if you had any pointers.

With this issue out of the way I can bring incremental rebuilds of bundles to jspm removing the one pain point from jspm that prevents people from migrating to jspm from webpack/browserify.

**Comment by guybedford** [comment]
Thanks so much for getting in touch - it would be great to have a contribution here. I think it may make sense to approach this at an even lower level, by separating compile into _compile load_ and _concat bundle_.

Currently both of the above steps happen in https://github.com/systemjs/builder/blob/master/lib/compile.js#L40.

By separating this into two parts, it would allow a caching system to just make the compile calls it needs using the compiled `source`, `sourceMap` entries (output of compileLoad at https://github.com/systemjs/builder/blob/master/lib/compile.js#L74) already from cache, and then concatenating fresh compiles along with cached compiles together.

Just doing this separation of writing `exports.compileOutputs` as a process calling `exports.compileLoad` and `exports.concatOutputs` would allow a custom build tool like yours to call into `require('systemjs-builder/lib/compile').compileLoad` etc directly in creating a cache-abstracted build tool.

That's the simple low-level API I can think of offhand, in turn it may make sense to add cache abstractions but maybe even not, and to leave that to higher level tools like a jspm watch server etc.

Just let me know if you have any more questions.

**Comment by guybedford** [comment]
Note we should probably export these methods on the builder class instance itself though - `builder.compileLoad` and `builder.concatOutputs`

**Comment by ohjames** [comment]
Thanks for the advice. This is my number one priority at the moment (well... after playing Splatoon) I'll have something for you to review soon I hope.

**Comment by ohjames** [comment]
Should be done now hopefully.

**Comment by guybedford** [comment]
I don't think this issue title is going to be possible, as mentioned in https://github.com/systemjs/builder/issues/222#issuecomment-121647018. We should always build from original sources for source maps support, and can use the cache to optimize this as discussed here.
