### ISSUE TITLE
Ignore by Wildcard

### ISSUE THREAD

**Issue by abakirov** [systemjs/builder#165]
Suggestion: allow ignoring external resources with wildcard.

Suppose you have a file:
```
import { a } from { 'lib/a' };
import { b } from { 'lib/b' };
...
```
`lib` is an external library. I would like to be able to exclude both `lib/a` and `lib/b` from build. Currently, I have to do something like this:
```
new Builder({
    meta: {
        'lib/a': { build: false },
        'lib/b': { build: false }
    }
});
```
It's fine when `lib` only has two modules `a` and `b` but it becomes a little too verbose if there are many modules in `lib`.

It would be nice if I could exclude externals as `lib/*` somehow.

**Comment by guybedford** [comment]
This should be supported currently with `app - [lib/*]`. Let me know if you're unable to have `lib` present at build time though and there might be some other options.

**Comment by abakirov** [comment]
One example of `lib` is [angular2](https://code.angularjs.org/2.0.0-alpha.22/angular2.dev.js) so it is present but already built. I am able able to config the builder like this:
```
builder.config({
    paths: {
        'angular2/*': 'lib/angular2/angular2.dev.js'
    }
});
builder.build('app - [angular2/*]', 'out.js');
```

This results in error (at angular2.dev.js:716:22):
```
    module.exports : window));
                     ^
ReferenceError: window is not defined
```

It would be cool if the builder didn't even try find and load `lib` if I say `app - lib/*`. This way I wouldn't have to call `config` for an external library that I'm excluding anyway.

Thanks!

**Comment by guybedford** [comment]
@abakirov this is a bug, and not related to the builder at all. The reason Angular is being executed is because it is in your original trace, and we therefore need to know it's dependencies so that is all by design. The issue actually is that angular2 is being detected as the System.register format by mistake here. You need to add `System.config({ meta: { 'angular2.dev': { format: 'amd' } } })` or global and that should work.

I've created a bug for the detection issue at https://github.com/systemjs/systemjs/issues/447.

**Comment by NisStrom** [comment]
I have a similar issue, when i try to minify the, into ES5  compiled angular 2 components.
As the project mixes with angularJs, the angularjs files ar getting minimized perfectly, but it tries to search for `angular2/angular2` im my app directory instead in the node_modules folder in the parent of the app folder.

adding the following does not work.

    builder.config = {
        meta: {
            'angular2/angular2' : {build: false} 
        }
    }

It is still trying to look for angular2.js in the app folder. 
How can i solve this problem?
