### ISSUE TITLE
How to handle CSS Resources (e.g. images, fonts, etc.) during BundleSFX

### ISSUE THREAD

**Issue by nkoterba** [systemjs/builder#166]
If this is a duplicate or similar issue, please close and/or link.

I tried searching and couldn't find any obvious answers to this issue.

I'm trying to use some web-fonts available in a package:
```javascript
jspm install npm:mdi
```

Installs this:
![image](https://cloud.githubusercontent.com/assets/2508944/7556849/277c5c86-f750-11e4-9011-5c5c398f2e73.png)

To use the web-fonts I need to include the css file in my application. I do so using the `systemjs css` plugin:
```javascript
import 'mdi/css/materialdesignicons.min.css!';
```

This file contains relative paths to resources (in this case fonts):
```javascript
@font-face {
  font-family: 'MaterialDesignIcons';
  src: url("../fonts/materialdesignicons-webfont.eot?v=1.0.62");
  src: url("../fonts/materialdesignicons-webfont.eot?#iefix&v=1.0.62") format("embedded-opentype"), url("../fonts/materialdesignicons-webfont.woff2?v=1.0.62") format("woff2"), url("../fonts/materialdesignicons-webfont.woff?v=1.0.62") format("woff"), url("../fonts/materialdesignicons-webfont.ttf?v=1.0.62") format("truetype"), url("../fonts/materialdesignicons-webfont.svg?v=1.0.62#materialdesigniconsregular") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

However, after bundling my application with `bundleSFX`, my output/build file contains relative paths to the `jspm_packages` folder for the fonts defined above:
```javascript
@font-face{
font-family:MaterialDesignIcons;
src:url(jspm_packages/npm/mdi@1.0.62-beta/fonts/materialdesignicons-webfont.eot?v=1.0.62);
src:url(jspm_packages/npm/mdi@1.0.62-beta/fonts/materialdesignicons-webfont.eot?#iefix&v=1.0.62) format(\"embedded-opentype\"), url(jspm_packages/npm/mdi@1.0.62-beta/fonts/materialdesignicons-webfont.woff2?v=1.0.62) format(\"woff2\"), url(jspm_packages/npm/mdi@1.0.62-beta/fonts/materialdesignicons-webfont.woff?v=1.0.62) format(\"woff\"), url(jspm_packages/npm/mdi@1.0.62-beta/fonts/materialdesignicons-webfont.ttf?v=1.0.62) format(\"truetype\"), url(jspm_packages/npm/mdi@1.0.62-beta/fonts/materialdesignicons-webfont.svg?v=1.0.62#materialdesigniconsregular) format(\"svg\")
```

So now when I run my "bundled" and "production" code on the server, I get `404s` because these resources don't exist (no `jspm_packages` folder exists in my `build/dist` folder) since all the source is bundled.

How is this situation supposed to be handled?  Do I need to copy things like resources into `build/dist` folder in the same path structure as they are under my "development" file structure?

Should systemjs or the css plugin be inlining these files?

**Comment by guybedford** [comment]
There has been some discussion of adding support for a copy assets feature like you say at https://github.com/systemjs/plugin-css/issues/23.

I'm not too keen on supporting inlining though.

**Comment by guybedford** [comment]
Ideally we do just want to have jspm_packages served in production though as it is also useful for dynamic loading scenarios.

**Comment by nkoterba** [comment]
@guybedford So I have no issue "including" `jspm_packages` in my production code, however, we have about ~100+ third-party javascript source files as well as project js files.  

By not bundling our production code, we end up with ~100+ HTTP GET requests which causes loading of our webapp to perform poorly and has forced us back to using our old `browserify` bundling/building system.

So would you say the 'ideal' situation is to **bundle** 3rd party source files and internal project js files into as *few* bundles as possible and then for those 3rd party files that do use resources in jspm just copy those `jspm_packages` folders over to our production deployment?

Or would you recommend just copying all `jspm_packages` resources (e.g. fonts, images, etc.) and non-js source files over to the production server?

I see one other alternative...in our current build process we **do** copy over things like images and fonts from included `jspm_packages` installed libraries to a `fonts` and `images` directory.  However the paths in the CSS files do not match.  I guess we could try to run our CSS files through a `gulp` pipe that would replace all `url` or `src` paths to the "production" paths of the `fonts` and `images` directories.

I just can't believe I'm the only encountering this issue so am curious to hear how the community at large is handling this situation...

**Comment by guybedford** [comment]
@nkoterba the ideal is exactly to bundle and still include jspm_packages for requests in production as resources and dynamic modules can then be loaded from there.

It would be advisable to run a gulp task over jspm_packages to minify everything in there depending on the resource type, and one could potentially do a filter if you're able to trace your required resources.

The functionality to do that above is something that may become part of builder in future, but for now it is not handled, and won't be for some time unfortunately.

If you do come up with solutions that you can share with the community that is always welcome.

**Comment by nkoterba** [comment]
@guybedford Ok. Thanks for the info.  To make sure I'm following your "ideal" situation, if I had the following tree structure for my project:

```javascript
├── app
│   ├── index.html
│   ├── scripts
│   │   └── app.js
│   ├── styles
│   │   └── app.scss
│   │   └── images
│   └── views
├── jspm_packages
├── config.js
├── package.json
```

and then I ran `bundleSFX` on my **app.js**, minified the js, processed and minified the scss, and had the following "build/output" directory, then I'd want it to look like:

```javascript
├── dist
│   ├── index.html
│   ├── scripts
│   │   └── app.min-bundled.js
│   ├── jspm_packages
│   ├── styles
│   │   └── app.min-bundled.css
│   │   └── images
│   └── views
```

Obviously I would need to get the *relative* paths correct...but in essence, I should **COPY** the jspm_packages folder in its *entirety* to my distribution/build output directory along with my `.html` templates, bundled `.js` file, and any `css` styles?

**Comment by guybedford** [comment]
Yes - ideally the entire project folder would get built into a `project-dist` folder that minifies everything. Gulping jspm_packages and minifying everything there will be slow, but could potentially be cached.

The alternative is to exactly calculate these resource trees ala assetgraph and pull just out what you need. As I say we could implement this workflow into builder, but we're not quite there on prioritising this yet.

**Comment by nkoterba** [comment]
@guybedford Sorry...it must be the lack of coffee or the fact it's Monday morning, but I'm still confused as to what I should be doing with the `jspm_packages` folder in my `project-dist` directory.

When I use `buildSFX` all the **.js** files I need for my project are already pulled from `jspm_packages` and minified.  Why would I also want to run a gulp task through all the **.js** files (I'm assuming) in the `jspm_packages` directory to minify those?  Especially since many 3rd party libraries often already include a minified version in the downloaded jspm package? I would potentially be processing and/or minifying a lot of unnecessary files (unless I just targeted the `main` file).

Also, won't my app, when it needs a resource, just "load" it from the bundled/minified **.js** file?

The only items I would think need to be in the jspm_packages folder in my `project-dist` would be resources (e.g. images, fonts, etc.) that my **bundled** js may try to pull in (most likely from imported css files).

For example, I imagine running the following "gulp" task on my `jspm_packages` directory during my *build* process:
```javascript
gulp.task('copyJSPMResoruces', function() {
  gulp.src('./jspm_packages/**/*, { base: './' })
         .pipe(filter([*.{svg,png,eot,ttf,wot,gif}])) <-- Or just ignore all .js files
         .pipe(gulp.dest('./project-dist'));
}
```

This would then create a `project-dist/jspm_packages` folder with only resources and all the JS would be bundled in my `app.min-bundled.js` file.

Perhaps I'm missing something here...or thinking about things incorrectly...if so, please knock some sense into me...thanks!

**Comment by guybedford** [comment]
@nkoterba certainly if you know for a fact that all js files are in the bundles you have created (and nothing is dynamically loaded otherwise), then yes exactly just copy the other file formats except js and minify them.

**Comment by nkoterba** [comment]
@guybedford Ok now I understand.

Regarding dynamically loaded items, is there any documentation or information on such things?

Although this is off-topic from this post, I'm now:

1) Concerned that 3rd party modules I install from jspm may now use dynamically loaded libraries...how would I know? How should I handle this? How are these "bundled"?

2) Worried that other developers on my team may load dynamic modules which would break the app again if we bundle...which leads me to think that bundling anything is just a **bad** design and we should just not bundle.

**Comment by guybedford** [comment]
Dynamically loaded modules will be given better support through contextual require, but for now all we have is https://github.com/systemjs/systemjs/wiki/Relative-Dynamic-Loading.

Not many libraries do this, so it isn't a big worry currently. In future the plan is to have the builder trace also detect tracable dynamic requries, but not all are tracable and could be variable. In the worst case one would have to notice requests out of bundle from the network tab after bundling and know to add those in via arithmetic.

The above is really not a big issue though, and dynamic loading is an encouraged scenario.

**Comment by nkoterba** [comment]
Ok my concerns are mostly alleviated...thanks!

I guess for the time being we will go with either:

A) copying "resources" from the `jspm_packages` folder into the `project-dist` folder maintaining file paths to enable relative lookups of css `url` and `src` properties in css files that were imported using the SystemJS `css` plugin.

B) During our bundle process, in the bundled **.js** file, attempt to "replace" or "update" relative url paths  to the `jspm_packages` folder to a location in our `project-dist` directory that contains the resources.

I defer closing this issue to you unless you want to leave it open until a more "complete" solution (either in css plugin or other means) is developed.

**Comment by guybedford** [comment]
Let's track a more complete solution in the CSS plugin itself. Development there will be given priority soon, we're just focusing on core work still at the moment.

**Comment by nkoterba** [comment]
:+

**Comment by rparsi** [comment]
@guybedford Hi I'm running into similar situation as nkoterba.
I'm using Symfony 3.0.4 with jspm, jquery, twitter bootstrap and misc jspm packages to make a simple page that uses jquery + bootstrap. 

So at the top level these are the directories (among others):
`./web`
`./frontend` all the jspm stuff is here
`./frontend/app` only has my custom es6 modules

My apache DocumentRoot is set to the absolute path of `./web` on my ubuntu server.
This is how Symfony3 defines the public facing side of the framework, so I won't change it.

I don't want my es6 modules to be in same directory as the generated bundle(s) so I
specify the bundle file name and path (ie `./web/build/blahModule.js`) when using `jspm bundle-sfx`.

However the urls/paths used for referencing the bootstrap font files points to `./frontend/app/jspm_packages` instead of `./web/fonts`, which makes sense as the bootstrap stuff is not installed in `./web/fonts`.

I can make a symlink in `./web/` to `./frontend/app/jspm_packages/github/twbs/bootstrap@3.3.6`, though I'm not sure if this is ideal or 'clean'.

What mechanisms does jspm and/or SystemJS provide for handling this case, where a public package like twitter bootstrap includes asset files like fonts?

**Comment by guybedford** [comment]
@rparsi did you try the plugin-css rootURL feature at https://github.com/systemjs/plugin-css#build-example?

**Comment by rparsi** [comment]
@guybedford Ah, so that's what `rootURL` was about.  I thought it goes in my `package.json`under `directories`.  Ok so I didn't use it correctly.
I read the example from the url you gave, but I'm lost as to where to put the code.
Which file does it go in?

**Comment by traab** [comment]
I am stuck on the same issue. Any update on this?

**Comment by rparsi** [comment]
@traab I tried using the "plugin-css" rootURL feature as described by guybedford.  No matter what I put as the rootURL value nothing worked.  I eventually gave up and hardcoded the `<link ...>` tags.

**Comment by traab** [comment]
@rparsi I put a "buildConfig" entry into jspm.config.js, but jspm does not respect the `rootURL `parameter. Nevertheless it uses the `separateCSS `parameter and I'm now linking the optimized css file in my` <head>` section.

@guybedford  It would be nice if JSPM would recognize other parameters like `rootURL`or `minify`, too.

**Comment by rparsi** [comment]
@traab Would you mind giving me a link (gist or to commit in github) to what your "buildConfig" looks like?  I never understood how you're supposed to use it.

**Comment by traab** [comment]
@rparsi Part of my jspm.config.js looks like:
```
SystemJS.config({
    nodeConfig: {
        "paths": {
            "inew/": "src/"
        }
    },
    buildConfig: {
        "separateCSS": true,
        "minify": true  
    },
[...]
```

**Comment by spookyvision** [comment]
I have a problem that could be related? In my JS, I import some js package that includes css, which in turn references images inside the package. As soon as I start using systemjs bundle, those images are not loaded when I load my JS app from a location that is inside some path (as opposed to the web site root '/'). 

Interestingly, baseURL is removed in the broken cases.

So, example of a correct URL, with main html/js app loaded from `https://HOST/` would be:
`https://HOST/static/jspm_packages/github/spookyvision/better-swipebox@1.4.5/src/img/loader.gif
`
and a broken one, where main html/js app loaded from https://ROOT/message/15/ (note the missing static/):
`https://HOST/message/15/jspm_packages/github/spookyvision/better-swipebox@1.4.5/src/img/loader.gif`


I worked around this issue with a nginx regex rewrite rule, but that's not exactly a 100% happy place solution...
`rewrite ^(?!static).*(/jspm_packages/.*)$ /static/$1  last;`
