### ISSUE TITLE
AMD define replacement is not always reliable

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#167]
From https://github.com/jspm/jspm-cli/issues/732#issuecomment-100714216, in Kendo UI we get:

```javascript
(function (f, define) {
    define([], f)
})(function () { 
      <<SOURCE CODE HERE>> 
}, typeof define == "function" && define.amd ? define : function (_, f) {
    f()
});
```

Turned into

```javascript
(function() {
function define(){};  define.amd = {};
(function(f, define) {  <-- Actual start of library source
  define([], f);
})(function() {
  <<SOURCE CODE HERE>>
}, typeof define == "function" && define.amd ? define : function(_, f) {
  f();
}); <-- Actual end of library source
})();
```

Because the define function is passed as a function parameter, the AMD transformer doesn't detect this pass to be able to replace the call of define with `System.register`.

It may be preferable to alter the AMD conversion to rather include the `System.register` call within the dummy define function at the top rather so we can handle these cases.

**Comment by nkoterba** [comment]
@guybedford :+1: 

I think the idea of replacing the `define` dummy function at the top would be a nice overall addition if it doesn't break other constructs.

It was confusing initially to see the following in the "bundled" source:
```javascript
function define(){};  define.amd = {};
```

Eventually, I realized that this was "tricking" the AMD module into thinking it was within an AMD environment and to behave like an AMD "module".

In addition, by placing the System.register call at the start of the library's source code it would be easier to always locate.  Right now the `System.register` replacement happens in the 3rd party library wherever they happen to use the `define` function which can be at the start of the file, the end of the file, etc.

**Comment by guybedford** [comment]
Another case of something similar also came up from https://github.com/jspm/jspm-cli/issues/750:

```javascript
  System.register("npm:node-forge@0.6.26/js/forge", [...], false, function(__require, __exports, __module) {
    return (function() {
      defineFunc.apply(null, Array.prototype.slice.call(arguments, 0));
    }).call(this, __require, __module, ...);
  });
```

Where `arguments` loses the deps context throwing in the bundle.

**Comment by codylindley** [comment]
Guy. I'm confused. Did you fix this issue or just decide it was not a bug anymore. With kendo UI, in AMD format the bundle is still breaking. I'd like to really understand the correct fix here.

**Comment by guybedford** [comment]
@codylindley as mentioned, this bug was fixed in https://github.com/systemjs/builder/issues/228. Working on getting the next beta out really soon, just need to smooth out quite a few things still.

**Comment by codylindley** [comment]
Sweet! Just tested now. And the bundling works with Kendo UI AMD. Thank you!

https://www.dropbox.com/s/0abez5aqrsiijvp/Screenshot%202015-10-07%2015.02.45.png?dl=0

**Comment by guybedford** [comment]
:+1:

**Comment by og-neth** [comment]
@codylindley Do you have an example of your set up? I am running into issues myself using AMD with Kendo UI and the systemjs builder, I keep getting this error:

`Uncaught Module 10 not present.`

The console traces this to my app.main.js module and highlights line 3

```
﻿import 'app.core'
import 'app.clubManagement'
import 'app.clubStatistics'
```

But my widgets are instantiated on my view ( I am using Kendo MVVM ). A bit of a head-scratcher. I am using grunt to run the builder task via the [grunt-systemjs-builder](https://www.npmjs.com/package/grunt-systemjs-builder) module. Here is my config:

```
systemjs: {
            options: {
                sfx: true,
                configFile: "Scripts/systemjs.config.js",
                minify: true,
                build: {
                    mangle: false
                }
            },
            dist: {
                files: [{
                    "src":  "Scripts/app/app.main.js",
                    "dest": "Scripts/bundles/app.min.js"
                }]
            }
        }

```
Any thoughts? I searched on the kendo forums and couldn't find anything related to this until I found this thread.

**Comment by guybedford** [comment]
@og-neth this is something currently being worked on in https://github.com/jspm/jspm-cli/issues/1555. I'm hoping to post out a release today with a fix for exactly this problem, please do test it out if you can later, by following the issue there.

**Comment by codylindley** [comment]
@og-neth - You might look here: 

https://github.com/codylindley/jspm-startup.

http://developer.telerik.com/featured/choose-es6-modules-today/

**Comment by og-neth** [comment]
@guybedford Sorry for the delay in response, I was tied up with some other assignments. Yes this worked thank you so much, the latest release resolved the issue you're a master. However I am seeing some slowness when I bundle. I am using a [grunt-systemjs-builder](https://www.npmjs.com/package/grunt-systemjs-builder) task to do the bundling since we're using grunt. However when I look in the github docs, it seems everyone is using gulp, which gets me thinking if we should switch to gulp. Do you have an opinion on that? Also I have reported the slowness here: https://github.com/yoavniran/grunt-systemjs-builder/issues/12#issuecomment-194121758

**Comment by guybedford** [comment]
@og-neth for a fast build look at https://github.com/jackfranklin/jspm-dev-builder, which can do incremental build caching.

**Comment by guybedford** [comment]
Also for a 400 second build, how big is your output file!?

**Comment by og-neth** [comment]
@guybedford yeah it's a big file it's 300kb....  it's a sfx-bundle too...  so it includes all libraries we use plus our app logic.  Thanks for the link I know that systemjs and jspm are married so it's logical for me to go that route. Thanks again for your support.

**Comment by guybedford** [comment]
@og-neth perhaps look at the source to that project - it's a very simple builder API approach that works without jspm fine.
