### ISSUE TITLE
Traceur runtime in sfx overrides System

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#169]
We need to ensure we wrap Traceur runtime accordingly.

**Comment by OliverJAsh** [comment]
Any ideas when this will be fixed? It's our only blocker.

**Comment by OliverJAsh** [comment]
Traceur also overrides when the runtime is loaded asynchronously.

**Comment by guybedford** [comment]
@OliverJAsh thanks I've fixed this in SystemJS master to not affect normal bundles or async loading of bundles. That just leaves the case described for this issue only.
