### ISSUE TITLE
How to author an AMD module with ES6

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/builder#172]
I want to author an AMD module but write it using ES6 syntax.

If I try to do this now, the module will be detected as AMD and not transpiled. If I specify `"format es6"` to get it to transpile, it will think my module is ES6 instead of AMD.

**Comment by OliverJAsh** [comment]
Even better if we could mix:

``` js
import foo from 'bar';

define(function () { return 'x'; });
```

We are trying to do something like this where we must export an AMD module but we want to use ES6 syntax as far as possible. /cc

**Comment by guybedford** [comment]
@OliverJAsh "script" ES6 modules are not supported via transpilation in the module loader.

The advisable way to do this currently is to write ES6 + AMD, and then use Babel to precompile the files into ES5, and then load as AMD.

We are working on unifying the transpilation to allow any module format to be written in any language, but for now the above is best.

If you want any assistance further with the workflow just let me know. It should be pretty quick to do, but may take a bit of trial and error I understand.

**Comment by OliverJAsh** [comment]
> We are working on unifying the transpilation to allow any module format to be written in any language

That would be great. Can I track an issue for that somewhere?

**Comment by guybedford** [comment]
Unfortunately not, it is architectural, and will take a couple of months.

**Comment by guybedford** [comment]
@OliverJAsh sorry haven't been a great help recently. Now that this release is out should have a bit more time to assist. Let me know if you want to discuss this further at all.
