### ISSUE TITLE
Bundle to AMD

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/builder#173]
Is it possible to bundle to AMD instead of `System.register`?

**Comment by guybedford** [comment]
Yes, but not within SystemJS builder - rather use a custom gulp task to do this.

**Comment by guybedford** [comment]
The coming release (soon!) of SystemJS now bundles AMD as AMD, so that you could transpile to anonymous AMD to have SystemJS builder create named defines to get that effect so far as all dependencies might be AMD.

**Comment by OliverJAsh** [comment]
> The coming release (soon!) of SystemJS now bundles AMD as AMD

Why will AMD not be bundled as `System.register`, out of curiosity?

**Comment by guybedford** [comment]
To fix https://github.com/systemjs/builder/issues/167.

**Comment by OliverJAsh** [comment]
Tracking https://github.com/systemjs/builder/issues/176
