### ISSUE TITLE
Inlining source maps results in loss of coverage

### ISSUE THREAD

**Issue by crisptrutski** [systemjs/builder#174]
via @johnraz

~~Generating external sourceMaps despite providing command line option.~~ jspm/jspm-cli#783

Manually forcing the sourceMapContents option in systemjs actually generates internal sourcemaps, but only for dependencies, not project code.

**Comment by johnraz** [comment]
setting `babelOptions.sourceMaps` to any other value than `"inline"` and forcing sourceMapContents seems to work for both deps and project code

**Comment by crisptrutski** [comment]
@johnraz is this still an issue, now that we're forcing `sourceMap` instead of `sourceMapContents`?

**Comment by johnraz** [comment]
As per my comment above I believe the problem was more related to babel than systemjs.
We most likely can close this.
