### ISSUE TITLE
es6-module-loader: Options must be an object

### ISSUE THREAD

**Issue by markstickley** [systemjs/builder#175]
Hi,

I'm seeing an issue with the latest master (95e3db8b91c08d9b6859977824d0bc1e5ad2486b) where instantiating a new Builder instance results in an error being thrown:

```
marks@localhost:systemjs-builder (master)$ git diff upstream/master
marks@localhost:systemjs-builder (master)$ node
> process.cwd('/Users/marks/workspace/systemjs-builder');
'/Users/marks/workspace/systemjs-builder'
> var Builder = require('./index');
undefined
> var b = new Builder();
TypeError: Options must be an object
    at new Loader (/Users/marks/workspace/systemjs-builder/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:2193:13)
    at Builder.reset (/Users/marks/workspace/systemjs-builder/lib/builder.js:61:30)
    at new Builder (/Users/marks/workspace/systemjs-builder/lib/builder.js:36:8)
    at repl:1:9
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
> 
```

Looking at the readme this should be an acceptable workflow. I have updated all the npm packages installed just in case the problem lay there.

Line 61 of builder.js is this:

```
var loader = this.loader = new baseLoader.constructor(baseURL);
```

and the constructor looks like this:

```
  function Loader(options) {
    if (typeof options != 'object')
      throw new TypeError('Options must be an object');
   ...
```

Which looks destined to throw when it gets called with baseURL as (following the preceding logic) baseURL seems to be a String.

It's making the unit tests fail as well... have I missed something obvious?

Many thanks!

**Comment by guybedford** [comment]
The current branch is now running against master ES6 module loader and SystemJS for the coming release. There are some detailed changes in this, but it should be mostly backwards-compatible.

**Comment by markstickley** [comment]
Thanks, I pulled the changes to package.json and ran `npm install -f` but it didn't seem to like it:

```
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-f"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: systemjs@'master'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.4.0","0.4.1","0.4.2","0.4.3","0.5.0","0.5.1","0.5.2","0.5.5","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.6.8","0.7.0","0.8.0","0.8.1","0.8.2","0.9.0","0.9.1","0.9.2","0.9.3","0.10.0","0.10.1","0.10.2","0.11.0","0.11.1","0.11.2","0.11.3","0.12.0","0.12.1","0.13.0","0.13.1","0.13.2","0.14.0","0.14.1","0.15.0","0.16.0","0.16.1","0.16.2","0.16.3","0.16.4","0.16.5","0.16.6","0.16.7","0.16.8","0.16.9","0.16.10","0.16.11"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'systemjs-builder'
npm ERR! notarget 
```

I feel like I must be doing something wrong...

**Comment by crisptrutski** [comment]
@markstickley @guybedford not sure how "master" was meant to work (no such dist-tag), have replaced with "latest".

So `npm install -f` raises no errors for this in the situation where the versions in your `node_modules` are symlinks (the setup Guy and I are using). 

If you can use `package.json` to control which git branch is checked out in symlinks I'd be quite amazed. Not even going to test that, so the wonder and befuddlement can linger. @guybedford what were you doing here? :man_with_turban:

**Comment by crisptrutski** [comment]
@markstickley seeing the same `TypeError: Options must be an object` issue with the `latest` versions checked out. I'd recommend replacing `node_modules/es6-module-loader` and `node_modules/systemjs` with checkout of their respective repos (and don't forget to `npm install` inside both).

Not sure if worth publishing a `dev` dist-tag to npm, the respective releases should be quite soon.

**Comment by crisptrutski** [comment]
Closing, but happy to continue discussion

**Comment by markstickley** [comment]
Ah got it, no worries. I'll symlink those two and try again, thank you!
