### ISSUE TITLE
Module name prefix

### ISSUE THREAD

**Issue by soulcorrosion** [systemjs/builder#179]
Hello, first of all thanks for the effort being done here.
I've been experimenting with the builder and it works great. I just have a question. I need to add a prefix to the module names. All System.register reflect the module names, but I need to prefix something in all modules in the bundle. I understand I can load a Systemjs config file and apply some traceur configuration via traceurOptions:  { prefix: 'something' }.
I haven't been able to do this customization. It looks like the config is ignored. Any clues? Thanks

**Comment by guybedford** [comment]
Sure, it would help if you can explain why you'd like to prefix all the paths? Can you not run your build against a baseURL that matches the structure of the client baseURL?

**Comment by soulcorrosion** [comment]
Thanks for the reply. And yes, that's what I'm using at the moment, however I have to copy my sources to a temp folder so it matches this baseUrl. But it would be good if I could do it without this step, pretty much like I can do with dts-generator where I need to specify a package name and this package name is used as a prefix for all modules in the bundle. This prefix is used to identify the bundle because we will have several bundles in the page.

**Comment by guybedford** [comment]
@soulcorrosion can you not alter your baseURL until it matches something that can work between both client and server? The alternative is to use custom paths here - `System.config({ paths: { 'app/*': '...' } })` where the paths config varies between client and server. I think between these solutions that is effectively the prefixing mechanism. Let me know your thoughts, but closing as I think that covers it.
