### ISSUE TITLE
Babel resolution issue

### ISSUE THREAD

**Issue by Juriy** [systemjs/builder#180]
Hello, 

Trying to test a production flow with Babel + System.js and getting an error during the build process. Looks like it is trying to load babel.js from my modules folder.

```
{ [Error: Error loading "main" at file:/Users/juriy/dev/es6-skeleton/modules/src/main.js
Error loading "babel" at file:/Users/juriy/dev/es6-skeleton/modules/src/babel.js
ENOENT, open '/Users/juriy/dev/es6-skeleton/modules/src/babel.js']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/juriy/dev/es6-skeleton/modules/src/babel.js' }
```

The bug looks exactly like this one https://github.com/systemjs/systemjs/issues/380 however
the fix should already be included in v0.10.6 that I'm using

The example setup is available here https://github.com/Juriy/es6-skeleton/tree/master/modules

In my setup I have two files:

```
// main.js - enrty point
import { Calculator } from 'Calculator';

let calc = new Calculator();
console.log(calc.add(2, 2));
```

```
// Calculator.js - dependency
export class Calculator {
	constructor() {
		console.log('this is an es6 class!');
	}

	add(a, b) {
		return a + b;
	}
}
```

Finally, the build script looks close to the original example:

```
var path = require('path');
var Builder = require('systemjs-builder');

var builder = new Builder({
  baseURL: 'file:' + path.resolve('src'),

  // opt in to Babel for transpiling over Traceur
  transpiler: 'babel'
})
.build('main', 'target/systemjs/outfile.js')
.then(function() {
  console.log('Build complete');
})
.catch(function(err) {
  console.log('Build error');
  console.log(err);
});
```

The result is the error that I mentioned above. When I compile the same files directly with Babel and load files dynamically on the page, the code works fine.

```
$ babel src --out-dir target/babel --modules system
```

As a workaround, if I point the same build tool to `target/babel` (the output from babel), then it works fine and creates the bundle.

Please help to fix it.

**Comment by guybedford** [comment]
The workaround is as you say - setting the path directly.

This should be fixed in the latest SystemJS, if you try the upgrade do let me know how it goes.
