### ISSUE TITLE
Path Issue to JSPM packages when using buildSFX

### ISSUE THREAD

**Issue by Quirksmode** [systemjs/builder#182]
For some reason (and it may just be my lack of understanding) when using buildSFX it will only work if I use 'app' as the path to my main module file (app.js), if I try to set the path to be ''./app/assets/src/js/app' it gives me the error (Error loading "app/assets/src/js/app/app" at file:/app/assets/src/js/app/app.js). 

I got around this by setting the baseURL to be '/app/assets/src/js/app', but now I must move my jspm_packages into that folder for it to work. Is there a way I can keep my jspm_packages folder in the root, whilst successfully referencing './app/assets/src/js/app/' for my main module?

    // load SystemJS config from file
    var builder = new Builder();
    builder.loadConfig('./config.js')
    .then(function() {
        // Change baseURL to match the file system
        builder.config({ baseURL: path.resolve('./app/assets/src/js/app/') });

        // Build a self-executing bundle (ie. Has SystemJS built in and auto-imports the 'app' module)
        return builder.buildSFX('app', './app/assets/dest/js/app.js', { minify: false, sourceMaps: true});
        }).catch(function(err) {
        console.error(err);
    });

**Comment by guybedford** [comment]
Currently relative path builds are not supported, although it's coming in the next release very soon.

So yes, you have to use a path relative to the baseURL, and if the baseURL is not low enough, lower it to include the jspm_packages.

The restriction of having jspm_packages within the baseURL though is something that won't apply in the next release as well.

**Comment by Quirksmode** [comment]
Thanks for getting back to me, so is moving my JSPM Packages the only solution for now? If I lower the base to include the JSPM packages I will no longer be able to reference the build? Or is there an additional config setting I am missing where I can define the build source folder?

I don't suppose you have a rough ETA for the next release? Thanks for all the hard work on this by the way, it's incredible that we are able to do these things already!!

**Comment by guybedford** [comment]
I'd suggest setting the baseURL to the lowest reference point - `app/assets`, which contains jspm_packages, and then bundling your app as `jspm bundle src/js/app`.

**Comment by guybedford** [comment]
Note a key point here is that the baseURL needs to match between client and server as a reference point. (`/app/assets` in client and `public/app/assets` on the server say). You can rerun the prompts with `jspm init -p`.

**Comment by Quirksmode** [comment]
I played around and was able to fix it using this:

    // load SystemJS config from file
    var builder = new Builder();
    builder.loadConfig('./config.js')
    .then(function() {
        // Change baseURL to match the file system
        builder.config({ baseURL: path.resolve('./') });

        // Build a self-executing bundle (ie. Has SystemJS built in and auto-imports the 'app' module)
        return builder.buildSFX('app/assets/src/js/app/app', './app/assets/dest/js/app.js', { minify: false, sourceMaps: true});
        }).catch(function(err) {
        console.error(err);
    });

Thanks for the help :-)

**Comment by guybedford** [comment]
Glad to hear it's working.

**Comment by Jandalf** [comment]
when I try this I get this error:

`TypeError: baseURL should only be configured once and must be configured first.`

I want to have different baseURLs for SystemJS-Builder and SystemJS-Runtime. Is this possible?

**Comment by guybedford** [comment]
@Jandalf you can set the baseURL when constructing the builder via - 

```javascript
new Builder('path/to/baseURL', 'path/to/config.js')
```

And it will ignore the config.js `baseURL` so there will be no conflict.
