### ISSUE TITLE
Wrong paths on windows

### ISSUE THREAD

**Issue by YoannDelpierre** [systemjs/builder#183]
Hi,

I have some troubles when i'm doing a build using Gulp and System-JS Builder on Windows.

When i'm logging builder.loader.paths, i have double `\` on them

Log for them

```js
{
    'traceur': 'file: ///c: \\xxxx\\xxxx\\node_modules\\systemjs-builder\\node_modules\\traceur\\bin\\traceur.js',
    'traceur-runtime': 'file: ///c: \\xxxx\\xxxx\\node_modules\\systemjs-builder\\node_modules\\traceur\\bin\\traceur-runtime.js',
    'babel': 'file: ///c: \\xxxx\\xxxx\\node_modules\\babel-core\\browser.js',
    'babel/external-helpers': 'file: ///c: \\xxxx\\xxxx\\node_modules\\babel-core\\external-helpers.js',
    '*': '.tmpFile/*.js',
    'github: *': 'jspm_packages/github/*.js',
    'npm: *': 'jspm_packages/npm/*.js'
}
```

And node `Error: Only file URLs of the form file:/// allowed running in Node.`

No problem with Jenkins which is running on Debian server

**Comment by guybedford** [comment]
Thanks so much for posting I've included a fix in https://github.com/systemjs/systemjs/commit/740be6169535b86410216770134823548fbdff9e. Will release a patch in the next few days.

**Comment by YoannDelpierre** [comment]
Thanks Guy !

**Comment by guybedford** [comment]
This has been released in the latest SystemJS + Builder finally.
