### ISSUE TITLE
error loading file from babel-runtime

### ISSUE THREAD

**Issue by YoannDelpierre** [systemjs/builder#184]
Hi,

Something is strange when systemjs load babel-runtime

`Error loading file://c:/xxx/xxx/xxx/jspm_packages/npm/babel-runtime@5.5.1/helpers/to-consumable-array.js from file:///c:/xxx/xxx/xxx/.tmpFile/avis.js`

babel-runtime@5.5.1 is present on my drive into `jspm_packages/npm/`

I changed my index.js with your fix from #183 

My log for `match`

```js
c:/xxx/xxx/xxx/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js
c:/xxx/xxx/xxx/node_modules/systemjs-builder/node_modules/traceur/bin/traceur-runtime.js
c:/xxx/xxx/xxx/node_modules/babel-core/browser.js
c:/xxx/xxx/xxx/node_modules/babel-core/external-helpers.js
undefined
c:/xxx/xxx/xxx/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js
c:/xxx/xxx/xxx/node_modules/systemjs-builder/node_modules/traceur/bin/traceur-runtime.js
c:/xxx/xxx/xxx/node_modules/babel-core/browser.js
c:/xxx/xxx/xxx/node_modules/babel-core/external-helpers.js
undefined
[13:05:50] Starting 'styles:build'...
[13:05:50] Starting 'styles:build/critical'...
[13:05:50] 'systemBuilder' errored after 800 ms
[13:05:50] Error: Only file URLs of the form file:/// allowed running in Node.
        Error loading file://c:/xxx/xxx/xxx/jspm_packages/npm/babel-runtime@5.5.1/helpers/to-consumable-array.js from file:///c:/xxx/xxx/xxx/.tmpFile/avis.js
        Error loading file://c:/xxx/xxx/xxx/jspm_packages/npm/babel-runtime@5.5.1/helpers/to-consumable-array.js
    at Gulp.emit (events.js:129:20)
    at lib$rsvp$$internal$$tryCatch (c:\wamp\www\adv\node_modules\systemjs-builder\node_modules\rsvp\dist\rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (c:\wamp\www\adv\node_modules\systemjs-builder\node_modules\rsvp\dist\rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (c:\wamp\www\adv\node_modules\systemjs-builder\node_modules\rsvp\dist\rsvp.js:472:11)
```

For babel-runtime@5.5.1, i got undefined

Below, my builder task

```js
gulp.task('systemBuilder', function () {
    var builder = new Builder();

    return builder
    .loadConfig('./jspm.conf.js')
    .then(function () {
        // additional config
        builder.config({
            baseURL: 'file:' + path.resolve(process.cwd()),
            paths: {
                '*':  options.tmpFile + '/*.js'
            }
        });

        return builder.build(
            'avis',
            options.tmp + '/build.js',
            {minify: true, sourceMaps: true}
        );
    });
});
```

**Comment by YoannDelpierre** [comment]
Ok I think i have a clue, i have a problem with System.register, because if i'm looking my js file, my first argument is `babel-runtime/helpers/to-consumable-array`

So i think it's when i want to register modules that i have my error.

**Comment by YoannDelpierre** [comment]
After some test, i think it's my baseURl from ma builderConfig

I have `baseURL: 'file:' + path.resolve(process.cwd()` into my builder.config

I log my config into Builder.protopye.config and i got this

```js
{ baseURL: '/',
  transpiler: 'babel',
  babelOptions: { externalHelpers: true, stage: 1, optional: [ 'runtime' ] },
  paths:
   { '*': '*.js',
     'github:*': 'jspm_packages/github/*.js',
     'npm:*': 'jspm_packages/npm/*.js' } }
{ baseURL: 'file:c:\xxx\\xxx\\adv',
  paths: { '*': '.tmpFile/*.js' } }
```

My **baseURL: 'file:c:\\wamp\\www\\adv'** is not correct for Node

**Comment by YoannDelpierre** [comment]
OK i changed my base Url for relative path

I don't have anymore errors about format URL for node.

Some troubles on error: ENOENT when systemjs-builder try to open a file :smile:

**Comment by guybedford** [comment]
Is it still providing an error specifically for the Babel runtime files? Do the files exist in the file system?

**Comment by YoannDelpierre** [comment]
For babel-runtime it's ok for the moment, i solved it with installing babel-runtine with Node and it's ok without

But the main problem in fact, after lots of tests, is i can not get file with the builder, dont know why for the moment.

My imports are broken i suppose...

On Windows

```
[15:41:43] Error: ENOENT, open 'c:\xxx\xxx\xxx\.tmpFile\modules\main\module' at Error (native)
```

I have this file into my path

![image](https://cloud.githubusercontent.com/assets/1655301/8007196/88b072fe-0b9a-11e5-87e3-fbf7a333d8cc.png)


On Debian with Jenkins

```
[15:44:57] Error: ENOENT, open '/var/lib/jenkins/jobs/xxx/workspace/.tmpFile/modules/main/module'
```

The same thing, i have it in my path

![image](https://cloud.githubusercontent.com/assets/1655301/8007242/cce2eb28-0b9a-11e5-862d-028fc2b33079.png)

**Comment by guybedford** [comment]
Which version of SystemJS / SystemJS Builder are you using?

**Comment by YoannDelpierre** [comment]
SystemJS v0.16.11

SystemJS Builder 0.11.3

**Comment by guybedford** [comment]
Are you using the `defaultJSExtensions` option?

**Comment by YoannDelpierre** [comment]
No.

I changed all of my imports, it's ok.

But still an error `[17:10:04] Error: ENOENT, open 'c:\wamp\www\adv\jspm_packages\npm\babel-runtime@5.5.3\core-js\array\from'`

I believe that it's babel-runtime/core-js/to-consumable-array.js which breaks it...

Thanks fo your help

**Comment by guybedford** [comment]
Right, yes Babel runtime does not yet support not having the `defaultJSExtensions` option enabled. Note that jspm itself does not support `defaultJSExtensions` disabled yet, so this issue will be pending that work. Closing for now as this will happen naturally in time.
