### ISSUE TITLE
`.js` suffix should not be included in import

### ISSUE THREAD

**Issue by SonofNun15** [systemjs/builder#186]
In README.md, the sample content for app.js includes: 
```
import $ from "./jquery.js";
```
Per this article (http://www.2ality.com/2014/09/es6-modules-final.html) on the final syntax for ES6 modules, it appears that ".js" is the default extension and should not be required on imports. However, when using systemjs builder, my imported modules are not found / can't be loaded if ".js" is not included.

**Comment by guybedford** [comment]
This was changed, and is part of the upgrade to SystemJS 0.17 / Builder 0.11. Module specifiers are now URLs with extra rules as opposed to a completely separate system.

**Comment by SonofNun15** [comment]
How was it changed? I'm using version 0.11 of the builder and this problem is still occurring. Can you explain how I can resolve this issue?

**Comment by SonofNun15** [comment]
Appears to be related to this configuration option: https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#defaultjsextensions

**Comment by mikehaas763** [comment]
>Module specifiers are now URLs with extra rules as opposed to a completely separate system.

Can you elaborate? Maybe you just meant "paths", because ES6 modules are not dependent on a browser environment. Also, what did you mean by it not being "a completely separate system".

**Comment by guybedford** [comment]
@mikehaas763 module specifiers are typically URLs now as the browser loader does assume a browser environment. When on the server all paths are URLs of the form `file:///`.

**Comment by mikehaas763** [comment]
@guybedford It was just odd to hear it called that to me because the term URL is defined in a document intended for internet standards. When loading modules in a node like environment directly from a filesystem, the internet is not involved.

**Comment by guybedford** [comment]
URLs are used in the browser loader standard. When we run the browser loader in Node, using URLs is the most natural way to do this. It means all the same resolution functions work without needing to worry about adapting them to file pathing rule differences. Note that typically users don't need to provide file URLs, as input paths are considered relative URLs to the baseURL, and the baseURL itself a relative path to the current directory.
