### ISSUE TITLE
upgrade to 0.11.x from 0.10.x

### ISSUE THREAD

**Issue by lookfirst** [systemjs/builder#190]
I just got upgraded to 0.11.x and now it seems like I need a .js extension on things, but that doesn't seem to be supported until systemjs 0.17.x.

**Comment by guybedford** [comment]
Did you run `jspm install` or `jspm init` to upgrade your configuration file? Bundling directly on the upgrade first will cause an issue. May be worth fixing this for the main release though as it is a catch - tracking at https://github.com/jspm/jspm-cli/issues/817.

**Comment by lookfirst** [comment]
I did run jspm install.

**Comment by guybedford** [comment]
What's the specific issue? Have you got `defaultJSExtensions` in the package.json?

**Comment by lookfirst** [comment]
Nothing like that changed in the file. In fact, it wasn't even clear from any of the documentation that `defaultJSExtensions` would go into the package.json.

**Comment by guybedford** [comment]
Sorry I mean `config.js` not package.json.
