### ISSUE TITLE
css loaded from jspm_packages

### ISSUE THREAD

**Issue by YoannDelpierre** [systemjs/builder#192]
Hello,

About css from jspm_packages which are imported in ES6, how can i add it to my bundle.css ? Is it possible ? Or exclude them ?

When i'm making a build into jenkins, i transfer only a dist repo on the final server without jspm_packages, so i have 404 on http request for those css. So do i need to copy jspm_packages or any solution?

Thanks

**Comment by guybedford** [comment]
See https://github.com/systemjs/plugin-css for builder support for CSS.

**Comment by YoannDelpierre** [comment]
Yes i saw this.

If i'm correct, i don't need separateCSSS to be true, because i need to have the same name.

And for buildCSS, i think i need to be false for my case. But i have still request.

I'm quite lost about this point, sorry

**Comment by guybedford** [comment]
Did you try following https://github.com/jspm/jspm-cli/wiki/Plugins#using-plugins?

**Comment by YoannDelpierre** [comment]
Yes i'm already using CSS plugins

My CSS, from files into jspm_packages, are loaded with `!`

I continue to search about

**Comment by guybedford** [comment]
Then `jspm bundle app` will bundle your CSS files and inline it in the JS file automatically.
