### ISSUE TITLE
builder is incapable of loading modules defined without '.js' extension

### ISSUE THREAD

**Issue by vatula** [systemjs/builder#194]
When I have this in index.js (an entry point)

```
import {AbstractClassError} from './errors.js';
import {SomeFile}                from './somefile';
import {SomePlugin}            from './someplugin.js';

export {AbstractClassError, SomeFile, SomePlugin};
```

then builder throws exception:

```
Trace: [Error: ENOENT, open 'j:\oddy\workspace\github\proj\src\main\javascript\com\lorem\ipsum\somefile'
	Error loading file:///j:/oddy/workspace/github/proj/src/main/javascript/com/lorem/ipsum/somefile from file:///j:/oddy/workspace/github/proj/src/main/javascript/com/lorem/ipsum/index.js
	Error loading file:///j:/oddy/workspace/github/proj/src/main/javascript/com/lorem/ipsum/somefile]
```

When I define an extension to **somefile**, then the error is gone.

It is acceptable to have modules without extensions.
No other builders/transpilers/IDEs have issues in recognizing modules without extension in this list:

 * webpack (builder)
 * traceur (transpiler)
 * babel (transpiler)
 * browserify  (builder)
 * Intellij IDEA (IDE)

**Comment by guybedford** [comment]
There are three ways of handling this in SystemJS:

1. Have a map or paths configuration  - `System.config({ map: { jquery: 'path/to/jquery.js' } })`
2. Use the legacy compatibility mode for automatically adding extensions - `System.config({ defaultJSExtensions: true })`
3. Configure the default extension rule for a package created at that location - https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages

The ES6 browser loader spec stopped the rule of automatically appending extensions. So this is the way things are going now.

**Comment by guybedford** [comment]
In terms of best-practices the thing to do is:

* Leave out extensions for packages (`import 'jquery'` etc)
* Include extensions for any paths (`import './file.js'`)
* Subpaths of packages are still a somewhat grey area though (`import 'jquery/subpath'` or `import 'jquery/subpath.js` could both be considered viable, depending on the configuration in play)

**Comment by vatula** [comment]
Why things are like that in system.js? According to the spec in mdn, it is not the best practice. 

Module identified does not have to have extensions. Examples in spec don't use extensions either.

Having/not having extensions occasionally does not contribute to consistency. Why is it recommended approach then?

**Comment by guybedford** [comment]
The recommended approach is exactly as I described in the previous comment. The module loader specification changed from having module ids without js extensions to making them expected.

**Comment by guybedford** [comment]
Basically the reasoning was to make module ids as close to URLs as possible, and to make moduleIds compatible with URLs. Since URLs are already the primary specifier of the web, having a system that contains URLs as a subset is much more useful and makes sense to more users.

**Comment by zeeshanjan82** [comment]
I have a related issue and would like to get your feedback @guybedford 
After upgrading jspm to the latest version I am facing issues with regard to importing html files in my ES6 classes. Everything was working fine in the older release and the line of code: 
````js
import ProviderGalleryTemplate from './provider-gallery.tpl';
````
was working as expected and importing the provider-gallery.tpl.html file but now it does not work. I have put defaultJSExtensions to true in system.config.js file. How can I make system to recognize the extension for the html pages which I am importing in js files.
