### ISSUE TITLE
Relative loading

### ISSUE THREAD

**Issue by m0ppers** [systemjs/builder#196]
I am not exactly sure if i really hit a bug but i can't seem to find anything about it and i am lost now :S 

```javascript
var Builder = require('systemjs-builder');

var builder = new Builder();
builder.config({baseURL: 'web/', paths: {'*': '*.js'}, transpiler: 'babel'});
builder.build('test', 'web/js/build.js')
.then(function() {
    console.log('SUCCESS');
})
.catch(function(err) {
    console.log('ERR', err);
});
```

in my web directory i have:

test.js:
```javascript
import './test2';
```

Then when executing:
```
hans-guenther:dingo mop$ iojs build.js 
ERR [Error: ENOENT: no such file or directory, open '/Users/mop/projects/xxx/web/test2'
	Error loading file:///Users/mop/projects/xxx/web/test2 from file:///Users/mop/projects/xxx/web/test.js
	Error loading file:///Users/mop/projects/xxx/web/test2]
```

It can't find the real file because it doesn't append '.js'. This only happens when building. I have the same setup working properly in the webbrowser :S 

This only happens when doing relative requires. When doing:

```javascript
import 'test2';
```

Everything is working fine.

**Comment by guybedford** [comment]
It sounds like you're running SystemJS 0.16 in the browser against builder 0.11? See the release notes on SystemJS 0.17 (which corresponds to builder 0.11) for more info on the js extensions issue - https://github.com/systemjs/systemjs/releases/tag/0.17.0.

**Comment by m0ppers** [comment]
yep. that's it
