### ISSUE TITLE
process.env.NODE_ENV dead code removal

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#197]
The CommonJS compiler can detect this expression as part of its transformation and inline it as `"production"` as part of the build process.

While not strictly the correct separation of concerns, it's simple and fits with the majority use case to make this useful.

This should get the footprint of React down (/cc @jackfranklin).

**Comment by guybedford** [comment]
@jackfranklin in my tests this has knocked off 45KB unminified from React.

**Comment by jackfranklin** [comment]
Awesome! Great stuff :+1:

**Comment by guybedford** [comment]
Released in 0.12.0.

**Comment by alexisvincent** [comment]
@guybedford How is this actually used?

**Comment by guybedford** [comment]
Just to note my response from Gitter:

> `process.env.NODE_ENV` dead code removal applies automatically in SystemJS builder for the CommonJS module format with minification enabled
