### ISSUE TITLE
Fix transformation mutation cases

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#198]
We're mutating the tree in https://github.com/systemjs/builder/blob/master/compilers/amd.js#L82 and https://github.com/systemjs/builder/blob/master/compilers/esm.js#L11, which can cause issues for parallel builds.

**Comment by OliverJAsh** [comment]
Is it worth me grabbing this one? Not sure how big it is

**Comment by guybedford** [comment]
It involves using Traceur transformer parse tree constructors in place of the mutations in the links above.

For example, in the first one `depTree` is an ArrayLiteralExpression, so we need to construct a new ArrayLiteralExpression with the given children, instead of mutating it.

The hard part is then working out from the Traceur source code how to construct the ArrayLiteralExpression.

**Comment by guybedford** [comment]
The parse tree mutations shouldn't cause any conflicts now, but there may still be other issues with parallel builds.
