### ISSUE TITLE
Improved load errors

### ISSUE THREAD

**Issue by nyarly** [systemjs/builder#201]
I'm attempting to translate a large-ish Traceur project to SystemJS, and while I was able to fix most of the map conversions, it was with some difficulty. Traceur's output on a failed load was extremely useful. It lists: 
* the host file (as opposed to the root of the bundle)
* the actual import name as used
* how it was normalized. (i.e. the information SystemJS provides)

It's a little chatty, but really helped pin down exactly what the problem was and made it much easier to put together map configurations.

**Comment by guybedford** [comment]
Sure, and thanks for posting here. What would you suggest for including this information in the current compiler we have?

**Comment by nyarly** [comment]
I'm not sure what you mean? Code-wise, maybe I can rustle up time for a PR. 

I assume you're not expecting "builder should emit this information with a load error" right?

**Comment by guybedford** [comment]
A PR contribution would be incredibly welcome here given your recent experience with it.

Otherwise will certainly look into it when I can.

**Comment by nyarly** [comment]
Digging into this, I realize that it's an example of https://github.com/ModuleLoader/es6-module-loader/issues/397 (with some of https://github.com/ModuleLoader/es6-module-loader/issues/399 to go with) - the issue should be addressed there, at which point this solves itself, so to speak.

**Comment by guybedford** [comment]
So your issues were specific examples of those cases?

**Comment by nyarly** [comment]
Tracking it down, the errors are generated within es6-module-loader. Because of the ENOENT related bug, they don't (I think?) show up as proper Error objects in SystemJS. As a result, the best that could be hoped for in "builder" would be a regexp match against the error message and then a new Error raised.

But: what I'm looking for here is exactly what https://github.com/ModuleLoader/es6-module-loader/issues/397 is talking about. The right fix, then, would seem to be to address that issue (and 399) so that ML reports the issue with loading.

**Comment by guybedford** [comment]
Thanks for the update - great to know, will get to those as soon as I can.
