### ISSUE TITLE
"Unable to calculate canonical name to bundle"

### ISSUE THREAD

**Issue by nyarly** [systemjs/builder#202]
I'm attempting to build an SFX for files on the local filesystem. The command I'm issuing is like
```
builder.buildSFX("../web/src/app/app.js", "bin/assets/application.js");
```

I get this error:
```
Unable to calculate canonical name to bundle file:///home/[...]/web/web/src/app/app.js
```

A little investigation reveals that this is happening when builder attempts to getCanonicalName for the root of the tree. A workaround appears to be to set up paths configuration for SystemJS - even just 
```
"../web/src/app/app.js": "../web/src/app/app.js"
```
works around this, but it's surprising.

**Comment by guybedford** [comment]
You need to set the baseURL to below the module path so it can be used as a reference point.

Alternatively, exactly as you've worked out paths config can indicate naming. For example `app: '../web/src/app/app.js'` and then import `app` in your code.

**Comment by nyarly** [comment]
The key thing here is that it's the entry-point for the SFX that raises the error. It isn't imported anywhere.

Could you elaborate on how the baseURL is used? I can't find an explanation anywhere of that.

**Comment by guybedford** [comment]
baseURL is simply the reference point when bundling. Your entry point should be within it.

**Comment by guybedford** [comment]
Basically `import 'x'` with no other rules loads relative to baseURL.

**Comment by nyarly** [comment]
Aha - I was noticing a different in map behaviors when 'x' referred to a single file vs. "y/z.js" when y mapped to a directory. I see how that works now.

"Your entry point should be within it" is the key data here, I think.

**Comment by enlait** [comment]
@guybedford I try to build a mixed java/js project with following layout:

src/main/java
src/main/js
node_modules
WebContent <- has all the stuff that gets packaged into webapp archive
WebContent/js <- my js build output goes here

So I try following build configuration: 
```
var builder = new Builder({
	transpiler: 'babel',
	baseURL: './src/main/js',
	map: {
		react : '../../../node_modules/react/dist/react.min.js'
	},

});
```
and it doesn't work for the same reason. How should I work around this issue?

**Comment by guybedford** [comment]
Try setting up react as a path instead of a map config.
