### ISSUE TITLE
SFX bundle registered module name

### ISSUE THREAD

**Issue by dsebastien** [systemjs/builder#203]
Hello,

I would like to know if there is a way to modify the way System.register(..) calls are generated when creating an SFXBundle? More specifically, I would like to know if I can control the name of the modules that are registered.

In my gulp build, I'm doing the following:
```
	var Builder = require('systemjs-builder');
	var builder = new Builder();
	return builder.loadConfig(config.files.jspmConfigFile)
		.then(function() {
			builder.buildSFX(
				config.javascript.srcDist,
				config.javascript.destDist,{
					sourceMaps: false,
					minify: false,
					mangle: false,
					sfxFormat: 'amd', // to output the SFX bundle in the AMD module format
					// runtime: false, // to exclude the Traceur or Babel runtime
					globalDefs: {
						DEBUG: false
					}
				}
			)
			.then(function() {
				return cb();
			})
			.catch(function(ex) {
				cb(new Error(ex));
			});
		});
```

Which for now only takes a 'core.bootstrap.js' file as input:

```
console.log('Hello world!');
```

With this, the bundle is created correctly, but the System.register calls use an absolute path rather than a relative one:

```
(['c:/dev/wks/midnightLightV2/.tmp/core/core.bootstrap'], function(System) {

System.register("c:/dev/wks/midnightLightV2/.tmp/core/core.bootstrap", [], function(_export) {
  'use strict';
  return {
    setters: [],
    execute: function() {
      console.log('Hello world!');
    }
  };
});
```

Instead of this, I would just like to have 'core/core.bootstrap'

I'd happily walk through the source of systemjs-builder to understand what it does but I have yet to learn how to debug nodejs/gulp code :)

**Comment by guybedford** [comment]
Can you share what your `process.cwd()` is for the build? And your baseURL?

Basically baseURL is supposed to avoid this and you should never get paths like this. Would be good to track it down to fix it.

**Comment by dsebastien** [comment]
I've just understood that jspm's config file's 'baseURL' influences the generated name.
By changing the baseURL to './' I now get the following which is closer to what I need but not exactly:

```
(['.tmp/core/core.bootstrap'], function(System) {

System.register(".tmp/core/core.bootstrap", [], function(_export) {
  'use strict';
  return {
    setters: [],
    execute: function() {
      console.log('Hello world!');
    }
  };
});
```

My problem with this is that the '.tmp' folder is.. temporary and doesn't exist once the packaging is over

Maybe a bit of information about my file structure could help:
* app/
  * core
    * core.bootstrap.js (gets transpiled using babel towards the same path in the .tmp/core folder)
* .tmp/
  * core
    * core.bootstrap.js (the transpiled file is saved here and is used as input for my systemjs-builder's SFX bundle
* gulpfile.babel.js
* jspm.config.js

**Comment by dsebastien** [comment]
The process cwd is the root folder of my project, which is under c:\dev\wks\midnightLightV2 (under which I have the file structure described above)

**Comment by guybedford** [comment]
And your value for config.javascript.srcDist?

**Comment by dsebastien** [comment]
srcDist: folders.temp + '/core/core.bootstrap.js',

-> ./.tmp/core/core.bootstrap.js

**Comment by guybedford** [comment]
If you're using jspm I'd suggest running builds via the jspm API - https://github.com/jspm/jspm-cli/wiki/API-Usage#bundleexpression-filename-options---promise. It will ensure your jspm_packages paths work out as well then.

Otherwise if you're set on this method, just shift the baseURL to `./.tmp` and then manually adjust the paths to `paths: { 'github:*': './jspm_packages/github/*' }` ( assuming you're running the jspm beta ).

**Comment by dsebastien** [comment]
Thanks for the info, I'll check that out. I just found the correct baseURL value while trying :)
I'm not set on much yet, I'm still in exploration mode so any improvement is very welcome.

Apart from more flexibility, what will I gain by using the jspm API? Will I still be able to use things like the css plugin later on?

Thanks Guy!

**Comment by guybedford** [comment]
The jspm APi is the same builder API instance, but it just comes pre-configured with the correct defaults for jspm.

**Comment by dsebastien** [comment]
I can't seem to get it working using the jspm api.

Here's what I've tried:

```
	var jspm = require('jspm');
	jspm.setPackagePath('.');
	return jspm.bundleSFX(
		config.javascript.srcDist,
		config.javascript.destDist,{
			sourceMaps: false,
			lowResSourceMaps: false, // can speed up generation
			minify: false,
			mangle: false,
			sfxFormat: 'amd', // to output the SFX bundle in the AMD module format
			// runtime: false, // to exclude the Traceur or Babel runtime
			globalDefs: {
				DEBUG: false
			}
		}
	);
```

Whatever I put in baseURL, I always end up with the following in the sfx bundle:

```
(['.tmp/core/core.bootstrap.js'], function(System) {

System.register(".tmp/core/core.bootstrap.js", [], function(_export) {
  'use strict';
  return {
    setters: [],
    execute: function() {
      console.log('Hello world!');
    }
  };
});
```

**Comment by guybedford** [comment]
That's correct - the baseURL in jspm is always the same reference point in the filesystem.

**Comment by dsebastien** [comment]
I'm a bit confused about how I should approach this; I think that for now I'll just leave this aside as it works but is just a bit 'ugly'.

Ideally I guess that to bypass my issue it would be nice to be able to alias some paths, knowing that they'll differ in production. In my case, .tmp/ only exist during builds and isn't there once in production; there I only care about the 'core/...'.

Sorry if this isn't clear, but not that much is very clear for me yet. I'm still in the process of learning about ES6 modules, TypeScript internal vs external modules, module packaging etc etc ;-)

**Comment by guybedford** [comment]
@dsebastien paths are exactly for this sort of aliasing that alters:

```javascript
System.config({
  paths: {
    'core/*': '.tmp/*'
  }
});
```

Where the path rule can change between environments.

**Comment by dsebastien** [comment]
Thanks Guy. I've got what I wanted using the following: "core/*": "./.tmp/core/*" and "./" as baseURL. Now the generated module's System.register only mentions "core/..." as I needed.

You can close this issue now, thanks. I'll post a link to my code's working revision once committed, just in case it can be useful to somebody else.

**Comment by guybedford** [comment]
Great, glad to hear you sorted it out.
