### ISSUE TITLE
Minimal SystemJS loader does not detect node environment

### ISSUE THREAD

**Issue by tengyifei** [systemjs/builder#204]
When using the full-fledged SystemJS loader, `System._nodeRequire` is properly set, but the field is absent in `buildSFX`, which poses problems when the resulting script is loaded in a hybrid-browser-node environment such as Electron.

It would be great if there is an API that allows extending the minimal SystemJS loader.

**Comment by guybedford** [comment]
Thanks, I've added this in https://github.com/systemjs/builder/commit/9a7fd5a9d75ec9b8941e0dbfeb510179d07d621f.

**Comment by tengyifei** [comment]
How about allowing users to extend the SystemJS loader during build time? This would be more future-proof in case anyone find themselves in need of more features. We are using jspm so I guess it would take a long time until this gets incorporated.

**Comment by guybedford** [comment]
The sfx use case is entirely about excluding dynamic loading scenarios, so I'm not sure I see the benefit extending features. For normal bundles, this is certainly something that is possible though by extending SystemJS directly.

**Comment by tengyifei** [comment]
Yes it's indeed about non-dynamic scenarios. What I'm referring to is the ability to add a property to core SystemJS e.g. `_nodeRequire` during `buildSFX`. This opens up new possibilities such as custom `register` and `import` implementations that are baked into the SFX bundle and can be safely minified. It also lets people cleanly patch SystemJS while waiting for some bug fixes to be released (which I had to in the case of `_nodeRequire`).

**Comment by guybedford** [comment]
Released in 0.12.1.
