### ISSUE TITLE
TypeScript bundling should generate compile errors

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/builder#206]
It is my understanding that [transpiling TypeScript (in the browser) does not generate compile errors (when there are any)](https://github.com/Microsoft/TypeScript/issues/2808).

When bundling we should do a whole compile (different from a transpile), which will generate compile errors. Currently we transpile [in the browser and when bundling](https://github.com/systemjs/builder/blob/7a71fdb39a98adc219fc7daa5d7a14ce190e3aa1/compilers/esm.js#L104).

**Comment by OliverJAsh** [comment]
See https://github.com/Microsoft/TypeScript/issues/2233#issuecomment-113368137.

**Comment by chadbr** [comment]
So is there any ETA for this?

**Comment by janua** [comment]
This would be wonderful!

**Comment by frankwallis** [comment]
FYI - I have added type-checking support to [plugin-typescript](https://github.com/frankwallis/plugin-typescript) so you are welcome to give that a try. You will need to use version 2.0.0-beta. 

There is an example project there showing the configuration, and if you have any issues then please raise them on that repo. It is pretty much feature complete, I have a couple of tasks left to look at the performance/caching when run as a watch task.

**Comment by guybedford** [comment]
This is also related to https://github.com/systemjs/systemjs/issues/595 for ensuring that helper code is not included within the System.register wrapper.

**Comment by guybedford** [comment]
@vladima let me know if there is anything we can do here - currently syntax errors don't seem to give any warnings when compiling with TypeScript.

**Comment by OliverJAsh** [comment]
By the sounds of https://github.com/jspm/jspm-cli/issues/1009#issuecomment-129605086, this is by design?

**Comment by guybedford** [comment]
The current focus for TypeScript support is via https://github.com/frankwallis/plugin-typescript which I believe gives better errors too.
