### ISSUE TITLE
Overwriting exports?

### ISSUE THREAD

**Issue by ahmedshuhel** [systemjs/builder#214]
Aren't we overwriting [this export ](https://github.com/systemjs/builder/blob/master/lib/builder.js#L11) with [this one](https://github.com/systemjs/builder/blob/master/lib/builder.js#L482) ? 

Shouldn't it be like:
```javascript
module.exports.getCanonicalName = getCanonicalName
module.exports.Builder = Builder;
```
Although, this may break a lot of other libs that depends on this. 
Could we add `getCannonicalName` func to `Builder's` prototype instead?

**Comment by guybedford** [comment]
Yes that would be a mistake!

Happy for it to be a static though, so not part of the prototype - `Builder.getCanonicalName`.

**Comment by guybedford** [comment]
Actually sorry, yes you're completely right - a prototype method would make the most sense as it needs the loader instance.

**Comment by ahmedshuhel** [comment]
Should I make a PR for this? Right now, Is there anything other than [arithmetic.js](https://github.com/systemjs/builder/blob/master/lib/arithmetic.js#L103) depends on it?

**Comment by guybedford** [comment]
@ahmedshuhel that would be amazing if you can.

**Comment by ahmedshuhel** [comment]
Great! I am on it.

**Comment by ahmedshuhel** [comment]
@guybedford Please review. 

Would it be better if we factor out [getCanonicalName](https://github.com/ahmedshuhel/builder/blob/57332989537f877f8eda90769327e5cd7ade4541/lib/builder.js#L40) from `builder` to a separate module? It may be useful in some cases to use a `static` function like this. 

 We may place it in `utils.js` as this houses all the static functions at the moment.

**Comment by guybedford** [comment]
We're trying to avoid statics as it adds unnecessary complexity to the API.

**Comment by guybedford** [comment]
Thanks, looking good.

**Comment by ahmedshuhel** [comment]
@guybedford Inlined the func. Thank you.

**Comment by guybedford** [comment]
@ahmedshuhel thanks for your help pushing this through.
