### ISSUE TITLE
"window is not defined" when subtracting app-vendor.js

### ISSUE THREAD

**Issue by jackfranklin** [systemjs/builder#216]
We're working on moving our app to jspm, and in development bundling the app into one file through a watch task, that should be quick using the new caching in the SystemJS builder.

Here's what currently happens:

- we run `npm start` to boot the dev server
- this runs `jspm bundle app/boostrap - [app/**/*] client/app-vendor.js`. This gives us `app-vendor.js` which all the 3rd party components in (ie, the things that very rarely change - Angular, LoDash and so on)
- we then kick off the initial JS build, with some JS that looks like below (this is all very rough!), the goal being to produce `client/dev-bundle.js`, which contains all the modules __except__ those in `app-vendor`.

```js
function build(fileChanged) {
  var builder = new jspm.Builder();
  builder.loadConfig('./config.js')
  return builder.build('app/bootstrap.js - app-vendor.js', 'client/dev-bundle.js', {
    minify: false,
    inject: true,
  }, cache).then(function(output) {
    console.log('Build FINISHED');
  }).catch(function(err) {
    console.log('build error', err);
  });
}
```

However, upon running we get a build error:

```
 ReferenceError: window is not defined
        Evaluating file:///Users/jackfranklin/git/gocardless/enterprise-dashboard/client/app-vendor.js
        Error loading file:///Users/jackfranklin/git/gocardless/enterprise-dashboard/client/app-vendor.js
```

I'm not really sure what to do here. What I want to do is build `client/dev-bundle.js`, which contains all the modules __not__ includes in `app-vendor.js`. How would I go about doing that? As usual, pretty convinced this is a user error rather than a SystemJS bug, and as usual thanks in advance for your help!

**Comment by jackfranklin** [comment]
Actually, this looks very related to https://github.com/systemjs/builder/issues/211. Is it the same deal?

**Comment by guybedford** [comment]
I don't think this is related to #211. Can you confirm you are running the latest versions of SystemJS and SystemJS beta? It may be a bug.

**Comment by guybedford** [comment]
I believe this is the same issue as https://github.com/systemjs/builder/issues/222. Considering options here.

**Comment by jackfranklin** [comment]
@guybedford ah sorry I never got round to replying. Looks like a related issue, although AMD doesn't come into play in our app. I'll confirm tomorrow but pretty sure that I am running the latest beta of SystemJS (through jspm).

**Comment by guybedford** [comment]
Oh ok, would be good to know the module format - if it's related.
