### ISSUE TITLE
Migration path from bower / <script> tags to SystemJS

### ISSUE THREAD

**Issue by laurentgoudet** [systemjs/builder#217]
I am trying to come up with a migration path for a large AngularJS code base shared between many different applications. Application developers are consuming modules from this shared library by injecting them manually in `<script>` tags.

I want to clean that mess up & introduce ES6 Modules & SystemJS. However, I cannot change all the existing applications at once and need to find a migration path allowing me to use ES6 modules (imports/exports) while still exporting the modules in the old self-executing format.

For that, I created the following script listing of the dependencies of a module & adding them to the `meta` `build: false` config. However, when executing these SFX bundles SystemJS complains that the dependencies are not available.

Is there a way to flag a dependency as `global` so that SystemJS just ignores it? And is there a better way to do what I am trying to achieve, as SFX bundles add a non-significant overhead (400B -> 11K)?

```js
import glob from 'glob';
import path from 'path';
import Builder from 'systemjs-builder';

const builder = new Builder();

builder.loadConfig('./config.js').then(() => {
  // get the modules list
  return new Promise((resolve, reject) => {
    glob('src/**/!(*.spec|*.mock).js', (err, files) => {
      if (err) reject(err); else resolve(files);
    });
  });
}).then((files) => {
  // create standalone self-executable System modules
  return Promise.all(files.map(file => {
    // module name, e.g. 'lg-validation/validation'
    const module = path.relative(path.join(__dirname, 'src'),  file.slice(0, -3));
    // module dest, e.g. 'dist/lg-validation/validation.js'
    const dest = path.join('dist', module + '.js');
    // gets the module deps first
    return builder.buildSFX(module).then(output => {
      // filter out the deps
      const deps = output.modules.filter(dep => {
        return dep !== module;
      });
      // build the arithmetic string
      let meta = {};
      deps.map(dep => {
        meta[dep] = { build: false };
      });
      // build the module without any deps
      // TODO: we shouldn't need to instantiate a new builder here
      const builder = new Builder();
      return builder.loadConfig('./config.js').then(() => {
        return builder.buildSFX(module, dest, {config:{meta}});
      });
    }).then(() => {
      console.log(`created bundle ${module} in ${dest}`);
    });
  }));
}).then(() => {
  console.log('done');
}).catch(err => {
  console.log(err);
});
```

**Comment by guybedford** [comment]
SFX modules with unbuilt dependencies is a workflow that will be possible in future but isn't currently. See https://github.com/systemjs/builder#adapter-modules for an approach that can be used here.

If you're interested in contributing to or sponsoring development on the SFX dependencies feature I'm always happy to discuss too.

**Comment by laurentgoudet** [comment]
Thanks, that's exactly what I ended up doing by using setting map config pointing the dependencies to adapter modules in the build script above.
