### ISSUE TITLE
Cannot override baseURL using builder.config();

### ISSUE THREAD

**Issue by kenkouot** [systemjs/builder#218]
If I have a config file generated by jspm with a the following code:
```js
System.config({
  baseURL: 'foo'
});
```
and I try to load config, then override (a la the examples from the README)
```js
var Builder = require('systemjs-builder');
var builder = new Builder();
builder.loadConfig('./path/to/cfg.js')
  .then(function () {
    builder.config({baseURL: '.'})
  })
```
I get the following error: `[TypeError: baseURL should only be configured once and must be configured first.]`

This is on 0.12.2 of the builder.

**Comment by guybedford** [comment]
Yes, the baseURL needs to be set before loading configuration.

**Comment by guybedford** [comment]
Note that if you are using jspm, it is preferable to use jspm's wrapped builder class which is pre-configured correctly.
