### ISSUE TITLE
can't figure out even a basic project...

### ISSUE THREAD

**Issue by lookfirst** [systemjs/builder#225]
trying to setup a basic project with latest jspm/builder/systemjs and it just won't work.

https://github.com/lookfirst/broken

```
npm install
gulp
```

@guybedford I gave you commit access. I'd love it if you could figure this out.

**Comment by nathanboktae** [comment]
You too? simply going `new Builder()` in gulp blows up for me. You're much farther along.

```javascript
var Builder = require('systemjs-builder')
gulp.task('build', function () {
  var builder = new Builder()
})
```

results in:

```
[16:59:48] Using gulpfile ~/work/clean-portal/client/gulpfile.js
[16:59:48] Starting 'build'...
[16:59:48] 'build' errored after 91 ms
[16:59:48] ModuleEvaluationError: undefined is not a function
    at needsPolyfill (/Users/nblack/work/clean-portal/client/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:1879:34)
    at polyfillMap (/Users/nblack/work/clean-portal/client/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:1889:9)
    at /Users/nblack/work/clean-portal/client/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:1553:14
    at Array.forEach (native)
    at polyfillAll (/Users/nblack/work/clean-portal/client/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:1552:15)
    at /Users/nblack/work/clean-portal/client/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:3494:3
```

I cloned your project and tried `./` as the baseURL as I had to do that to get mine working (outside of gulp) but no dice for your issue. Also tried `.`. btw thanks for the `angularjs-systemjs-seed` project - I used that a lot.

**Comment by lookfirst** [comment]
That exception looks like some weirdness with a traceur default? I've also noticed that traceur gets added to my jspm devDeps... which seems kind of weird given that I don't want to use it and specify babel for things.

**Comment by guybedford** [comment]
Yes Traceur is used for builder transformations.

@lookfirst as mentioned in gitter, using paths for setting extensions is no longer supported as in https://github.com/lookfirst/broken/blob/master/gulpfile.babel.js#L38. Rather remove the default extensions here.

@nathanboktae are you able to just require Traceur? Like `require('systemjs-builder/node_modules/traceur/bin/traceur.js`)?

**Comment by lookfirst** [comment]
If I use the jspm builder, then I get the "[10:42:06] TypeError: baseURL should only be configured once and must be configured first.", but if I use the systemjs-builder builder, then things are ok. I've updated the broken project mentioned above to show you.

There is also an issue where the source map urls that are generated at the top level are based at the wrong url root. it goes up one level of `../` too much.

**Comment by nathanboktae** [comment]
> @nathanboktae are you able to just require Traceur? Like require('systemjs-builder/node_modules/traceur/bin/traceur.js)?

Nope I'm not - which leads to some odd interaction between gulp and Traceur, so I didn't file an issue here. Also systemjs-builder still needs it even though you specify `babel` as the transpiler, or don't use ES6 code.

**Comment by guybedford** [comment]
@lookfirst thanks, can you share a test case by any chance with the source map URL issue?

@nathanboktae that's really strange you can't even require Traceur in Node. It sounds like an interaction unrelated to jspm, but if you can share the code I can try to take a look. As mentioned in the previous comment we always use Traceur for additional code transformations during builds, even when transpiling via Babel.

**Comment by lookfirst** [comment]
@guybedford clone the broken project that I mentioned before, npm install and run gulp and look at the generated map file.

**Comment by guybedford** [comment]
@lookfirst I've sent https://github.com/lookfirst/broken/pull/1 with your fixes.

**Comment by guybedford** [comment]
Closing to follow-up separate issues as described in https://github.com/lookfirst/broken/pull/1#issuecomment-120992280.
