### ISSUE TITLE
Investigate source maps relative URLs

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#230]
Example project at https://github.com/lookfirst/broken/tree/ecd24391f6bb21a8e56f8b9c889555118c611112.

See comment https://github.com/lookfirst/broken/pull/1#issuecomment-120744283.

**Comment by guybedford** [comment]
@lookfirst did you manage to fix these issues? Do you think this is still worth looking into?

**Comment by lookfirst** [comment]
@guybedford I don't think there has been any change.

**Comment by guybedford** [comment]
I recently did some refactoring of this code and it all seemed ok to me. Do let me know if you notice anything strange at all again here.
