### ISSUE TITLE
Trace cache

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#232]
GoCardless report their build went down from 5s to 1.8s using a build cache object. The remaining 1.8s should be possible to reduce significantly with a trace cache.

The way this would work is that the `cache` object is extended to have two top-level keys - `cache.loads` and `cache.compiles`. For the trace and compile caches respectively. The `cache.compiles` would be exactly as the current cache object handles. The `cache.loads` would then simply include the load records as traced from `bulider.loader.loads`. Serialization of this object would be harder than for the compile cache as it has some self-referencing, but it may be possible to sanitize these out first to make a more cache-friendly representation.

Plugging the trace cache into the loader itself will require some extension to the loader mechanics.

Trace cache invalidation could be left entirely to the end-user. Or it could be worth considering a better invalidation API around this. Perhaps something like:

```javascript
builder.setCache(cacheObj, invalidationFunction);
```

Where `invalidationFunction` is run against each load record in the trace, with the information, allowing easy custom invalidation. Perhaps that is overkill, but just throwing out ideas here.

//cc @jackfranklin

**Comment by guybedford** [comment]
The only remaining optimization after the above is https://github.com/systemjs/builder/issues/209, at that point the build will be optimially cache enabled.

Further optimizations of course are possible for the initial build time though.

**Comment by jackfranklin** [comment]
@guybedford :+1: sounds pretty perfect. Let me know if I can be of any more use. We're about to move to incremental builds at GC so if we can be guinea pigs, you know where we are!

**Comment by guybedford** [comment]
@jackfranklin if you can try disabling your manual invalidation and let the cache invalidate itself it would be interesting to hear how the performance compares. I'd guess it won't make any difference?

Prioritising the 0.16 jspm release currently, along with the bug fixes for that at the moment, but would be great to get this trace cache work in. If you're interested in working on it let me know too.

**Comment by jackfranklin** [comment]
@guybedford will have a go and let you know, although I would expect the difference to be minimal.

Would love to try and work more on the trace cache stuff, although aware it hits lots of internal bits I'm not too familiar with. Happy to get stuck in!

**Comment by guybedford** [comment]
Awesome, it is a tricky one yes. Basically the trace is done by doing an import in https://github.com/systemjs/builder/blob/master/lib/builder.js#L332, and then reading the loads object on the loader from https://github.com/systemjs/builder/blob/master/lib/builder.js#L342.

Adding a cache to that process would be done by doing the normalization first, then checking if the normalized module is in the cache, and using the trace cache instead of that direct import and `loader.loads` usage.

There are some tough details, so I wouldn't recommend unless you're feeling particular brave / in need of a solution here.

**Comment by jackfranklin** [comment]
@guybedford ditched our custom cache invalidation, it made little to no  difference but still all works fine :+1:

**Comment by guybedford** [comment]
Thanks, good to know!

**Comment by guybedford** [comment]
@jackfranklin I went ahead and implemented a trace cache in master now, accessible via:

```javascript
builder.trace('stuff').then(function(trace) {
  var storedCache = builder.cache.trace;

  builder.reset();

  builder.cache.trace = storedCache;
  // etc
});
```

It's a really simple API, but we can add methods in future if necessary. Let me know if that works for you. Will be posting a release at some point this coming week.

**Comment by guybedford** [comment]
The cache API is now:

```javascript
var cacheObj = builder.getCache();

builder.reset();

builder.setCache(cacheObj);
```

As before, the compile cache will invalidate relatively independently. The trace cache will require custom invalidation.

**Comment by jackfranklin** [comment]
@guybedford sweet, this sounds pretty good! So does `cacheObj` contain two keys, one for the compilation and one for the trace cache?

**Comment by guybedford** [comment]
Yes exactly! Let me know how you get on. Note that this requires an update to SystemJS as well. Still a few days away from the next beta release with this included.

**Comment by lawrencejones** [comment]
Hi @guybedford, I've got our dashboards to use jspm master, which is consuming systemjs-builder master. Running our build script now, without calling the cache lines above results in a slow down in build times, from roughly 5s to 9.5s.

I've had a look at the code and it would appear that systemjs-builder should now be using a cache [by default](https://github.com/systemjs/builder/blob/master/lib/builder.js#L78), so we can remove our passing in of our own cache object. With trace caching enabled, I'm not sure why we should be seeing a slow down in our build times. Would you have any ideas why this may be occurring?

I'm also ran the `builder.reset()` and then the explicit `builder.setCache(cacheObj)`, though what I can see from the code would suggest this doesn't do anything that just new'ing a builder would do anyway. :/

Hoping you can shed some light on this!

CC @jackfranklin

**Comment by guybedford** [comment]
@lawrencejones SystemJS comes with no default caching persistance between separate builds currently. That `setCache` command you linked is effectively a cache clear between separate `builder.reset()` calls.

Are you running `setCache` before the build and `getCache` after the build to get the `5s` time? Is that with minification disabled and low res source maps? Thought the time was slightly better than that here?
