### ISSUE TITLE
add slash before css font's src

### ISSUE THREAD

**Issue by omerts** [systemjs/builder#233]
First of all thanks for the great tool (once again :)).
When bundling, our importing of fonts becomes:
```
src:url(jspm_packages/npm/roboto-font@0.1.0/...
```
When accessing a url on the site, which isn't the base url, for example: test.com/hello/systemjs, the fonts are trying to be found under:
```
test.com/hello/systemjs/jspm_packages/npm/roboto-font@0.1.0/
```
instead of:
```
test.com//jspm_packages/npm/roboto-font@0.1.0/
```

**Comment by guybedford** [comment]
A CSS `urlPrefix` option may be the way to go here - I've created https://github.com/systemjs/plugin-css/issues/52.

**Comment by omerts** [comment]
@guybedford thanks alot
