### ISSUE TITLE
javascript module dosen't work in cordova

### ISSUE THREAD

**Issue by hon** [systemjs/builder#234]
My project use jspm, bebal(translate es6) and reactjs. It works well in browser, but dosen't work in cordova.
script part of the index.html file:

    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script src="cordova.js"></script>
    <script>
        function loadApp() {
          cordova.exec.setJsToNativeBridgeMode(cordova.exec.jsToNativeModes.XHR_NO_PAYLOAD);

          var head = document.getElementsByTagName('head')[0];
          var script = document.createElement('script');
          script.type = 'text/javascript';
          script.src = 'build.js';
          head.appendChild(script);
          
          System['import']('app');
        }
        document.addEventListener("deviceready", loadApp, false)
   </script>

code within System.register function does not execute in both build.js and app.js, but can execute out of System.register function.
I missed something?

**Comment by guybedford** [comment]
This could be some kind of Cordova compatibility issue in SystemJS.

If you can help debug where the issue might be that would be incredibly helpful. Can you confirm that `System.baseURL` seems correct in the Cordova environment? Then the next thing to check is that the names of the modules from the bundle seem correct when logging `Object.keys(System.defined)`. If you could compare those values between Cordova and a Browser, any inconsistencies would be useful to know.

**Comment by hon** [comment]
```System.baseURL```  is set to '/' and  ```Object.keys(System.defined)``` value in browser contains an array of nodejs modules, but in cordova is empty.

**Comment by hon** [comment]
Below is the part of config.js:
```
System.config({
  "baseURL": "/",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
    "build/*": "dist/*.js"
  }
});
```
and the bundle command:
```
jspm bundle build/* build.js
```

**Comment by hon** [comment]
I rebuilt the bundle with this command:
jspm bundle-sfx dist/app + build/* build.js --mimify --inject
and the promble is sovled.

**Comment by guybedford** [comment]
Great, just let me know if you have any further issues.
