### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#236]
Just to try and bring everything into one place, I have the following issues pending:

* https://github.com/systemjs/builder/issues/177 Source Maps support
* https://github.com/systemjs/builder/issues/178 Helper sharing / separation
* https://github.com/systemjs/builder/issues/206 Compile errors when bundling in TypeScript
* https://github.com/systemjs/builder/issues/200 Enable TypeScript tests

Is there anything else here I'm missing? Please post here if anyone is working on any of these, otherwise they probably should be prioritised in terms of user experience benefits. Will aim to find some time myself too if necessary.

//cc @robwormald @vladima

**Comment by guybedford** [comment]
The alternative here would be to focus work on the TypeScript plugin rather and make that the core experience, as it is being actively driven by @frankwallis.

**Comment by vladima** [comment]
#177 and #178 are scheduled for TypeScript 1.6 which is the next TypeScript release.
Re: #200, I'm working on it, related question: clean `npm install` fails with the following error:
```
npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15
```

**Comment by guybedford** [comment]
@vladima thanks so much for the update! I assume that issue is running npm3? Perhaps force downgrade the phantomjs dependency in the package.json to 1.9.7 and see if that helps?

**Comment by vladima** [comment]
@guybedford I've tried to enable tests for TypeScript and it seems that currently the majority of failures happens because TypeScript does not have built-in support for remapping dependencies (similar to [Traceur](https://github.com/systemjs/builder/blob/master/compilers/esm.js#L77) or [Babel](https://github.com/systemjs/builder/blob/master/compilers/esm.js#L138)). Is it something that should be resolved on TypeScript side or you have some way to workaround this issue?

**Comment by vladima** [comment]
Ok, I guess [this](https://github.com/systemjs/builder/issues/262) intended to be the answer to my previous questions. Unfortunately I don't think that custom resolvers will solve the issue. Currently they are only used to help TypeScript compiler resolve names of imported modules (i.e. if during development imported modules are fetched on demand from some file share) and they does not affect code generation - module name in generated javascript will be exactly the same as it is was written in original .ts file. What we probably can do is provide a way to pass `depMap` to the compiler so during emit if `depMap` was provided it will be used to rename items in dependency list

**Comment by guybedford** [comment]
After the current merges, all that is left now is helper separation and compilation error reporting. Closing as this means we have the baseline covered now.
