### ISSUE TITLE
Issues when tracing bundles, loading bundles through System.bundles API and AMD format in bundling

### ISSUE THREAD

**Issue by carlosagsmendes** [systemjs/builder#238]
Hi @guybedford, I'm experiencing some issues with the Builder and asked about this in the Gitter room. You requested a repo so I tried to reproduce the problems  I'm experiencing using the demo-es6 repo as a base.

Here's the link to [my fork](https://github.com/carlosagsmendes/demo-es6) so you can assess the issues that I'm describing below.

## When subtracting bundles, some bundled dependencies are still being included 

You can reproduce this with the following steps:

1) I added *jquery-ui* as a dependency to the *demo-es6* project and then created a `jquery-bundle` using the following command:

```jspm bundle jquery + jquery-ui jquery-bundle.js```

2) I changed *my-class.js* to also import it:

```
import $ from 'jquery';
import 'jquery-ui';

export class MyClass {
  constructor() {
    $(document.body).css('background-color', 'grey');
    this.writeMessage('es6 class method');
  }
  writeMessage(msg) {
    $(document.body).html(msg);
  }
}
```

3) I created a new bundle from the *main.js* that imports *my-class.js* (that imports *jquery* and *jquery-ui*)

```
import { MyClass } from './my-class';
new MyClass();
```

Since I have a bundle with *jquery* and *jquery-ui* (as described in the step 1), I want to exclude the bundled items from my *main-bundle*. To do so I used the following command:

```jspm bundle lib/main - jquery-bundle.js main-bundle.js```

Although *jquery* was not included (as expected), *jquery-ui* is still being included in the *main-bundle*. This is the problem I tried to report through Gitter

I've also uploaded the bundled files for your convenience. Here's the link to the [main-bundle.js](https://github.com/carlosagsmendes/demo-es6/blob/master/main-bundle.js#L29) file that shows that *jquery-ui* is still being included in the *main-bundle*.
 
## Setting bundles configuration through the System.bundles API isn't working

I've followed the instructions for configuring bundles using the API but it is not working for me. Here's how I'm declaring the bundles:

```
<script>
    System.bundles["jquery-bundle"] = [
      "github:components/jquery@2.1.4/jquery.js",
      "github:components/jquery@2.1.4.js",
      "github:components/jqueryui@1.11.4/jquery-ui.js",
      "github:components/jqueryui@1.11.4.js"
    ];
    System.bundles["main-bundle"] = [
      "npm:core-js@0.9.18/library/modules/$.fw.js",
      "npm:babel-runtime@5.7.0/helpers/class-call-check.js",
      "github:components/jqueryui@1.11.4/jquery-ui.js",
      "npm:core-js@0.9.18/library/modules/$.js",
      "github:components/jqueryui@1.11.4.js",
      "npm:core-js@0.9.18/library/fn/object/define-property.js",
      "npm:babel-runtime@5.7.0/core-js/object/define-property.js",
      "npm:babel-runtime@5.7.0/helpers/create-class.js",
      "lib/my-class.js",
      "lib/main.js"
    ];
  </script>
  <script src='config.js'></script>
```

Here's the full [test.html](https://github.com/carlosagsmendes/demo-es6/blob/master/test.html#L13) file. 

Although bundles are being declared, they aren't loaded in runtime.

When I add them manually to the *config.js* (or when using the --inject option) they are loaded as expected in runtime.

## AMD Format in Bundling

I've switched to the amd format due to the issue found by the Aurelia team in regards to speed - caused by Babel and the system.register format.

I've changed my [config.js](https://github.com/carlosagsmendes/demo-es6/blob/master/config.js#L5) to do so.

Nevertheless, the bundles' output is still using system (instead of amd). Here's a link to a [sample](https://github.com/carlosagsmendes/demo-es6/blob/master/main-bundle.js)

Thanks in advance.

**Comment by guybedford** [comment]
There are a couple of issues happening here actually:

1. The bundle isn't being detected as a bundle because the first module in the bundle is AMD, so the bundle is being detected as AMD.
2. If we execute the bundle as a bundle (`"format register"` at the top of the source), it throws due to an execution error. This is exactly the issue tracking in https://github.com/systemjs/builder/issues/222.
3. Even then, `System.registerDynamic` isn't being properly traced. I've fixed this in https://github.com/systemjs/builder/commit/73111f2828117f96dd440369cc620d9c032e4ac0.

Then the workaround for now is to use the fix from (3) and then to add `"bundle true"` to the top of the bundle (make it clear to SystemJS that it is a bundle).

Working on a better fix for (1) and (2) here and tracking that in #222.

**Comment by carlosagsmendes** [comment]
Thank you. 

I'm sorry but I didn't get the solution for "Setting bundles configuration through the System.bundles API isn't working" or if that's a bug where is it being tracked.

**Comment by guybedford** [comment]
You need to just change the call to `System.config({ bundles: {...} })` and do it after loading the `config.js` file.
