### ISSUE TITLE
Production optimization for process.env.NODE_ENV

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#240]
We currently apply `process.env.NODE_ENV` production optimizations for minification of CommonJS.

It would be worth moving this code removal process to run before picking up CommonJS dependencies. That would allow `require` statements within this wrapper to be removed from the tree, allowing a smaller code footprint at the end.

**Comment by tyscorp** [comment]
Is there a reason for only checking process.env.NODE_ENV in CommonJS modules? This would be useful in ESM to do debugging stuff without having separate entry points.

**Comment by guybedford** [comment]
Detection and handling of these code paths can be done via pre-processing rather.
