### ISSUE TITLE
Problem with file paths on Windows

### ISSUE THREAD

**Issue by rootical** [systemjs/builder#241]
Hello, thank you for exciting work out here. 

Please check a piece of code I have somewhere inside my app:

``` javascript
   return through2.obj(function(file, enc, next) {
      var basename = path.basename(file.path).replace('.ts', '.js');
      var builder = new Builder();
      builder.reset();

      builder
         .loadConfig(systemJsConfig)
         .then(function() {
            return builder.buildSFX(file.path, path.resolve(dest, basename));
         });
```

I am using latest jspm beta, typescript, system module option.

On Mac and other Unix machines it compiles systemJs module just fine.

But on windows there's following error happens:
`SystemJS Error: Only file URLs of the form file:/// allowed running in Node.
        Error loading D://\Work\ATG\wk.ui\src\wk.ui.module.ts.js`

Is there a way to fix it without manually changing slash direction for windows?
Thanks in advance.

**Comment by guybedford** [comment]
Glad you're liking the project. SystemJS builder takes an input module name as argument. Module names must use `/` in paths not `\`, as we even use URLs for builds. Just let me know if you have any more questions at all.

**Comment by rootical** [comment]
I see now, so on Windows node's `file.path` consist the relevant value, I thought it should be the same on all systems when using file in node. 
Thank you very much for clarification.
