### ISSUE TITLE
Typescript Imports will not work without `.ts` extension added

### ISSUE THREAD

**Issue by rootical** [systemjs/builder#242]
Sorry if it's a wrong place.

I need my code to be compiled not only with the help of System.JS but also with `tsc`.
Currently without setting extension in an import, like below it can't find a file:
``` typescript
import { myModule } from 'my.module.ts';
```
Looks like it's one of the problems described [here](https://github.com/systemjs/systemjs/issues/490). 

Am I missing an option or anything? Thanks

**Comment by guybedford** [comment]
Yes setting extensions in imports is the currently suggested way. There is the `defaultExtension` package configuration option (https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages), which will set it automatically when there is no extension, but that would only apply to `import { myModule } from 'module'` and not `import { myModule } from 'my.module'` as the last one already has an extension.
