### ISSUE TITLE
buildSFX is treating babel file as directory (\babel-core\browser.js\external-helpers)

### ISSUE THREAD

**Issue by marcorinck** [systemjs/builder#244]
Hi, 

I'm trying to get familiar with es6 currently and at least have successfully converted my toy angular project to es6.  I can open it in browsers successfully and its using systemjs, es6-module-loader and babel-core. Transpilation is done on the fly.

However, it was not so easy to integrate it in my grunt workflow for a production build with systemjs-builder. After some trial and error, I can do a builder.build(...) successfully, but builder.buildSFX seems to treat the babel 'browser.js' file as a directory and is trying to read external-helpers.js from there:

````
{ [Error: ENOENT, open 'C:\Users\marco\WebstormProjects\ngStart\app\modules\external-libs\babel-core\browser.js\external-helpers']
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\Users\\marco\\WebstormProjects\\ngStart\\app\\modules\\external-libs\\babel-core\\browser.js\\external-helpers' }
````

My builder code is looking like this:

````
var Builder = require('systemjs-builder'),
            builder = new Builder({
                baseURL: 'app/modules',
                transpiler: 'babel',
                defaultJSExtensions: false
            });
        builder.loadConfig('./app/modules/config-system.js').then(function () {
            builder.buildSFX('app.js', 'target/outfile.js', {minify: true, mangle: false})
                .then(function () {
                    console.log('Build complete');
                    done();
                })
                .catch(function (err) {
                    console.log('Build error');
                    console.log(err);
                    done(false);
                });
        });
````

The same config, but a call to builder.build() is running successfully! 

You can see the full gruntfile (and the complete project) here (look for build and buildSFX grunt tasks):
https://github.com/marcorinck/ngStart/blob/es6/gruntfile.js

Can you give me some pointers what the problem could be?

Thanks!

**Comment by guybedford** [comment]
So the assumption in SystemJS is that it will find `babel` at `System.import('babel')` and the babel helpers at `System.import('babel/external-helpers')`.

This assumption will work nicely if setting up `babel` as a SystemJS package configuration.

If you're using paths or map to set the path to babel then you'll need to separately set the path or map for `babel/external-helpers` separately here.

Let me know if that helps.

**Comment by marcorinck** [comment]
Yes, that helped! Thanks a lot!

Is that intentional or does it need to be fixed? Should I close the issue?

**Comment by guybedford** [comment]
Yes it's just the way it is unfortunately, we have to make some configuration assumptions. I've added a commit to give a better error here in future, that's probably the best action for now.
