### ISSUE TITLE
Issue with builder paths

### ISSUE THREAD

**Issue by zellwk** [systemjs/builder#246]
jspm version: 0.15.7 

I had an error when I tried using `.build()` 

~~~bash
[Error: ENOENT, open '/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter-with-jspm/process.js']
~~~

The error is resolved once I used this command: 

~~~bash
$ jspm install process=npm:process
~~~

My builder config is: 

~~~js
let builder = new Builder();

  builder.loadConfig('./jspm.config.js')
  .then(()=> {
    return builder.buildSFX('src/js/main', 'dev/js/main.js')
    .catch((err) => {
      console.log('build error');
      console.log(err);
    })
  })
~~~

Just thought you should know.

**Comment by guybedford** [comment]
This would happen if one of your packages required `process` but it was not installed as a dependency.

If you can trace which npm package in your app this is, that may help to diagnose it.

**Comment by zellwk** [comment]
Well, I didn't use `process` anywhere. Seems like `process` is installed by systems js automatically

**Comment by guybedford** [comment]
It would have been used automatically if you installed a package from npm via jspm. Which package it was that needed `process` would help to work out why it wasn't installed automatically. Note also that this sounds like a jspm issue not a SystemJS one.

**Comment by guybedford** [comment]
Just let me know if you have any further questions here at all.

**Comment by zellwk** [comment]
Sorry didn't have the time work with JSPM the past few days. Seems like either `lodash` or `jquery` uses `process`. Thanks for the help!

**Comment by MeoMix** [comment]
:+1: 

I just encountered this issue trying to do a build after pulling in the latest version of lodash instead of using my own, local copy.
