### ISSUE TITLE
Cannot inline babel helpers in non-sfx builds

### ISSUE THREAD

**Issue by enlait** [systemjs/builder#257]
Specifying ```babelOptions : {externalHelpers: false}``` seems to have no effect on ```Builder.build``` output. Am I missing something? Documentation refers to babel website for pretty much all of babel configuration.

I use subtraction arithmetic in build for some libraries => not an sfx build.

**Comment by guybedford** [comment]
@enlait helpers aren't inlined into non SFX builds yes, the assumption is to simply include them with a script tag as that's the best caching workflow.

**Comment by guybedford** [comment]
There is actually an issue to track helpers working for builds in https://github.com/systemjs/systemjs/issues/431 but I'm still hesititant to make the runtimes a hard modular dependency.
