### ISSUE TITLE
Reconfiguring baseURL?

### ISSUE THREAD

**Issue by zellwk** [systemjs/builder#260]
Is it possible to reconfigure baseURL? I got this error when I tried to reconfigure baseURL after loading the config. 

~~~
build error
[TypeError: baseURL should only be configured once and must be configured first.]
~~~

I'm building a static site generator, and needed baseURL to be `/` during development. When compiling for production, I need baseURL to be `./` instead.

**Comment by guybedford** [comment]
You can alter the baseURL if you reset the builder (`builder.reset()`) or create a new builder instance.

**Comment by guybedford** [comment]
Just let me know if you're still having issues with this at all.

**Comment by zellwk** [comment]
What I'd like to do is to load a config and reset the baseURL. Something like this: 

```js
 builder.reset();
  builder.loadConfig('./jspm.config.js')
  .then(()=> {
    // Doesn't allow's builder to reconfigure.
    builder.config({
      baseURL: './',
    });
    return builder.buildSFX();
  })
```
Can it be done?

**Comment by guybedford** [comment]
@zellwk for jspm rather use `require('jspm').Builder` see https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder for more info.

**Comment by albv** [comment]
I am not using jspm, just system.js and system.js builder still having the same issue though. I've seen a few samples following exact the same pattern. Isn't it valid by now?

**Comment by zellwk** [comment]
I'm still having some problems, 

Here's the complete error: 
```
build error
{ [Error: Error loading "src/js/main.js" at file:/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/src/js/main.js.js
ENOENT, open '/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/src/js/main.js.js']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/src/js/main.js.js' }
```

Here's my JSPM config: 
```
build error
{ [Error: Error loading "src/js/main.js" at file:/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/src/js/main.js.js
ENOENT, open '/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/src/js/main.js.js']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/src/js/main.js.js' }
```

Here's how I added JSPM to my index.html file 

```
<script src="/jspm_packages/system.js"></script>
  <script src="/jspm.config.js"></script>
  <script>
    System.import('js/main');
  </script>
```

Any ideas? Thanks so much for the support

**Comment by guybedford** [comment]
@zellwk note that in jspm 0.15, js extensions are added automatically so you should be bundling / importing `src/js/main` which will automatically add '.js'. By bundling `src/js/main.js` you're getting an extra .js in your file load. If you look at the error it shows which file it is trying to load, which directly indicates this.

**Comment by zellwk** [comment]
Aawesome. got it to work! Thanks alot :)

**Comment by zellwk** [comment]
Just to check, I got this error now, is there a way to remove it? 

```
[BABEL] file:/Users/zellwk/Projects/PersonalProjects/privateRepos/static-starter/src/js/main.js: Deprecated option metadataUsedHelpers: Not required anymore as this is enabled by default
```

**Comment by albv** [comment]
@guybedford I am still not sure about answer to the original question. Can baseUrl be altered after System.js config loading or not?

**Comment by zellwk** [comment]
BaseUrl can be reconfigured if you use the JSPM package. It contains systems js builder as well. 







Stay Awesome!  Zell
