### ISSUE TITLE
Emscripten module compatibility

### ISSUE THREAD

**Issue by Garciat** [systemjs/builder#261]
Builder makes the emscripten [shell](https://github.com/kripken/emscripten/blob/master/src/shell.js) think it's running in node. It then tries to require node modules like `fs`.

Related discussion [here](https://github.com/kripken/emscripten/issues/3379). Possible solution [here](https://github.com/kripken/emscripten/issues/1061).

**Comment by guybedford** [comment]
@Garciat it sounds like the wrapper assumes it is in Node if it is using CommonJS with `process` defined.

You can alter the way that SystemJS interprets the module by forcing it to be loaded as a `global` or `amd` format via meta configuration, which may then work better for building the wrapper. See https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md for more info on format handling in SystemJS.

**Comment by Garciat** [comment]
@guybedford I'll take a look; thanks :+1:

**Comment by Garciat** [comment]
Yup. That did the trick.

For future reference:
```javascript
new Builder({
    ...

    meta: {
        'myapp/emscripten_module': {
            format: 'global'
        }
    }
})
```

**Comment by Garciat** [comment]
Yup. That did the trick.

For future reference:
```javascript
new Builder({
    ...

    meta: {
        'myapp/emscripten_module': {
            format: 'global'
        }
    }
})
```
