### ISSUE TITLE
TypeScript implement custom resolver

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#262]
To ensure that bundle dependencies are normalized correctly, it is necessary to have a custom resolver to pass into TypeScript.

@vladima you mentioned previously this was the plan for custom resolutions? Please keep me posted on how that goes.

**Comment by vladima** [comment]
@guybedford sure. Currently we plan to expose custom resolution via [CompilerHost.resolveModuleName](https://github.com/Microsoft/TypeScript/blob/reuseAndCache/src/compiler/types.ts#L2265) so host can implement any resolution policy it needs. Can you please tell if it will cover your scenarios?

**Comment by guybedford** [comment]
@vladima thanks yes that looks exactly right. In SystemJS we can always relate every module to an absolute URL or filepath, but it may be worth considering relaxing this constraint and allowing virtual naming as well. For example, we use the `@empty` module in SystemJS as an output for this for nulled out modules (an edge case certainly, but to illustrate).

**Comment by vladima** [comment]
@guybedford  [this PR](https://github.com/Microsoft/TypeScript/pull/4319) on the TypeScript side should allow to pass map (originalName -> newName, effectively `load.depMap`) to transpiler. Can you please check if it will cover your scenarios?

**Comment by guybedford** [comment]
It works excellently, thanks @vladima for your work on this.

**Comment by guybedford** [comment]
Released in 0.13.2.
