### ISSUE TITLE
Babel options 

### ISSUE THREAD

**Issue by Globegitter** [systemjs/builder#265]
I am just starting out and I want to build our existing app using the systemjs builder. Currently we use browserify with a lot of custom transforms I indent to replace with custom loaders. 

Just getting started, I define babel as the transpiler but how can I set it to transpiled with stage: 0? 
Other things that seemed a bit difficult to find how I can overwrite the es6 module to automatically append the .js again here within the builder. The docs seem a bit short on that.

Once I do understand myself I would be happy to add some docs about these things.

**Comment by Globegitter** [comment]
Ahhh solver issue number 1 by just passing babelOptions - great!

**Comment by guybedford** [comment]
@Globegitter sure I've added https://github.com/systemjs/builder/commit/5fbbb37967c2a369c06482d3a0282c4dcc772e79, let me know if that works for you here.

Note that the way to build paths like '//third_party/js/react' is to use a paths configuration for them:

```javascript
System.config({
  paths: {
    react: '//third_party/js/react.js'
  },
  meta: {
    react: { build: false }
  }
});
```

That way the builder can know to just refer to it as `react`. Then to remove it from the build the meta config above will leave it as an unbundle dependency.

**Comment by Globegitter** [comment]
Sweet thanks for that - yeah I am still in the process of figuring out what the best way is to move our current build system to use systemjs.

Is there any way to add additional files to the build? For example if we want to add polyfills we could do something like `builder.add('path/to/polyfill.js').buildSFX(...)` or, `builder.buildSFX('myModule.js', 'outfile.js', { external: ['path/to/polyfill.js'] })`.

Or can you already do that with one of the existing SystemJS options? The only thing I could find in that direction is the bundle option, but not sure if that is supposed to be used for that use-case.

**Comment by guybedford** [comment]
The build will only ever build dependency trees into JS source. You can concatenate the output further with other tasks though outside of builder though rather.

**Comment by Globegitter** [comment]
Ah thanks for letting me know - seems this can be closed now.
