### ISSUE TITLE
Missing dependences in bundle when using plugins for loading main file

### ISSUE THREAD

**Issue by prefiks** [systemjs/builder#266]
I am using my own plugin to perform conversion from typescript1.6 to babel to javascript. 

Unfortunately when i am trying to bundle this using `jspm bundle` some deps that are used by typescript1.6 and some other module i am using in my program are not properly included in generated bundle.

I prepared small example that can be used to reproduce this issue, first by executing this In shell
```
$ jspm init
$ jspm install underscore
$ mkdir app
$ echo "U = require('underscore');exports.translate=function(){}" > plugin.js
$ echo "import _ from 'underscore';_" > app/main.js
$ cp app/main.js app/main2.js
```
and then adding this to config.js
```
  "packages": {
    "app": {
      "meta": {
        "main.js": {
          "loader": "plugin.js"
        }
      }
    }
  }
```
This only happens when plugin using file is used as first item in `jspm bundle`, so
`jspm bundle app/main` will generate broken bundle while `jspm bundle app/main2 + app/main` will make good one.

**Comment by guybedford** [comment]
When transpiling TypeScript make sure to use the `system` module format output.
