### ISSUE TITLE
+ instead of & in https://github.com/systemjs/builder#example---common-bundles

### ISSUE THREAD

**Issue by bushuyev** [systemjs/builder#267]
The page says that "To build the shared dependencies of two modules, use the & operator:" Looks like it's +, not &. At least it works fine with '+' and produces blank file with &.

**Comment by guybedford** [comment]
Sure, I've clarified in https://github.com/systemjs/builder/commit/7b0836cf8922d81031cb86be054004a209a1093f. `&` is the intersection while `+` is the union.
