### ISSUE TITLE
Global SFX bundle dependency 

### ISSUE THREAD

**Issue by Globegitter** [systemjs/builder#268]
Using the `buildSFX` command I am getting the following error:

[TypeError: Global SFX bundle dependency "/path/to/react.js" (/path/tot/react.js) must be configured to an environment global via the sfxGlobals option.]

But there isn't any documentation on why this is necessary or how to do it. I did figure it out but it does seem to me like a very tedious manual step. Similar to the `map` function. Whenever you add a third party dependency you manually have to add this.

Surely there must be some way to automate these steps or at least provide some easier ways to automate this.

**Comment by guybedford** [comment]
Thanks, I've added a better message for this in jspm with https://github.com/jspm/jspm-cli/commit/76232eb020e102080455bfe25ed4032f28f0a73b.
