### ISSUE TITLE
Forcing format of an "empty" module

### ISSUE THREAD

**Issue by pkozlowski-opensource** [systemjs/builder#271]
I'm bumping into a corner case that gives me a bit of headache: in Angular2 we've got a [file](https://github.com/angular/angular/blob/master/modules/angular2/src/router/route_definition.ts) that has only TypeScript interfaces export. Such file, when transpiled to ES6 comes out empty (rightly so). Now, the problem is that when such an empty file is bundled with other files (it gets bundled since there are references to interfaces from other files) systemjs/builder auto-detect the empty file as "global".

Is there is a way of letting systemjs/builder know that such file is really using "es6" format? I was trying to do:

```javascript
var bundleConfig = {
  paths: {
    "*": "dist/js/prod/es6/*.js"   
  },
  meta: {
    '*': {
      format: 'es6'
    }
};
```

but it doesn't seem to have much effect (that is - auto-detection still kicks in). 

Any advice here?

**Comment by pkozlowski-opensource** [comment]
Hmm, I can see that I can easily force format using exact module name:

```javascript
meta: {
    'angular2/src/router/route_definition': {
        format: 'es6'
      }
    }
```

but this is rather fragile. 

Is there any support for globs build in for meta settings? Or shell we list all the modules for which we want to force format?

**Comment by guybedford** [comment]
Arbitrary use of wildcard `*` is supported in meta configuration - can that work for you here?

**Comment by guybedford** [comment]
```javascript
System.config({
  meta: {
    'angular2/src/*': { format: 'esm' }
  }
});
```

**Comment by pkozlowski-opensource** [comment]
@guybedford thnx for coming back to me on this one. I've just tried and can't make wildcards to work. Maybe it is due to the fact that we are using older version of the builder (0.10.6)?

If you could point me to a place where meta-data are resolved / format decided for a given module, I could debug on my end.

**Comment by guybedford** [comment]
Ah right, yes wildcards are only supported in builder 11+. You'll have to list the files manually then unfortunately.

**Comment by guybedford** [comment]
It could also be possible to add a custom extension at build time to the loader - 

```javascript
var loaderLocate = builder.loader.locate;
builder.loader.locate = function(load) {
  if (load.name.indexOf(path.resolve('angular2/src/')) 1= -1)
    load.metadata.format = 'es6';
  return loaderLocate.call(this, load);
}
```

**Comment by pkozlowski-opensource** [comment]
OK, we are going to migrate to a newer version of a builder then. AFAIK we need to do this for System.register performance.

Thnx for your super-fast and effective support @guybedford !

**Comment by guybedford** [comment]
Sure! Just ping me if you need any help at all with the upgrade.
