### ISSUE TITLE
Document sfxGlobalName

### ISSUE THREAD

**Issue by bushuyev** [systemjs/builder#273]
Can't find any documentation on sfxGlobalName option to buildSFX.  Will it be further supported  or it's some rudiment? This option was the only way I was able to find to import resulting sfx file. 

Please also have a look at 

http://stackoverflow.com/questions/31882316/how-to-import-system-js-sfx-library

and

http://stackoverflow.com/questions/31862834/randomly-failing-polymer-web-component-test

would be greatly thankful for any comment.

**Comment by guybedford** [comment]
Yes it is not currently documented. I tend to keep new features undocumented until they are stable.

**Comment by bushuyev** [comment]
Ok, so it's new one. Good :) Thank you!
