### ISSUE TITLE
Building with emscripten modules.

### ISSUE THREAD

**Issue by matthewbauer** [systemjs/builder#274]
I can update with more details later, but basically Emscripten generated output is going to break the builder for any nontrivial Emscripten program.

For an example: https://github.com/matthewbauer/gametime-player

```sh
git clone https://github.com/matthewbauer/gametime-player.git
cd gametime-player
npm install
jspm bundle snes9x-next
```

**Comment by guybedford** [comment]
This is example is definitely working ok for me - that is I can bundle `snes9x-next` fine. Are you running the latest version of jspm here?

**Comment by matthewbauer** [comment]
Never mind not getting this anymore.
