### ISSUE TITLE
Cannot use the name property from imported module after build with mangle: true

### ISSUE THREAD

**Issue by ryanirilli** [systemjs/builder#279]
```
import angular from 'angular';
import applicationController from './applicationController';

let app = angular.module('myApp', [])
  .controller(applicationController.name, [applicationController]);

export default app;
```

The above code works great for dev, but when I build for production with this cmd
`jspm bundle-sfx app/main dist/js/app.min.js --minify --skip-source-maps`

this results in my 'applicationController' being undefined in Angular, presumably because I am not registering it as that string but rather some mangled version of it. Should I be doing this another way?

**Comment by guybedford** [comment]
Perhaps this is due to something like https://docs.angularjs.org/api/auto/service/$injector#inference?

**Comment by guybedford** [comment]
Closing, but let me know if you still have any questions.
