### ISSUE TITLE
Uncaught ReferenceError: $__System is not defined

### ISSUE THREAD

**Issue by gig177** [systemjs/builder#282]
I try to use systemjs-builder api (builder.build) but the output which i has contents the '$__System' variable. Don't understand why this happen. I try to use system-csp-production + config + bundle. If i use $ jspm bundle ... then it's fine.

**Comment by guybedford** [comment]
The `$__System` output is for `builder.buildSFX` only. There was a bug that was fixed in 0.13.3 where this was being incorrectly output for CommonJS modules. Make sure to upgrade to that version and I believe that should fix it.
