### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by gig177** [systemjs/builder#290]
I try to separate my bundles for some 'a' and 'c' modules. The 'a' bundle is main. It contains some inlined css. When i try to subtract common modules ( $ jspm bundle modules/c - modules/a ), then this issue was occured. I was created a [repo](https://github.com/gig177/systemjs-builder-evaluating-issue).

**Comment by guybedford** [comment]
The reason for this is that the CSS plugin outputs `document` calls, I've created https://github.com/systemjs/plugin-css/issues/60 to track this.
