### ISSUE TITLE
Tape breaks sfx bundle?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/builder#291]
I'm having issues creating a sfx bundle when using [tape](https://www.npmjs.com/package/tape). 
It creates the error: `System is not defined`. 

Running it through a regular `System.import()` works fine. 
Using an injected bundle (`jspm bundle index.js --inject`) also works fine. 

Minimal example: https://github.com/peteruithoven/jspm-tape-bundle

**Comment by guybedford** [comment]
Thanks, I've added a fix in https://github.com/systemjs/builder/commit/eb63a85ed623d07a1a6511a17bc5f2701d7f3ded.

**Comment by peteruithoven** [comment]
Awesome, thanks!
