### ISSUE TITLE
Sourcemap output should include `sourcesContents`

### ISSUE THREAD

**Issue by jackfranklin** [systemjs/builder#298]
It would be really useful if the sourcemap generated from a bundle included the original content of the file in the `sourcesContents` field. UglifyJS supports this (at least, from the command line), and the ability to use it in a bundle would be really useful so we could have it in our production environment and then our app that deals with exceptions can read it and map the errors back to the source code :)

**Comment by jackfranklin** [comment]
@guybedford it seems that systemjs-builder does support this - I can edit lib/builder.js and edit the `opts` object before it gets passed to `writeOutputs`. The Q here more seems to be a flag in the jspm-cli that would enable this option when calling `bundle`. Happy to do this - LMK if you'd like me to attempt a PR if this solution sounds like the right one.

**Comment by guybedford** [comment]
@jackfranklin I think this is just the `--inline-source-maps` option when bundling in jspm?

**Comment by Rush** [comment]
Well, don't just do it in `jspm-cli`, some of us are using the API. ;-)

**Comment by guybedford** [comment]
@Rush it's the `sourceMapContents: true` option in the builder API or equivalently `sourceMaps: 'inline'`.

**Comment by jackfranklin** [comment]
@guybedford but doesn't `--inline-source-maps` cause the entire source map to be placed inside the JS file? I'd rather keep the sourcemap separate, but have `sourcesContent` included - apologies if I've misunderstood this.

**Comment by guybedford** [comment]
@jackfranklin thanks for clarifying - right so the builder API method you're wanting to use here is just `sourceMapContents: true` which is different to `sourceMaps: 'inline'`. If you wanted to set that up as an option in jspm like `jspm bundle x --source-map-contents` or similar, I'll gladly take a PR.

**Comment by jackfranklin** [comment]
@guybedford thanks, will close this and track in the PR on jspm https://github.com/jspm/jspm-cli/pull/1091
