### ISSUE TITLE
Support SystemJS builder dependency extraction without execution

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#299]
We currently execute transpiled ES6 in the target environment to extract the dependencies, but we don't use the execute function at all, so this is unnecessary work.

In addition, not execution would allow transpiling to ES6 itself say just using the modules transformer when transpiling for browser environments that support more than Node does (previously discussed in https://github.com/jspm/jspm-cli/issues/884).

This can be done by having a truncated instantiate for the builder, and just applying a regex in the tracer to extract the `System.register` dependencies since we can rely on it being the first line of code after comments and meta strings.

**Comment by awalGarg** [comment]
This would be pretty awesome. Any updates? What parts of the code should potential contributors be looking at to help out?

**Comment by guybedford** [comment]
This isn't a priority currently, and may be somewhat tricky for contributions. Such an intercept would be at https://github.com/systemjs/builder/blob/master/lib/trace.js#L284 skipping instantiate. It would be important to ensure any useful functions of instantiate are replicated in this case (such as concatting the dependencies with `load.metadata.deps`).

**Comment by guybedford** [comment]
Released in 0.15.0.
