### ISSUE TITLE
jspm 0.16.2: modules are imported as undefined (sometimes)

### ISSUE THREAD

**Issue by OrKoN** [systemjs/builder#300]
Steps to reproduce:

1. download the gist https://gist.github.com/OrKoN/bca49654576439e3af43
2. run `jspm install`
3. bundle `jspm bundle-sfx main build.js`
4. `http-server .` and open in the browser

Error happens: Uncaught TypeError: Cannot read property 'setLevel' of undefined

**Comment by guybedford** [comment]
@OrKoN thanks so much! Fixed in https://github.com/systemjs/builder/commit/262d1c56c69cd3b3c6f292113a10342614c101a1.

**Comment by OrKoN** [comment]
@guybedford Hi, when do you plan a new release?

**Comment by guybedford** [comment]
This was released in 0.13.6.
