### ISSUE TITLE
Question: How to use with typescript?

### ISSUE THREAD

**Issue by mjw56** [systemjs/builder#301]
I'm looking to do the most simple setup with angular2, typescript using gulp and systemjs builder.

Looking for some help here as I know this space moves fast. Here is my most naive approach :) 

...can anyone tell me what I am missing here?

```js

var gulp = require('gulp');

gulp.task('default', ['builder']);

gulp.task('builder', function(cb) {
    var path = require("path");
    var Builder = require('systemjs-builder');

    var builder = new Builder({
        defaultJSExtensions: false,
        baseURL: './',

        map:{
            'angular2': 'node_modules/angular2/angular2'
        },

        transpiler: 'typescript'

    });

    builder
        .buildSFX('app/index.ts', 'dist/bundle.js')
        .then(function() {
            console.log('Build complete');
            cb();
        })
        .catch(function(err) {
            console.log('Build error');
            console.log(err);
        });
});
````

**Comment by jonricaurte** [comment]
make sure you load config

```
builder.loadConfig('config.js')
    .then(function() {
      builder.buildSFX('app/assets/javascripts/application.js', 'public/assets/application.js')
        .then(function () {
          cache = builder.getCache();
          console.log(new Date())
          console.log('Build complete');
        })
        .catch(error);
    })
    .catch(error);
```

**Comment by mjw56** [comment]
@jonricaurte thanks, but what does the config file look like?

And it looks like you're adding javascript files and not typescript files there?

**Comment by jonricaurte** [comment]
The config is your systemjs config file which for typescript would probably be similar to this one:

https://github.com/frankwallis/plugin-typescript

**Comment by mjw56** [comment]
Hmm, ok thanks @jonricaurte. I will have a look at the examples in that repo.

**Comment by rob-bateman** [comment]
@mjw56 did you get this working? Would you be able to post your setup? I'm trying to go down the same path, really don't understand how to get this running with systemjs builder.

There seems to be so little documentation for typescript here, i've read all i can find but really don't have enough info to confidently set this up. All I'm trying to achieve is a standalone build with typescript and systemjs. Any links to helpful tutorials / blog posts would be greatly appreciated!

**Comment by rob-bateman** [comment]
for ref, this is where i've got to with my gulpfile.


    gulp.task('build', function() {
        var Builder = require("systemjs-builder");

        var builder = new Builder("../", {
            typeScriptOptions: {
                "target": "ES5",
                "module": "system",
                "moduleResolution": "classic",
                "sourceMap": true
            },
            packages: {
                "awayjs-core/lib": {
                    defaultExtension: "ts",
                    "meta": {
                        "*.ts": {
                            "loader": "ts"
                        }
                    }
                }
            },
            map: {
                "ts": "github:frankwallis/plugin-typescript@4.0.5"
            }
        });

        builder.buildStatic("./index.ts", "./dist/awayjs-core.js");
    });


this currently produces the following error:

    Unhandled rejection Error: Unable to fetch "github:frankwallis/plugin-typescript@4.0.5". Only file URLs of the form / allowed running in Node.

perhaps i need to update my node runtime?

**Comment by guybedford** [comment]
@rob-bateman for jspm use `require('jspm').Builder` instead of `require('systemjs-builder')`, this will then configure SystemJS correctly for the jspm project. See https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder.

**Comment by rob-bateman** [comment]
@guybedford thanks for the reply. I managed to get things working with `systemjs-builder` when using the following config file:

    System.config({
        baseURL: "../",
        defaultJSExtensions: true,
        transpiler: "typescript",
        typescriptOptions: {
            "module": "system",
            "sourceMap": true
        },
        paths: {
            "awayjs-core/*": "awayjs-core/*"
        },
    
        packages: {
            "awayjs-core": {
                "defaultExtension": "ts"
            },
            "awayjs-core/node_modules": {
                "defaultExtension": "js"
            }
        },
    
        map: {
            "typescript": "./node_modules/typescript/lib/typescript"
        }
    });

and in the gulpfile

    gulp.task('bundle', function(callback) {
        var builder = new Builder('../', './system.config.js');
        
        builder.bundle('./index.ts', './build/awayjs-core.js').then(function() {
            callback();
        })
    });

this creates a nice reusable bundle with proper submodule access like 'awayjs-core/lib/attributes/AttribtuesBuffer' which is more what i was after than the single point of entry provided by buildStatic

However, now i am wondering if i can use the bundled awayjs-core js file as the pre-compiled code in a project that uses this lib? The docs would suggest yes, using the 'meta' property. I've tried writing

     meta: {
        "awayjs-core/*": {
            build: false,
            format: "register"
        }
    },

in the config for a project that implements the awayjs-core lib, and this seems to work so hopefully no more issues :)

**Comment by rob-bateman** [comment]
ok, i seems to be tying myself in knots here. I'm trying to replicate my old browserify workflows in systemjs but am tripping up over the fundamental area of loaders.

My aim is to have a number of libs that all cross-reference each other, but can all be compiled independently. So in one lib i can refer to the transpiled source of the dependency libs rather than re-compile everything every time a change is made.

pretty straightforward, except i've drawn a blank on how to do that with systemjs. I followed the installation process for plugin-typescript (from what i can tell this is the only way to specify granularity on what to compile using typescript and what to leave), but even this first hurdle is proving difficult.

After running jspm install ts, i get the following in my config:

    System.config({
        baseURL: "./",
        defaultJSExtensions: true,
        transpiler: "typescript",
        paths: {
            "github:*": "jspm_packages/github/*",
            "npm:*": "jspm_packages/npm/*"
        },

        map: {
            "ts": "github:frankwallis/plugin-typescript@4.0.5",
            "typescript": "npm:typescript@1.8.9",
            "github:frankwallis/plugin-typescript@4.0.5": {
                "typescript": "npm:typescript@1.8.9"
            },
            "github:jspm/nodelibs-os@0.1.0": {
                "os-browserify": "npm:os-browserify@0.1.2"
            },
            "npm:os-browserify@0.1.2": {
                "os": "github:jspm/nodelibs-os@0.1.0"
            },
            "npm:typescript@1.8.9": {
                "os": "github:jspm/nodelibs-os@0.1.0"
            }
        }
    });

so far so good. I then add my specific package for the lib (awayjs-display) that i want the transpiler to act on:

    System.config({
        baseURL: "./",
        defaultJSExtensions: true,
        transpiler: "typescript",
        paths: {
            "github:*": "jspm_packages/github/*",
            "npm:*": "jspm_packages/npm/*"
        },
        packages: {
            "lib": {
                defaultExtension: "ts",
                meta: {
                    "*.ts": {
                        loader: "ts"
                    }
                }
            }
        },
        map: {
            "ts": "github:frankwallis/plugin-typescript@4.0.5",
            "typescript": "npm:typescript@1.8.9",
            "github:frankwallis/plugin-typescript@4.0.5": {
                "typescript": "npm:typescript@1.8.9"
            },
            "github:jspm/nodelibs-os@0.1.0": {
                "os-browserify": "npm:os-browserify@0.1.2"
            },
            "npm:os-browserify@0.1.2": {
                "os": "github:jspm/nodelibs-os@0.1.0"
            },
            "npm:typescript@1.8.9": {
                "os": "github:jspm/nodelibs-os@0.1.0"
            }
        }
    });

and call this from gulp via this task:

    gulp.task('bundle', function(callback) {
        var builder = new Builder('./', './system.config.js');
    
        
        builder.buildStatic('./index.ts', './build/awayjs-display.js').then(function() {
            callback();
        })
    });

running this gives the following error:

    Unhandled rejection Error on translate for index.ts at file:///Users/robbateman/WebstormProjects/awayjs-display/index.ts

Ok. Looks like my problem is my entry file index.ts is outside my lib folder. this is a problem in itself, i as don't understand how i define a package configuration for plugin-typescript when some of the ts files are in the root folder of the lib.

Regardless, i try moving my index.ts inside the lib folder, and run the bundle again

    Unhandled rejection Error: EISDIR: illegal operation on a directory, read
	    at Error (native)
    Error loading /Users/robbateman/WebstormProjects/awayjs-display/jspm_packages/github/frankwallis/plugin-typescript@4.0.5

This is where i've now got to. The directory installed by jspm for plugin-typescript appears to be inaccessible. I can confirm is definitely exists adn 

This wasn't even my main goal - once this was working i wanted to try using the bundles property to define my precompiled bundles so that the bundler for the current lib could reference the modules in there rather than having to run them all through the ts compiler. This should give me a faster recompile time for dependent libs and projects, but I've not quite made it there yet.

Sorry if i'm being a complete noob about this but for the last few days I've really tried to make this work as i would like to move all my packaging scripts from browserify to systemjs. Perhaps there is a migration doc i've not yet discovered for those of us coming at systemjs with that sort of mindset? If not, it would probably help us stick-in-the-muds get our heads around this new way of working ;)

**Comment by rob-bateman** [comment]
Made it a bit further along with this, looks like i was missing the deprecated property

    defaultJSExtensions: true

in my config. Adding this now gives me this error:

    Unhandled rejection Error on fetch for awayjs-core/lib/utils/getTimer at file:///Users/robbateman/WebstormProjects/awayjs-display/awayjs-core/lib/utils/getTimer

This is closer to what i want as now at least builder is looking for my dependencies in awayjs-core. Now i want to create a bundle reference to my pre-compiled sources for awayjs-core that are already in the register format:

        bundles: {
            './node_modules/awayjs-core/build/awayjs-core.js': ['awayjs-core/lib/utils/*']
        },

sadly, this seems to be ignored by systemjs-builder. I've also tried without the wildcard:

        bundles: {
            './node_modules/awayjs-core/build/awayjs-core.js': ['awayjs-core/lib/utils/getTimer']
        },

but i get the same error. Is this the right approach or am i way off?

**Comment by mjw56** [comment]
@rob-bateman do you have a minimal setup that we could clone and work off of?

I don't know how much I can help, I don't use SystemJS much in my day-to-day. But I am genuinely interested in understanding how to get this working.

**Comment by mjw56** [comment]
Also I can empathise with your frustration. I too felt these same pains when trying to get this working.

I think having this documented could be really beneficial for the community and people facing this same issue in the future.

**Comment by rob-bateman** [comment]
@mjw56 sure, i can upload something in a hour or two. need to tidy up here first as obviously things have been a bit fraught trying to get this to work :)

**Comment by rob-bateman** [comment]
ok, have uploaded a minimal setup here: https://github.com/rob-bateman/systemjs-builder-test

The basic idea is that the awayjs-core lib does not have to go through typescript compilation, it uses the precompiled systemjs module in the dist folder. The bundle setup would be fine working live in a browser, but doesn't seem to be picked up in the same way when using the builder in gulp

**Comment by rob-bateman** [comment]
as a comparison, this config will work but will compile the getTimer class in awayjs-core:

  System.config({
    paths: {
      "github:*": "jspm_packages/github/*",
      "npm:*": "jspm_packages/npm/*",
      "awayjs-core/*": "node_modules/awayjs-core/*"
    },
    packages: {
      "src": {
        defaultExtension: "ts",
        meta: {
          "*.ts": {
            loader: "plugin-typescript"
          }
        },
      },
      "node_modules/awayjs-core": {
        defaultExtension: "ts",
        meta: {
          "*.ts": {
            loader: "plugin-typescript"
          }
        },
      },
      "plugin-typescript": {
        defaultExtension: "js",
      },
      "typescript": {
        defaultExtension: "js",
      }
    },
    map: {
      "babel": "npm:babel-core@5.8.38",
      "babel-runtime": "npm:babel-runtime@5.8.38",
      "core-js": "npm:core-js@1.2.6",
      "plugin-typescript": "github:frankwallis/plugin-typescript@4.0.5.js",
      "github:frankwallis/plugin-typescript@4.0.5": {
        "typescript": "npm:typescript@1.8.9.js"
      },
      "github:jspm/nodelibs-assert@0.1.0": {
        "assert": "npm:assert@1.3.0"
      },
      "github:jspm/nodelibs-os@0.1.0": {
        "os-browserify": "npm:os-browserify@0.1.2.js"
      },
      "github:jspm/nodelibs-path@0.1.0": {
        "path-browserify": "npm:path-browserify@0.0.0"
      },
      "github:jspm/nodelibs-process@0.1.2": {
        "process": "npm:process@0.11.2"
      },
      "github:jspm/nodelibs-util@0.1.0": {
        "util": "npm:util@0.10.3"
      },
      "npm:assert@1.3.0": {
        "util": "npm:util@0.10.3"
      },
      "npm:babel-runtime@5.8.38": {
        "process": "github:jspm/nodelibs-process@0.1.2"
      },
      "npm:core-js@1.2.6": {
        "fs": "github:jspm/nodelibs-fs@0.1.2",
        "path": "github:jspm/nodelibs-path@0.1.0",
        "process": "github:jspm/nodelibs-process@0.1.2",
        "systemjs-json": "github:systemjs/plugin-json@0.1.0"
      },
      "npm:inherits@2.0.1": {
        "util": "github:jspm/nodelibs-util@0.1.0"
      },
      "npm:os-browserify@0.1.2": {
        "os": "github:jspm/nodelibs-os@0.1.0.js"
      },
      "npm:path-browserify@0.0.0": {
        "process": "github:jspm/nodelibs-process@0.1.2"
      },
      "npm:process@0.11.2": {
        "assert": "github:jspm/nodelibs-assert@0.1.0"
      },
      "npm:typescript@1.8.9": {
        "os": "github:jspm/nodelibs-os@0.1.0.js"
      },
      "npm:util@0.10.3": {
        "inherits": "npm:inherits@2.0.1",
        "process": "github:jspm/nodelibs-process@0.1.2"
      }
    }
  });

**Comment by rob-bateman** [comment]
also, i have real trouble stopping builder from adding .js to ts files when defaultJSExtensions is enabled. without it, most libs in jspm fail because they need .js

you can seem my hamfisted fix to this above, but there has to be a better way!

**Comment by rob-bateman** [comment]
ok, i think i discovered something - issue #430:

> SystemJS and SystemJS builder will detect, run and build anonymous System.register modules just like any other module as a separate file.
>
> As soon as they are named System.register("moduleName", ... defines then it is no longer supported to build them.
>

If i understand correctly, this would throw out any possibility of using pre-bundled files in the creation of new bundles.

Would love to know if there is a fundamental issue with using built files in this way, as i would prefer to keep flattened files in my dist output rather than a replication of the folder tree

**Comment by rob-bateman** [comment]
@guybedford just to confirm, is the idea of allowing bundles to be rebundled something you would consider? I think it holds some value in cases where lib authors would prefer to have a single js file for distribution, and users would prefer to re-bundle for production releases

**Comment by guybedford** [comment]
@rob-bateman we support subtracting bundles as part of arithmetic, so in theory this is something that could be supported as a kind of concatenation of bundle files.

**Comment by rob-bateman** [comment]
@guybedford that would be great to have, but i also think there should be a way to use the bundle syntax as a way of rebundling existing register references in a library bundle _without_ simply concatenating the whole bundle. Kind of like the way webpack's CommonsChunkPlugin works
