### ISSUE TITLE
build: false doesn't seem to work as expected

### ISSUE THREAD

**Issue by MeoMix** [systemjs/builder#304]
Hey,

I'm looking at `trace.js` and I'm wondering how the `build: false` flag could ever work.

The function `getLoadRecord` calls `getCanonicalName` **before** looking at load.metadata.build. So, even if build was set to false, getCanonicalName would still be called and thus emit an error for an external URL.

Is there a working example of build: false working as expected?

Ref:

- https://github.com/systemjs/builder/blob/master/lib/trace.js#L22
- https://github.com/systemjs/builder/blob/master/lib/trace.js#L45

You stated on Gitter that I might need to map the external dependency to '@empty', but then the external dependency would not load at all. So, I don't believe that's the real cause. I just want to import the dependency asynchronously at run time.

**Comment by Mosho1** [comment]
I use `build: false` in production, where I get several dependencies (angular, moment, rxjs etc.). It's been working fine for months. Can I see your config.js?

**Comment by MeoMix** [comment]
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "background/*": "js/background/*",
    "common/*": "js/common/*",
    "contentScript/*": "js/contentScript/*",
    "foreground/*": "js/foreground/*",
    "test/*": "js/test/*",
    "lib/*": "js/lib/*",
    "github:*": "js/lib/jspm_packages/github/*",
    "npm:*": "js/lib/jspm_packages/npm/*"
  },

  meta: {
    "analytics": {
      "exports": "ga",
      "format": "global",
      "build": false
    }
  },

  map: {
    "analytics": "https://www.google-analytics.com/analytics.js",
    "babel": "npm:babel-core@5.8.23",
    "babel-runtime": "npm:babel-runtime@5.8.20",
    "backbone": "npm:backbone@1.1.2",
    "backbone.babysitter": "github:marionettejs/backbone.babysitter@0.1.10",
    "backbone.cocktail": "npm:backbone.cocktail@0.5.10",
    "backbone.wreqr": "github:marionettejs/backbone.wreqr@1.3.5",
    "chai": "npm:chai@3.2.0",
    "core-js": "npm:core-js@1.1.4",
    "jquery": "github:components/jquery@2.1.4",
    "lodash": "npm:lodash@3.10.1",
    "marionette": "github:marionettejs/backbone.marionette@2.4.2",
    "mocha": "npm:mocha@2.3.1",
    "process": "npm:process@0.11.1",
    "sinon": "npm:sinon@1.16.1",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.4.3"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.20": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:buffer@3.4.3": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.6",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:chai@3.2.0": {
      "assertion-error": "npm:assertion-error@1.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "deep-eql": "npm:deep-eql@0.1.3",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "type-detect": "npm:type-detect@1.0.0"
    },
    "npm:core-js@1.1.4": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:deep-eql@0.1.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "type-detect": "npm:type-detect@0.1.1"
    },
    "npm:formatio@1.1.1": {
      "process": "github:jspm/nodelibs-process@0.1.1",
      "samsam": "npm:samsam@1.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:lodash@3.10.1": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:mocha@2.3.1": {
      "css": "github:systemjs/plugin-css@0.1.16"
    },
    "npm:process@0.11.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:sinon@1.16.1": {
      "formatio": "npm:formatio@1.1.1",
      "lolex": "npm:lolex@1.3.1",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "samsam": "npm:samsam@1.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});

**Comment by Mosho1** [comment]
try moving it from `map` to `paths`, I think I had the same problem as well.

**Comment by MeoMix** [comment]
Seems to have helped. Encountering a new error:

> Global SFX bundle dependency "analytics" <analytics> must be configured to an environment global via the sfxGlobals option

**Comment by Mosho1** [comment]
If I'm not mistaken, you can just set `sfxGlobals: ['window.analytics']` or. You may also have to use `sfxFormat: 'global'`. This just wraps the SFX bundle with a function that is called with the dependencies.

**Comment by MeoMix** [comment]
Cool. Passing in 

      sfxGlobals: {
        analytics: 'window.ga'
      }

to buildSFX resolved the issue. Although I must admit I would've preferred it to just have realized it needed this through the "format: global" on the meta tag, but maybe those are entirely different things?

**Comment by Mosho1** [comment]
Maybe in conjunction with `build: false`. You can bundle global modules.

**Comment by guybedford** [comment]
Yes you need to use paths when bundling this as paths implies the names to use in the bundle.

SFX with an exclusion will assume you're loading it with a script tag though first. If you want it explicitly loaded use a normal bundle.

**Comment by guybedford** [comment]
Note this would get easier with https://github.com/systemjs/builder/issues/269.

**Comment by guybedford** [comment]
@MeoMix I've done some fixing up of build: false in the latest master branch.

**Comment by guybedford** [comment]
Released in 0.14.0.

**Comment by MeoMix** [comment]
:clap:  Thank you! <3

**Comment by MeoMix** [comment]
@guybedford I just tried it out and I'm still a bit confused. Can you explain the intended result?

I've got:

config.js:

  paths: {
    "analytics": "https://www.google-analytics.com/analytics.js"
  },

  meta: {
    "analytics": {
      "exports": "ga",
      "format": "global",
      "build": false
    }
  },

analyticsManager.js:

    import 'analytics';

Gruntfile.js:

      sfxGlobals: {
        analytics: 'window.ga'
      }

and when I run bundleSfx I have:

    "globals.window.ga analytics";

but that does not cause https://www.google-analytics.com/analytics.js to be requested ever.

**Comment by guybedford** [comment]
@MeoMix paths are never built in explicitly. Use map config rather if you want the bundle to contain the reference to `https://www.google-analytics.com/analytics.js`.

The other alternative is to alter the output format of your sfx build. Say outputting AMD or CommonJS, so that the analytics is an explicit require.

**Comment by MeoMix** [comment]
This still doesn't seem to work.

With the latest update if I move the analytics declaration back to map I encounter an exception, "Cannot read property 'substr' of undefined" which is due to another error in the code really trying to say that it cannot resolve the canonical name.

**Comment by guybedford** [comment]
Ah right, yes you would need to use paths actually, and then include that same paths and meta config in production.

**Comment by wprater** [comment]
@MeoMix did you ever solve this?  Im using google analytics too in a SFX build, but get module loading issue.

**Comment by guybedford** [comment]
@wprater what sort of issue are you getting here?

**Comment by MeoMix** [comment]
@guybedford @wprater No I did not get this successfully working. I'm taking another stab at it right now with a fresh mind, but I'm still struggling.

Here's the values I'm playing around with in my configuration file:

  paths: {
    "ga": "//www.google-analytics.com/analytics.js"
  },

  meta: {
    "//www.google-analytics.com/analytics.js": {
      "scriptLoad": true,
      "format": "global",
      "exports": "ga",
      "build": false
    },
  },

  map: {
    "ga": "//www.google-analytics.com/analytics.js"
  }

I have tried:

- Not referencing the module via "ga" and trying to import "//www...". This results in the error "Unable to calculate canonical name to bundle file://www..."

- Using explicit paths (i.e. https://) rather than leading with "//". This had no effect.

- When the `build:false` flag is included then `buildStatic` does not throw an error. However, the built page throws an error: `Uncaught Module 1 not present.` Toggling any of the other meta/path/map variables does not seem to affect this outcome. As far as I can tell `build:false` is not desirable.

- When I do not pass the `build:false` flag then buildStatic throws an error: `Unable to fetch https://www... Only file URLs of the form file:/// allowed running in node."

Here's a list of issues and documentation I've referenced while attempting to get this to work:

- https://github.com/jspm/jspm-cli/issues/984: This issue alludes that `build:false` should work.
- https://github.com/systemjs/builder/issues/269: This issue ALSO alludes that `build:false` should work.
- https://github.com/systemjs/systemjs/issues/225: This issue talks about script loading. More usefully, it links to a GitHub repository, https://github.com/circlingthesun/systemjs-script-plugin, which mentions the "scriptLoad" property. This isn't necessary for Google Analytics specifically, but could be useful for loading other external URLs.
- https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#exports: Documentation on using custom meta for loading analytics. Does not mention `build:false` and implies that the key for the meta entry should be the URL not the mapped name.

That's about where I'm at.

**Comment by guybedford** [comment]
@MeoMix my suggestion here would be this config:

```javascript
paths: {
    "ga": "//www.google-analytics.com/analytics.js"
},

meta: {
    "gs": {
        "build": false
    }
}
```

And then to do `jspm bundle-sfx app - ga --format amd`.

That should give you an AMD module of the form:

```javascript
define(['ga'], function(...) {
});
```

Then in the environment where you load the SFX module to add the loader config:

```javascript
paths: {
    "ga": "//www.google-analytics.com/analytics.js"
},
meta: {
    "//www.google-analytics.com/analytics.js": {
        "scriptLoad": true,
        "format": "global",
        "exports": "ga",
        "build": false
    }
}
```

Or even just to map it to a global in the first place via sfxGlobals and include Google Analytics with a script tag.

The point is - sfx bundles don't do dynamic fetching. They are just plain modules themselves.

**Comment by MeoMix** [comment]
@guybedford Thanks for the response. Your answer has left me with more questions :)

I'm creating my build via Gulp. So, I'm doing a bit of juggling in my head to convert your suggestions from command line to JS. Just going to reiterate my thoughts below.

My goals are:

- Do not transform code during a build step to include a script tag.
- Leverage ES6 'import' to load an aliased external URL (i.e. `import 'analytics'`)
- Preserve working functionality. `import 'analytics'` works prior to bundling.

I am building an SFX bundle using the following code:

	gulp.task('build-compiledJs', (done) => {
		const builder = new Builder('compiled/', 'config.js');
		const options = {
			runtime: false
		};

		builder.buildStatic('main.js', `dist/main.js`, options)
			.then(() => {
				util.log(util.colors.green(`Built successfully to ${paths.dist}`));
			})
			.catch((errorMessage) => {
				util.log(util.colors.red(errorMessage));
			})
			.finally(done);
	});

I believe this logic is equivalent to `jspm bundle-sfx compiled/main dist/main` with the exception of the `runtime: false` option.

Confusion I have from your response:

- Your first code snippet indicates that the `build: false` option should be provided in `config.js`. However, you then state I should run `jspm bundle-sfx` with the `- ga` arithmetic. I do not understand why both of these are necessary. `- ga` signals that the module should be excluded from bundling, but I would expect that to be known from `config.js`. If this is not the case - what use is specifying `build:false` in `config.js`?

- You imply that there are two distinct configurations at work here. I do not believe that to be the case with my setup because I am providing the `runtime: false` option. I do not believe I need to provide `jspm_packages/` nor `config.js` as independent files for distribution. All I need to do is target my original `config.js` with SystemJS-Builder and provide additional options as necessary, correct?

Taking all of that into consideration... I still feel like my current configuration makes sense and should work:

- I provide `build:false` in `config.js` to signal to SystemJS-Builder that it should skip over `ga` during bundling.
- This is a self-executing bundle with all ES6 converted to ES5. So, providing `runtime: false` as an option to exclude Babel makes sense and should not introduce any issues. I have no desire to provide just-in-time transpilation in production.
- I have given SystemJS-Builder a reference to `config.js` and it has used it to generate the build. Importing an external dependency works in development, prior to bundling, and I have excluded the module in question from being considering by the bundler. So, it should be untouched and remain functional.

I'm clearly missing something from all of this. Could you enlighten me?

**Comment by guybedford** [comment]
> Your first code snippet indicates that the build: false option should be provided in config.js. However, you then state I should run jspm bundle-sfx with the - ga arithmetic. I do not understand why both of these are necessary. - ga signals that the module should be excluded from bundling, but I would expect that to be known from config.js. If this is not the case - what use is specifying build:false in config.js?

That is the way it should work yes, but this is pending https://github.com/systemjs/builder/issues/407.

The thing missing here is that Google analytics is not being built into your bundle, as we don't build URLs. Even if we did build URLs, Google analytics would likely not work as it relys on being loaded dynamically in the page it is used on. So once you have your SFX bundle, you still need to somehow tell the page to go and fetch Google analytics before running your code. That means either including a script tag in the head, or treating your SFX bundle as a module which depends on Google analytics.

**Comment by MeoMix** [comment]
Okay.

If I treat my SFX bundle as a module with a dependency on GA then I will need to bloat my distribution file with tools to handle module dependencies, correct? That doesn't seem ideal.

Including a script tag, while totally doable, feels odd to me. The `scriptLoad` attribute hints at the fact that SystemJS can totally generate that script tag for me and does so for development... but then leaves me high and dry for production?

Do people really load external dependencies via SystemJS only for development and then write a manual transform for production? I don't see any benefit in that compared to simply using script tags from the start. And, if that's the case, I'm surprised there isn't some big, bold text in the documentation highlighting that SystemJS shouldn't be used to load external dependencies for production. All of the docs just seem to skirt around the fact by hinting that the module can be excluded from the build... but what use is that?

**Comment by guybedford** [comment]
@MeoMix to focus on the solution, I'd suggest using the `globalDeps: { ga: 'ga' }` option when building the sfx bundle into a global module, and then just loading Google analytics with a script tag before loading the SFX script. It will then pick up Google analytics from the `ga` global.

**Comment by MeoMix** [comment]
Ehh. I agree that given the scenario that's probably the best suggestion that falls inline w/ JSPM/Modules, but waiting for external dependencies to load before being able to start parsing my bundle sounds bad for performance. I ended up just throwing it onto the page as an async/defer'ed script tag and coded against the global with the assumption that it might not be defined yet.
