### ISSUE TITLE
Calling builder.buildSFX multiple times

### ISSUE THREAD

**Issue by MeoMix** [systemjs/builder#305]
Hey,

I've currently got the following (ugly) code:

    var backgroundBuilder = new Builder(undefined, 'src/js/lib/jspm.config.js');
    backgroundBuilder.loader.baseURL += 'src/';

    var foregroundBuilder = new Builder(undefined, 'src/js/lib/jspm.config.js');
    foregroundBuilder.loader.baseURL += 'src/';

    var youTubePlayerBuilder = new Builder(undefined, 'src/js/lib/jspm.config.js');
    youTubePlayerBuilder.loader.baseURL += 'src/';

    var done = this.async();
    var options = {
      runtime: false,
      sourceMaps: false,
      minify: false
    };

    Promise.all([
      backgroundBuilder.buildSFX('js/background/plugins.js', 'dist/js/background/main.js', options),
      foregroundBuilder.buildSFX('js/foreground/plugins.js', 'dist/js/foreground/main.js', options),
      youTubePlayerBuilder.buildSFX('js/contentScript/youTubePlayer/plugins.js', 'dist/js/contentScript/youTubePlayer/main.js', options)
    ]).then(function() {
      grunt.task.run('replace:manifestCleanup replace:htmlBundle');
      done();
    }).catch(function(error) {
      console.log('buildSFX error:', error);
      done();
    });

I'd like to clean it up by (at the very least) using a single Builder instance rather than N Builder instances. However, if I try to call .buildSFX like so:

    var builder = new Builder(undefined, 'src/js/lib/jspm.config.js');
    builder.loader.baseURL += 'src/';

    var done = this.async();
    var options = {
      runtime: false,
      sourceMaps: false,
      minify: false
    };

    Promise.all([
      builder.buildSFX('js/background/plugins.js', 'dist/js/background/main.js', options),
      builder.buildSFX('js/foreground/plugins.js', 'dist/js/foreground/main.js', options),
      builder.buildSFX('js/contentScript/youTubePlayer/plugins.js', 'dist/js/contentScript/youTubePlayer/main.js', options)
    ]).then(function() {
      grunt.task.run('replace:manifestCleanup replace:htmlBundle');
      done();
    }).catch(function(error) {
      console.log('buildSFX error:', error);
      done();
    });

This throws errors, though. I was wondering if this could be supported, or perhaps if there was another, more intended method of building multiple packages.

**Comment by guybedford** [comment]
Sure, I've created https://github.com/systemjs/builder/issues/308 to track this.
