### ISSUE TITLE
Babel runtime not getting traced

### ISSUE THREAD

**Issue by Mosho1** [systemjs/builder#306]
I'm trying to trace using babel with `optional: ["runtime"]`, and the resulting trace doesn't have the `babel-runtime/helpers/interop-require-default` or any of the runtime that would be required.

Here's what I run:

    var SystemjsBuilder = require('systemjs-builder');
    var builder = new SystemjsBuilder()
    builder.loadConfigSync('config.js');
    builder.trace('test.js').then(function(x) {console.log(Object.keys(x))})

test.js

    import babel from 'babel';

config.js

    System.config({
      baseURL: "/",
      defaultJSExtensions: true,
      transpiler: "babel",
      babelOptions: {
        "optional": [
          "runtime",
          "optimisation.modules.system"
        ]
      },
      paths: {
        "github:*": "jspm_packages/github/*",
        "npm:*": "jspm_packages/npm/*"
      },

      map: {
        "babel": "npm:babel-core@5.8.23",
        "babel-core": "npm:babel-core@5.8.23",
        "babel-runtime": "npm:babel-runtime@5.8.20",
        "core-js": "npm:core-js@1.1.4",
        "github:jspm/nodelibs-process@0.1.1": {
          "process": "npm:process@0.10.1"
        },
        "npm:babel-runtime@5.8.20": {
          "process": "github:jspm/nodelibs-process@0.1.1"
        },
        "npm:core-js@1.1.4": {
          "fs": "github:jspm/nodelibs-fs@0.1.2",
          "process": "github:jspm/nodelibs-process@0.1.1",
          "systemjs-json": "github:systemjs/plugin-json@0.1.0"
        },
      }
    });

the resulting trace has the keys:

    [ 'test.js',
      'npm:babel-core@5.8.23',
      'npm:babel-core@5.8.23/browser' ]

while the result from `babel test.js --optional=runtime` is: 

    var _interopRequireDefault = require('babel-runtime/helpers/interop-require-default')['default'];
    var _babel = require('babel');
    var _babel2 = _interopRequireDefault(_babel);

which, if run through builder.trace results in the keys:

    [ 'test.js',
      'npm:babel-core@5.8.23',
      'npm:babel-runtime@5.8.20/helpers/interop-require-default',
      'npm:babel-core@5.8.23/browser' ]

**Comment by guybedford** [comment]
`interop-require-default` is a helper that is only needed for CommonJS, and not when using ES6 directly in jspm. Try using a feature like class extension to see the helpers show up in the trace.

**Comment by Mosho1** [comment]
It's something that babel uses instead of the inline functions when you opt for `optional: ["runtime"]`. Since transpiling on the fly is slow, I transpile to a separate folder and use that for development, so I `import` the transpiled ES5 files, where these helper modules are a requirement. I don't see how it has anything to do with CommonJS.

**Comment by guybedford** [comment]
It is your own precompilation step that would be expected to include the helpers here in this case. It's not trivial though I know, and would be great if jspm could handle it, or a jspm gulp task. Note that this is a jspm issue though.

**Comment by Mosho1** [comment]
I'm still not sure what you mean. Where would they go? I don't want to include the helpers as a script, I want to have them as a module registered with System, and this seems like the natural way to do that. I'm also pretty sure this worked in some past version. 

Anyway, simply going over the trace and setting `metadata.format = 'cjs'` adds the missing modules correctly and everything seems to work.

**Comment by guybedford** [comment]
@Mosho1 jspm will manage the helpers for you only if you build through jspm. So the ability for jspm to precompile separate files would enable this - which is definitely a useful feature to have. Tracking at https://github.com/jspm/jspm-cli/issues/1107.
