### ISSUE TITLE
Parallel builds

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#308]
Apparently we're still getting errors on parallel build operations. We should fix these and include some tests to ensure they work out.

**Comment by typhonrt** [comment]
Making a reference to #384  as I ran into a problem with 0.14.10 that prevented using `loadConfig` with parallel builds. Previous versions 0.14.1 - 9 didn't exhibit this problem.

**Comment by guybedford** [comment]
Closing to rather track individual issues if they arise further.
