### ISSUE TITLE
Builder.build getCache and setCache not working (non sfx builder)

### ISSUE THREAD

**Issue by jonricaurte** [systemjs/builder#310]
Due to the below ticket, I started using builder.getCache and builder.setCache and did not use the sfx bundler.

https://github.com/systemjs/builder/issues/296

My code is below:

```
var cache;
gulp.task('js', ['slim'], function(done) {
  var builder = new Builder({
    baseURL: '.',
    transpiler: 'babel'
  });

  //if (cache){
  //  builder.setCache(cache);  
  //}
  
  builder.loadConfig('config.js')
    .then(function() {
      builder.build('app/assets/javascripts/application.js', 'public/assets/application.js')
        .then(function () {
          //cache = builder.getCache();
          done();
        })
        .catch(error);
    })
    .catch(error);

  function error(msg) {
    console.log('Build error');
    console.log(msg);
    done();
  }
});
```

When the task rebuilds when watching js files, it builds correctly when the cache is commented out. However when I put the cache in, it doesn't see the new changes and gives me the old file contents. I tried putting console.log('test') in a js file, and then changing it to console.log('testing'). Without the cache, on the rebuild I get testing in the console, but with the cache, I get test.

I am wondering if I am doing something wrong?

Thanks!

**Comment by jonricaurte** [comment]
I ended up just trying with nothing but a console.log in my application.js file, and it does not get the new changes.

```
console.log('test')
```
Then I change my application.js to be:
```
console.log('testing')
```
and it logs test.

**Comment by guybedford** [comment]
@jonricaurte the cache needs to be manually invalidated yes, by removing entries from the `cache.trace`. Any suggestions for a better invalidation API are welcome too here, but I thought letting the caching system do the magic seemed to make the most sense.

**Comment by jonricaurte** [comment]
@guybedford Thanks for an update on this, too. So I made a gulp task that looks like the following:

```
gulp.task('js', function () {
  return gulp.src('app/assets/javascripts/**/*.js')
    .pipe(plumber())
    .pipe(cache('scripts'))
    .pipe(babel({ 
      modules: 'system', 
      moduleIds: false,
      getModuleId: function (name) {
        return name + '.js';
      }
    }))
    .pipe(remember('scripts'))
    .pipe(concat('application.js'))
    .pipe(gulp.dest('public/assets'));
});
```
What this does is use https://github.com/wearefractal/gulp-cached to: "This keeps an in-memory cache of files (and their contents) that have passed through it. If a file has already passed through on the last run it will not be passed downstream. This means you only process what you need and save time + resources."

So the first time it builds, it will take about 8 seconds because none of the files are stored in memory. Then it transpiles all the files using babel with system modules.Then it uses https://github.com/ahaurw01/gulp-remember to bring back all the files that it has seen in the stream: 'gulp-remember is a gulp plugin that remembers files that have passed through it. gulp-remember adds all the files it has ever seen back into the stream.'

What is nice about this set up is the first time gulp-cached will read all the files and pass along all the files  to babeljs to transpile into es5. Then it will go through gulp-remember which will add all the transpiled files to its own in memory cache. The next time I change a file, gulp-cached will only pass along that specific file to babeljs to be retranspiled again. Then gulp-remember will bring back all the other already transpiled files and put them back in the stream. Then I concat all the transpiled files into one file. Using jspm cache, without removing the cache.trace, it took my app 3-4 seconds to reload. Using the above method, takes 200 milliseconds. It would be awesome if systemjs builder internally had something similar to the above setup.

Thanks!

**Comment by guybedford** [comment]
Thanks for sharing your workflow here. Yes I'm working on optimizing the builder caching to get these times down, will be looking into this next week.

**Comment by jonricaurte** [comment]
@guybedford Thanks! Looking forward to the changes.
