### ISSUE TITLE
Unable to bundle react-router

### ISSUE THREAD

**Issue by jbe456** [systemjs/builder#319]
In one of the file I'm bundling there is the following ES6 import:

```
import Router from 'react-router';
```

Here is the bundler configuration:
```
{
  paths: {
    'react-router': 'file:/' + require.resolve('react-router/lib/index.js')
  }
}
```
The `index.js` from `react-router` is importing other files through `require` which are not resolved.

```
'use strict';

exports.DefaultRoute = require('./components/DefaultRoute');
exports.Link = require('./components/Link');
...
```

**My first issue is related to the upgrade to version 0.14.3**
 In version 0.14.3, it triggers the following stack:

```
TypeError: Cannot read property 'substr' of undefined
    at Trace.getLoadRecord (C:\Users\User\MyProject\node_modules\systemjs-builder\lib\trace.js:67:16)
    at Trace.getAllLoadRecords (C:\Users\User\MyProject\node_modules\systemjs-builder\lib\trace.js:377:15)
    at C:\Users\User\MyProject\node_modules\systemjs-builder\lib\trace.js:387:21
    at Array.map (native)
    at C:\Users\User\MyProject\node_modules\systemjs-builder\lib\trace.js:386:96
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
```

Looking at the code, the `depMap` attribute of the `load` object is empty.

In version 0.13.6, I had a nicer error:

```
Unable to calculate canonical name to bundle file:///C:/Users/User/MyProject/node_modules/react-router/lib/components/DefaultRoute
```

**My second issue is related to the unresolved files**
I'm trying to use `paths` to resolve the file by adding a `.js` at the end (I assume this is the reason why it is not resolved). I tried the following without luck:

```
{
  paths: {
    'absolute_path_to_react-router/*': 'absolute_path_to_react-router/*.js'
  }
}
```

Looking at `utils.js` method `getCanonicalName` in v 0.13.6 this is what I have:

`p` = `file:///C:/Users/User/MyProject/node_modules/react-router/lib/*`
`curPath` = `file:///C:/Users/User/MyProject/node_modules/react-router/lib/*.js`
`normalized` = `file:///C:/Users/User/MyProject/node_modules/react-router/lib/components/DefaultRoute`

`normalized.substr(0, wIndex)` = `file:///C:/Users/User/MyProject/node_modules/react-router/lib/`
`curPath.substr(0, wIndex)` = `file:///C:/Users/User/MyProject/node_modules/react-router/lib/`
`normalized.substr(normalized.length - curPath.length + wIndex + 1)` = `ute`
`curPath.substr(wIndex + 1)` = `.js`

Did I misunderstood the paths API?

**Comment by guybedford** [comment]
Thanks for posting. I'm not sure I follow exactly your API use here, but it sounds like you're trying to load a NodeJS module that won't be able to load in SystemJS without custom package config that you need to set up to add `defaultExtension` and other such properties, or to have this done automatically with a tool like jspm.

The error reporting issue above has now been fixed in https://github.com/systemjs/builder/issues/317. Posting out a patch shortly.

**Comment by jbe456** [comment]
OK I managed to load correctly the `react-router` dependency using the `packages` configuration:

```
{
  baseURL: '../../../node_modules',
  transpiler: 'babel',
  babelOptions: {
    modules: 'system',
    moduleIds: true,
    keepModuleIdExtensions: true,
    sourceMaps: true
  },
  packages: {
    'react-router': {
      main: 'lib/index.js',
      //format: 'cjs',
      defaultExtension: 'js',
      map: {
        'object-assign': './node_modules/object-assign/index.js',
        'qs': './node_modules/qs/lib/index.js'
      }
    },
    react: {
      main: 'dist/react.js',
      //format: 'global',
      defaultExtension: 'js'
    }
  }
}
```

However, the output file still contains `require`, `process` or `module` variables.

I'm getting the following error `Uncaught ReferenceError: process is not defined` or `Uncaught ReferenceError: module is not defined` if I force the format as shown in the commented lines.

Seems like I'm missing a part of the API. Any idea?

PS: I'm using `systemjs` 0.19.2 and `systemjs-builder` 0.14.5

**Comment by guybedford** [comment]
Yes you would need to ensure the `format: 'cjs'` option is set, and also add the `process` global via a shim library that can provide it as expected in Node, something like:

```javascript
'react-router': {
      main: 'lib/index.js',
      format: 'cjs',
      defaultExtension: 'js',
      map: {
        'object-assign': './node_modules/object-assign/index.js',
        'qs': './node_modules/qs/lib/index.js'
      },
      globals: {
        process: 'some-process-shim-library'
      }
    },
```

This is all because SystemJS uses a completely different resolution system to NodeJS modules. jspm can handle some of this stuff for you if you do `jspm install npm:react-router`. But if you keep going along this path, it will work out absolutely fine, and it looks like you've already made good progress too.

Just let me know if you need any more help here at all.

**Comment by jbe456** [comment]
Unfortunately I cannot access `jspm/nodelibs` shims for `process` or `module` because they are not available on npm registry and I could not find one for `module`.

This is where you could ask me why don't you use `jspm`? because I would like to use a bundler in a gulp task without having to maintain a config file or launch a CLI (as you could do with browserify for example). I don't think I can do that with jspm, but correct me if I'm wrong.

**Comment by guybedford** [comment]
The shims to use are the Browserify shims. These are listed at https://github.com/substack/node-browserify#compatibility and can be installed through npm and configured to be used via the package configs. Note that the shim packages themselves will also in turn need to be configured with package configuration in this way.
