### ISSUE TITLE
"System is not defined" in SFX bundle

### ISSUE THREAD

**Issue by JordanBelford** [systemjs/builder#320]
I started getting this error after updating to jspm 0.16.6
At the end of my static bundle I have lines such as
```System.register('client/css/site.css!github:systemjs/plugin-css@0.1.16', [], false, function() {});```

The problem is, the rest of the file is using "$__System.register" instead of "System.register"
Chrome throws a "System is not defined" error when I try to run with the SFX.

I manually renamed these lines to "$__System" and the bundle worked fine.

I could see this cropping in during the refactoring in commit 83a1b4a341699ec0299767facdab19f61492b477
There are changes to the regex replacement for the "$__" prefix

**Comment by guybedford** [comment]
Try updating the CSS plugin - it has a patch to support SFX bundles with this release.

**Comment by JordanBelford** [comment]
Awesome, that was it. I will remember to update jspm next time. Thanks @guybedford
