### ISSUE TITLE
imports started with / not supported? 

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/builder#321]
I noticed that when I use `bundle-sfx` I can't start an import with `/`, while this works fine with SystemJS. 
So I can't do: 
``` javascript
import Library from '/lib/library.js';
```
I can do: 
``` javascript
import Library from 'lib/library.js';
import Library from '../library.js';
```
It's mostly confusing because you'd expect these to work out paths in the same way.

**Comment by guybedford** [comment]
When running in a builder environment, `/` paths mean root-relative to the file system. They will work, but just aren't consistent between browser and build environments.
