### ISSUE TITLE
problem changing buildUrl for builder

### ISSUE THREAD

**Issue by Jandalf** [systemjs/builder#323]
just starting a separate issue (original #182)

I have this folder structur

client/js/bootstrap.ts
client/index.html (including config.js and importing bootstrap.ts)
config.js (baseURL: "../")
gulpfile.js
jspm_packages

and this gulp task

    gulp.task('js', function (cb) {
        var Builder = require('systemjs-builder'),
            builder = new Builder('./', './config.js');

        builder.reset();

        builder.buildStatic('client/js', 'dist/app.min.js', {
                minify: true
         })
        .then(() => cb)
        .catch(cb);
    });

running the index.html with live-server is no problem but running the gulp task will throw this error:

    Error: ENOENT: no such file or directory, open '/dev/github/jspm_packages/github/frankwallis/plugin-typescript@2.0.17.js'

because the path should be '/dev/github/repo-name/jspm_packages/github/frankwallis/plugin-typescript@2.0.17.js'

how should I configure the builder?

(simple repo with this example https://github.com/Jandalf/angular2-jspm-docker-vscode-template)

**Comment by guybedford** [comment]
The above should certainly work. It sounds like the `baseURL` value from `config.js` of `../` is somehow leaking in which it shouldn't. Have you tried this with the latest version of SystemJS Builder?

**Comment by Jandalf** [comment]
I had version 0.14.3 and updated to 0.14.7 and now everything builds. thank you.
