### ISSUE TITLE
Supporting source string as input

### ISSUE THREAD

**Issue by dristic** [systemjs/builder#330]
This would be the ability to provide a string as input into the builder that is JavaScript source code, i.e.:
```javascript
var script = "import foo from 'bar.js'; function useBar() { bar(); }";
var builder = new Builder('', 'system.conf.js');
builder.buildStatic(script);
```

The reason for this would be for build systems such as gulp, where you can chain multiple commands together. In my instance I am trying to build angular templates, attach them to the initial source file, then use system to build my dependency tree.

Thoughts?

**Comment by guybedford** [comment]
It might be possible to provide this via a fetch hook for the builder:

```javascript
builder.fetch = function(path) {
  return 'my custom source';
}
```

It could well be a useful feature to have.

**Comment by dristic** [comment]
Sounds like a good idea! I will try to look into it if I have some extra time.

**Comment by dristic** [comment]
I added a pull request for this. It is a first draft, just looking for feedback.

I am not entirely happy with passing around the `fetchHook` everywhere, but I don't think it can be avoided. This implementation was the easiest way to provide a fetch hook even for use in expression strings and dependency fetches, which is nice.
