### ISSUE TITLE
Global System access in SFX bundles

### ISSUE THREAD

**Issue by derekrobbins** [systemjs/builder#332]
It would be nice to have a build option for SFX bundles that will expose the System object to the global scope with all of the modules contained within the bundle registered as loaded. This would effectively leave the user in the same state as including system.js then executing System.import('bundle') but would do it in a single, render-blocking script tag.

**Comment by davis** [comment]
+1

**Comment by guybedford** [comment]
SFX bundles will be making internal optimizations and as such not exposing any internal registry at all. Normal bundles with a micro build of SystemJS would be the better focus for this kind of workflow, and better micro bulids of SystemJS will be an area for further work in future.

**Comment by CxRes** [comment]
@guybedford I have a use case where I am lazy-loading modules with SystemJS which cannot be known at the time of bundling (I believe that with webcomponents this will happen more and more). As of now the only way I can use sfx bundling is if I include SystemJS within that bundle as a jspm dependency.  Or I create a regular bundle and push SystemJS separately to the browser first. Even with microbuilds of SystemJS wouldn't this imply a redundancy (leaving aside http/2) - either I push two things or I push something larger. Or am I missing something and should I be doing things differently altogether?
