### ISSUE TITLE
"Unable to calculate canonical name to bundle" using "text" plugin. UPD: problem with relative paths

### ISSUE THREAD

**Issue by finom** [systemjs/builder#334]
Hey guys. I'm getting the error when using "text" plugin.
```js
import gTemplate from '../templates/g.html!text'
```
```
Unable to calculate canonical name to bundle file:///home/.../templates/g.html
```

My config file:
```js
System.config({
    transpiler: 'babel',
    baseURL: 'src',
    defaultJSExtensions: true,
    babelOptions: {
        stage: 0
    },
    map: {
        text: 'lib/text'
    }
});
```
The part of my gulpfile:
```js
gulp.task('build', function(cb) {
	var path = require("path");
	var Builder = require('systemjs-builder');
	var builder = new Builder();

	builder.loadConfig('src/config.js').then(function() {
		builder.buildStatic('app.js', 'dist/js/app.js')
			.then(function() {
				console.log('Build complete');
				cb();
			})
			.catch(function(err) {
				console.log('Build error');
				console.log(err);
				cb();
			});
	}).catch(function(e) {
		console.error(e);
	})
});
```

package.json
```js
...
"systemjs-builder": "^0.14"
...
```

That can I do?

**Comment by finom** [comment]
Guys?

**Comment by finom** [comment]
OK, just made a quick look to the source code (getCanonicalNamePlain function) and moved ``templates`` folder to the root of ``basePath`` (it looks really tricky!). Anyway I've done it. The new problem is that html module isn't presented in compiled JS file. JS throws an error:
```
Uncaught Module 2 not present.
```

**Comment by guybedford** [comment]
`baseURL` needs to be the lowest common path as it is the shared reference point between browser and server for bundling. If you want to have `import 'x'` not import from the baseURL, you can use a wildcard paths configuration to set this to any other path within the baseURL.

**Comment by finom** [comment]
@guybedford OK, but client-side SystemJS allows to use paths outside of basePath. Can you throw an error or so?

**Comment by guybedford** [comment]
@finom paths outside of the baseURL are allowed in builder, they just won't build in bulder (that is they would need `build: false` metadata).
