### ISSUE TITLE
esmExports support in static builds

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#338]
From https://github.com/systemjs/systemjs/issues/714#issuecomment-143837640

**Comment by lookfirst** [comment]
:+1:

**Comment by laurentdesmet** [comment]
+1 for this one, because it causes a security exception when using static bundles in cross origin iframes and the core-js global module.

**Comment by guybedford** [comment]
I've included an alternative fix for this issue in https://github.com/systemjs/builder/commit/78887114b077777a64d037a5983900efe0be49b4, which is basically just not to do separate exports when the module is the environment global. That should cover the major use case for this for now.

**Comment by ggutenberg** [comment]
How do we make this fix work in conjunction with jspm?  I've updated jspm to the latest version, and run `jspm update`, but the fix mentioned here isn't included, and the system.js files didn't change.

**Comment by guybedford** [comment]
This option has been deprecated in SystemJS now.
