### ISSUE TITLE
Conditional support for static bundle build

### ISSUE THREAD

**Issue by martinmicunda** [systemjs/builder#339]
Hi @guybedford,

For last couple of months I am using `conditional import` feature in my app and I can see you have added this feature to `builder` but it doesn't work as I would expect so let me explain my use case.

**Development Workflow**:
I have file called [`env.conditions.js`](https://github.com/martinmicunda/employee-scheduling-ui/blob/master/env.conditions.js) where I defined global conditions (these value are always injected from cli e.g. by `gulp-inject`):

```js
window.ENV = {
    <!-- inject:env -->
    mock: false, optimize: false, environment: 'dev',
    <!-- endinject -->
};

System.set('ENV', System.newModule({ 'default': window.ENV, __useDefault: true }));
```

then in my [`index.html`](https://github.com/martinmicunda/employee-scheduling-ui/blob/master/src%2Findex.html) I include this file:

```html
<script src="jspm_packages/system.js"></script>
<script src="jspm.conf.js"></script>
<script src="env.conditions.js"></script>
<script>
    System.import('app/app').catch(console.error.bind(console)); 
</script>
```
here is how I use these conditions in my [code](https://github.com/martinmicunda/employee-scheduling-ui/blob/master/src%2Fapp%2Fcore%2Fconfig%2Fconfig.js#L9):

```js
import './config.#{ENV|environment}.js';
import './employee.mock.js#?ENV|mock';
```

and all this work **great**.

**SFX bundle Workflow**:
Currently I am using `gulp-preprocess` to remove all these conditions from source code to create bundle and this is really ugly workaround hack and I saw couple days ago you have added conditional support to builder so I decided to try it but I can't get conditional import works with builder in way that I need for my project. I know that current builder conditional support only condition for different packages but my **requirement is that builder load `env.conditions.js` file that includes all these conditions and build the SFX bundle**. When I try build the bundle then builder is throwing error because it can't find conditions that are defined in the source code. I also tried add these conditions to source code but nothing work for me so **is there way that I can include this file somewhere in build config so when builder start creating bundle it first load these conditions?**. Thanks

```js
gulp.task('bundle', (cb) => {
    const Builder = require('systemjs-builder');
    const builder = new Builder();
    const inputPath = 'src/app/app'; 
    const outputFile = `${path.tmp.scripts}build.js`;
    const outputOptions = { sourceMaps: true, config: {sourceRoot: path.tmp.scripts} };

    builder.loadConfig(`${path.root}/jspm.conf.js`)
        .then(() => {
            builder.buildStatic(inputPath, outputFile, outputOptions)
                .then(() => cb())
                .catch((ex) => cb(new Error(ex)));
        });
});
```

**Comment by guybedford** [comment]
@martinmicunda thanks for trying this work out!

SFX bundles do support conditional builds, but they need to be provided with the exact environment conditions to build.

This can be done via - 

```javascript
buildStatic(inputPath, outputFile, { conditions: { 'ENV|mock': true, 'ENV|environment': 'production', 'ENV|optimize': true } })
```

The builder will need a complete unique conditions solution to do an SFX build (unlike normal bundling which will be able to deal with conditions being indeterminate). Tracking of SFX build support for indeterminate conditions is in https://github.com/systemjs/builder/issues/311.

Also I guess you know but just to mention again this stuff isn't completely stable yet.

**Comment by martinmicunda** [comment]
@guybedford hmm that doesn't work ... Am I missing something?

this is my SFX builder task:
```js
gulp.task('bundle', ['jshint', 'js-preprocess'], (cb) => {
    const Builder = require('systemjs-builder');
    const builder = new Builder();
    const inputPath = 'src/app/app'; with conditional import for systemjs-builder will be fixed
    const outputFile = `${path.tmp.scripts}build.js`;
    const outputOptions = { sourceMaps: true, config: {sourceRoot: path.tmp.scripts}, conditions: { 'ENV|mock': false, 'ENV|environment': 'prod', 'ENV|optimize': true } };

    builder.loadConfig(`${path.root}/jspm.conf.js`)
        .then(() => {
            builder.buildStatic(inputPath, outputFile, outputOptions)
                .then(() => cb())
                .catch((ex) => cb(new Error(ex)));
        });
});
```
and these are conditions in my source code:

```js
import './config.#{ENV|environment}.js';
import './employee.mock.js#?ENV|mock';
```

I am getting follow error:

```bash
 Error: Error: ENOENT, open '/Users/martinmicunda/projects/employee-scheduling/ui/ENV.js'
    at /Users/martinmicunda/projects/employee-scheduling/ui/gulp/tasks/scripts.js:68:35
    at lib$rsvp$$internal$$tryCatch (/Users/martinmicunda/projects/employee-scheduling/ui/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/martinmicunda/projects/employee-scheduling/ui/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/martinmicunda/projects/employee-scheduling/ui/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$$internal$$publishRejection (/Users/martinmicunda/projects/employee-scheduling/ui/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:419:7)
    at lib$rsvp$asap$$flush (/Users/martinmicunda/projects/employee-scheduling/ui/node_modules/systemjs-builder/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by guybedford** [comment]
This sounds like it could be a bug due to the handling of environment condition canonicalization not detecting the set module correctly. I'll look into it!

**Comment by martinmicunda** [comment]
@guybedford thanks .. You can ping me once you fix it and I will verify if it's working

**Comment by guybedford** [comment]
Sure, will do!

**Comment by guybedford** [comment]
@martinmicunda I just had a look at this and the reason is that the builder will still try to trace the environment conditional itself as it is considered as a dependency to include in the bundle, as conditions are always evaluated dynamically at runtime, and not built in statically.

**Comment by martinmicunda** [comment]
@guybedford so how can include 'env.conditions.js' as a dependency into bundle should be that done through systemjs config?

**Comment by guybedford** [comment]
@martinmicunda it will be done for you - you just need to ensure that the condition is itself a module that is available to be loaded. I've added a test in https://github.com/systemjs/builder/commit/55b41980e14aa87d2c1c77b159f140c5bb2b3997 which may also help to see how it works.

**Comment by martinmicunda** [comment]
@guybedford I still didn't get that fully running but I made at least some progress...

*env.conditions.js* -> where I define ENV module
```js
'use strict';

window.ENV = {
    mock: true, optimize: false, environment: 'test'
};

System.set('ENV', System.newModule({ 'default': window.ENV, __useDefault: true }));
```

*jspm.config.js* -> I include this file in `map` block
```js
  map: {
      "ENV": "env.conditions.js",
```

*gulp SXF bundle task*
```js
gulp.task('bundle', ['jshint'], (cb) => {
    const ENV = !!util.env.env ? util.env.env : 'DEV';
    const Builder = require('systemjs-builder');
    const builder = new Builder();
    const inputPath = 'src/app/app'; 
    const outputFile = `${path.tmp.scripts}build.js`;
    const outputOptions = { sourceMaps: true, config: {sourceRoot: path.tmp.scripts}, conditions: { 'ENV|mock': ENV.toLowerCase() === 'test', 'ENV|environment': ENV.toLowerCase()} };

    builder.loadConfig(`${path.root}/jspm.conf.js`)
        .then(() => {
            builder.buildStatic(inputPath, outputFile, outputOptions)
                .then(() => cb())
                .catch((ex) => cb(new Error(ex)));
        });
});
```

this will create SXF bundle without error but when I load my app I am getting follow error:

```
Uncaught ReferenceError: System is not defined
```

I am assuming it something to do with `System.set` that I define in `env.conditions.js` file...

I have also one question why do I need to still specify `conditions: { 'ENV|mock': ENV.toLowerCase() === 'test', 'ENV|environment': ENV.toLowerCase()} }` in output options when I already include them to `jspm.config.js` map block `map: {"ENV": "env.conditions.js",...}` as module. Wouldn't be easy when I specify all my conditions in one file and then builder just load them as module so I don't need to duplicate this logic?

**Comment by guybedford** [comment]
@martinmicunda try writing your condition module as just:

env.conditions.js
```javascript
export var mock = true;
export var optimize = true;
// ..etc..
```

with a `System.config({ map: { 'ENV': 'env.conditions.js' } })`.

**Comment by martinmicunda** [comment]
@guybedford yeah I did 

```
export var mock = true;
export var environment = 'test';
```

but know when I create SFX bundle and load this bundle in the browser I am getting follow error:

```
Uncaught TypeError: Cannot read property 'noop' of undefined
```

**Comment by guybedford** [comment]
@martinmicunda that sounds like something else here! Any clues which line of code that is happening on?

**Comment by martinmicunda** [comment]
@guybedford I fixed the problem with `noop`. The problem was how I map angular dependencies in my `jspm.config.js` file.

I find one more bug and I have one enhancement question:

**Bug:**

If I set conditions in bundle like this:
```js
const outputOptions = {conditions: { 'ENV|mock': false, 'ENV|environment': 'dev' }};

import './config.#{ENV|environment}.js';
import './employee.mock.js#?ENV|mock';
```

then `./config.dev.js` is loaded correctly but it also load all `mock files` into bundle (**it should not load mock files as `ENV|mock` flag is set to `false`**). Keep in mind this behaviour only doesn't work for bundle use case when I am using systemJS in development the mock files are not loaded correctly if flag is set to `false` so this is only conditional problem with SFX bundle. 

**Enhancement:**

I am duplicating conditional logic in two places:

For development:
*env.conditions.js*
```js
export var mock = false;
export var environment = 'dev';
```

For bundle:
```js
const outputOptions = {sourceMaps: true, config: {sourceRoot: path.tmp.scripts}, conditions: { 'ENV|mock': false, 'ENV|environment': 'dev')} };
```

wouldn't be better for bundle use case if I could load conditions from `env.conditions.js` as this file is already included in `System.config({ map: { 'ENV': 'env.conditions.js' } })` or is this enhancement tracking with issue #311? Thanks

**Comment by guybedford** [comment]
@martinmicunda the conditions module will need to be the normalized path to ENV. This should be resolved. (`'path/to/ENV.js|mock': false`).

The condition passed into the build, is not a single condition evaluation - it represents conditional branches to build. A condition value can't be both true and false, while a conditional build object can provide both true and false branches to build.

**Comment by martinmicunda** [comment]
@guybedford sorry but I have problem to understand that. I been looking on your test cases but I can't find good example with boolean condition `false` value.

my conditions are defined in follow directory file:
*src/app/core/config/env.conditions.js*
```js
export var mock = false;
export var optimize = true;
export var environment = 'prod';
```

then I specify this ENV in *jspm.config.js* file
```js
map: {
  "ENV": "src/app/core/config/env.conditions.js",
```

then I pass conditions into build:
```js
const outputOptions = {conditions: { 'src/app/core/config/env.conditions.js|mock': false, 'ENV|environment': 'prod'} };
```

conditions in source code:
```js
import './config.#{ENV|environment}.js';
import './employee.mock.js#?ENV|mock';
```

I tried add normalized path (I am not sure if it's correct) **but the mock files are still included into bundle** what should I do if I want to pass `false` value so mock files won't be included into bundle?)

**Comment by guybedford** [comment]
@martinmicunda yes there were canonicalization issues, I've corrected this in https://github.com/systemjs/builder/commit/81483f24cdf589bd282b0a80cf0f627ab01309ca so that `'ENV|mock': false` should work now.

**Comment by martinmicunda** [comment]
@guybedford Could you make a release and push these changes to npm and I will test them? Thanks

**Comment by guybedford** [comment]
@martinmicunda I will likely only be posting a release next weekend at this point to be sure I've tested it thoroughly. In the mean time if you want to test it out you can try doing `cd node_modules/jspm && npm install systemjs/builder#master`? I think that is the right npm command at least.

**Comment by martinmicunda** [comment]
@guybedford I installed latest `systemjs/builder#master` and now I am getting follow error:

```bash
TypeError: No resolution found at all for condition employee-scheduling-ui/app/core/config/config.#{employee-scheduling-ui/app/core/config/env.conditions|environment}.
```

*builder*
```js
conditions: { 'ENV|mock': false, 'ENV|environment': 'prod'}
```

*env.conditions.js*:
```js
export var mock = false;
export var environment = 'prod';
```

*source code*
```js
import './config.#{ENV|environment}.js';
import './employee.mock.js#?ENV|mock';
```

**Comment by martinmicunda** [comment]
@guybedford I been debugging above issue and when I change `ENV` value to normalized path it fix the issue but I still can see that `mock` modules are imported into bundle even with your commit changes [`81483f2`](https://github.com/systemjs/builder/commit/81483f24cdf589bd282b0a80cf0f627ab01309ca).

```js
conditions: { 'src/app/core/config/env.conditions.js|mock': false, 'src/app/core/config/env.conditions.js|environment': 'prod'}
```

**Comment by guybedford** [comment]
@martinmicunda it sounds like this may not be linked in correctly, because otherwise the config normalization problem you have in https://github.com/systemjs/builder/issues/339#issuecomment-147522927 would have been resolved by the latest commit.

I'd suggest waiting for the release and trying again then.

**Comment by martinmicunda** [comment]
@guybedford I will try that.. I already wrote a blog post about [Conditional module loading with SystemJS](https://github.com/martinmicunda/martinmicunda.github.io/blob/master/_drafts/conditional-module-loading-with-systemjs.md) (I am just waiting till I get run builder condition and then I will publish it).

**Comment by lucianlature** [comment]
@martinmicunda @guybedford I suspect a bad normalisation of the condition, and this is based of the `trace` output. Let me explain, based on the above example, if you check the returned tree of the `trace` method of the `builder`, you'll see that for `employee.mock` entry it looks like:
```
'src/app/core/resources/employee/employee.mock.js#?src/app/core/config/env.conditions.js|mock.js'
```
So, those extra `.js` last characters at the end make the difference, therefore a quick **fix** is to add `'src/app/core/config/env.conditions.js|mock.js': false,` to the conditions object to eliminate the mocks form the prod build. A quick hack, I know, but at least it works as expected, in my case at least.

**Comment by martinmicunda** [comment]
@lucianlature yeah I can confirm when I add extra `.js` it will fix the problem.

```js
conditions: { 'src/app/core/config/env.conditions.js|mock.js': false, 'src/app/core/config/env.conditions.js|environment': 'prod'}
```  

It would be nice in the future if we would not need to use `src/app/core/config/env.conditions.js` path but instead `ENV` variable as this path is already specify in `jspm.config.js` so if I want to change the path I need to make changes in two places now.


**The below is separate error and not related to conditions:**
@guybedford I been testing my app with JSPM `v0.16.13` and SystemJS Builder `v0.14.8` and everything works fine however when I update SystemJS Builder to `v0.14.9` my bundle is broken and I can see lot of errors in my browser console like this:

```js
TypeError: Cannot read property '1' of null
    at update (http://localhost:8000/scripts/main-b899601eb0.min.js:16703:49)
    at link (http://localhost:8000/scripts/main-b899601eb0.min.js:16720:13)
```

the cause of this problem is that `uiSrefActive` is undefined

```js
return {
          restrict: 'A',
          require: ['?^uiSrefActive', '?^uiSrefActiveEq'],
          link: function(scope, element, attrs, uiSrefActive) {
                  var activeDirective = uiSrefActive[1] || uiSrefActive[0];
```


I been debugging this issue but can't find real casue of this problem but I believe it had to be introduced in SystemJS Builder `v0.14.9` as my development use latest `JSPM` that use latest SystemJS `v0.19.5` and I can't see these errors so I assume the issue is with builder `v0.14.9`

**Comment by guybedford** [comment]
@martinmicunda can you share a test repo for this at all?

**Comment by martinmicunda** [comment]
@guybedford here is the [repo](https://github.com/martinmicunda/employee-scheduling-ui)

I have updated repo with latest JSPM `v0.16.13` and SystemJS Builder `v0.14.8` this morning and everything works great included conditional imports. However when I update SystemJS builder to `v0.14.9` I can see above error. 

Steps to reproduce error:

```bash
git clone git@github.com:martinmicunda/employee-scheduling-ui.git 
cd employee-scheduling-ui 
```

Update SystemJS builder to `v0.14.9` in [package.json](https://github.com/martinmicunda/employee-scheduling-ui/blob/master/package.json#L61) and run follow commands:

```bash
npm install
npm start -- --env=TEST --optimize=true
```

npm start should automatically open your browser (open browser console and observe the error):

> **TIP:** you might disable uglify option for bundle in [gulp/tasks/build.js](https://github.com/martinmicunda/employee-scheduling-ui/blob/master/gulp%2Ftasks%2Fbuild.js#L152)

**Comment by guybedford** [comment]
@martinmicunda thanks I had a look at this and I suspect this may be due to https://github.com/systemjs/builder/issues/367.

**Comment by martinmicunda** [comment]
@guybedford ok.. I will keep eye on #367 and once it fixed I will run my tests...

**Comment by wprater** [comment]
@guybedford this was a fun thread.  helped my get my env setup, but Im having an issue with the current version.  keep getting an issue like `[TypeError: No resolution found at all for condition data/initial-states.#{ENV.production.js|environment}.js.]` when trying to `buildStatic`.  Also, it does not seem to take the config set in the `conditions` property and is looking for and ENV file.

**Comment by guybedford** [comment]
@wprater condition names need to match up carefully. Did you try specifying the condition name as exactly `"ENV.production.js|environment": "x"`?

**Comment by wprater** [comment]
@guybedford adding the `.js` did the trick, however, what if I wanted to instead use another file for ENV during my build instead of the `conditions` prop?  I still get the same error unless I pass the conditions prop.  Or is that a requirement?

also, where is the interpolation syntax for "`#MAPPING|propertyName`" defined?  I see a couple different uses in this thread.

**Comment by guybedford** [comment]
@wprater I would advise using a path configuration to set the ENV module:

```javascript
builder.config({
  paths: {
    'ENV': 'ENV.production.js'
  }
});
```

That way you can alter the environment module at any point, and also then you only need to refer to it as `"ENV|environment": "x"` in the conditional system.

I've created https://github.com/systemjs/builder/issues/426 to try and avoid these normalization issues though in general (and allow `map` to work properly here) as it sounds like a common catch so far.

The conditions object is a requirement for SFX builds, but isn't mandatory for normal bundles. This is because SFX builds need to exactly link to a single tree resolution.

The syntax itself is mostly undocumented until it is deemed stable. There are some notes in the code at https://github.com/systemjs/systemjs/blob/master/lib/conditionals.js.

**Comment by wprater** [comment]
@guybedford that's exactly what I had tried before, but there was still an issue.  Maybe it's a bug?

```
[Error: ENOENT: no such file or directory, open '/Users/wprater/Development/xxx-yyy/src/ENV.production.js']
```

**Comment by guybedford** [comment]
@wprater you still need to provide the `conditions` object with paths, the path just allows the object to read `conditions: { "ENV|environment": "x" }` instead of `conditions: { "ENV.production.js|environment": "x" }`. Paths config should definitely work to provide that name simplification though.

**Comment by wprater** [comment]
yeah, they were not working for me, which is why I wanted to post here again to make sure Im doing everything correctly.  It would be nice to have a ENV.development.js and an ENV.production.js and just override the path in the build process, but since I need to specify all the conditions again, there is no need for me to have these two fiels and alter the path at all.  So I've worked around this by having a separate config file, keeping the path and just changed the `environment` condition in the build process.
