### ISSUE TITLE
Not able to use functions provided by core-js with optional runtime babelOptions

### ISSUE THREAD

**Issue by prathamesh7pute** [systemjs/builder#346]
By using the following System.js configuration Builder

gulp task 
````
  var builder = new Builder('.', 'system.config.js');
  builder.buildStatic('main', output.js, {minify:true, sourceMaps:true});
````

system.js
````
System.config({
    baseUrl: './',
    defaultJSExtensions: true,
    transpiler: 'babel',
    babelOptions: {
        optional: [
            'runtime'
        ]
    },
    map: {
        ...
   }
});
````

If code is using any core-js aliasing like Map, Set, Symbol etc its not getting bundled, transpiled
script.js (for e.g)
 
````
    var sym = Symbol();
    var promise = new Promise();
````

issue seems to be with the system.js builder not passing proper path for babel to find core-js
as when in bundle step traspiler babel tries to find the core-js it is referring to wrong path of core-js/library 
(it tries to find the core-js in the baseURL path pass to new Builder('.', 'system.config.js' )

But if same script run through babel it works -
$ babel --optional runtime script.js

**Comment by guybedford** [comment]
You need to ensure you have a map configuration for `core-js` present in your SystemJS configuration in order for SystemJS to be able to find `core-js`.

**Comment by prathamesh7pute** [comment]
As suggested I tried to provide the path of core-js, by adding core-js in project and mapping. It works.

But I do have a babel-core install as a dependency, and I believe it internally references to the core-js (as it is depend on it) 

This seems to be issue if I try to transpile with systemjs builder only as babel-core is not using core-js which it has, Instead it tried to find core-js in the baseURL path provided to Builder.

Note: - I am not using the jspm, only system.js with builder builder.

**Comment by guybedford** [comment]
Yes that is correct - npm dependencies need to be configured manually through SystemJS.
