### ISSUE TITLE
perf(bundling): watchify like bundling approach

### ISSUE THREAD

**Issue by douglasduteil** [systemjs/builder#347]
Hi @guybedford 

Currently I'm using the builder a lot and I would like to work on a [watchify](https://github.com/substack/watchify) approach of it. 

The goal is to speed up the bundling time by caching the already built files

**Comment by guybedford** [comment]
@douglasduteil have you seen the project at https://github.com/jackfranklin/jspm-dev-builder? There is definitely scope for projects to wrap SystemJS builder with this functionality. I'm currently liking the idea of having third-party projects provide this, then over time we can gradually iterate features back here and possibly even bring these features into builder core in due course.

**Comment by douglasduteil** [comment]
Cool. Thanks
