### ISSUE TITLE
Document how to include bundles

### ISSUE THREAD

**Issue by jack4it** [systemjs/builder#348]
Hi Folks -

My scenario is very basic. I'm trying to make a regular bundle (starting from app.js, ending up with sth called app-bundle.js). And I successfully made it, which was so straightforward. Then I'm trying to use this bundle on a page. I simply put it on the page using < script src="app-bundle.js" >< /script >, nothing else changed, I mean, system.js and config.js are still on the page like they are before the bundle.

What I expected is that the System.import("app") will just work, I mean, it should load the dependencies from the already loaded app-bundle.js. But in my case, it continues loading everything directly from the original location and totally ignores the app-bundle.js.

I feel I'm missing something, but I can't find a complete/working sample on this site and the web. Can you guys help me out?

I can provide any further information needed.

Thanks,
-Jack

**Comment by jack4it** [comment]
Ah, got it working by using the following. This really should at least mentioned in the example...
            System.config({
                bundles: {
                    "app-bundle": ["app"]
                }
            });

**Comment by guybedford** [comment]
Thanks, marking as a documentation issue.

**Comment by guybedford** [comment]
Tracking in https://github.com/systemjs/builder/issues/250.
