### ISSUE TITLE
Tracuer non-ES features broken

### ISSUE THREAD

**Issue by nyarly** [systemjs/builder#349]
I'm finding that code that uses types or annotations produce buggy code.

Something like:
```
@MyAnno()
export default class MyClass extends SuperClass {}
```

becomes something like:
```
execute: function() {
  $__export('default', function($__super) {
    function MyClass(){ ... }
    return ($traceurRuntime.createClass)(MyClass, { ... })
  }(SuperClass);
  Object.defineProperty(MyClass, "annotations", {get: ... })
```

which raises a ReferenceError early in code loading.

If the constructor function were outside the $__export or the defineProperty were inside, obviously this would work (which I've tested by manually making the change.)

I also suspect that if I could change the es6 code to be more like
```
@MyAnno()
class MyClass extends SuperClass {}
export default MyClass
```
the scope issues would go away, based on how analogous code seems to have been built. Not all of this code is under my control, and I'm loathe to issue PRs to workaround what appears to be a bug in the build I'm setting up.

I'm at a loss about how to proceed. I can confirm that the same code builds under just traceur with similar configuration.

**Comment by guybedford** [comment]
Have you tried using Babel instead here?

**Comment by nyarly** [comment]
Switching in babel (after I figured out how: documenting transpiler: "babel" + babel-core would be helpful, incidentally) produces a slower but working build.

On this middling codebase, Babel takes 12s, and Traceur <2s (to produce broken ES5)

**Comment by guybedford** [comment]
Thanks for sharing the stats - yes Traceur is faster than Babel. There are some projects aiming to improve the developer experience and avoid repeated in-browser transpilations. These workflows would provide the way forward here.
