### ISSUE TITLE
Hardcoded ascii-only minification

### ISSUE THREAD

**Issue by enlait** [systemjs/builder#350]
Uglify.js is hardcoded to use ascii_only output mode, which leads to output bloat in cases where unicode is used extensively.

Relevant code line is commented with
```// for some reason non-ascii broke esprima.... this does break unicode though```

Can we get an option to have out unicode intact?

**Comment by guybedford** [comment]
Thanks, I've removed this in https://github.com/systemjs/builder/commit/68cef2e1fe6cccc4efe8e6ecfde8ab857b2b75b5.
