### ISSUE TITLE
Does builder need to handle transpilation?

### ISSUE THREAD

**Issue by nyarly** [systemjs/builder#357]
Is it possible to separately transpile files, and then have builder assemble the results, or does builder need to manage the transformation from ES6 for some reason?

**Comment by guybedford** [comment]
@nyarly I see you're already thinking in the right directions. Yes precompilation workflows can work, where SystemJS just treats the module format as `register`. This can be done via running Babel manually on the separate files.

**Comment by guybedford** [comment]
This feature for jspm is tracking in https://github.com/jspm/jspm-cli/issues/1107.
