### ISSUE TITLE
Name build results by input hashes

### ISSUE THREAD

**Issue by wmertens** [systemjs/builder#358]
Taking a great idea from http://nixos.org, it would be great if builder would identify build products by a hash that includes all their inputs. Then you would only need to minify/transpile/optimize/... a requirement once for every combination of source files and plugins.

For this to work, the build process needs to be deterministic, meaning that given a certain set of plugin versions and source contents, you will always get the same output, or at the very least one of a set of equivalent outputs. (For modules/plugins that don't meet this requirement, simply include the timestamp as an input, they will be rebuilt every time)

To calculate the hash, you need to sort and concatenate (e.g.) the md5 sum of all plugins and source files, all compilation options (paths and settings), all input hashes of imported modules, and all builder module versions (e.g. babel v1.1.2), and create an md5 sum from that string. This will give you a unique input hash representing the entire input that will result in the build product. Then, to build, you check if the build product with that input hash already exists, and if so, simply re-use it.

NixOS manages to build an entire linux distribution this way in tens of seconds (provided everything has already been built), so it should make builder very fast in the common case that only a small subset of things change. These files are also infinitely cacheable, since they will never change.

**Comment by wmertens** [comment]
I just noticed https://github.com/systemjs/builder/blob/master/lib/compile.js#L25 so maybe you're already doing this :)

**Comment by guybedford** [comment]
Yes we already provide a build cache, it's just not documented while the API stabilizes.
