### ISSUE TITLE
Canonicalization in utils.js does not work for non-js Files

### ISSUE THREAD

**Issue by stefanocke** [systemjs/builder#359]
Hi,

system-js-builder version: "0.14.8"
system-js version: 0.19.4

I was able to successfully import an html-Template with System.js using the the new package-style configuration an the text plugin. The config looks like this:

```javascript
  defaultJSExtensions: true,
  paths: {
    "*": "build/js*",
    "github:*": "jspm_packages/github/*"
  },

  packages: {
    "app": {
      "defaultExtension": "js",
      "modules": {
        "*.html": {
          "loader": "text"
        }
      }
    }
  },
 map: {
    "angular": "github:angular/bower-angular@1.4.7", ...
```

As you see, I still need defaultJSExtensions for angular and other 3rd party libs.
However, thanks to the defaultExtension in the "app" Package, the suffix "js" is only appended, if there is no other suffix. So, the  System.import(app/foo.html) works.

However, when I try to bundle the app with SystemJS-Builder, there is an error regarding the html-import saying that the following File does not exist:

build/js/build/js/app/app/foo.html.js

So there are two strange effects here: The "build/js" appears twice and the suffix ".js" is appended.

I am not sure if this issue is something that will be fixed with the release of jspm 0.17 anyway, since the bug is in system-js-builder which is already using the latest version of system.js.

I did some debugging an got the following:

In util.js the path is canonicalized. For this, the fuction "normalizePath" is called.  There we have:

```javascript
if (loader.defaultJSExtensions && !isPlugin && curPath.substr(curPath.length - 3, 3) != '.js')
    curPath += '.js'
```

So, in my case , there was always ".js" appended to the path, which then never matched for any non-js resources. So,  the module name for foo.html was not canocialized correctly.  The result was "build/js/app/foo.html" instead of "app/foo.html". So, system.js tried to load it from file  build/js/build/js/app/app/foo.html.js.

(It seems, I could avoid that by having isPlugin=true  but this paramter seems not to be set anywhere)

Best regards,
Stefan.

P.S.:  I tried to append "!"  to the module name. This seems to set the parameter "isPlugin" to true. But the canolicalization seems to be called multiple times and sometimes the parameter is true and sometimes not. So even with "!", the same error occured.

**Comment by stefanocke** [comment]
P.S.: The same issue occurs for *.ts instead of *.html, even when the default extension for the package is set to ".ts".

**Comment by guybedford** [comment]
@stefanocke your analysis here is completely correct - this is an edge case of the normalization in builds as we can't handle plugin assumptions without knowing the metadata, which is not part of that stage in the pipeline. This is something that will naturally resolve when `defaultJSExtensions: false` lands in jspm 0.17.

I'd suggest using the `!` in the module name and then waiting on jspm 0.17 for the full use case. This case does normalize and build correctly for me.

**Comment by stefanocke** [comment]
I tried again with "!" and got it running.  Thanks a lot.
