### ISSUE TITLE
bundle library - help

### ISSUE THREAD

**Issue by stephenlautier** [systemjs/builder#361]
Hi,

I'm trying to build a library and publish it as a package using AMD (not too necessary being AMD), which then I can install into another project using JSPM/SystemJS.

What I'd like to have when I distribute it is simply 3 files:
- my-lib.js **(consists of multiple source files combined excluding external modules)**
- my-lib.js.map
- my-lib.d.ts

My issue is when it comes to bundling/combine them into a single file, tried several which "works", however when I install into another project they won't work correctly.

I've tried the following:
- jspm.bundle
- builder.buildStatic (via new jspm.Build())
- builder.bundle

Am I able to achieve this with the builder? If so which should I use?

To give a bit more context, I'm trying to build a library for AngularJS (1.x) (several actually), which are dependant on AngularJS along others, and I don't want dependencies to be included within the bundle itself.

The following is what I'm doing and the outcomes.

### Using JSPM Bundle ###
Attempt using JSPM bundle

- Excluding external dependencies (tried also with the `app - angular` which also works)
```
  meta: {
    "angular": {
      build: false
    }
  },
```
- Building using JSPM API
```
return jspm.bundle(`ssv-angular-core`,
	`dist/ssv-angular-core.js`, {
		mangle: false,
		inject: false,
		sourceMaps: true
	});
```
it outputs okish, dependencies are omitted 
- installing via jspm within a sample project using:

`jspm install ssv-angular-core=github:stephenlautier/ssv-angular-core`
all files within `dist` are downloaded correctly

- running the sample project
after running the sample project, the injected module results as empty

![2015-10-20 00_35_42-angular tooltipster](https://cloud.githubusercontent.com/assets/3908723/10593289/a29b498a-76c2-11e5-85b7-8b507a329496.png)

### Using buildStatic ###
The following is very similar to the above, with different build and different error when importing.

- Build
```
	var builder = new jspm.Builder();
	return builder.buildStatic(
		`ssv-angular-core`,
		`dist/ssv-angular-core.js`, {
			format: "amd",
			sourceMaps: true, 
			lowResSourceMaps: true,
			// minify: true, 
			// mangle: true,
			runtime: false // doesn't seems to change anything
		})
```
- After installing and running I get the following error:

`Uncaught (in promise) Module 7 not present.`
I've seen the file which generates and the reason seems to be because I'm excluding the external module e.g. angular, this is part which I believe is causing an error
```
define("6", ["require", "exports", "7", "4", "5"], function(require, exports, angular, logger_1, core_consts_1) {
...
```

If you'd like to see the repo itself, its open source https://github.com/stephenlautier/ssv-angular-core
to run:
`npm install`
`gulp build:rel`

Any help would be highly appreciated, thanks.

**Comment by guybedford** [comment]
If you want a single-file build, I'd suggest using the `buildStatic` here to AMD, with subtraction - `(new jspm.Builder()).buildStatic('ssv-angular-core - angular - other-deps', { format: 'amd', sourceMaps: true })`.

If you want to build files separately, you can call `builder.compile` against each file as a separate file to the `System.register` format so no transpilation etc is necessary on install.

Improving these publishing workflows is very much a priority, we're just not there yet on the ideal easy two-step process here.

Just let me know if you have any further questions at all.

**Comment by stephenlautier** [comment]
Thanks for the reply. That's very similar to what I was doing, I will give it a little more try, hopefully I can get this working :+1:.

Thanks again.
