### ISSUE TITLE
Ascii uglify flag

### ISSUE THREAD

**Issue by lookfirst** [systemjs/builder#363]
This is angular.js source that is being minified with the builder and it is getting corrupted by the builder.

http://take.ms/y8MGr

latest builder/jspm/systemjs

**Comment by lookfirst** [comment]
https://github.com/systemjs/builder/commit/68cef2e1fe6cccc4efe8e6ecfde8ab857b2b75b5

???

**Comment by lookfirst** [comment]
@guybedford seriously, please write some tests around this stuff.

**Comment by lookfirst** [comment]
reverting to    "jspm": "0.16.12" fixes the issue

**Comment by guybedford** [comment]
@lookfirst this is actually server-specific stuff. Try adding a `<meta charset="utf-8">` tag to the main page and see if that helps?

**Comment by lookfirst** [comment]
This has nothing to do with the server. The JS file that is served up is corrupted. I already have that header in my page. As I said, reverting to the previous version of jspm fixed this issue.

**Comment by lookfirst** [comment]
Also, look at what I'm showing you... it is two JS files. One is the angularjs source code viewed on Github directly and the other is in developer tools. How can a meta header fix that?!?

**Comment by enlait** [comment]
@lookfirst @guybedford There is nothing wrong with the builder output. This is an obvious encoding issue: utf8-encoded file is opened as ASCII (seems like win 1252). You can confirm it in any text editor at hand.

I vote for making ascii-only mode configurable through builder.

**Comment by lookfirst** [comment]
@enlait I think you're pretty off there with your analysis... =(

**Comment by guybedford** [comment]
@lookfirst here's my test:

```
  jspm install angular
  jspm bundle angular -mi
```

Loading that in a test page works completely fine for me. It's definitely an encoding issue, but I think the problem you are having is at the network not the filesystem level?

**Comment by enlait** [comment]
@guybedford
can't blame @lookfirst, encodings are quite a quagmire and escaping unicode helps with compatibility. There are pros and cons for either way, in case of sparsely used special characters (which I understand is the case with angular) escaping is justified.

BTW isn't `content-type`-specified encoding more important then `meta`?

**Comment by lookfirst** [comment]
bundler.buildStatic() with minification on?

**Comment by guybedford** [comment]
@lookfirst if you open the file on the filesystem are the characters encoded correctly there? I added a simple test in https://github.com/systemjs/builder/commit/490fe612a2551158f16efa381e509199578873d9 and it's definitely working. I'd advise checking your server is setup to load and serve utf-8 correctly?

**Comment by lookfirst** [comment]
@guybedford This is a bug. My 'server' is fine. I'm using Google AppEngine. Like I said before, this works fine in the previous version of jspm, it only breaks after you made that utf change.

**Comment by lookfirst** [comment]
Your test is not accurate, you need to use the same characters as what I showed you in the angularjs source code. I also want to see this as part of the output of bundler.buildStatic() and with minification turned on.

**Comment by guybedford** [comment]
Sure, see https://github.com/systemjs/builder/commit/18a2913f089aa3c96816b97714a7bc03e7df6c8e, this is a test with both sfx and minification of the exact characters.

@lookfirst I appreciate your reports, but I hope you can work on your tone in these issue queues.

**Comment by lookfirst** [comment]
I'm starting to debug this further. It only happens when I turn minification on.

**Comment by lookfirst** [comment]
builder installs uglify-js 2.4.24

**Comment by lookfirst** [comment]
echo "if (isInfinity) formatedText = '\u221e';" > test.js
uglifyjs test.js
if(isInfinity)formatedText="∞";
uglifyjs test.js > out.js
more out.js
if(isInfinity)formatedText="∞";

So basically, uglify is encoding things.

**Comment by lookfirst** [comment]
uglifyjs -b ascii_only=false test.js
if (isInfinity) formatedText = "∞";
uglifyjs -b ascii_only=true test.js
if (isInfinity) formatedText = "\u221e";

**Comment by lookfirst** [comment]
Let's not have uglify mess with the source code. =)

**Comment by lookfirst** [comment]
Ok... so as a test, I made sure to send 'Content-Type: application/javascript;charset=utf-8' with the response. Never mind that I shouldn't have to do that. 

What this does is make the browser handle the javascript ok... or at least it does for Chrome and Safari, Firefox on the other hand totally screws this up.

On the left is chrome, on the right is firefox (loading the same exact file): http://take.ms/pkbFi

I really recommend telling uglifyjs to not rewrite the unicode. Keep it as ascii.

**Comment by guybedford** [comment]
I'd be happy to add a flag for this option certainly.

**Comment by lookfirst** [comment]
@guybedford Sweet, I can't upgrade to latest jspm until this happens. =( 

Seems weird that your tests are passing. The input clearly isn't the same as the output here.

I'm also really surprised that I'm the only one having this issue. It really turns up if you use angular with `$format('currency')`. Maybe someone will search and find this issue.

**Comment by guybedford** [comment]
Added in https://github.com/systemjs/builder/commit/b1c09a5c9aad659301abab27018ab6b17c5f2808.

**Comment by lookfirst** [comment]
:+1: thanks @guybedford

**Comment by guybedford** [comment]
Released in 0.14.10.

**Comment by lookfirst** [comment]
:+1: works
