### ISSUE TITLE
Paths don't resolve on Windows.

### ISSUE THREAD

**Issue by dzearing** [systemjs/builder#364]
I have an entrypoint like "lib/foo/bar". I'm using a fully qualified path using something like fs.resolve(rootDir, entry), which resolves to C:\git\project\lib\foo\bar.js

When I call builder.bundle, I get:
```
Error: Unable to calculate canonical name to bundle C://\git\project\lib\foo\bar\index.js
```
If I do not use a fully qualified path and instead only relative, such as 'foo/bar/index.js', then things work.

Inside arithmetic.js, there is this code in expandGlobAndCanonicalize:
```javascript
return loader.normalize(operation.moduleName)
    .then(function(normalized) {
```
When operation.moduleName is:
```bash
C:\git\project\foo\bar\index.js
```
The resulting "normalized" value is:
```bash
C://\git\project\foo\bar\index.js
```
This is not correct. If i don't use fully qualified paths:

operation.moduleName:
```bash
lib/foo/bar/index.js
```
resulting normalized:
```bash
file:///lib/foo/bar/index.js
```
And this seems to build ok on Windows.

Using fully qualified paths works just fine on Mac, but Windows users are totally broken by this.

**Comment by guybedford** [comment]
@dzearing the input into bundling is a module name not a file path. Absolute module names in Node are `file:///` URLs. So if you want to bundle an absolute path, use `bundle('/absolute/path/to/file.js')` or `bundle('file:///absolute/path/to/file.js')`. Converting from a file path into a file URL is necessary as part of the input creation process.

**Comment by dzearing** [comment]
Ah ok, that makes sense. That wasn't obvious in the samples. In order for that to work, we will need to use something like https://github.com/sindresorhus/file-url to preprocess the paths coming out of fs.resolve. May want to suggest that in the docs.

(or alternatively just use the plugin in the builder)

Thanks for the explanation!
