### ISSUE TITLE
InMemory Build with css plugin and 'separateCSS'

### ISSUE THREAD

**Issue by davinkevin** [systemjs/builder#365]
Hi, 

I am very fan of the feature allowing me to access the build result directly from memory. But if I use a plugin like 'css' and define the behavior to 'separateCss : true', the option.source doesn't contains the css part, only the JS parts.

To have the better user experience in production, we have to separate the CSS and JS file (CSS loads first to do the rendering) and JS load last... If we load the CSS with the JS at the begging or end, we will have a blank page for few milliseconds or a page without style during milliseconds (and trigger a new rendering by the way...).

Is it possible to improve the behavior of the In-Memory build to let us work with different files (CSS files in this case) in task manager (like gulp) without using the file system ?

Thanks

**Comment by guybedford** [comment]
@davinkevin there is a new builder feature called `output.assetList`. The CSS plugin will provide the list of CSS files used here. You can disable the CSS builds via `options.inlinePlugins: false` in builder and then use this feature to manage your own CSS pipeline in-memory.

**Comment by davinkevin** [comment]
Good to know. 

I think it should be added to the main documentation (I answer here because I don't have time to do a PR for that... sorry).

I think it closed the issue, Thanks a lot !
