### ISSUE TITLE
Don't remove AMD defines in bundle

### ISSUE THREAD

**Issue by arackaf** [systemjs/builder#366]
This may be related to case https://github.com/systemjs/builder/issues/264

but when creating a bundle from AMD modules, it seems the define for each helper is removed inside of the bundle file, presumably through the call to 

```javascript
var _removeDefine = System.get("@@amd-helpers").createDefine();
```

and

```javascript
_removeDefine();
```

So that a `require` for one of the helpers in the bundle elsewhere in the code loads that helper fresh, even though it's contained within a bundle that's already been loaded.

Is it possible to turn this off somehow?  It looks like the call is hard coded from the peak I took in the code.  Is there some other workaround though to obviate this behavior?  Ie replace that amd-helper with a noop somehow? 

SystemJS looks tremendous either way - thanks for your hard work!

**Comment by guybedford** [comment]
If you want to keep the `window.define` around then try setting `window.define = System.amdDefine`. The idea is that you should choose to set the global rather than it being imposed.

Glad to hear you like it! Just let me know if you have any further questions at all.

**Comment by arackaf** [comment]
Hmmm - thanks for the reply - I think this entire case may have been wrong.  My original bundle was never really loading - per case #863 on your main SystemJS repo.  Once I can get my built bundle to load I'll give this another try de novo :)

**Comment by guybedford** [comment]
Sure, closing for now, but do update here when you can.

**Comment by arackaf** [comment]
Oh, no, after getting my module to load correctly this works as expected.  Loading a piece of an already-loaded bundle does correctly load nothing new.  So this is absolutely good to go.  Thanks!
