### ISSUE TITLE
Builder requires modules that shouldn't be required

### ISSUE THREAD

**Issue by OrKoN** [systemjs/builder#368]
For example, if a module contains such code:

```
   try {
        /* NPM module name */
        validator = require('validator');
    }
    catch (e) {
        /* Bower module name */
        validator = require('validator-js');
    }
```

The builder will try to require both packages although only the first one should be required. Is it a bug or just a limitation of the builder? Does it parse the file to what needs to be required at the build time?

**Comment by guybedford** [comment]
This is the way SystemJS bundling works - we trace all CommonJS requires statically.

To remove a require you can use map config to set it to `@empty`, either in the System config or via an override.

**Comment by OrKoN** [comment]
Do you have some notes/docs somewhere on why it works like this? I have already fixed it in my project using `@empty` but I wonder why it's needed? Is it to prevent errors if smth is required but not declared as a dependency?

**Comment by guybedford** [comment]
@OrKoN this is the way that static tracing of CommonJS works, which is the tracing that SystemJS uses, just like Browserify does. There are certainly limitations to it, and that was a strong argument for ES modules themselves to enable static analysis.

**Comment by OrKoN** [comment]
In case anyone else has a similar problem - the override should work like this:

```
     "npm:tv4-formats@1.0.2": {
        "map": {
          "validator-js": "@empty"
        }
      },
```

where `npm:tv4-formats@1.0.2` is the full name of the problematic module.
