### ISSUE TITLE
jspm bundle fails to convert ES6 if no imports are found.

### ISSUE THREAD

**Issue by richburdon** [systemjs/builder#369]
I have some strange edge cases when building bundles.

The minimal repro is:

    jspm bundle-sfx --minify test.js

[test.js]
    'use strict';
    import './test2.js';  // This can be an empty file.
    let x = 100;
    console.log(x);

The above works. But if you comment out the (completely redundant import statement), then there is the following error:

    err  Error: Unexpected token: name (x) (line: 573, col: 8, pos: 16033)

Since "let" is not converted to "var" and minify does not understand "let".

**Comment by guybedford** [comment]
This is how module format interpretation works in SystemJS. Only the existence of `import` or `export` syntax gives the ES module treatment. There will be a separation of module format and transpilation in jspm 0.17 to address this further.
