### ISSUE TITLE
Config not included in bundle but included in sfx-bundle

### ISSUE THREAD

**Issue by CxRes** [systemjs/builder#376]
At the very least this is a documentation request, I realized that SystemJS was throwing errors I tried to import bundle because they could not locate paths correctly. This was not a problem with sfx-bundles I used earlier.

I would have thought that config belongs to a bundle because they carry within the map associations used for imports that are within the bundle???

**Comment by guybedford** [comment]
Yes config needs to be included with the bundle. Config builds are in progress for 0.17. Documentation will be a priority once 0.17 lands.

**Comment by CxRes** [comment]
OK, Good to know. Thanks!
