### ISSUE TITLE
Built module throws error when loaded in Chrome devtools extension.

### ISSUE THREAD

**Issue by richburdon** [systemjs/builder#380]
I have an edge case where I'm building a devtool chrome extension using the module builder to create an SFX module.

At runtime, chrome throws the following error:

    Uncaught SecurityError: Failed to read the 'frame' property from 'Window': Blocked a frame with origin "chrome-extension://ienpdnnbhalgcppicgnjfnbggacimkmb" from accessing a frame with origin "chrome-devtools://devtools".  The frame requesting access has a protocol of "chrome-extension", the frame being accessed has a protocol of "chrome-devtools". Protocols must match.

Which refers to this line in the bundle:

    function linkDynamicModule(entry) {
    ...
        if (d = Object.getOwnPropertyDescriptor(exports, p))

This only seems to happen when importing modules defined as "packages" in the config.js

I'm still working on getting a minimal repro, but why is linkDynamicModule being called in an SFX?

**Comment by guybedford** [comment]
This sounds like https://github.com/systemjs/builder/issues/338?

**Comment by guybedford** [comment]
If this was #338, it should be fixed in the latest release - let me know if that solves it for you.

**Comment by richburdon** [comment]
Fantastic. Yeah that works (in 0.19.5).
