### ISSUE TITLE
Minification of resources

### ISSUE THREAD

**Issue by alexkolt** [systemjs/builder#381]
Guy, thanks and great job.

Is there a plan to add minification for included resources(html, json, etc.)? These are imported and passed through text plugin.

```sh
import template from './template.html!text';
```

That works great for development, but for production build I would like to minify templates.

**Comment by guybedford** [comment]
Template minification is supported in principle, but would need to be handled by the plugin itself. So template plugins could implement their own minification if they check `outputOptions.minify` flag passed into the `bundle` function. See the CSS plugin for example - https://github.com/systemjs/plugin-css/blob/master/css-builder.js#L56.

If you're interested on working on a plugin here, just let me know how I can help.
