### ISSUE TITLE
Builder generates empty sourcemaps for typescript project

### ISSUE THREAD

**Issue by bnolan** [systemjs/builder#389]
I've got a really radical reproduction repository right here:

https://github.com/bnolan/systemjs-coverage

If you run *gulp* - it outputs the sourcemap:

```
  sourceMap: '{"version":3,"sources":[],"names":[],"mappings":"","file":"undefined"}',
```

Not sure what I'm doing wrong / what's wrong with system?

**Comment by guybedford** [comment]
Apologies for the delayed response, I missed this one.

Just to follow up - the advised workflow here is to use https://github.com/frankwallis/plugin-typescript instead of the internal typescript support.
