### ISSUE TITLE
Determine which modules are in a bundle

### ISSUE THREAD

**Issue by arackaf** [systemjs/builder#390]
Hi.  I've had success beyond what I had hoped for switching over to SystemJS-builder from r.js.  I'm hoping you can just help me over what seems to be the final hurdle.  

If I've created a bundle, how do I programmatically determine which modules are IN the bundle.  In other words, all of the dependencies of the module from which the bundle was made, *EXCLUDING* any modules that were excluded.

The object that's returned from `builder.bundle` does seem to contain a deep list of all dependencies, but it includes things which were left out of the bundle.  Ditto with the `builder.tracer.loads` object.

Is there a way to do this natively, or will I have to just run a check on each dependency over my list of exclusions—which should be straightforward, I just imagine there has to be a native way which I'm missing.

Thank you!

**Comment by arackaf** [comment]
Err - actually it looks like the Promise's resolve object and `builder.tracer.loads` both appear to provide shallow dependencies only, and not dependencies of dependencies, so the search would have to be recursive.

In any event, hoping this is built in somehow.

**Comment by arackaf** [comment]
Sigh, in the various things I was trying I failed to see that result.modules is exactly what I needed.  I knew it had to be there somewhere.  Apologies if that's documented somewhere that I missed.

**Comment by guybedford** [comment]
I've marked this as a documentation issue - SystemJS Builder API has been somewhat in flux, and I've been hesitant to document all features until they are stable. As soon as jspm 0.17 lands, comprehensive documentation here will be a major priority.

**Comment by arackaf** [comment]
Sounds great.  So what's your timeline looking like for jspm 0.17?

Also, is the method I settled on—using the modules property on the bundle result—stable for the future?  Ie, will that be changing in the post-jspm 0.17 world?

**Comment by guybedford** [comment]
Yes, the `output.modules` is set to stay. We're currently aiming for an alpha mid December.

**Comment by arackaf** [comment]
Sweet.

Your SystemJS builder has been like mana from heaven for us.  r.js was taking a few minutes for a full build - and that's with me twisting and doing awful things to squeeze better performance out.  Yours takes seconds for the same tasks out of the box.

Thanks SO much for the great work on this.
