### ISSUE TITLE
Log error in compileTree

### ISSUE THREAD

**Issue by LongYC** [systemjs/builder#391]
There is a long chain of Promise in `compileTree` dealing with modules and plugins which also means there is a high chance of things could go wrong here but there is no log or any other information available  when it happens. I would rather have something like:

```
Building the single-file sfx bundle for jsx/main.js...
[ 'jsx/main.js:5:3: Unexpected token <',
  'jsx/main.js:5:4: Unexpected token div',
  'jsx/main.js:5:8: Semi-colon expected',
  'jsx/main.js:5:34: Unexpected token >',
  'jsx/main.js:7:1: Unexpected token )' ]
```

then nothing at all. I propose add a `catch` to Promise chain and log the error.

**Comment by guybedford** [comment]
If

**Comment by guybedford** [comment]
It looks like you are getting errors swallowed somehow in jspm?

If that is the case it may be a jspm bug not propagating error messages, although this should be handled by the rejection handler in https://github.com/jspm/jspm-cli/blob/master/lib/bundle.js#L177.

**Comment by LongYC** [comment]
Sorry for the silly PR. Yeah, it seems to happen when I try to bundle JSX with `require` instead of ES2015 `import` and somehow the error does not get propagated, it got lost somewhere in jspm's `ui.log`.
