### ISSUE TITLE
Basic bundling issue (a.k.a - I don't think I'm fully understanding this)

### ISSUE THREAD

**Issue by mcavanagh** [systemjs/builder#395]
Apologies if I'm being really stupid, but I'm trying to get a basic 1-file bundle working, and having all kinds of pain.

### File structure

```
/Ts
    /main.ts
    /SgfParser.ts
    /StringReader.ts
```

main.ts imports angular2 and my own class, _SgfParser_

I'm compiling these typescript files into individual .js files in the same directory, with the following **tsconfig.json**:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "noEmitOnError": true
  }
}
```

The first line of the compiled .js is as follows:

**main.js**
```
System.register(["angular2/angular2", "SgfParser"], function(exports_1) {
...
```

In my **gulpfile.js**, I'm then using systemjs-builder as per the sample code to try and create a one-file bundle:

```javascript
gulp.task('bundle', function() {
    var builder = new Builder(".");

    builder.config({
        meta: { 'angular2/angular2': { build: false } }
    });

    builder
        .bundle('main', '../wwwroot/js/app.js')
        .then(function() {
            console.log('Build complete');
        })
        .catch(function(err) {
            console.log('Build error');
            console.log(err);
        });
});
```

Running this task results in 
```
[Error: ENOENT, open 'D:\Code\Visual Studio Projects\SgfClient\src\SgfClient\Ts\main']
```

This is the correct path, except for the missing '.js' on the end. Is there some config setting in systemjs-builder where you tell it to assume a file extension of '.js' (like when you use System.config in the browser), or is that not the issue?  If I change this line:

```
.bundle('main', '../wwwroot/js/app.js')
```

to 

```
.bundle('main.js', '../wwwroot/js/app.js')
```
 it finds the main.js file, but then proceeds to throw a similar error trying to find 'SgfParser' (this is what makes me assume it's a file path issue rather than a module name issue.  I've had a lot of confusion determining where systemjs is referring to paths vs names).  However, I also suspect that this isn't the fix, because I read another issue where you said that the first argument to bundle() is a module name, not a path.

At this point I'm fairly lost.  Any pointers welcome.

**Comment by fictitious** [comment]
The first argument to bundle() is indeed a module name, but given that there are no mappings of any kind in your builder.config({...}) argument, module name is the same as file name.

The first thing to try is to set System.defaultJSExtensions = true in the gulp task and see if it helps - see also similar issue that was discussed not long ago: https://groups.google.com/d/msg/systemjs/ynYFi_zRIno/FScX2A80AwAJ

**Comment by mcavanagh** [comment]
> The first thing to try is to set System.defaultJSExtensions = true

I thought this was only relevant when including files in the browser.  I'm having trouble at the bundling stage.

**Comment by fictitious** [comment]
Nothing in the documentation says it's only relevant in the browser. In fact, there is code in the builder which is called in the process of translating module name to file name and it uses that setting - see https://github.com/systemjs/builder/blob/master/lib/utils.js#L222

In general, as far as I know, builder uses the same configuration and the same logic for locating files as the loader in the browser - the only difference is that absolute URLs have file: protocol instead of http:

**Comment by fictitious** [comment]
Sorry I did not realize that assignment to System.defaultJSExtensions does not work, unless it's contained in the configuration file loaded with builder.loadConfig().

You need to set it for the loader in gulp file like this

        builder.loader.defaultJSExtensions = true;

Sorry for misleading comment.

**Comment by mcavanagh** [comment]
Thanks, I'll give that a try.

**Comment by mcavanagh** [comment]
Success!

The System.register calls now look like this:

```System.register("main.js", ["angular2/angular2.js", "SgfParser.js"], function(exports_1) {```

Is there any way of removing the '.js' from the module names?

**Comment by mcavanagh** [comment]
Ok, maybe 'Success!' was a bit premature.

In the browser, I'm telling System.import to load the built single-file module, and I can tell that it's loading the file (from Chrome's network view), but it never actually executes the code in the 'execute' block.

This is my .ts file
```typescript
import {Component, bootstrap} from "angular2/angular2";
import {SgfParser} from "SgfParser";

console.log("in main");

@Component({
    selector: "my-app",
    template: "<h1>asdfasdf</h1>"
})
class AppComponent {
    constructor() {
        console.log("in AppComponent constructor");

        var parser = new SgfParser();
        parser.parse("f(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3])");
    }
}

bootstrap(AppComponent);
```

This is the equivalent section of the built file:

```javascript
System.register("main.js", ["angular2/angular2.js", "SgfParser.js"], function(exports_1) {

/* snip all the Reflect/decorator/etc stuff */

  var angular2_1,
      SgfParser_1;
  var AppComponent;
  return {
    setters: [function(angular2_1_1) {
      angular2_1 = angular2_1_1;
    }, function(SgfParser_1_1) {
      SgfParser_1 = SgfParser_1_1;
    }],
    execute: function() {
      console.log("in main");
      AppComponent = (function() {
        function AppComponent() {
          console.log("in AppComponent constructor");
          var parser = new SgfParser_1.SgfParser();
          parser.parse("f(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3])");
        }
        AppComponent = __decorate([angular2_1.Component({
          selector: "my-app",
          template: "<h1>My First Angular 2 App</h1>"
        }), __metadata('design:paramtypes', [])], AppComponent);
        return AppComponent;
      })();
      angular2_1.bootstrap(AppComponent);
    }
  };
});
```

This is my index.html:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>asdf</title>
    <script src="/js/lib/system.src.js"></script>
    <script src="/js/lib/angular2.dev.js"></script>
</head>
<body>
    <script>
        System.config({
            packages: { 'js': { defaultExtension: 'js' } }
        });
        System.import('js/main');
    </script>

    <my-app></my-app>
    <pre id="parse-log"></pre>
</body>
</html>
```

and here's how I know the file is being loaded:
![files-loaded](https://cloud.githubusercontent.com/assets/6319592/11102587/5603fdce-88b5-11e5-94f1-aff2951f84c8.png)

Again, apologies if I'm missing something really obvious, or if this is a problem with my typescript rather than systemjs-builder.

**Comment by fictitious** [comment]
Hard to tell without having compete example, but:

is your main.js file really in js/ directory ? 

if so, why it has `System.register("main.js", ... `  rather than   `System.register("js/main.js",`  ? 

was it in the different directory during the build?

**Comment by mcavanagh** [comment]
Yeah, the built main.js is in /js

I assume the reason for the module name is that I specified a base dir when i constructed the builder, eg:

```javascript
var builder = new Builder("/Ts");
```

Because all the individual .js files are in that directory after compiling them from typescript.

**Comment by fictitious** [comment]
Ok, so you have /Ts directory in the builder, and /js directory in the browser ? Then probably config for the browser should specify `js` as baseDir, if you don't need to load anything from outside that dir.

Having System.require() to refer to the module using one name, and loading code that registers that module under some other name indeed does not call `execute()` from that module, and does not give any errors - most likely that's what is happening in your case.

**Comment by mcavanagh** [comment]
Ah, I thought I didn't need baseURL in the browser config, because I was doing this:

```
 System.config({
            packages: { 'js': { defaultExtension: 'js' } }
        });
        System.import('js/main');
```

I thought this basically had the effect of making 'js' the baseURL.  Indeed, if it didn't, it wouldn't try to load the script from /js/main.js would it?

**Comment by fictitious** [comment]
> I thought this basically had the effect of making 'js' the baseURL

Not quite. System.import() translates module name to the URL, taking into account baseURL, map, packages and ton of other things in config, but it does not take apart the path if it exists in the module name - that is, 'js/main' goes through translation process as a whole - in your case, it ends up as `js/main.js` because the only thing that affects mapping in config is `defaultExtension`.

**Comment by mcavanagh** [comment]
I really appreciate your help on this so far.  I'm now getting a different problem.

My config in the browser is now:

```
        System.config({
            baseURL: '/js'
        });
        System.defaultJSExtensions = true;
        System.import('main');
```

The browser is now trying to load ```/js/angular2/angular2.js```

I assume this is because that's what the builder renamed the angular dependency to in the built file.

In the individually compiled main.js, the first line is:

```System.register(["angular2/angular2", "SgfParser"], function(exports_1) {```

but in the bundled file, the equivalent line is:

```System.register("main.js", ["angular2/angular2.js", "SgfParser.js"], function(exports_1) {```

I assume this is because the builder just names the modules after the files it finds them in.  But of course, in the angular2.dev.js library, it's registered as `angular2/angular` (no ".js" on the end)

**Comment by fictitious** [comment]
Yeah sorry it's unforeseen consequence of setting `defaultJSExtensions`  globally in the builder. Angular modules do not need that, I assume, because

- that code was not generated by systemjs builder
- that code is loaded by explicit script tag in your HTML, not by the loader

and as long as names for angular modules for System.import() in your code and System.register() in angular2.js match, everything should work.

You just need to add `.js` extension to your files, so that builder and loader will be able to locate them - one way to do that is to have your script files in a separate directory, and configure baseURL and defaultJSExceptions only for that directory, using `packages` in config.

**Comment by mcavanagh** [comment]
> You just need to add .js extension to your files, so that builder and loader will be able to locate them - one way to do that is to have your script files in a separate directory

Not 100% sure what you mean here.

I can't see any documentation on specifying a 'packages' config to the builder the way you can in the browser.  I've tried putting it on ```builder.loader.packages```, and I've tried putting it as a property of ```builder.config({ ...```, but removing ```defaultJSExtensions``` from the builder just causes fail finding files eg: ```[Error: ENOENT, open 'D:\Code\Visual Studio Projects\SgfClient\src\SgfClient\Ts\main']```

**Comment by fictitious** [comment]
Oh sorry there is no package-specific baseURL setting. My bad. 

I was thinking about package-specific mapping. I think it's possible, but then your module names should have some directory prefix, for example you would be using `'app/main'` in the code everywhere instead of just `main`, and have configuration like this


    builder.config({
        packages: {
             'app': {
                   defaultExtension: 'js',
             }
             map: {
                    'app': 'Ts'  // for the builder
             }
        }
    });


(not tested)

**Comment by fictitious** [comment]
Ok I was confused by 

> The browser is now trying to load /js/angular2/angular2.js

It turns out baseURL affects only how the files are located, not how the modules are registered and imported.

In other words, global baseURL should not affect angular code, as long as it's loaded by the script tag and not by the loader.

So, if you have Ts/app/main.js file for the builder, js/app/main.js for the browser, and you are referring to your module as `app/main`, then this config should work:

        builder.config({
            baseURL: 'Ts', // 'js' for the loader
            packages: {
                'app': {
                     defaultExtension: 'js'
                }
            }
        });


(sorry again, not tested).

**Comment by mcavanagh** [comment]
Ok, I've changed my directory structure to match what you suggested.  So now we have:

```
/Ts
    /sgfapp
        /main.js
        /SgfParser.js
```

And the build task in my gulp file:

```javascript
    var builder = new Builder();

    builder.config({
        baseURL: '/Ts/sgfapp', /* You suggested just 'Ts' in your example, but it seemed to be looking one directory up */
        packages: {
            'sgfapp': {
                defaultExtension: 'js'
            }
        },
        meta: {
            'angular2/angular2': {
                build: false
            }
        }
    });
       
    builder.bundle('sgfapp/main', '../wwwroot/js/sgfapp.js');
```

But then I get the error

```[Error: ENOENT, open 'D:\Code\Visual Studio Projects\SgfClient\src\SgfClient\Ts\sgfapp\sgfapp\main.js']```

So I think "ok, it's duplicating '/sgfapp', so I'll change it to:

```builder.bundle('sgfapp/main', '../wwwroot/js/sgfapp.js');```

but then I get

```[Error: ENOENT, open 'D:\Code\Visual Studio Projects\SgfClient\src\SgfClient\Ts\sgfapp\main']```

Which is close, but again, has dropped the '.js'.  Which makes me think that it's no longer recognising the right package name, because it's missing the 'defaultExtension' setting.

I can't seem to find the right combination of module names, file paths and builder configs.  There's several settings where I'm still confused as to whether it purely represents a module name, or whether it also expects a matching directory structure.  Earlier in this thread, we confirmed that the first argument to bundle() is a module name, not a file path, but there are examples where the first argument is something like "foo/bar.js", which really makes me think the filename is relevant too.

**Comment by fictitious** [comment]
> There's several settings where I'm still confused as to whether it purely represents a module name, or whether it also expects a matching directory structure.

Module name is a kind of logical name. Like file name, it can have directory component, file name component and file extension component. Directory and extension are optional. If a module is found to be in a package (using directory and/or name match) then settings defined for the package apply. Those settings can change the actual directory where module file is expected to be located, or add an extension, like '.js'

Then, when loading the file, baseURL is added to the front.

Based on earlier comments, you need '.js' extension added to some modules, but not all.

The only way I know of to add '.js' extension selectively is to partition your namespace - you can have `sgfapp` package for which `.js` is the default extension, and anything else is left alone. But that partitioning is always explicit - that is, you need to refer to the modules in sgfapp package as `sgfapp/main` when importing them - there is no way to avoid the prefix AFAIK. That's why I was suggesting to set baseURL to `Ts`, and not `Ts/sgfapp` - if you do the later, `sgfapp` is not part of the namespace and could not be used to selectively apply configuration.

**Comment by mcavanagh** [comment]
Ok, I get what you're saying about the package and the .js extension.  So I've changed the baseURL back to just '/Ts', specified the package name as 'sgfapp', and then in the bundle command, passed 'sgfapp/main' as the first argument.  This finds main.js, but then, when trying to resolve main.js's dependency on SgfParser, it fails to find it with the error

```[Error: ENOENT, open 'D:\Code\Visual Studio Projects\SgfClient\src\SgfClient\Ts\SgfParser']```

as if the .js setting doesn't apply any more.

Relevant builder settings here:

```
var builder = new Builder();

    builder.config({
        baseURL: '/Ts/',
        packages: {
            'sgfapp': {
                defaultExtension: 'js'
            }
        },
        meta: {
            'angular2/angular2': {
                build: false
            }
        }
    });
       
    builder.bundle('sgfapp/main', '/wwwroot/js/sgfapp.js')
```

**Comment by mcavanagh** [comment]
Looking at the individually generated .js files, I'm guessing the reason the module resolution is failing is that each ```System.register()``` call anonymous (has no name specified as the first argument, eg:

```javascript
/* SgfParser.js */
System.register(["StringReader", "SgfModels"], function(exports_1) {
```

The thing is, in my .ts files, I'm importing them like so:

```typescript
/* main.ts */
import {Component, bootstrap} from "angular2/angular2";
import {SgfParser} from "SgfParser";
```

and in the imported file:
```typescript
import {StringReader} from "StringReader";
import {CharacterCodes} from "CharacterCodes";
import {SgfGameTree, SgfNode, SgfProperty} from "SgfModels";

export class SgfParser {
    /* ... */
```

which makes sense, and is how I've seen it done in all the tutorials.  But this then results in a load of anonymous modules.  Not sure what the best solution is here.

**Comment by guybedford** [comment]
However you are transpiling your TS here needs to be naming the modules. Using the SystemJS TypeScript plugin or internal transpilation layer will provide this by default.
