### ISSUE TITLE
location of jspm_packages during build if 'directories' is set in package.json

### ISSUE THREAD

**Issue by davinkevin** [systemjs/builder#396]
Hi, 

First of all, thanks for your work, I really like the SystemJS and JSPM !

But, right now I have some problem on a "test | seed" project I create : https://github.com/davinkevin/JspmTypeScript

My project has the following organisation with all the jspm_packages inside the public folder (and configured inside the packages json (https://github.com/davinkevin/JspmTypeScript/blob/master/package.json#L26)
![image](https://cloud.githubusercontent.com/assets/1970922/11099138/e4f9b34a-88a9-11e5-9302-57885b6c216d.png)

When I try to build, SystemJS doesn't seems to know the files jspm_packages are not locate at the root of project but inside a subfolder, when the builder try to load some files inside jspm_packages, it results the following error : 
![image](https://cloud.githubusercontent.com/assets/1970922/11099189/3d903696-88aa-11e5-838b-cd5beb1b1c51.png)

Some help could be very useful. :smile: 

Thanks

PS : to build, I have to add some strange package property (https://github.com/davinkevin/JspmTypeScript/blob/master/public/config.js#L9). Don't know if it's a bug or a misunderstanding... I will try to find out later...

**Comment by davinkevin** [comment]
I try to locate in systemjs/builder when (and where in lib) the jspm_packages are read and/or accessed, to try to solve that bug and do a PR... but I don't find it. 

A hint could be useful to solve the problem please /cc @guybedford

**Comment by guybedford** [comment]
If using jspm, you can load SystemJS Builder via the API at https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder. This will automatically configure the baseURL for you. Note that `directories.baseURL` should be set to `public` in the package.json in jspm for this to work though.

**Comment by davinkevin** [comment]
Thanks for your help, this obviously solve the problem.

I stop using the JSPM builder in build task to avoid some "BaseUrl error", but now I understand my error.

Thank again for your support and the great job you do with this lib !
