### ISSUE TITLE
Cannot generate sourcemap for typescript project

### ISSUE THREAD

**Issue by bnolan** [systemjs/builder#397]
I made a repository here to demonstrate the problem:

https://github.com/bnolan/systemjs-coverage/tree/master

Basically - system-builder using the typescript transpiler won't generate sourcemaps. Not sure what's going on here. Source map looks like this:

    {"version":3,"sources":[],"names":[],"mappings":"","file":"undefined"}

**Comment by bnolan** [comment]
Running `tsc --sourceMap` on the command line happily compiles and generates a sourcemap:

    {"version":3,"file":"test.js","sourceRoot":"","sources":["test.ts"],"names":[],"mappings":"AAAA,4CAA4C;;;;;;;;;YAI5C,QAAQ,CAAC,eAAe,EAAE;gBACxB,EAAE,CAAC,gBAAgB,EAAE;oBACnB,IAAI,CAAC,GAAO,IAAI,qBAAQ,CAAC;oBACzB,MAAM,CAAC,CAAC,CAAC,OAAO,EAAE,CAAC,CAAC,OAAO,CAAC,MAAM,CAAC,CAAC;gBACtC,CAAC,CAAC,CAAC;gBAEH,EAAE,CAAC,SAAS,EAAE;oBACZ,MAAM,CAAC,IAAI,CAAC,CAAC,OAAO,CAAC,IAAI,CAAC,CAAC;gBAC7B,CAAC,CAAC,CAAC;YACL,CAAC,CAAC,CAAC"}

**Comment by guybedford** [comment]
Yes the TypeScript workflow isn't great, and we're moving away from this in the next release.

The goal is to make the TypeScript plugin here - https://github.com/frankwallis/plugin-typescript the primary way to use TypeScript with SystemJS as it handles the cases much better.

Perhaps try that out and see if you get better results?

This may just be a documentation issue then to encourage that over the `transpiler: 'typescript'` option in the SystemJS readme.

**Comment by guybedford** [comment]
The current transpilation for builds is handled in https://github.com/systemjs/builder/blob/master/compilers/esm.js#L95.

Work on this build is not something that is being prioritised for development here, but PRs are welcome.
