### ISSUE TITLE
Bundling with npm without gulp

### ISSUE THREAD

**Issue by Ludo09** [systemjs/builder#398]
Is it possible to use system.js builder directly in npm script without Gulp?
If yes, how which npm package should I use and how should I use it on the command line?
If no, is there any plan to provide such a package in the near future?

**Comment by fictitious** [comment]
The package is named `systemjs-builder`

        npm install systemjs-builder

Then you write a script, for example `build.js` like this

        var Builder = require('systemjs-builder');
        var builder = new Builder;

        builder.config({ ... });  // systemjs config

        builder.bundle('package-name', 'output-file.js', {minify:true});

Then

**Comment by tdillon** [comment]
Thanks @fictitious, exactly what I've been looking for.
