### ISSUE TITLE
Support cache invalidation of SFX name encodings

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#399]
Currently these give errors that the numeric encoding module name is not found.

**Comment by guybedford** [comment]
Test added here in https://github.com/systemjs/builder/commit/c646ecc9adc09d046f8e50dec14c844c1412c02d, which all seems to be working ok to me.

**Comment by guybedford** [comment]
@jackfranklin this seems to work fine from my testing here. Perhaps let's try again with the coming release.

**Comment by jackfranklin** [comment]
@guybedford perfect, thank you. Just noticed that 0.16.15 of jspm is out with this addition, so I'll test this soon.

**Comment by guybedford** [comment]
Thanks @jackfranklin for testing this out. Unfortunately jspm 0.17 is a higher priority right now, but if you're able to look into this and come up with suggestions for why it is happening, that would always be appreciated.

**Comment by jackfranklin** [comment]
@guybedford not sure if you saw, but unfortunately latest jspm doesn't fix the error. I'll dry to dive into it and see if I can find anything useful!

**Comment by jackfranklin** [comment]
And no worries on 0.17 being higher priority, totally understand :)
