### ISSUE TITLE
how to force include of traceur runtime

### ISSUE THREAD

**Issue by metamatt** [systemjs/builder#403]
Hi. I'm using jspm 0.16.13, systemjs 0.19.5, traceur 0.0.92 to transpile and package and load a browser app. I just hit a case where the app blows up at runtime because `$traceurRuntime` is not defined.

I don't totally have my head around

- which cases I as the app author do/don't need the traceur runtime present at actual runtime (see https://github.com/google/traceur-compiler/issues/777, https://github.com/google/traceur-compiler/issues/1007)
- why this case (a `typeof` operator) requires the traceur runtime (and many other uses of `typeof` do not). Seriously, this ends up being the only reference to `$traceurRuntime` in my entire transpiled bundled app.

However, it seems the right solution is to include the traceur runtime. I looked at https://github.com/systemjs/builder/issues/46 and https://github.com/systemjs/builder/commit/4862dde333ab6defc2d9bce4dad131fc423ec3a5 and it looks like you already added mechanisms to do that, and they've already change since that commit. (I tried setting `opts.runtime=true` and that had no effect; looking at the current source of compile.js it looks like it tries to figure this out automatically now.)

Then I found this snippet in your [chat archives](https://gitter.im/jspm/jspm/archives/2015/07/16):

jackfranklin Jul 16 15:07
> @guybedford cool, I think I've figured it out. It's because we're currently precompiling, so the code in compilers/esm.js of systemjs-builder that sets metadata.usesTraceurRuntimeGlobal = true never gets executed. This work on incremental builds should in theory lead to us not precompiling anyway

guybedford Jul 16 15:09
> nice, yes that would make sense - I suppose we can't make assumptions for other formats when not directly managing the transpiling, so may be best to have a manual step there.

Did that happen? If not, I think I need it too.

**Comment by metamatt** [comment]
(I don't understand the advice in #46 to [just inline the actual `traceur-runtime.js` as a named global module called `@traceur-runtime`](https://github.com/systemjs/builder/issues/46#issuecomment-77696618).)

**Comment by guybedford** [comment]
It's best to just include Traceur runtime with a script tag at the top of the page. I know this workflow is not ideal, it will be automated in jspm 0.17.
