### ISSUE TITLE
`Process.env.NODE_ENV is undefined` error in browser after running builder.buildStatic

### ISSUE THREAD

**Issue by dmbrowne** [systemjs/builder#405]
I fixed my previous issue https://github.com/systemjs/builder/issues/404#issuecomment-158565160.

but the `bundle.js` is spitting out `if (process.env.NODE_ENV !== 'production') {` in the bundled file, but obviously doesn't have a  `process` variable. I think https://github.com/systemjs/builder/issues/197#issue-88489589 is related? I'm running version systemJsBuilder `0.14.11` so the line should be removed but I'm getting the error.

How would I fix or remove the condition?
I could simply do `window.process.env.NODE_ENV = 'production'`, but that surely can't be safe.

----------
I tried the setting the NODE_ENV on window like I suggested, I still get the same error :(

**Comment by guybedford** [comment]
`process.env.NODE_ENV` only applies to CommonJS modules in the builder. Ensure the relevant module is being treated as CommonJS for the removal to work.

**Comment by dmbrowne** [comment]
all of my modules are commonJs so I set set a wildcard like this:
```
meta: {
    "*": {
        "format": "cjs"
    }
}
```
but `process.env.NODE_ENV` is still present in the bundle

**Comment by guybedford** [comment]
The `process.env.NODE_ENV` optimization is only done when minification is enabled during bundling.

**Comment by dmbrowne** [comment]
Thanks for your help @guybedford, but it just doesn't seem to work for me. I've given up and decided to use browserify for productions bundling.

**Comment by guybedford** [comment]
Sure, that is certainly understandable. Just to follow up - if I write `test.js` containing - 

```javascript
if (process.env.NODE_ENV != 'production') {
  module.exports = 'dev';
}

module.exports = 'prod';
```

Then run the builder with minification enabled, it definitely removes the dead code in the above. CommonJS with minification works in all cases, but if you do still have a test case that fails it would be interesting to hear what it was.
