### ISSUE TITLE
builder.bundle doesn't add sourceMappingUrl

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/builder#406]
Is there a reason for this? I notice it is added when I use the jspm CLI, but not when I use systemjs-builder directly. Specifically, the comment doesn't appear in `result.source`: https://github.com/buddhike/gulp-jspm-build/blob/1edeac7acbb011e0d6eb248d504f5ff7dc080fb6/lib/compile.js#L48

**Comment by guybedford** [comment]
source maps are disabled by default.

**Comment by OliverJAsh** [comment]
I am opting in using the sourceMaps option.

**Comment by guybedford** [comment]
Ah, ok I think it only adds the comment then when `outFile` is set. When doing an in-memory build, it returns `source` and `sourceMap` as separate objects on the output only?
