### ISSUE TITLE
SFX build: false should be treated as an external dependency

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#407]

**Comment by gcnm-pgeil** [comment]
As explained earlier today in the systemjs gitter channel:

# Use case

My project consists of

+ Application specific module files
+ 3rd party libraries hosted at CDN (referred to as "external dependencies")

I want only the application modules to be compiled into a single static bundle file. By configuring modules `build: false` in the meta option,  external dependencies (for example hosted at CDN) should remain external and therefore not being fetched and stored locally by JSPM. When an external dependency is resolved (=imported by another module) somewhere inside my static bundle, I want the included loader runtime, to fetch/load the script just in time (only the first time it is requested) and then resolve it.

**Comment by guybedford** [comment]
Released in 0.14.12.
