### ISSUE TITLE
A noob question about building for production

### ISSUE THREAD

**Issue by moreofmorris** [systemjs/builder#41]
Hello there. Firstly, absolutely amazing work on JSPM and SystemJS. I've only just got started using JSPM and SystemJS and, so far in my development, they've been fantastic and so easy to use and understand.

I hope you don't mind me asking some noob questions around SystemJS and the best way to build my app for production. I love simplicity and clarity and I'm trying my best to come up with a nice structure, development environment and simple build process.

Firstly, I have my app structure something like this:

```
app/
  packages/
  config.js
  index.html
  main.js
  style.css
  ...
builder.js
package.json
server.js
```

I have a basic Express based server that serves the front end as well as providing some JSON APIs which is in the root at `server.js`. I then have my SystemJS Builder script in the root as `builder.js` and inside the `app/` folder is the front end stuff, including where JSPM puts the packages (in my case in the `app/packages` folder and the SystemJS configuration file at `app/config.js`.

The `app/index.html` file looks like this:

```
<!DOCTYPE html>
<html>
<head>
  <title>Development</title>
</head>
<body>
  <script src="packages/system.js"></script>
  <script src="config.js"></script>
  <script>
    System.baseURL = '/';
    System.import('main');
  </script>
</body>
</html>
```

The `app/config.js` file looks like this:

```
System.config({
  "paths": {
    "*": "*.js",
    "app/*": "/*.js",
    "github:*": "packages/github/*.js",
    "css": "packages/github/systemjs/plugin-css@0.1.0.js",
    "json": "packages/github/systemjs/plugin-json@0.1.0.js"
  }
});

System.config({
  "map": {
    "jquery": "github:components/jquery@2.1.3",
    "plugin-css": "github:systemjs/plugin-css@0.1.0",
    "plugin-image": "github:systemjs/plugin-image@master",
    "plugin-json": "github:systemjs/plugin-json@0.1.0",
    "plugin-text": "github:systemjs/plugin-text@0.0.2"
  }
});
```

So far so good, or at least I think? Everything seems to run fine in development (please tell me if any of this is already fishy, I want to learn!) ...and now I want to know how to build this app ready for production.

I don't really know the best way to go about this with SystemJS Builder. Would I direct the builder to build into a separate build folder (like `build/`)? From what I could see, I still need to include the `packages/system.js` library in the `index.html` for the build? Is there any options to include the SystemJS library as well into my build outfile so I just can include a single script in my build's `index.html` file?

What is the best way to approach a successful build the right way using SystemJS Builder? I'm quite used to Webpack just bundling everything into a single `bundle.js` file and my build directory just has a simple `index.html` that references that `bundle.js` file and that's that. Is there anyway of achieving something similar with SystemJS Builder, where it'll include all the CSS (which I'm loading as a module using the plugin), the SystemJS library and my app code into a single minified JS file that I can simply include with a `<script>` tag?

Or am I just approaching all of this completely wrong (I fully accept that I am!)

I just want to do it right :)

**Comment by guybedford** [comment]
A good place to start is https://github.com/jspm/jspm-cli/wiki/Production-Workflows if you haven't read that already.

Your setup looks fine to me. You may want to install your plugins with easier names perhaps:

```
jspm install css image json text
```

So that the requires are easier - `import 'file.json!'` instead of `import file.json!plugin-json'`.

CSS is not currently bundled with jspm, although that's on the list to do soon. See https://github.com/systemjs/builder/issues/12 to follow the progress.

**Comment by moreofmorris** [comment]
Thank you for your time Guy. All this work you're doing is incredible. I might be having a few teething problems (I'm actually a designer at heart, with a big passion for code) but I can see how many benefits JSPM/SystemJS brings to the table.

I got up early this morning to try and work out some of these problems I was having, finally realising I should of been using `jspm bundle-sfx main build/app.js --minify` and that worked great, but yes, then realised my CSS wasn't getting bundled with it. I will be keeping a close eye on this support as that looks like the final piece of the puzzle for me.

Thank you for all your hard work!

**Comment by guybedford** [comment]
Great to hear that, help ironing out teething issues is really appreciated. Do let me know if you hit anything else.

**Comment by bmcorser** [comment]
Production workflow documentation has moved https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md
