### ISSUE TITLE
Systemjs-builder with gulp streams

### ISSUE THREAD

**Issue by joerideg** [systemjs/builder#410]
Hi, first of all awesome work that you are doing with systemjs and jspm!

I got my team to want to use ES6 (yay!). So in our old Grunt build system I made my own little grunt task that used systemjs-builder to compile the ES6 code which worked splendid.
Now we are switching to Gulp, and Gulp works with streams. So I'm trying to avoid outputting a tmp file because well, its an advantage of Gulp to not have to do this. Is there any way I can use systemjs-builder to accept+output a stream on itself? Would that be a feature you would be willing to add?

Btw I did look around but I couldnt find a gulp plugin wrapper for systemjs, which suprises me and leads me to think I'm missing something. There is one for jspm, and I might just create gulp-systemjs if the functionality is not in the builder itself.

**Comment by lookfirst** [comment]
It is *highly* recommended to use the builder for jspm because getting all the configuration and setup correct for systemjs-builder directly is a very hard thing to do. Basically, I'd suggest that you look at the code for the jspm builder to figure out how to call the systemjs builder... and at that point, you might as well just use the jspm builder.

I basically have a bunch of bundles that I need to build so I wrap that into a gulp task...

```
import {Builder} from 'jspm';

let bundler = (bundle) => {
	let builder = new Builder();
	return builder.buildStatic(`js/${bundle.name}/app`, `${path.war}/js/${bundle.name}/${bundle.name}-bundle.js`,
		{minify: bundle.minify, sourceMaps: false, ascii: true});
};

bundles.forEach((bundle) => {
	if (bundle.hasBundle) {
		gulp.task('bundle-' + bundle.name, () => {
			return bundler(bundle);
		});
	}
});

gulp.task('deploy', (callback) => {
	if (!situation.isDevelopment()) {
		let bundleTasks = _.reduce(bundles, (tasks, bundle) => {
			if (bundle.hasBundle) {
				tasks.push('bundle-' + bundle.name);
			}
			return tasks;
		}, []);

		return runSequence('recompile',
			bundleTasks,
			'copy-css',
			callback);
	} else {
		return runSequence('recompile', 'symlinks', callback);
	}
});
```

**Comment by joerideg** [comment]
Well lets leave the discussion of using jspm or not for another time. Let me just say I currently have no problems whatsoever using just systemjs and am wondering whether I can just make do with npm3 flat dependency tree. I am just curious if I can combine Gulp and Systemjs with streams some how. 

In any case the gulp task I have is like this:
```javascript
function scripts(done) {
    gulp.src(cfg.src.scripts)
      .pipe(plumber())
      .pipe(esLint())
      .pipe(esLint.format())
      .pipe(esLint.failOnError());

    const systemjs = new Builder();
    systemjs.buildStatic(cfg.src.indexScript, cfg.dist.indexScript, {
      sourceMaps: 'inline',
      config: './system.config.js'
    }).then(function () {
      gulp
        .src([
          cfg.dist.indexScript,
          cfg.src.templates,
          '!' + cfg.src.indexHtml
        ])
        .pipe(plumber())
        .pipe(gulpif('*.html', templateCache({
          module: cfg.pkg.name
        })))
        .pipe(ngAnnotate())
        .pipe(concat(cfg.pkg.name + '.js'))
        .pipe(gulp.dest(cfg.dist.scripts));

      done();
    });
  }
```

Which works, but I rather have it in stream form for better readability :) For the systemjs cli it could also come in handy when you are reading in a couple of files and want to pipe them to the systemjs cli.

**Comment by vadimpopa** [comment]
I'm interested of this too. Found sth here https://github.com/origin1tech/gulp-traceur-compiler . (see output from production) but still have some issues with the task.

**Comment by vadimpopa** [comment]
For example I would like to inline the templates and then build the js, what you see below is just to get an idea.
```javascript
      gulp.src(global.paths.js)
      .pipe(inlineNg2Template({ base: global.paths.src}))
        .pipe(through.obj(function (file, enc, cb) {
          var self = this;

          builder.buildStatic("app", "dist/app.min.js", {minify: true})
          .then(function (output) {

            // get the file contents from the output source.
            file.contents = new Buffer(output.source);

            // push the file to the connection.
            self.push(file);

            // callback to let through2 we're all done.
            cb();

          })
          .catch(function(err) {
            console.log(err);
            cb(err);
          });
      }))
      .pipe(gulp.dest('dist/app.min.js'));
```

**Comment by vadimpopa** [comment]
I've got it working, even if is not by streaming way

```javascript
gulp.task('buildjs', function (cb) {
  var Builder = require('systemjs-builder');
  var builder = new Builder("./","system.config.js");
    
  builder.reset();

  builder.buildStatic("app", "dist/app.min.js", {minify: true})
    .then(function (output) {
      gulp.src("dist/app.min.js")
        .pipe(inlineNg2Template({ base: "./", css: false}))
        .pipe(gulp.dest('dist/'))
  })
  .catch(function(err) {
    console.log(err);
    cb(err);
  });
});

//buildjs produces same as this one
// gulp.task('bjs', function(){
//     return gulp.src('app/app.ts')
//         .pipe(gulp_jspm({
//           selfExecutingBundle: true
//         }))
//         .pipe(inlineNg2Template({ base: "./", target: 'es5', css: false }))
//         .pipe(rename({
//           basename: 'app.min',
//           extname: '.js'
//         }))
//         .pipe(gulp.dest('dist/'));
// });
```

**Comment by joerideg** [comment]
I would appreciate a direct answer to the question I posted. Is it possible to input and output a stream with systemjs builder?

@vadimpopa:
Will that task end when successfull though? When successfull it doesnt return a promise, calls the done() or calls the callback function or am I missing something. Also I had a similar thing going but then when I was using watch and ran ['buildjs', 'unitTests'] it would fail the tests because as soon as the promise resolved it would start the unit tests even though the templates had not been merged with the dist/app.js yet because the whole inlineNg2Template was still running.

I'm currently using gulp4(branch) and came up with this interesting setup of 3 functions called in gulp.series. Its not as gulpy as I would like, but its pretty clean and works. 

```javascript
// importing the plugins and 
// defining the systemjs builder happends before this piece of code.
  function scripts(done) {
    gulp.series(
      function lintES6() {
        return gulp
          .src(cfg.src.scripts)
          .pipe(plumber())
          .pipe(esLint())
          .pipe(esLint.format())
          .pipe(esLint.failOnError());
      },
      function transpile() {
        return systemjs.buildStatic(cfg.src.indexScript, cfg.dist.indexScript, {
          sourceMaps: 'inline'
        });
      },
      function templatesNgAnnotateConcat() {
        return gulp
          .src([
            cfg.dist.indexScript,
            cfg.src.templates
          ])
          .pipe(plumber())
          .pipe(gulpif('*.html', templateCache({
            module: cfg.pkg.name
          })))
          .pipe(ngAnnotate())
          .pipe(concat(cfg.pkg.name + '.js'))
          .pipe(gulp.dest(cfg.dist.scripts))
          .pipe(browserSyncServer.stream());
      })(done);
  }

gulp.watch(cfg.src.scripts, gulp.series(scripts, unitTests); // this now works!
```

**Comment by vadimpopa** [comment]
@joerideg I've updated my comment with calling the callback. I added in my code but forgot to update here also, you noticed right.  Then as soon as I finish with the distro build task will take a look on the watch task, thanks though for mentioning about the watch issue, will let you know. Also yeah, gulp.series is fine, I'm using run-sequence on the build also.

**Comment by guybedford** [comment]
A `gulp-systemjs-builder` project would be great to have. Please do share if you can.

**Comment by vadimpopa** [comment]
There's something in the wild, https://github.com/brillout/gulp-jspm. And is much faster at build than  ```systems-builder```: see my comment above, ```bjs``` task is much faster than ```builds```

**Comment by joerideg** [comment]
@vadimpopa Yes gulp-jspm is there and works great, I checked it out aswell as the outstanding pullrequest it has. I will obviously base the gulp-systemjs-builder plugin on it if I decide to create it. Wanted to create a gulp plugin for a while now anyway.

@guybedford From your reply I take it it is currently not possible. Thought so already, was just hoping I was missing something hehe. I will close this issue then. If I find some time I will create the gulp-systemjs-builder plugin. 

Thanks everyone for their replies.

**Comment by guybedford** [comment]
@joerideg yes we do not output any streaming interfaces as the build is a two phase process of analysing the full tree into memory and then compiling. Keep me posted if you do work on something here.

**Comment by darrenshrwd** [comment]
If it helps anyone else, I didn't want to construct a bunch of gulp tasks, rely on ES6 and I have a simple 'jsBundlesArr' obj array that defines my inFile and outFile, as Node.js now has promises built in I could use **Promise.all()** like below:

```
function bundleJs(shouldWeMinify) {
    var builder = new jspm.Builder();
    return jsBundlesArr.map(function (obj) {
        return builder.buildStatic(obj.inFile, obj.outFile, {
            buildCSS: false,
            minify: shouldWeMinify,
            sourceMaps: shouldWeMinify,
            runtime: false
        })
    })
}

gulp.task('bundle:js:Release', ['clean:js'], function () {
    var actions = bundleJs(true);
    Promise.all(actions)
        .then(function () {
            //Can now do other things here
        })
        .catch(function (err) {
            throw 'Bundling err: ' + err;
        });
});
```
