### ISSUE TITLE
A way to include config in static build?

### ISSUE THREAD

**Issue by iamcdonald** [systemjs/builder#411]
I realise that this is odd but I'm currently just experimenting to see if it's possible. 

I'm looking at trying to build a static bundle which would all be fine except one of the dependencies I'm pulling in (aurelia) does on the fly imports through it's own loader (which wraps either the non-static SystemJS or Require loader given your context). 

I have created my own implementation of their loader which utilizes the ```$__System``` object available within a static build. However, in order to properly load the dynamic dependencies I would need to normalize the module names, which would require access to the original config (specifically the ```map```) used to build the static bundle.

Is there a way to accomplish this without pulling in the actual ```config.js``` file i.e. a setting within the builder itself which would include the object passed into System.config in the output? 

Thanks

**Comment by guybedford** [comment]
This is actually included when the `buildConfig: true` build option is set. It's still a somewhat experimental feature though.

**Comment by iamcdonald** [comment]
Ah, ok. I thought that might be the case but I can't for the life of me see it in the output.
I'm using the following code to build

```js
var builder = new Builder('./', './config.js');
  builder.buildStatic('app/app.js', 'outty.js', {
    buildConfig: true,
    encodeNames: false
  });
```

Is there possibly somewhere I'm going wrong here?
I was expecting to see the object passed into ```System.config``` within the auto-generated ```config.js``` appear somewhere in the output file (in this case outty.js).

**Comment by guybedford** [comment]
The config is only included for `bundle` builds not static builds as they are already linked.

**Comment by iamcdonald** [comment]
Yeah, that makes sense. As I said before I was just trying to work around the dynamic loading inherent in aurelia (therefore all dependencies can't be traced at build time). While I can stop the names from being encoded within a static build I would need access to the config map in order to normalise say a reference to ```aurelia-framework``` to ```npm:aurelia-framework@1.0.0-beta.1.0.2```. 

I take it there's no appetite to facilitate inclusion of the buildConfig within static builds? Although, if you were going that far it'd make sense to utilise it within the ```$__System``` loader that's bundled with a static build. I'd be happy to chip in but I would also completely understand if it was deemed to be unwanted, extra bloat.

**Comment by guybedford** [comment]
Yes it's not something we can support unfortunately, you'd have to add that through some kind of custom build step if you really need it, by exporting System to a global internally. I'd strongly suggest using a normal bundle though. Static bundles aren't really designed for dynamic linking cases. https://github.com/systemjs/builder/issues/417 may be somewhat related here.

**Comment by iamcdonald** [comment]
Yeah, I figured that. I started going down the route of defining a fake System global in order to grab the config but it's just too hacky. Also, it certainly looks like this is the same point raised in  [#417](https://github.com/systemjs/builder/issues/417). Thanks for your time.
