### ISSUE TITLE
Babel 6 support and documentation

### ISSUE THREAD

**Issue by enlait** [systemjs/builder#412]
It seems there are quite a lot of breaking changes in (relatively) recently released babel 6.

For one thing, `babel-core` package was split into many smaller packages. Because, you know, *more is better*. In 5.* it included `external-helpers.min.js` file which I just included on the page and things worked. Now there are dozens of helper packages, and I have no idea how to gather all that mess together.

So,
1. what's the current status of babel 6 in systemjs
2. could you document the switch if (or when) it's available

**Comment by lookfirst** [comment]
Ref https://github.com/babel/babel.github.io/issues/550

**Comment by gcnm-pgeil** [comment]
+1

**Comment by joerideg** [comment]
+1

**Comment by guybedford** [comment]
Tracking Babel 6 support in https://github.com/systemjs/systemjs/issues/953, where progress updates will be posted.
