### ISSUE TITLE
Builder drops file extension when js module is imported from jsx module

### ISSUE THREAD

**Issue by maxlk** [systemjs/builder#413]
SystemJS Build Tool drops file extension when js module is imported from jsx module. I will illustrate the problem in a simple example.

There is a package `test-app` that sits in `lib` folder and consists of two modules `main.jsx` and `module.js`. Module `module.js` is imported into `main.jsx` module. In development mode (files are loaded separately to browser) SystemJS loads both modules as expected with correct extensions.

During build of self-executing bundle SystemJS builder is looking for `lib/module` file instead of `lib/module.js`:
```
err  Error on fetch for test-app/module at file:///c:/systemjs-builder-issue-import-js-from-jsx/lib/module
        Loading lib/main.jsx
        Error: ENOENT, open 'c:\systemjs-builder-issue-import-js-from-jsx\lib\module'
         at Error (native)
```
It is only reproducible when both `defaultExtension: false` option is set **and**  path to package is specified in `paths` option.
```javascript
packages: {
  "test-app": {
    main: "main.jsx",
    format: "esm",
    defaultExtension: false
  }
},

paths: {
  "test-app*": "lib*",
  "github:*": "jspm_packages/github/*",
  "npm:*": "jspm_packages/npm/*"
},
```
Particularly, when renaming `lib` folder to `test-app` and removing its entry from `paths`, build passes successfully. 

Pay attention that **SystemJS** and **SystemJS Build Tool** both work with the same configuration, but first handles it correctly and second fails.

See full example here: [maxlk/systemjs-builder-issue-import-js-from-jsx](https://github.com/maxlk/systemjs-builder-issue-import-js-from-jsx)

**Comment by maxlk** [comment]
Maybe #395 has the same root cause

**Comment by guybedford** [comment]
Thanks, this does sound like a bug.

**Comment by guybedford** [comment]
If you use map configuration instead of paths configuration for the package does that avoid the issue here?

The paths configuration with an empty wildcard as you have used for the main is not supposed to be supported currently actually.

**Comment by maxlk** [comment]
@guybedford
> If you use map configuration instead of paths configuration for the package does that avoid the issue here?

Yes, when I use map instead of paths it works fine. I use it as a workaround meanwhile.

>The paths configuration with an empty wildcard as you have used for the main is not supposed to be supported currently actually.

I used `"test-app*": "lib*"` instead of two mappings `"test-app": "lib", "test-app/*": "lib/*"` and it works in dev mode :satisfied:
By *not supposed to be supported* you mean that you didn't expect it to work, or you mean that it's a wrong usage that should be avoided?

Sorry for late reply and thanks to you and to @fictitious for your attention :+1:

**Comment by guybedford** [comment]
Closing as a won't fix after discussion in https://github.com/systemjs/builder/pull/414.

**Comment by maxlk** [comment]
@guybedford
The flag `defaultJSExtensions` is deprecated, but in *jspm* registry there are a lot of packages which will not work without it, because they import files without extensions.
The issue will not be resolved until `defaultJSExtensions` is completely removed, because you have to maintain problematic code even when the flag is deprecated. But its removal will broke all mentioned packages.
Do you have plans to remove `defaultJSExtensions` completely? I see that in *jspm 0.17-beta.3* it still exists.

**Comment by guybedford** [comment]
@maxlk in jspm 0.17 defaultJSExtensions is fully deprecated, to use package configuration defaultExtension rather. See https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages.
