### ISSUE TITLE
Builder doesn't pass through es6 syntax

### ISSUE THREAD

**Issue by maxlk** [systemjs/builder#415]
Modern browsers support some es6 features and I want to take advantage of it in my project.

When I add particular es6 transformations to Babel's blacklist, everything works fine in development mode. But when I try to build a bundle I get an error.

A simple example below.

**main.js**
```javascript
{
	let message = "Hello, World!"
	console.log(message)
}
```

**Babel configuration in config.js**
```javascript
transpiler: "babel",
babelOptions: {
  "optional": [
    "runtime",
    "optimisation.modules.system"
  ],
  "blacklist": [
    "es6.blockScoping"
  ]
},
```

**builder output**
```
     Building the single-file sfx bundle for test-app...

err  SyntaxError: evalmachine.<anonymous>:8
                                let message = "Hello, World!";
                                ^^^
     Unexpected strict mode reserved word
        Evaluating file:///C:/systemjs-es6-pass-through/lib/main.js
        Error on instantiate for lib/main.js at file:///C:/systemjs-es6-pass-through/lib/main.js
```

**Comment by guybedford** [comment]
Thanks, yes this is a known issue and being tracked in https://github.com/systemjs/builder/issues/299.

**Comment by maxlk** [comment]
#299 was released in *0.15.0* but this issue is still reproducible in *0.15.2*.
@guybedford Please, reopen.

**Comment by guybedford** [comment]
@maxlk this feature only applies to the use of the Babel plugin in jspm 0.17, and not the internal transpilation layer in jspm 0.16.

**Comment by maxlk** [comment]
@guybedford you mean that in jspm 0.16 *internal transpilation layer* is used to transpile es6 when `require('jspm').Builder.buildStatic()` is invoked, right?

**Comment by guybedford** [comment]
Yes.
