### ISSUE TITLE
Not able to create bundle with builder when I import json file

### ISSUE THREAD

**Issue by martinmicunda** [systemjs/builder#42]
When I import json file (e.g. `import abc from './abc.json!'`) in my code I am not able to build bundle with builder as I am getting below error. 

> **NOTE:** I am not getting any error when I am using `jspm` command e.g. `jspm bundle-sfx app/bootstrap build.js` and bundle is created successfully.

**Gulp Task Code:**
```js
var builder = require('systemjs-builder');
builder.reset();

builder.loadConfig('./src/jspm.conf.js')
    .then(function() {
        builder.loader.baseURL = path.resolve('./src/');
        builder.buildSFX('app/bootstrap', paths.tmp.scripts + 'bootstrap.js', { sourceMaps: true, config: {sourceRoot: 'src/.tmp/scripts/'} })
            .then(function() {
                return cb();
            })
            .catch(function(ex) {
                cb(new Error(ex));
            });
    });
```

**Error:**
```bash
Error: Error loading "app/components/employee/fixtures/employee_1.json!github:systemjs/plugin-json@0.1.0" at <unknown>
Error loading "app/components/employee/fixtures/employee_1.json!github:systemjs/plugin-json@0.1.0" from "app/bootstrap" at file:/Users/martinmicunda/projects/employee-scheduling/ui/src/app/bootstrap.js
Error loading "github:systemjs/plugin-json@0.1.0" at github:systemjs/plugin-json@0.1.0.js
Only file URLs of the form file: allowed running in Node.
    at /Users/martinmicunda/projects/employee-scheduling/ui/gulpfile.js:295:24
    at promiseHandle (/Users/martinmicunda/projects/employee-scheduling/ui/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:1874:20)
    at /Users/martinmicunda/projects/employee-scheduling/ui/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:1868:9
    at flush (/Users/martinmicunda/projects/employee-scheduling/ui/node_modules/systemjs-builder/node_modules/traceur/bin/traceur.js:1672:7)
    at process._tickCallback (node.js:419:13)
```

**Comment by guybedford** [comment]
Try changing this line - `builder.loader.baseURL = path.resolve('./src/');` to `builder.loader.baseURL = 'file:' + path.resolve('./src/');`

**Comment by martinmicunda** [comment]
@guybedford I tried however it didn't work :(

**Comment by guybedford** [comment]
@martinmicunda did it give the same issue?

**Comment by guybedford** [comment]
@martinmicunda does your config file include a path configuration for `github:` like:

```javascript
System.paths['github:*'] = 'jspm_packages/github/*.js';
```

**Comment by martinmicunda** [comment]
@guybedford yes

**Comment by guybedford** [comment]
It could be worth checking `builder.loader.paths` in the code there to be sure it is being set properly?

**Comment by guybedford** [comment]
@martinmicunda I've worked out the issue here - https://github.com/systemjs/builder/issues/43. Aiming to get a fix in very soon. Thanks so much for helping to catch this.

**Comment by martinmicunda** [comment]
no problem glad to help ;)

**Comment by guybedford** [comment]
@martinmicunda this has been fixed with https://github.com/systemjs/builder/commit/93566a733ad55d144cb8579005dab2634ffdeba7, I'll be posting out a release tomorrow.

**Comment by martinmicunda** [comment]
That's perfect I will test it! Thanks
