### ISSUE TITLE
Document plugin build hooks

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#420]
It may be worth rethinking the signature in line with the use case at https://github.com/jspm/jspm-cli/issues/1329#issuecomment-161109135, as something that can always be called, not just when the `inlinePlugins` option is set, but rather to see if we could potentially provide the inlining and asset list features as part of this single API call.

**Comment by guybedford** [comment]
We could then relax the restriction of an Array return value too.

**Comment by guybedford** [comment]
Marking as a documentation issue, the forms are:

bundle(loads, compileOpts, outputOpts) -> [outputs] / undefined
listAssets((loads, compileOpts, outputOpts) -> [assets{utl,type,[source],[sourceMap]}]

Allowing bundle to return undefined in https://github.com/systemjs/builder/commit/54cb5c45534492d2de378d6a6bc0e78f1bac4b1b allows it to nicely double as a lifecycle event.

**Comment by CxRes** [comment]
I am sorry, but this still does not make sense. Specifically, I struggle to understand the outputs expected and what does SystemJS do with output/assets that the build routines return?
I am having trouble with Hypercubed/systemjs-plugin-html when bundling any html asset and trying to figure how to get it bundle the loader and instruct it load output files. Right now it applies `System.register()` on input files which are deleted after bundling.
