### ISSUE TITLE
An option to load modules from node_modules: plugins don't work

### ISSUE THREAD

**Issue by finom** [systemjs/builder#421]
Hey, I'm referring to [this](https://github.com/systemjs/systemjs/issues/767) feature request. In general it works but doesn't allow to use modules from node_modules as plugins.

Source code:
```js
import gTemplate from 'templates/g.html!systemjs-plugin-text';
```

It works perfectly with client-side SystemJS but it doesn't allow to make a bundle.

```
ENOENT: no such file or directory, open '/path/to/folder/node_modules/node_modules/package.json
```

Config file:
```js
System.config({
    transpiler: 'babel',
    baseURL: '.',
    defaultJSExtensions: true,
    babelOptions: {
        stage: 0
    },
    paths: {
        '*': './node_modules/*',
        'templates/*': './templates/*',
        'app/*': './src/app/*'
    },
    packageConfigPaths: ['./node_modules/*/package.json'],
    map: {}
});
```

Package:
```js
{
  "devDependencies": {
    "systemjs-builder": "^0.14.11"
  },
  "dependencies": {
    "systemjs": "^0.19.6",
    "systemjs-plugin-text": "git@github.com:systemjs/plugin-text.git"
  }
}

```

P. S. Babel is outdated (5.8) but I don't think this is Babel version issue.

**Comment by guybedford** [comment]
The duplication is likely because of the `'*': './node_modules/*'` path here, which is likely a bug.

To work around it I would suggest trying to work around this without using the `*` path.
