### ISSUE TITLE
SystemJS-builder + NPM + Typescript + Karma

### ISSUE THREAD

**Issue by Ludo09** [systemjs/builder#423]
I'm trying to create a snippet of code I could re-use in all sorts of projects. Indeed I want to create different libraries, written in Typescript, and bundled in a single es5 file.

However I'm facing 2 issues right now:
- when I run `npm run bundle` or just `node build.js` I'm getting `Build error [Error: ENOENT, open '/Users/ludo09/typescript_template/dist/build/src/B']`
- when I run `karma start` I'm getting `You need to include some adapter that implements __karma__.start method!` 

Here is the code:

    src/
      A.ts
      api.ts
      B.ts
      C.ts
    test/
      e2e/
      unit/
        CSpec.ts
    build.js
    karma.conf.js
    package.json
    tsconfig.json
    tsd.json

A.ts

    import {B} from './B';

    export class A {
        private _a = 1;

        public a() {
            return this._a + new B().b();
        }
    }

api.ts (what will be visible to the outside world: A and C)

    export {A} from './A'
    export {C} from './C'

B.ts

    export class B {
        private _b = 2;

        public b() {
            return this._b;
        }
    }

C.ts

    export class C {
        private _c = 3;

        public c() {
            return this._c;
        }
    }

CSpec.ts

    import {C} from '../../src/C';

    describe('Test C', () => {
        it('should return correct value', () => {
            expect(new C().c()).toEqual(3);
        });
    });

karma.conf.js
```
    module.exports = function (config) {
        config.set({
            basePath: '',
            frameworks: ['jasmine'],
            files: [
                'dist/build/**/*.js'
            ],
            exclude: [],
            preprocessors: {
                '**/*.js': ['commonjs']
            },

            reporters: ['progress'],

            port: 9876,
            colors: true,
            logLevel: config.LOG_INFO,
            autoWatch: true,
            browsers: ['Chrome'],
            singleRun: false,
            concurrency: Infinity
        })
    };
```

package.json
```
    {
      "name": "mylib",
      "version": "0.0.1",
      "devDependencies": {
        "karma": "latest",
        "karma-chrome-launcher": "^0.2.2",
        "karma-commonjs": "latest",
        "karma-jasmine": "latest",
        "rimraf": "latest",
        "systemjs-builder": "latest",
        "tsd": "latest",
        "typescript": "latest"
      },
      "scripts": {
        "setup:install": "npm install && tsd reinstall -so",
        "setup:update": "npm update && tsd update -so",
        "clean": "rimraf dist/*",
        "prebuild": "npm run clean -s",
        "build": "tsc",
        "prebuild": "npm run build",
        "bundle": "node build.js"
      }
    }
```
tsconfig.json
```
    {
      "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "removeComments": true,
        "outDir": "dist/build",
        "sourceMap": true
      },
      "exclude": [
        "node_modules"
      ]
    }
```

tsd.json
```
    {
      "version": "v4",
      "repo": "borisyankov/DefinitelyTyped",
      "ref": "master",
      "path": "typings",
      "bundle": "typings/tsd.d.ts",
      "installed": {
        "jasmine/jasmine.d.ts": {
          "commit": "78d36dd49b6b55b9fdfe61776a12bf05c8b07777"
        }
      }
    }
```
     
What am I missing or doing wrong?

**Comment by gcnm-pgeil** [comment]
You must include the filename extension (`.js` or `.ts` in your case) when referencing external module files inside `import`/`export` statements. It's an officially recommended practice. However, I have no experience with TypeScript builds using systemjs-builder, but when building JS/ES6+ projects the rror message you posted occurs when something is messed up with the filename suffix.

**Comment by Ludo09** [comment]
I forgot to attach build.js (and of course the following doesn't work): 

```
var Builder = require('systemjs-builder');
var builder = new Builder;

builder.config({
    baseUrl: './src/',
    defaultJSExtensions: true,
    transpiler: 'typescript',
    packages: {
        'mylib': {
            main: './api.ts',
            defaultExtension: 'ts'
        }
    }
});
builder.bundle('dist/build/src/api.js', 'dist/mylib.js', {minify: true, sourceMaps: true})
    .then(function () {
        console.log('Build complete');
    })
    .catch(function (err) {
        console.log('Build error');
        console.log(err);
    });
```

The bundling works fine if I run `tsc` before `node build.js`. Somehow it looks like `tsc` is not called by `build.js`.

**Comment by guybedford** [comment]
It's advisable to rather use the TypeScript plugin at https://github.com/frankwallis/plugin-typescript instead of the internal transpilation workflow as the internal TypeScript support is limited and does not support definition files.

**Comment by Ludo09** [comment]
I switched to Webpack, this was more easy for me.
