### ISSUE TITLE
sourceMapContents array is full of nulls

### ISSUE THREAD

**Issue by aniranc** [systemjs/builder#427]
Reproducible example here: https://github.com/aniranc/systemjs-builder-sourceMapContents-min-failing

Looks like going through the source path normalizing (https://github.com/systemjs/builder/blob/master/lib/sourcemaps.js#L83) adds an extra `../` to the front, which causes both the attempted file read and the `contentsBySource` lookup to fail. Here's an example debugging session:

<img width="1680" alt="screen shot 2015-12-12 at 8 58 57 pm" src="https://cloud.githubusercontent.com/assets/4604619/11764939/2fd2e96e-a113-11e5-969d-f63f31d00505.png">

Any reason the paths need to be normalized here? As far as I can see the solution is just to remove the normalization, but I'm not sure of what other implications that might have.

**Comment by guybedford** [comment]
Thanks so much for the explanation and test case. I've fixed this in https://github.com/systemjs/builder/commit/fdfa6a4300df576bf8879b68b763ba328dbd689a.

**Comment by sgwatgit** [comment]
@guybedford just ran into this issue. My `src/app` bundle files get their contentSource correctly in the .js.map file but my `jspm_packages/` bundle files have null for all the content.

I tried patching in your fix into my builder code and it worked perfectly.

Thanks!

**Comment by guybedford** [comment]
Released in 0.14.12.
