### ISSUE TITLE
Bundling js in Application A depends on Application B

### ISSUE THREAD

**Issue by tom10271** [systemjs/builder#428]
Assuming I have 2 Applications: App A and B while A depends on B

```
/src
|_ /app_a
   |_/jspm_packages
   |_config.js
|_ /app_b
   |_/jspm_packages
   |_config.js
```

jQuery has installed in App B, and App A will use it too. Yet I don't want to install one more copy in App A. How should I configure and build scripts?

I have no idea how should I set config in App A so that it knows the path of jQuery installed and and use map set in App B's config.js

**Comment by guybedford** [comment]
If you want app A and app B to share code you would need them to share the same jspm_packages, perhaps with a folder structure like:

src
  app_a
  app_b
jspm_packages
config.js

If that really isn't appropriate you can also consider linking workflows, although these aren't as nice to work with pending jspm 0.17.

**Comment by tom10271** [comment]
Thank you for your reply, may have a bit more about linking workflow? Or do you mean I need to hardcode urls?

**Comment by guybedford** [comment]
Sure, see https://github.com/jspm/jspm-cli/blob/master/docs/linking.md.

**Comment by tom10271** [comment]
Thank you for your helpful reply. I really appreciate it.
