### ISSUE TITLE
Non-exported modules visible in bundle

### ISSUE THREAD

**Issue by jamiewinder** [systemjs/builder#429]
I'm not sure if I'm missing something here, or if this is the expected behavior. If I've got two files:

*internal.js*
```javascript
export const value = 123;
```
*external.js*
```javascript
import { value } from './internal';
export function run() {
    alert(value);
}
```
If I use builder to bundle external.js, I end up with the following result (trimmed):
```javascript
System.register("internal.js", [], ...);
System.register('external.js', ['internal.js'], ...);
```
In other words, two public modules are registered - 'internal' and 'external'. Given the nature of the source code, and the fact that 'external.js' was specified as the source, I'd have expected the internal.js module to be hidden. As it stands, a consumer of the bundle would be able to import either when I'd intended only the exports of 'external.js' to be available. 

Is this intended, or am I doing something wrong?

**Comment by guybedford** [comment]
Yes by default all modules are public in SystemJS.

I'd advise rather using a project like Rollup (http://rollupjs.org) to handle these kinds of internal optimizations, then move to SystemJS builder to handle the public tree builds. We're working on integration of Rollup for these kinds of optimizations, but these workflows are not yet ready in SystemJS Builder.

**Comment by jamiewinder** [comment]
Thanks Guy, I'll take a look at Rollup - first I've heard of it, looks promising!
