### ISSUE TITLE
builder.loadConfig must configure plugin loader as well

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#43]
In https://github.com/systemjs/builder/blob/master/index.js#L167, it is just configuring `builder.loader`, when `builder.pluginLoader` must also be called with the same configuration.

From https://github.com/systemjs/builder/issues/42.

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/builder/commit/93566a733ad55d144cb8579005dab2634ffdeba7.

**Comment by martinmicunda** [comment]
@guybedford I tried test your fix and it kind of work however after your fix I am not able to overwrite `loader.baseURL` in my `gulpfile`. We have been discussing the reason to overwrite `baseUrl` in issue #23 see this [comment](https://github.com/systemjs/builder/issues/23#issuecomment-63499034). Thanks

**Comment by guybedford** [comment]
@martinmicunda I've updated the documentation in https://github.com/systemjs/builder#setting-configuration. You can use a `builder.config` call here.

**Comment by martinmicunda** [comment]
It's working great for me .. thanks

**Comment by guybedford** [comment]
Excellent, thanks for letting me know.
