### ISSUE TITLE
Using a separate build pipeline

### ISSUE THREAD

**Issue by ghempton** [systemjs/builder#430]
Am I correct in understanding that this project relies on doing the transpiliation itself? We currently have a project that uses broccoli to do transpilation, concatenation, etc. and I am exploring ways of breaking the project up into separate bundles.

There is a point in our build process where we have a long list of separate files containing `System.register` calls. Right now we just do a dumb concatenation of them all, but ideally we would build them into some pre-defined set of bundles that are loaded separately when needed. Is it possible for builder to read the `System.register` calls?

Even better might be to have each module be a separate file and rely on http2 to make up the difference. Is it within the scope of this project to pre-compute dependency trees so they can all be downloaded in parallel?

**Comment by guybedford** [comment]
SystemJS and SystemJS builder will detect, run and build anonymous `System.register` modules just like any other module as a separate file.

As soon as they are named `System.register("moduleName", ... ` defines then it is no longer supported to build them.

Building up a dependency tree from the anonymous System.register modules and then chunking those with arithmetic would be completely supported though.

HTTP/2 workflows with separate files aren't showing great numbers unfortunately, so it's advisable to bundle until these workflows can be better optimized through prioritised sending mechanisms.
