### ISSUE TITLE
How to ingore dependency

### ISSUE THREAD

**Issue by SebastianStehle** [systemjs/builder#434]
Hi, I try to bundle my angular2 application via builder.buildStatic. I also have to include reflect.js which has the following dependency.

       var nodeCrypto = isNode && require("crypto");

Obviously the builder does not detect the "isNode" variable and tries to integrate the dependency into my bundle. How can I tell them to ignore it?

I tried the following options:

         defaultJSExtensions: true,
          meta: {
              'crypto': {
                  build: false
              }
          }

But I always get the message: Global SFX bundle dependency "crypto.js" must be configured to an environment global via the globalDeps option.

**Comment by guybedford** [comment]
You can use map config to set crypto to undefined for that specific parent package:

```javascript
builder.config({
  packages: {
    'path/to/package-folder-using-crypto': {
      map: { crypto: '@empty' }
    }
  }
});
```

Alternatively you can provide that map config on install of the package in jspm.

**Comment by SebastianStehle** [comment]
Thank you for your fast response. Is it also possible to make the builder stop and predefined dependencies. I want to use the prebuild angular2 packages and I want to have one file with my custom code. 

I think my scenario is the same like the following issue and I thought it is already released: https://github.com/systemjs/builder/issues/407

I tried:

             meta: {
              'angular2/*': {
                  build: false
              }
          }

**Comment by guybedford** [comment]
Did you manage to sort out your issue here?

**Comment by joerideg** [comment]
hi @guybedford I have a similar issue. I'm also trying to build angular2 but in fact instead of building everything with the systemjs builder I include the systemjs-register-only js file in index.html, then include the angular.js file which is already transpiled to System.register format, and then want to include my own code. My own code is something like import { Component } from 'angular2/core', do something with Component. I currently have the following in my systemjs config: 
```javascript
System.config({
  defaultJSExtensions: true,
  transpiler: 'babel',
  babelOptions: {
    optional: ['es7.decorators']
  },
  meta: {
    'angular2/*': {
      build: false
    }
  }
});
```
And I'm getting the same error: "Global SFX bundle dependency "angular2/core.js" must be configured to an environment global via the globalDeps option."
It would be ideal if I can just completely ignore angular2/* imports with just adding build:false.
Is there something I can add to make this work right now? Having a bit larger example for [globalDefs](https://github.com/systemjs/builder#minification-options) would already help.

**Comment by SebastianStehle** [comment]
@guybedford Yes, it is working fine now, but I use the same approach like joerideg. I only build my custom code and use the existing angular2 bundles.

@joerideg Had the same issues. The problem is that all references are resolved with the ".js" extension. The following approach works for me:

	var config = {
		baseURL: scripts,
		packages: {
			'app': {
				defaultExtension: 'js'
			}
		},
		meta: {
			'angular2/*': {
				build: false
			},
			'rxjs/*': {
				build: false
			}
		}
	};

All my typescript files are in the "app" folder.

**Comment by joerideg** [comment]
hmm I hoped that would do it. I do use babel, not typescript but still.

Currently the builder code im using is this:
```javascript
        var systemjs = new Builder();
        systemjs.config({
          transpiler: 'babel',
          babelOptions: {
            optional: ['es7.decorators']
          },
          meta: {
            'angular2/*': {
              build: false
            },
            'rxjs/*': {
              build: false
            }
          }
        });
        return systemjs.buildStatic(cfg.src.indexScript, cfg.dist.indexScript, {
          sourceMaps: true
        });
```
unfortunately that still ends in the aformentioned error.

**Comment by guybedford** [comment]
You need to provide `globalDeps` when doing a static global build so it knows which modules correspond to which global names:

```javascript
systemjs.buildStatic(cfg.src.indexScript, cfg.dist.indexScript, {
          globalDeps: { 'angular2/core.js': 'angular', 'rxjs/main.js': 'rx-global-name-on-window' }
          sourceMaps: true
        });
```

**Comment by joerideg** [comment]
hmm ok. I kinda understand globalDeps now, thing is that angular2/core is not really a global dependency. It does not set anything on the window, its a System.register('angular2/core') module. I tried your example and actually it now works for angualr2/core. Unfortunately it then simply errors on the next angular2/somemodule import. So I tried star patterns:
```js
globalDeps: {
    'angular2/*': 'angular2/*'
}
```
Star patterns don't seem to work, so it would require me to list every single module im importing from angular2 anywhere in my code in the globalDeps :( 

Btw, in another branch of my build system Im now simply transpiling my own code with gulp-babel first and then doing a System.import of my own code's main module. Which works! It would be nice to ignore external module libraries with just build:false without listing every single one of the modules of the module library in the globalDeps.

**Comment by guybedford** [comment]
A static build means building a module. Any module.must have its
dependencies explicitly declared.

Perhaps you just want a normal bundle which will support easy arbitrary
exclusions as each individual module is registered into the main registry.

**Comment by joerideg** [comment]
Ah right. Yes if I do .bundle and not .buildStatic it does transpile without having to declare all the globalDeps. Awesome. I guess I then just have to manually System.import the main module to execute the app. Thanks for your help and keep up the great work, cant wait untill you have your babel6 plugin ready.

**Comment by robwormald** [comment]
@SebastianStehle our (ng team) current recommendation is to not import zone and reflect (well, reflect is OK, but...) as imports but to use them in `script` tag imports. which I agree is a bit annoying. We provide both of them in a file called `angular2-polyfills` in the `bundles` dir of the npm distro.

@guybedford i'd mentioned this to you before, but forgot to follow up - one feature that might be useful in the builder would be a 'prepend/append' option - for sticking licenses / polyfills etc into a bundle in front of actual bundled code (and respecting sourcemaps). 

I'll see about adding the above configs to the registry as well.

**Comment by guybedford** [comment]
Thanks @robwormald for the update here! Just et me know if there is anything further I can do to help with any of these configurations.
