### ISSUE TITLE
Regression: 0.14.12 Builder in loadConfigSync require is no longer defined or shimmed?

### ISSUE THREAD

**Issue by typhonrt** [systemjs/builder#436]
Greets Guy et al...

I've been updating several of my demo repos and noticed a regression or at least a change that I could not see in any of the code commits tracked in the release notes between JSPM 0.16.15 and 0.16.16. when creating SFX bundles. Example of including extra config loading below:

```
  var builder = new jspm.Builder('./config.js');
  builder.loadConfigSync(extraConfig);
```

Previously when loading that `extraConfig` file which has a `System.config({})` in addition to usage of `require` to load a NPM module before the `System.config` block there was a likely shimmed `require` function available. Print out of the function in 0.16.15 is this:

```
function require(path) {
  return self.require(path);
}
```

It's no longer available in 0.16.16+ when invoking `loadConfigSync`. I assume this associated with SystemJS Builder `0.14.11` -> `0.14.12`. I just couldn't find a change that would remove this functionality. Do you have any insight on this change?

Here is the `extraConfig` file being loaded by loadConfigSync which fails now:
https://github.com/typhonjs-demos/backbone-parse-es6-todos/blob/master/config/config-app-paths.js#L9

**Comment by fictitious** [comment]
It should be accessible as `global.require`

This is the commit I suppose https://github.com/systemjs/builder/commit/f436a92a5e5ebba6326cc64b07026086adb01ab2

**Comment by typhonrt** [comment]
Yeah.. `global.require` was the first thing I tried too. That commit does look like a good culprit. Hmm.. I suppose Guy will chime in at some point. It is handy having access to require on the server to pull in utility code that aids in parsing the current environment:
https://www.npmjs.com/package/typhonjs-config-jspm-parse

**Comment by typhonrt** [comment]
Thanks for taking a look and posting a PR @fictitious. Cheers!
