### ISSUE TITLE
Builder as a class

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#44]
We should change builder itself to be a class that is created with config, so that we don't pollute the global build environment.

**Comment by crisptrutski** [comment]
@guybedford how do suggest we isolate the `System.config` calls being eval'd  by `loadConfig`?

Will System also need to exposes class instances?

**Comment by crisptrutski** [comment]
Nevermind, see your trick just above.

**Comment by guybedford** [comment]
Suggested API ideas:

```javascript
  var Builder = require('builder');
  var builder = new Builder('./cfg' / {cfg});
  builder.config();
  builder.buildTree();
  builder.build();
  // .. etc ..
```

**Comment by guybedford** [comment]
@crisptrutski ^

**Comment by crisptrutski** [comment]
@guybedford let's merge + bump?
