### ISSUE TITLE
Internal error trying to parse:  var 0= $__require("15");

### ISSUE THREAD

**Issue by sberney** [systemjs/builder#441]
Ok, I didn't expect this to work, but my first pass at getting my project built (hopefully the customizations I've made don't cause too many problems here) is going pretty badly:

```javascript
var path = require('path');
var Builder = require('systemjs-builder');
var builder = new Builder('/', 'jspm.config.js');

builder
//.buildStatic('js/**/*', 'bazout.js', {   // same thing, but produces error with "28" instead of "15"
.buildStatic('js/*', 'bazout.js', {
  sourceMaps: true,         // just garbage because of the error
  lowResSourceMaps: false,  // what is this supposed to do?
  format: 'amd',
  minify: false,
  mangle: false
  })
.then(function () {
  console.log('Build complete.');
})
.catch(function (err) {
  console.log('Build error:');
  console.log(err);
});
```

```console
PS D:\workspace\Content> node .\systemjs-builder-test.js
Build error:
[Error: Internal error trying to parse:

var 0= $__require("15");
    var global = this, __define = global.define;
    global.define = undefined;

null:1:5: Unexpected token 0]
```

Not sure what to make of that. Anyway, in the meantime I'm going to attempt to take a more piecewise approach. Ah, worth noting, grep -R "var 0=" * produces no results.

##### Update:
Sweet! Some stuff builds, eg
```javascript
.buildStatic('js/modules/*', 'bazout.js', {
```

But I'm still perplexed by that error message.

##### Update:
I've traced down this to a file (the rest of it builds now) I created to work around [global namespace pollution](https://github.com/systemjs/systemjs/issues/942#issuecomment-161720668) ([this](https://github.com/systemjs/systemjs/issues/960) was your proposal to hopefully eliminate the need for this):

```javascript
var SmogHighcharts = require('highcharts-lib');

delete window.Highcharts && delete window.HighchartsAdapter;

getOwnPropertyNames(SmogHighcharts).forEach(function (key) {
  module.exports[key] = SmogHighcharts[key];
});
```

trying to sfxify a minorly more verbose version of that file:
```javascript
.buildStatic('js/highcharts-stub.js', 'bazout.js', {
```

```javascript
PS D:\workspace\Content> node .\systemjs-builder-test.js
Build error:
[Error: Internal error trying to parse:

var 0= $__require("3");
    var global = this, __define = global.define;
    global.define = undefined;

null:1:5: Unexpected token 0]
```

I feel like the error message could be a little more helpful...

##### Update:
Well, obviously I'm trying to run this in node, so I changed the stub to exactly

```javascript
var SmogHighcharts = require('highcharts-lib');

var global_ = window || global;
delete global_.Highcharts && delete global_.HighchartsAdapter;

getOwnPropertyNames(SmogHighcharts).forEach(function (key) {
  module.exports[key] = SmogHighcharts[key];
});
```

But I get exactly the same error. My node-fu isn't what it could be at the moment, so not sure if there's something different I should be doing. Anyway, still doesn't work.

##### Update:
The offending line appears to be
```javascript
var SmogHighcharts = require('highcharts-lib');
```

I can leave the rest of the file intact if I stub out SmogHighcharts. Or exclude it from the build. But, I would prefer not to exclude it from the build.

**Comment by Bnaya** [comment]
I believe it's related to this line:
https://github.com/systemjs/builder/blob/master/compilers/cjs.js#L136
The builder using is using 
```
0
```
As variable name. I don't know if its a bug or edge case.

How can i repro this?

**Comment by guybedford** [comment]
Thanks, yes this is a bug in that globals handling. We need to validate the variable names.

**Comment by guybedford** [comment]
Actually this isn't a bug.

@sberney it sounds like you've just set `System.config({ meta: { 'some-module': { globals: ['x'] } })`, where globals as an array value is not supported.

**Comment by sberney** [comment]
Thanks, I'll look into it. Preliminary recreation attempts failed, but I've
been busy myself. Error message still very much unintuitive.
