### ISSUE TITLE
Using a CDN hosted module instead of downloading it

### ISSUE THREAD

**Issue by delux75** [systemjs/builder#445]
I'm using a CDN hosted module of jQuery like this:
```javascript
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    [...]
    "jquery": "https://code.jquery.com/jquery-1.11.3.min.js",
    [...]
});

```

And I have several questions about it: 
1- Is it a good idea to used a CDN hosted module instead of downloading it from Github / npm?
2- If yes, what is the workflow for production, because so far I have an error when I want to export my code?

**Comment by gcnm-pgeil** [comment]
1) This depends on what you want to accomplish and whether you want to ship a static bundle file containing all your code (thus not having to load external dependencies during runtime).
2) I wated to do the same and the only way that worked for me was: Building a default bundle (non-static) and having the module 'jquery' being excluded. Therefore your must configure your Builder instance like this:

```
builder.config({
  paths: {
    jquery: 'jquery'
  },
  meta: {
    jquery: { build: false }
  }
});
```
and then define a custom module path for your SystemJS loader instance used during runtime like this: 

```
System.config({
  paths: {
    jquery: 'http://code.jquery.com/jquery-2.1.4.min.js',
  }
})
```

**Comment by delux75** [comment]
Okay, I'll try this. Thank you for your help @gcnm-pgeil :+1:

**Comment by guybedford** [comment]
Thanks @gcnm-pgeil for the suggested workflow here. In the 0.15 builder, the build: false part will no longer be necessary here.
