### ISSUE TITLE
Globbing and extensions

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#447]
When doing glob arithmetic, we need to skip any default extension adding. From https://github.com/jspm/jspm-cli/issues/1204.

**Comment by frankwallis** [comment]
Just to note that this should also include the ```!plugin``` extension as that causes mismatches even when using normal js extensions (see frankwallis/plugin-typescript#79).

repro [here](https://github.com/frankwallis/jspm-ts-bundle)
