### ISSUE TITLE
Every other build w/ Babel breaks

### ISSUE THREAD

**Issue by tjclement** [systemjs/builder#448]
When using jspm-dev-builder to enable partial rebuilds of an app, having configured jspm to transpile with Babel, every other built bundle seems to contain non-canonicalized dependencies in the file that was changed. Performing another partial build, again first invalidating that same file, corrects the issue, but the bundle after that breaks it again etc. 

This is what the bundle looks like, correct on the left and broken on the right:
![](http://i.imgur.com/6m6mfkZ.png)

A repro test can be found here https://gist.github.com/tjclement/7d6e606b2ba4411ced51

The cause of this issue is that the esm compiler uses the globally defined Babel instance's options [here](https://github.com/systemjs/builder/blob/master/compilers/esm.js#L245), and adds its own resolveModuleSource method to that options variable (still referenced, not copied) [here](https://github.com/systemjs/builder/blob/master/compilers/esm.js#L266).

The next time babel.transform is called for determining the module dependencies [here](https://github.com/systemjs/builder/blob/master/lib/trace.js#L368), it uses the resolveModuleSource method to normalize the dependencies, where it shouldn't do that here since we want to extract the raw dependencies and normalize them ourselves [here](https://github.com/systemjs/builder/blob/master/lib/trace.js#L404).

The fix is to clone the Babel options in esm.js instead of referencing them [on this line](https://github.com/systemjs/builder/blob/master/compilers/esm.js#L245), so the resolveModuleSource option doesn't stick around globally.

**Comment by guybedford** [comment]
Thanks again for the clear breakdown here. I've included the correction you suggested pending the next release.

**Comment by tjclement** [comment]
Thank you for the help and fast response!

**Comment by guybedford** [comment]
Released in 0.15.0.
