### ISSUE TITLE
buildStatic and AMD Async requires

### ISSUE THREAD

**Issue by amenadiel** [systemjs/builder#449]
I have a module that I'm bundling as an AMD standalone script with `builder.buildStatic`.

This module has its dependencies in the `define` section, but it also has factory methods that use RequireJS async requires as it's mentioned in [systemjs/systemjs#404](https://github.com/systemjs/systemjs/issues/404).

The code looks like this:

```js
define(['depA','depB'], function(fnA, fnB) {
  var myModule=function();

  myModule.thingFactory=function(attrs, callback) {
    require(['depC'], function(fnC) {
      callback( new fnC(attrs));
    });
  };

  return myModule;
});

```

I know that these kind of requires are not included as dependencies, so I'm bundling arithmetic using `'myModule.js + depC.js'` as source expression.

Now, if I use `bundle` the resulting file has a named `define`  for `depA`, `depB` and `depC`, which is good. For example, depC is defined as:

```js
(function() {
  var _removeDefine = System.get("@@amd-helpers").createDefine();
  define("depC",[...],function(...) { ... });
  _removeDefine();
})();
```

So when I call the factory and `require(['depC'],fn())` happens, it has already a definition of depC in memory, to avoid requesting depC from the filesystem.

However, this script will also be used with RequireJS, so I can't rely on `System.get` usage.

If I use `buildStatic` the resulting file doesn't need to be run in a SystemJS enabled environment, but  it mangles the dependencies names:

```js
(function() {
  var _removeDefine = $__System.get("@@amd-helpers").createDefine();
  define("2", [...],function(...) { ... });
  _removeDefine();
})();
```

But the require call in the factory is still asking for 'depC', and will request it from the filesystem since it doesn't know that it should have required `2`. 

So... is there a way to avoid buildStatic renaming dependencies, or a way to have the dependencies rewritten inside async requires as well? I've tried with named and anonymous modules, and it's the same.

**Comment by guybedford** [comment]
This is the way static builds are designed to work. They don't share their registry at all, so it's just as if you wrote a large global script with a dynamic require in the middle.

**Comment by amenadiel** [comment]
I get it, and of course it makes sense. However, since nested/async dependencies are not inlined, their manual inclusion should preserve an identifiable name. 

Since they get renamed as numbers or single characters, any remaining runtime require call won't be able to find the resource.

**Comment by guybedford** [comment]
The point is that `depC` in the static bundle does not exist any more as an individual module - it has been statically compiled. Normal bundles are the only way to preserve the record that there ever was a `depC` in the bundle itself.

**Comment by amenadiel** [comment]
That would be fine if dynamic requires or imports were rewritten to the compiled dependency name. Either way it should make the same name replacement, don't you think?

**Comment by guybedford** [comment]
So do you think `depC` should be contextually normalized in place as part of the static build?

**Comment by amenadiel** [comment]
Well, I guess it's not that straightforward. The compiler would need to know if the required modules are defined for the current module (or the current context if it makes more sense).

From my early experiments, the normalization for `depC` would be available in `cache.encodings`, but I don't fully understand if at that point it is already too late to perform meaningful replacements for nested requires.



,

**Comment by guybedford** [comment]
@amenadiel so are you saying `depC` in your case is already contained in the static bundle?

**Comment by amenadiel** [comment]
Yes. I'm calling

```
builder.buildStatic('myModule.js + depC.js', 'myModuleBundle.js').then(...)
```

But the bundled depC gets renamed when I build.

**Comment by guybedford** [comment]
Ok, I do think to deal with dynamic requires properly in static builds we should trace and normalize those dynamic requires as a natural part of the tree. I've created a feature task for this at https://github.com/systemjs/builder/issues/452.

Then once we've got that in place, it would be easy to see that the dynamic require is made to something already in the bundle itself and replace it with the right stub.

That said, I'm not sure if this is something that should be supported actually. Dynamic requires are as described, dynamic. They resolve in the target environment. Just because you have a `require(['depC'])` in your bundle, doesn't mean you can't map `depC` to something else in production.

So I'm actually tempted to say this is a wontfix after all.

**Comment by amenadiel** [comment]
You're right... If a sfx bundle can't register modules into the global loader, then you can't get a grab of those  internal modules through an async require.

As a matter of fact, RequireJS has given me a lot of headaches because bundles pollute the global requirejs instance, and stubbed loaders in them override your defined loader plugins. 

In the light of the tradeoff, I'd rather keep things as they are instead of opening the door to define nightmares.

**Comment by guybedford** [comment]
Sure, I'll close this to track the other feature, although that isn't being prioritised currently.
