### ISSUE TITLE
Module module not declared as a dependency

### ISSUE THREAD

**Issue by victorwpbastos** [systemjs/builder#45]
I have a plugin to `precompile` Ractive components:

```js
var Load = require('ractive-load');
var Ractive = require('ractive');

exports.translate = function(load) {
	load.source = 'module.exports = ' + JSON.stringify(load.source);
	return Load(load.address).then(function(c) {
		Ractive.components['ract-teste'] = c;
	});
}
```
In browser all is working but when I try to bundle i get:
![captura de tela de 2015-01-14 03 43 37](https://cloud.githubusercontent.com/assets/1017515/5734602/8b435bbe-9b9f-11e4-9889-2692f0666d7e.png)

I installed both `ractive` and `ractive-load` from npm (`npm:ractive` and `npm:ractive-load`). When I try to use `github:ractivejs/ractive-load` i get:
![captura de tela de 2015-01-14 03 42 24](https://cloud.githubusercontent.com/assets/1017515/5734594/63e37b6c-9b9f-11e4-91da-1254c8dd760a.png)

**Comment by guybedford** [comment]
This error is specifically that the file `ractive-load.js` has a require to `require('module')`, which is not executing correctly in Node. I've created an issue for that in jspm here - https://github.com/jspm/npm/issues/39.

**Comment by whitecolor** [comment]
npm package image-size contains the code
```javascript
var libpath = process.env.TEST_COV ? '../lib-cov/' : '../lib/';
  var detector = require(libpath + 'detector');
```
so it causes an error while build
`Module ../lib/detector not declared as a dependency.`

**Comment by guybedford** [comment]
Yes we can only load CommonJS modules that are "statically analyzable" in SystemJS. This is because require is not synchronous.

**Comment by whitecolor** [comment]
Is there way to work this around? This is need for build less files with builder (nmp:less requires this module `image-size`).

**Comment by guybedford** [comment]
@whitecolor yes. I'd probably want to send a PR to https://github.com/netroy/image-size/blob/master/lib/index.js to make it use static requires. In the mean time you could fork the repo perhaps.

**Comment by whitecolor** [comment]
@guybedford isn't there a way to define such "hidden" dependencies via config?

**Comment by guybedford** [comment]
I've posted at https://github.com/jspm/registry/issues/221.
