### ISSUE TITLE
Error : Unable to calculate canonical name to bundle file...

### ISSUE THREAD

**Issue by kktos** [systemjs/builder#451]
Hi there,

I saw this question was quite often asked but I didn't find a answer I was able to understand :/ Sorry about that.

So here is my config:
In the project folder, I have some subfolders like:

```bash
./web -- which is the doc_root for the http server
./docs -- documents related to the project
./server -- the server part
```
and last but not least
```bash
./build -- which is where we put all our build scripts
```
Let's focus on that one.*
So we have
```bash
./build/server -- for the building scripts of the server part
./build/client -- same but client
```

This is in this last one that I did my jspm install and init.
So to test the process, I've created a ./web/app.main.js and I tried to build it with a
jspm bundle app/main build.js

I've added in the config.js in the map object this:
```JSON
  baseURL: "/",
  map: {
    "app":"../../web/app",
```
in order for the process to find the app/main.js

And I got:
```bash
Error: Unable to calculate canonical name to bundle file:///project/web/app/main.js
```

Is there a way to change the config to make it works ? (And no, I cannot change the hierarchy of the project)

Thanks for your help

**Comment by guybedford** [comment]
To fix this error, you just need to ensure the `file:///project/web/app/main.js` path is lower than the baseURL. Try setting the baseURL for the build to say `/project/web`.

**Comment by guybedford** [comment]
Just let me know if you need further help here.
