### ISSUE TITLE
[0.15.0] Unexpected token when bundling Angular2

### ISSUE THREAD

**Issue by antonybudianto** [systemjs/builder#453]
Hi, I just updated to builder `0.15.0` and systemjs `0.19.14`, I got the following error when bundling my app: (same error when no minification)
<img width="1279" alt="screen shot 2016-01-10 at 6 20 59 am" src="https://cloud.githubusercontent.com/assets/7658554/12219037/41860602-b764-11e5-9cae-06f102638ea0.png">

My config:
```javascript
var systemjsBuild = {
        map: {
            'angular2': 'node_modules/angular2',
            'rxjs': 'node_modules/rxjs'
        },
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
    };
```

in index.html script tag
```
System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
      });
      System.import('app/boot')
            .then(null, console.error.bind(console));
```

the previous version of builder **worked** for me `0.14.x`
Angular2 version: 2.0.0-beta1
Thank you.

**Comment by guybedford** [comment]
@antonybudianto thanks so much for sharing. Is there any way you can provide a replication test case here at all? That would help a lot to be able to investigate the issue.

**Comment by antonybudianto** [comment]
@guybedford , you can clone my [repo](https://github.com/antonybudianto/angular2-starter) and checkout to `repro-mangle-error`, and update `systemjs-builder` in `package.json` to `0.15.0`
and run `gulp serve-build`

**Comment by guybedford** [comment]
@antonybudianto this is the breaking change of the 0.15 upgrade, which I should have properly documented. I updated the release notes in https://github.com/systemjs/builder/releases/tag/0.15.0. All you need to do is add a `normalize: true` to the bundle command.

**Comment by antonybudianto** [comment]
@guybedford , Thank you so much, now it worked :+1:

**Comment by antonybudianto** [comment]
@guybedford , By changing `map` to `path`, it worked without `normalize: true`
