### ISSUE TITLE
lowResSourceMaps - what does it do?

### ISSUE THREAD

**Issue by olsonpm** [systemjs/builder#454]
> Compile time with source maps can also be improved with the lowResSourceMaps option

I found nothing in the commits nor the code.  I then clone traceur -> become confused as to why this project relies on both traceur and babel -> sustain my confusion as to what lowResSourceMaps does because traceur doesn't explain either.

Please document what lowResSourceMaps does, which in turn should explain how it improves source map compile time

**Comment by guybedford** [comment]
Low res source maps generates lower resolution source maps in Traceur which is faster than the full high resolution source maps it generates by default. I've added a note about this to the API documentation task at https://github.com/systemjs/builder/issues/250#issuecomment-152299085.

**Comment by olsonpm** [comment]
Low Resolution needs to be explained.  Traceur nor its dependency 'mozilla/source-map' explains it.  I guess I'll play around with it tonight and get back with my results.
