### ISSUE TITLE
bundle-sfx still only support addition and wildcard arithmetic?

### ISSUE THREAD

**Issue by larryhe** [systemjs/builder#458]
Hi guys, 
we are trying to migrate our RequireJS code base to SystemJS and SystemBuilder. But I noticed that SFX bundles can only use addition and wildcard arithmetic in this documentation. Any specific reason behind this? we have a few separate bundles (e.g. commonA.js, moduleB.js  where moduleB may reference some of commonA dependencies.), with bundle, we do builder.bundle('commonA.js' 'A.js');  builder.bundle('commonB.js - commonA.js' 'B.js'); can we do same thing to sfx? if not, any workaround? Looks like we could use builder Direct Trace API to do it? Looking forward to your reply. Thanks.

**Comment by guybedford** [comment]
@larryhe sfx bundles actually do fully support exclusion how. I've removed the note, thanks for asking about this.
