### ISSUE TITLE
Auto-include runtime for bundle sfx

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#46]
There should be an option for bundle sfx, that detects if Traceur or Babel runtime is needed in the generated output, and automatically includes it if the bundle if so.

**Comment by guybedford** [comment]
It could be useful to add an option to include promise polyfill as well.

**Comment by guybedford** [comment]
This can also be supported for 6to5 now.

**Comment by hgl** [comment]
In additional to es6 polyfill, my project also use other polyfills like DOM, requestAnimationFrame, etc. I wonder what's the best way to bundle these?

Could systemjs (or jspm) offer some way to bundle global scripts (i.e., `this` refers to the global object in the script)?

Giving es6 polyfill a special treatment here is not a perfect solution IMHO.

**Comment by guybedford** [comment]
Yes jspm does bundle global scripts through this builder. I'd suggest having other polyfills like that being included as dependencies. The ES6 layer only is the builder concern.

**Comment by hgl** [comment]
Hope it's ok to ask here (couldn't find the answer in systemjs/jspm's Production Workflows wiki) , how do I ask jspm to include global scripts as dependencies? I installed the polyfill via `jspm install <name>` and `<name>` is in the `dependencies` entry in `package.json`. The `build.js` file generated by `jspm bundle` doesn't seem to contain the polyfill package I installed.

If you are saying I should Import it from the bundle entry point, that makes the polyfill become a module and nukes the `this` value.

I believe I missed something here, would be grateful if you could enlighten me.

**Comment by hgl** [comment]
Or you are saying I should just simply include them with `<script>`?

**Comment by hgl** [comment]
I give it some another thoughts.

For some code to be executed as a global script, I think it should satisfy at least two conditions:

- `this` in the top level refers to the global object.
- Variable declarations in the top level add properties to the global object.

So to include this code as a global script with the regular unbundled or bundled approach, author should simply include it via a `<script>` element.

For `bundle sfx`, this code should simply be concatenated to the bundled file. It should live in the top level and not to be wrapped in an IIFE, and then the bundled file should be include via a `<script>` element. The only thing here is `bundle sfx` should reference these concatenated code in the source map.

So it looks like in additional to an entry point, `bundle sfx` should also allow authors to specify a list of files to be concatenated (either before or after the entry point), and generate the correct source map.

Do you think it's the right approach?

**Comment by guybedford** [comment]
@hgl SystemJS supports loading global scripts as global scripts with `this` and variables treated correctly. SystemJS builder has code to carefully bundle global scripts as well managing the same scope treatment.

All you need to do is ensure your module is loaded **as a global**. Read https://github.com/systemjs/systemjs/wiki/Module-Format-Support for some background.

The simple way is to add `"format global";` to the top of the source file in question.

**Comment by hgl** [comment]
Somehow I missed the module format wiki. Will go through the whole wiki some time.

Didn't know it's already supported. Thanks for the explanation.

**Comment by guybedford** [comment]
The obvious thing to do here is just always to include the helper / runtime module. Babel does provide an output variable to read on the compiler, and the output reduction pipeline could process this. But the first step of just inlining the actual `babel-helpers.js` or `traceur-runtime.js` (as a named global module called `@babel-helpers` or `@traceur-runtime`) is the way to go here.

**Comment by hgl** [comment]
Possible to add an option to opt out auto-inclusion?  When using bundle sfx multiple times to generate multiple files,  would like to share the helpers/runtime.

**Comment by guybedford** [comment]
Sure I've added https://github.com/systemjs/builder/commit/4862dde333ab6defc2d9bce4dad131fc423ec3a5.

**Comment by hgl** [comment]
:+1:
