### ISSUE TITLE
the build example in this documentation is not working

### ISSUE THREAD

**Issue by larryhe** [systemjs/builder#463]
Hi guys, 
I am following example exactly in this documentation,  but got below build error. any suggestions? Thanks for your time. By the way, it works fine when I do jspm bundle-sfx. below is my config.js
```
Build error
[Error: ENOENT, open 'demo2/babel-runtime/helpers/interop-require-default.js']
```
//config.js
```
System.config({
  baseURL: "./",
  defaultJSExtensions: true,
  transpiler: "babel",
  paths: {
      'babel': './node_modules/babel-core/index.js'
  }
});
```

**Comment by larryhe** [comment]
Also if I use JSPM to automatically generate config, it works fine. But it does not work with above simple config. Seems that JSPM does a lot of complicated stuffs behind the scene. because I don't want to use JSPM to manage the packages(We use bower here) and just want to use SystemJS and SystemBuilder. Is it easy to do it with JSPM?  Thanks for your time.

**Comment by guybedford** [comment]
Babel 6 is not supported by SystemJS. Rather use Babel 5 here.

**Comment by larryhe** [comment]
Hi @guybedford , thanks for your quick reply. npm install babel-core@5.8.34 fixes the my problem. You might need to update documentation. because latest babel does not work at all. Also do you have plan to upgrade babel. The babel that SystemJS builder and JSPM is using is quite old.  Thanks for your time.
