### ISSUE TITLE
Regression: static bundles generated with builder 0.9.14+ fail to call `factory()` (Must use `umd` now?)

### ISSUE THREAD

**Issue by typhonrt** [systemjs/builder#464]
While this may not be an issue / regression per se the change did provide a jolt as there was no documentation about the change that I found or other issues documenting it specifically. Previously in all of my demo repos I generated a static bundle for `amd` and able to have it load as a static bundle. 

Examining `sfx-amd.js`:
https://github.com/systemjs/builder/commits/master/templates/sfx-amd.js

One can see the removal of calling `factory()`. Previously the tail end of the amd static bundle was this:
```
(function(factory) {
  if (typeof define == 'function' && define.amd)
    define([], factory);
  else
    factory();
});
``` 

With the latest builder changes it is now this:
```
(function(factory) {
  define([], factory);
});
```

Interestingly enough though if you change the builder 0.9.14+ amd static bundle to use the older `else factory()` statement then things work fine. I'm just checking if this is a possible omission. 

It seems like the only way to generate a self-executing bundle is to now use `umd`. That is fine and glad to see a `umd` option now, but I found no documentation on this matter.

**Comment by guybedford** [comment]
Thanks, I've updated this in the release notes.
