### ISSUE TITLE
Question: Packaging to Single File App/Module

### ISSUE THREAD

**Issue by ToddThomson** [systemjs/builder#465]
I've been using AMD module bundles and require optimizer in a gulp build pipeline to produce a single app js file ( requirejs, the app bundle, plus any external minimized app dependent libs, in one package ).
I am investigating making a change to systemjs, but am not sure of how to proceed as there seems to be many options. Can I accomplish a single file production build js file by using systemjs builder? How is this accomplished using the gulp build pipeline?
I'm not looking for a detailed response - perhaps something to get me started in the right direction.
Thanks in advance!

**Comment by lookfirst** [comment]
Yes, you can build a single file with builder (that is the point of it actually).

Everyone has a different workflow. I use a combination of my gulp-helpers project and a bit of code in my gulpfile:

```
let bundler = (bundle) => {
	let builder = new Builder();
	return builder.buildStatic(`js/${bundle.name}/app`, `${path.war}/js/${bundle.name}/${bundle.name}-bundle.js`,
		{minify: bundle.minify, sourceMaps: false, ascii: true});
};
```

**Comment by ToddThomson** [comment]
Thanks. I am going to investigate using Builder as a dependency in my NPM Typescript compiler - TsProject. I have Typescript bundling and minifying, but producing a single file systemjs app package would be nice!

**Comment by ToddThomson** [comment]
@lookfirst After a quick look at the Builder code - I don't need to compile/transpile, or minify my Typescript project files - this is done in the Typescript build step within my gulp build pipeline. I really only want to have an additional step which takes the minified js bundle (from the Typescript compilation task), any dependent external ( already minified ) libs and the systemjs loader and outputs to a single js app file.

**Comment by lookfirst** [comment]
I'm not touching TS for a while (waiting for more stability in all the tooling around it) so I can't be of much use there. =(

**Comment by ToddThomson** [comment]
I will look at builder.bundle() when I have a bit more time. Thanks anyway.

**Comment by ToddThomson** [comment]
@lookfirst I looked at the source again this morning and buildStatic() is the answer. Thanks.
