### ISSUE TITLE
How to install optional modules?

### ISSUE THREAD

**Issue by delux75** [systemjs/builder#466]
I want to install the optional module validate (located in `/js/jquery.fileupload-validate.js`) and process (located in `/js/jquery.fileupload-process.js`) from the repository jQuery-File-Upload (repository: https://github.com/blueimp/jQuery-File-Upload).

How can I do it with JSPM? 

When I do `jspm install github:blueimp/jQuery-File-Upload` I only get the main module `/js/jquery.fileupload.js`.

**Comment by typhonrt** [comment]
There is a JSPM registry override for blueimp/jQuery-File-Upload which is restricting the installed files to just `jquery.fileupload.js`:
https://github.com/jspm/registry/blob/master/package-overrides/github/blueimp/jQuery-File-Upload%409.3.0.json

Provide a local override. You also need to load other jQuery resources. Here is what things look like in package.json w/ a local override. After adding this to your `package.json` run `jspm install`:
```
  "jspm": {
    "dependencies": {
      "jquery": "npm:jquery@2.2.0",
      "jquery-fileupload": "github:blueimp/jQuery-File-Upload@^9.11.2",
      "jquery-ui": "github:jquery/jquery-ui@^1.11.4",
      "text": "github:systemjs/plugin-text@^0.0.2",
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.34",
      "babel-runtime": "npm:babel-runtime@^5.8.34",
      "core-js": "npm:core-js@^1.2.6"
    },
    "overrides": {
      "github:blueimp/jQuery-File-Upload@9.11.2": {
        "main": "jquery.fileupload",
        "files": [
          "js/jquery.fileupload.js",
          "js/jquery.fileupload-process.js"
        ],
        "shim": {
          "js/jquery.fileupload": [
            "jquery"
          ],
          "js/jquery.fileupload-process": [
            "jquery"
          ]
        }
      }
    }
  },

```

I haven't of course tested things fully, but in your main.js or app loading point you then apparently need to do this:
```
import 'jquery-ui/ui/widget.js';
import 'jquery-fileupload';
import 'jquery-fileupload/js/jquery.fileupload-process.js';
```

Good luck...

**Comment by delux75** [comment]
Thanks @typhonrt! I'll try that ;)

P.S. : You are everywhere!

**Comment by typhonrt** [comment]
Glad to see you checking out JSPM / SystemJS.  Once you get a hang of it there is no going back.. ;)
