### ISSUE TITLE
Bundle all JSX in sub dirs?

### ISSUE THREAD

**Issue by NicholasGW** [systemjs/builder#468]
Wondering if this is related to #440  issue. I'm having and issue bundling all .jsx files in my project. For JS files, 'directory/\*\*/*' works as expected and gets all JS files, but skips JSX (even when the defaultExtension is configured correctly via packages).  
  
'directory/subdir/\*.jsx' works, but only bundles the jsx files in the subdir. 'directory/\*\*/\*.jsx' seems to do nothing.

Any ideas? I'm using the builder API in a node build script, not jspm bundle from the command line.

**Comment by NicholasGW** [comment]
I seem to have figured it out. If I have a subdir 'directory/components' where all my JSX is and has defaultExtensions configured in config, then to get all the JS in 'directory' as well as the JSX you must do the following:

'directory/**/* + directory/components/**/*' which I realize now probably makes sense. However, I was thinking originally that since /components/ would be included in directory/** that the jsx mapping would be applied there.

Cheers,

Nick

**Comment by guybedford** [comment]
@NicholasGW all your examples should have worked here actually. Are you definitely running the latest version of SystemJS Builder?

**Comment by NicholasGW** [comment]
Hey @guybedford , updated my examples with correct markdown :). I think these actually work now that I updated SystemJS Builder, but I will confirm for sure Monday at work.

**Comment by NicholasGW** [comment]
Hey @guybedford , so it seems to be working as expected but ONLY if the default extension is specified, which seems odd. Is this the expected behaviour? Example:

project/js ->JS Files
project/jsx -> JSX files
project/icons -> SVG

If I try and bundles project/**/* - project/icons/* it won't exclude the SVG unless I specifically put defaultExtension: .svg in my config.js. This seems like odd behaviour because I just want to exclude the entire directory regardless of extension (similar in tests where I have both js and jsx)...even if I do something like project/**/* - project/icons it still tries to bundle my SVG.
  
I should note that this project also uses mapping as it is located in different directories on the server vs client, i.e in my map config I have `project: 'my/real/path/project' which may be affecting things. Also I am bundling from multiple directories under the root, ie

module1/js
module2/js

and mappings module1: /real/path/1/module1, module2: real/path/module2 and then attempting to bundle module1/**/*  + module2/**/* - module1/icons - module2/icons

Thanks a lot for the help!

**Comment by guybedford** [comment]
@NicholasGW thanks for the follow up. I had a look at this use case again and added https://github.com/systemjs/builder/commit/478f38a34ee847176ba8f6912c76e34c1d6be4ef. Let me know if that helps.

**Comment by NicholasGW** [comment]
Hey @guybedford , seems to work awesome for local files, but I think it's stripping the extension from things in jspm_packages...when I update trace.js I get this when trying to bundle a small test project:

    jspm bundle "src/**/* - src/test/**/*"
         Building the bundle tree for src/**/* - src/test/**/*...
    
    err  Error on fetch for npm:react@0.14.6 at file:/ jspmtest/jspm_packages/npm/react@0.14.6
            Loading src/js/do.js
            Error: EISDIR: illegal operation on a directory, read
             at Error (native)`

**Comment by guybedford** [comment]
@NicholasGW thanks, that may be a dealbreaker then here unfortunately for that so I will revert it. I would advise upgrading to 0.17 if you can rather for better support as `defaultJSExtensions` is disabled there making the normalization system much more well-defined for these kinds of cases.

**Comment by NicholasGW** [comment]
Thanks @guybedford for the attempt! Appreciate all the work you put into this project. I'll see about upgrading :smile: Cheers!
