### ISSUE TITLE
Documentation; Cannot figure out configuration for simple packaging solution

### ISSUE THREAD

**Issue by OClement** [systemjs/builder#469]
Hi,
I created a StackOverflow question and wanted to bring your attention here; Unfortunately I would need a solution quite fast, hence the issue creation here. Apologies for breaking any unwritten rules by doing so!

I guess the issue at hand here is the documentation being unclear; I cannot figure out how I should configure the builder properly, no matter what I try;

Please refer to this [SO post](http://stackoverflow.com/questions/34817977/systemjs-builder-cannot-configure-properly-bundling-typescript-into-a-packag) for details

Any help is welcome!

**Comment by OClement** [comment]
No one can lend me a quick hand with this, or give me just some pointers?
Trying out my luck -> @guybedford  ?

 I know it's the weekend, sorry 'bout this! :/

**Comment by guybedford** [comment]
@OClement `defaultExtension` is a package configuration option only in SystemJS. So it must be specified via something like `builder.config({ packages: { './app': { defaultExtension: 'ts' } } })`.

**Comment by OClement** [comment]
@guybedford  
Thanks, will look into this
For the time being I managed to have it work by building from the compiled .js files directly
I guess you can close this issue if you feel like it
