### ISSUE TITLE
Enhancement: Include "canonicalPath" in external dependencies for SFX bundles. (utils.js->getAlias)

### ISSUE THREAD

**Issue by typhonrt** [systemjs/builder#470]
Greets Guy et al,

So, in my further library writing regarding [backbone-parse-es6](https://github.com/typhonjs-parse/backbone-parse-es6) to solve a serialization issue I now have to override a Parse library file (ParseObject). This new class [BackboneParseObject](https://github.com/typhonjs-parse/backbone-parse-es6/blob/master/src/BackboneParseObject.js#L3-L4) imports a file from `parse/lib/browser/encode.js` with `parse` being aliased to `npm:parse`. When creating a SFX bundle for backbone-parse-es6 which excludes external dependencies including Parse I use this ['meta' config](https://github.com/typhonjs-parse/backbone-parse-es6/blob/master/config/bundle-config.json#L4-L21).

In particular I mark as external dependencies anything under this path: `"parse/lib/browser/*": { "build": false }`

Currently in [utils.js -> getAlias](https://github.com/systemjs/builder/blob/master/lib/utils.js#L60-L85) only the canonical name of the module is resolved which is just `parse` and the path is dropped. This is no good and causes things to break for the SFX bundle. For instance for the AMD bundle it looks like this:
```
(function(factory) {
  define(["underscore","parse","jquery","parse"], factory);
});
```

when it really should be this:
```
(function(factory) {
  define(["underscore","parse","jquery","parse/lib/browser/encode"], factory);
});
```

The potential issue is in [utils.js -> getAlias](https://github.com/systemjs/builder/blob/master/lib/utils.js#L60-L85) and in particular [right here](https://github.com/systemjs/builder/blob/master/lib/utils.js#L76-L79).

Here is a new getAlias with my changes to support canonical paths in addition to canonical name substitution / matching:
```
exports.getAlias = getAlias
function getAlias(loader, canonicalName) {
  var pluginIndex = loader.pluginFirst ? canonicalName.indexOf('!') : canonicalName.lastIndexOf('!');

  if (pluginIndex != -1)
    return getAlias(loader, canonicalName.substr(0, pluginIndex)) + '!' + getAlias(loader, canonicalName.substr(pluginIndex + 1));

  if (canonicalName.match(/\#[\:\{\?]/))
    throw new Error('Get alias not implemented for conditional name "' + canonicalName + '". Remove the conditional exclusion, or post a SystemJS Builder bug if needed!');

  var canonicalPath;

  if (canonicalName.indexOf('/') >= 0)
    canonicalPath = canonicalName.substr(canonicalName.indexOf('/'), canonicalName.length);

  var bestAlias;

  function getBestAlias(mapped) {
    return canonicalName.substr(0, mapped.length) == mapped &&
        (canonicalName.length == mapped.length || canonicalName[mapped.length] == '/');
  }

  Object.keys(loader.map).forEach(function(alias) {
    if (getBestAlias(loader.map[alias]))
    {
      bestAlias = alias;

      if (canonicalPath)
        bestAlias += canonicalPath;
    }
  });

  if (bestAlias)
    return bestAlias;

  return canonicalName;
}
```

The above change does the trick and properly exports the aliased name + canonical path correctly. I don't have any visibility into if such a change would cause problems. If so though perhaps an additional meta boolean `buildIncludePath` could be added and when setting to true ala: `"parse/lib/browser/*": { "build": false, "buildIncludePath": true }` then the canonical path is included. 

I can create a PR, but just want to get your input on the issue first. 
Thanks...

**Comment by guybedford** [comment]
@typhonrt thanks, this is definitely a bug. A PR to getAlias would be really great.

**Comment by typhonrt** [comment]
Excellent. The associated PR: https://github.com/systemjs/builder/pull/483

Do let me know about #478 too as it's related to this change.
