### ISSUE TITLE
Enhancement: UMD SFX bundle fails w/ Builder 0.15.4 & `meta build false`

### ISSUE THREAD

**Issue by typhonrt** [systemjs/builder#478]
Greets Guy et al,

I haven't had time to track down why there is a failure, but here is what I'm seeing. I have tested between Builder `0.15.3` and `0.15.4` and when trying to bundle a UMD module which uses:
 `"meta": { "underscore": { "build": false } }`

to exclude underscore from the bundle here is the error I receive:
`TypeError: Global SFX bundle dependency "underscore" must be configured to an environment global via the globalDeps option.`

It should be noted that this is a specific change to `0.15.4` as `0.15.3` works fine for creating UMD bundles. It also should be noted that this error doesn't occur for `amd` or `cjs` bundles with the same exact meta / config setup with `0.15.4`. 

I'll try and poke around in the next day or two to find the error, but do post here if you get to it first. 

Thanks.

**Comment by typhonrt** [comment]
@guybedford  So your change in this commit added `umd` bundles to always check that globalDefs is defined if not resolved:
https://github.com/systemjs/builder/commit/496498abdf265010f17581b22440ea5cb75a5ecb#diff-71a1f6779f4a9a1fe69fcec81f85db12R368

IMHO I think UMD bundling should complete and if globalDeps is not available for a given dependency then just the AMD / CJS bundles work in the UMD template.  If globalDeps is defined then AMD / CJS / Global resolve. IE don't enforce the necessity of providing for the Global path. Perhaps a warning on bundling can note that just the AMD / CJS path is resolved. 

I've tested the following replacement for `externalDepIds` resolution in `wrapSFXOutputs` which outputs a warning when there are any non-resolved dependencies from globalDeps:
```
  var externalDepIds = externalDeps.map(function(dep) {
    if (compileOpts.format == 'global' || compileOpts.format == 'umd') {
      var alias = getAlias(loader, dep);
      var globalDep = compileOpts.globalDeps[dep] || compileOpts.globalDeps[alias];
      if (!globalDep)
      {
        if (compileOpts.format == 'umd') {
          console.warn('SystemJS Builder UMD bundle will not support `Global` format as dependency "' + alias  +
           '" is not configured to an environment global via the globalDeps option.');
        }
        else {
          throw new TypeError('Global SFX bundle dependency "' + alias +
           '" must be configured to an environment global via the globalDeps option.');
        }
      }
      globalDeps.push(globalDep);
    }

    // remove external deps from calculated entry points list
    var entryPointIndex = entryPoints.indexOf(dep);
    if (entryPointIndex != -1)
      entryPoints.splice(entryPointIndex, 1);

    if (compileOpts.encodeNames)
      return getEncoding(dep, cache.encodings);
    else
      return dep;
  });

  if (compileOpts.globalName && globalDeps.length != externalDeps.length) {
    throw new Error('not enough globalDeps');
  }
```

For my repo which includes underscore here is the warning that is posted:
`SystemJS Builder UMD bundle will not support `Global` format as dependency "underscore" is not configured to an environment global via the globalDeps option.`

**Comment by typhonrt** [comment]
@guybedford I now have a specific use case for supporting the above. It is related to #470 and the necessity of [backbone-parse-es6](https://github.com/typhonjs-parse/backbone-parse-es6) when it comes to creating a UMD bundle. As mentioned in #470 there is a need to inject a module + canonical path, "parse/lib/browser/encode" and this is incompatible with creating a global path of the bundle as there is no globally accessible way to access "parse/lib/browser/encode" as it's not available from the global Parse distribution. In this case when creating an UMD bundle it's desirable to only have AMD / CJS paths and the global path to throw: `new Error("Module must be loaded as AMD or CommonJS");`.

I am going to mark this issue as an enhancement now, but please do when you have time provide a comment.

**Comment by guybedford** [comment]
Sure I'd be happy to support this.

Perhaps lets make the condition in the case that when `globalName` and `globalDeps` are both not provided at all, we skip doing the global checks for UMD. But if any of `globalName` or `globalDeps` are provided then we retain this throwing behaviour.

I'm not too keen on doing warnings though as we currently don't do any other output pollution in SystemJS builder.

**Comment by typhonrt** [comment]
Excellent! Here is an updated version which checks `compileOpts.globalDeps.length > 0`. Let me know if it looks good and I'll submit a PR.

```
  var externalDepIds = externalDeps.map(function(dep) {

    if (Object.keys(compileOpts.globalDeps).length > 0 && (compileOpts.format == 'global' ||
     compileOpts.format == 'umd')) {
      var alias = getAlias(loader, dep);
      var globalDep = compileOpts.globalDeps[dep] || compileOpts.globalDeps[alias];
      if (!globalDep)
      {
        throw new TypeError('Global SFX bundle dependency "' + alias +
         '" must be configured to an environment global via the globalDeps option.');
      }
      else
        globalDeps.push(globalDep);
    }

    // remove external deps from calculated entry points list
    var entryPointIndex = entryPoints.indexOf(dep);
    if (entryPointIndex != -1)
      entryPoints.splice(entryPointIndex, 1);

    if (compileOpts.encodeNames)
      return getEncoding(dep, cache.encodings);
    else
      return dep;
  });
```

**Comment by guybedford** [comment]
Thanks. We do still need to do the check for `global` though. So it must be explicitly `global || umd && (globalName || globalDeps)`.

**Comment by typhonrt** [comment]
Oop.. ;)

This should be good, so let me know:
```
  var externalDepIds = externalDeps.map(function(dep) {
    if ((compileOpts.format == 'global' || compileOpts.format == 'umd') && (compileOpts.globalName ||
     Object.keys(compileOpts.globalDeps).length > 0)) {
      var alias = getAlias(loader, dep);
      var globalDep = compileOpts.globalDeps[dep] || compileOpts.globalDeps[alias];
      if (!globalDep)
        throw new TypeError('Global SFX bundle dependency "' + alias +
         '" must be configured to an environment global via the globalDeps option.');

      globalDeps.push(globalDep);
    }

    // remove external deps from calculated entry points list
    var entryPointIndex = entryPoints.indexOf(dep);
    if (entryPointIndex != -1)
      entryPoints.splice(entryPointIndex, 1);

    if (compileOpts.encodeNames)
      return getEncoding(dep, cache.encodings);
    else
      return dep;
  });
```

**Comment by guybedford** [comment]
```javascript
if (compileOpts.format == 'global' || compileOpts.format == 'umd' && (compileOpts.globalName ||
     Object.keys(compileOpts.globalDeps).length > 0)) {
```

:)
