### ISSUE TITLE
Regression: Unable to build 3rd-Party Dependency Bundle

### ISSUE THREAD

**Issue by dak** [systemjs/builder#479]
As of SystemJS 0.15 (tested on 0.15.4 and 0.15.0) the '3rd party dependency bundle' syntax appears to be aggressively including all files in a project, rather than just those files in the dependency tree that are not part of the project.

Thus:
`builder.bundle('app/**/* - [app/**/*]', 'dependencies.js', { minify: true, sourceMaps: true });`
seems to be treated as:
>  take **all the files in the app directory** and all its dependencies, and subtract just the modules in app, thus leaving us with the tree of dependencies of the app package **and all other unused files**.

Thus, if I have in my /app directory a file named 'main.css' that **is never used, referenced, or otherwise included in any other file**, I'll get an error such as:
`[Error: ENOENT: no such file or directory, open '[...]/app/main.css.js']`

**Comment by guybedford** [comment]
@dak yes, that is strictly what the syntax means. Try using the expression `'app/**/*.js - [app/**/*.js]'` here perhaps.

**Comment by dak** [comment]
@guybedford In 0.14 it built a dependency tree based on what was actually imported/required (and that's still what the docs say).  Why should it be aggressively taking every file in the directory rather than what's actually used in the dependency tree?

**Comment by guybedford** [comment]
@dak tracing through arithmetic is prodecural. That is it will compute the graphs of all the modules in app, before doing the final subtraction. Just like how `console.log('a') - console.log('b')` will print a then b. It's on the trace of the first part `app/**/*` that the error is happening.

**Comment by dak** [comment]
@guybedford I just updated my expression to `app/**/*.js - [app/**/*]'` and that does appear to fix the issue on 0.15.4.

**Comment by guybedford** [comment]
Glad to hear that. Closing as this was part of the breaking upgrade path.

**Comment by dak** [comment]
@guybedford This issue seems to have resurfaced in 0.15.6.  0.15.5 is still working with `app/**/*.js - [app/**/*]'`.

**Comment by guybedford** [comment]
@dak thanks for the update, yes I was working on this area again. I tried to replicate this case with the folder structure:

* app/test.js imports "./test.css.js"
* app/test.css.js
* app/test.css

Where I run `bundle('app/**/*.js - [app/**/*]')`, but that seems to work fine for me. Is there any way you can share how to modify this test case into something that catches your issue? Do you have `loader` configuration or plugin syntax in use?

**Comment by dak** [comment]
@guybedford Currently I'm using Gulp 4 and running the task below.  I will also attempt to find a simplified test case later today if something doesn't immediately jump out as issue.

```javascript
var path = require('path');
var gulp = require('gulp');
var config = require('../config');
var Builder = require('systemjs-builder');

function systemjs() {
    var builder = new Builder('./', path.join(config.dest, '/app/config.js'));
    var appPath = path.join(config.dest, '/app/**/*');
    var dependencies = `${appPath}.js - [${appPath}]`;
    var output = path.join(config.dest, '/dependencies.js');

    builder.config({
        paths: {
            '~/*': `${config.dest}/app/*.js`,
            'settings': `${config.dest}/settings.js`,
            'github:*': 'jspm_packages/github/*',
            'npm:*': 'jspm_packages/npm/*'
        }
    });

    return builder.bundle(dependencies, output, {
        minify: (config.env === 'production'),
        sourceMaps: (config.env !== 'production')
    })
    .catch((err) => {
        console.log('SystemJS Build error');
        console.log(err);
    });
}

gulp.task(systemjs);

gulp.task('systemjs:watch', () => {
    gulp.watch('./jspm_packages/**/*', {
        usePolling: true
    }, systemjs);
});
```

**Comment by guybedford** [comment]
Try changing the paths configuration:

```javascript
paths: {
  '~/*': `${config.dest}/app/*.js`
}
```

to without the `.js` extension? I think it might be that.

**Comment by dak** [comment]
@guybedford That appears to have fixed the issue.  Thanks again! :+1:
