### ISSUE TITLE
help: @empty map entry doesn't work

### ISSUE THREAD

**Issue by xealot** [systemjs/builder#487]
I'm sure it does work, but I cannot for the life of me get it to. This is completely related to #368 and other issues but I cannot find specific documentation outside of this.

I have code like this:

```javascript
var isNode = "object" === typeof process && Object.prototype.toString.call(process) === "[object process]";

module.exports.Client = isNode ? require("./connector/node") : require("./connector/xhr");
```

I'm aware that systemjs does static analysis to determine what to include so it isn't a surprise that is loads both of these modules. I'm trying to find a way to load one for the browser and one for nodejs, my current best guess is to use the `@empty` override for this.

I have tried the following options in the browser as a `System.config` assignment:

```javascript
map: {
  './connector/node': '@empty'
},
```

```javascript
map: {
  'connector/node': '@empty'
},
```

```javascript
map: {
  'package/path/connector/node': '@empty'
},
```

```javascript
packages: {
  'package/path': {
    map: {
      './connector/node': '@empty',
      'connector/node': '@empty',
      'node': '@empty'
    }
  }
},
```

```javascript
packages: {
  'package/path/connector': {
    map: {
      'node': '@empty'
    }
  }
},
```

At this point, trial and error isn't working. And Google isn't returning much useful data with regards to how to do this. What is the *best* way to achieve this and even if it isn't by using `@empty`, what am I doing wrong?

**Comment by guybedford** [comment]
Your trial and error was exactly on the right track, the correct method is:

```javascript
packages: {
  'package/path': {
    map: {
      './connector/node': '@empty'
    }
  }
},
```

Are you sure that case was not working for you?

**Comment by xealot** [comment]
Yeah, I tried that. And I tried it again just now.

The module still loads and its dependencies also load (`url`, `http` and `querystring`), which is what is breaking. Here is my full config.

```javascript
System.config({
    map: {
        'app': 'js',
        '@my': 'node_modules/@my',
        'es6-promise': 'node_modules/es6-promise/dist/es6-promise.js',
        'spark-md5': 'node_modules/spark-md5/spark-md5.js',
        'lodash': 'node_modules/lodash/index.js'
//      'url': '@empty',
//      'http': '@empty',
//      'querystring': '@empty'
    },
    packages: {
        'app': {
            format: 'register',
            defaultExtension: 'js'
        },
        '@my/ngsdk': {
            main: 'js/index.js'
        },
        '@my/tools': {
            main: 'js/index.js'
        },
        '@my/network': {
            main: 'js/index.js'
        },
        '@my/http': {
            main: 'js/index.js',
            map: {
                './connector/node': '@empty'
            }
        },
        '@my/auth': {
            main: 'js/index.js'
        },
        '@my/objectdb': {
            main: 'js/index.js'
        }
    },
    meta: {
        '@my/*': {
            format: 'cjs'
        }
    }
});
```

When I comment out `url`, `http` and `querystring` in the global `map` it works. However when I try doing just the `./connector/node` those imports still come in.

**Comment by guybedford** [comment]
@xealot the empty map should definitely be working - did you try adding a console.log to the require statement? Perhaps these requires are coming in from another dependency?

**Comment by xealot** [comment]
I just tried commenting out the `./connector/node` require call and it doesn't attempt to include those things. Also, I can see `./connector/node` being requested in the network tab, which means it's definitely being included.

**Comment by xealot** [comment]
If you point me to a place I could start looking I can try to debug it a little. But I don't even know where I should start.

**Comment by guybedford** [comment]
@xealot and the path is definitely `node_modules/@my/http/connector/node.js`? Perhaps try including the `.js` extension in the relative map - `'./connector/node.js'`: '@empty'`?

**Comment by guybedford** [comment]
If the path is `js/connector/node.js` then the relative map must be `'./js/connector/node': '@empty'` even if the require is `require('./connector/node')`. It is package-relative.

**Comment by xealot** [comment]
Yes! Adding `js` did the trick.

My code modules are split into ts/js directories and I was trying to figure out a way to make systemjs look in the "js" folder. So I used the `main` directive to enter at `js/index.js` but it looks like the `map` isn't based off the relative entry point.

This is somewhat confusing.

Do you have a recommendation for doing this any better?

**Comment by guybedford** [comment]
This is the way to do it, I think if anything it's a documentation issue. Package config is currently only documented at https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages, but this will be expanding with more detail.

**Comment by xealot** [comment]
So if your modules have split ts/js or src/dist type of dirs you have to call them all out individually? I suppose I could try incorporating jspm's config to solve it a little more automatically.

**Comment by guybedford** [comment]
You can specify a package.json `directories.dist` folder to only take the package as that folder - `jspm install x -o "{directories: {dist:'js'}}"`.
