### ISSUE TITLE
Loading shims via Path no longer works in 0.15.6

### ISSUE THREAD

**Issue by silver2k** [systemjs/builder#490]
I have:
>
>paths: {
>    "github:*": "jspm_packages/github/*",
>    "npm:*": "jspm_packages/npm/*",
>    "npm:jquery@2.2.0/*": "shim/jquery",
>    "npm:angular@1.4.9/*": "shim/angular"
>  }

As of 0.15.6 I get :

>Error: Error: ENOENT: no such file or directory, open '/Volumes/xxxxxxx/src/shim/angular'
>    at /Volumes/xxxxxxxx/build.js:103:22

Building using just a basic bundle command.

**Comment by guybedford** [comment]
Unfortunately wildcards mapping to exact paths is not a use case that is supported, so this is a valid regression on an unsupported case.

Try changing your paths configuration to:

```javascript
paths: {
  "npm:jquery@2.2.0/dist/jquery.js": "shim/jquery"
}
```

**Comment by guybedford** [comment]
Let me know if you need more help here.
