### ISSUE TITLE
Error bundling when meta url doesn't have http or https specified

### ISSUE THREAD

**Issue by vidalsasoon** [systemjs/builder#491]
Notice the map URL's which should be ok (//ajax.googleapis.com/...):

When I do this I get an error when trying to build:

_[Error: Unable to calculate canonical name to bundle file://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js. Ensure that this module sits within the baseURL or a wildcard path config.]_

```
		System.config({
			baseURL: staticContentRoot,
			paths: {
				...
			},
			map: {
				"jquery": '//ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js',
				"angular": '//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js',
				"jqueryui": '//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js',
				...
			},
			meta: {
				"*.html": {
					loader: 'systemjs-text'
				},
				"*.json": {
					loader: 'systemjs-json'
				},
				"angular": {
					exports: 'angular',
					format: 'global',
					globals: {
						"jQuery": "jquery"
					},
					build: false
				},
				"jquery": {
            		format: 'cjs',
					build: false
				},
				"jqueryui": {
            		build: false
				}
			}
		});
```

**Comment by guybedford** [comment]
@vidalsasoon I'd suggest including the protocol in the map. When running the builder, the base path is `file:///path/to/project` so that `//asdf` resolves to `file:///asdf` in the build environment.

**Comment by vidalsasoon** [comment]
The reason everyone else supports this format is so a web site can be protocol agnostic so it's possible to avoid the issues of mixing http and https.

**Comment by guybedford** [comment]
Yes, and you are welcome to include that configuration in your browser configuration. But at build time it has different meaning.
