### ISSUE TITLE
GoogleMaps: Module must be loaded as AMD or CommonJS

### ISSUE THREAD

**Issue by happylinks** [systemjs/builder#493]
Hi,

I'm trying to implement the plugin: https://github.com/HeinrichFilter/systemjs-plugin-googlemaps
There was an issue which I'm trying to resolve: https://github.com/HeinrichFilter/systemjs-plugin-googlemaps/issues/6

My setup is the following:
```
"meta": {
    "https://maps.googleapis.com*": {
      "loader": "systemjs-googlemaps",
      "build": false,
    }
  },
map: {
    "google-maps": "https://maps.googleapis.com/maps/api/js?key=XXX&libraries=places&",
}
```
```
import GoogleMaps from "google-maps";
```

This works fine when running in dev-mode, but when I'm trying to build my bundle it builds a version which outputs this:
```
(function(factory) {
  if (typeof define == 'function' && define.amd)
    define(["https://maps.googleapis.com/maps/api/js?key=XXX&libraries=places&.js"], factory);
  else if (typeof module == 'object' && module.exports && typeof require == 'function')
    module.exports = factory(require("https://maps.googleapis.com/maps/api/js?key=XXX&libraries=places&.js"));
  else
    throw new Error("Module must be loaded as AMD or CommonJS");
});
```
This code immediately returns "Module must be loaded as AMD or CommonJS".

I'm wondering if this usecase would be possible with the builder, because I don't think it adds the loader-code to the bundle. And I don't think it should.
But I'm wondering if there is another way that this could still work.

**Comment by guybedford** [comment]
When creating the static bundle, set the `globalName` and `globalDeps` options to enable the global case.

**Comment by guybedford** [comment]
(Yes this is a documentation gap pending the builder API documentation update)

**Comment by happylinks** [comment]
Got a small hint where these should be set?
I found this code: https://github.com/systemjs/systemjs/blob/7c2dd14b824eecea7d3252917fbc0918bc739a2c/dist/system.src.js#L3528

Do I have to set them in the plugin or in the config?
I tried this:
```
"meta": {
    "https://maps.googleapis.com*": {
      "loader": "systemjs-googlemaps",
      "build": false,
      "format": "global",
      "globalName": "google-maps",
      "globalDeps": []
    }
  },
```
But I don't think that's what you mean.

**Comment by guybedford** [comment]
Oh, so are you using jspm? In that case it is `jspm bundle-sfx x --global-name x --global-deps "{'https://maps.googleapis.com/maps/api/js?key=XXX&libraries=places&.js':'google.maps'}"` (whatever the google maps global will be in the production environment).

**Comment by happylinks** [comment]
No, I'm using systemjs builder. But it has to go through the systemjs-plugin-googlemaps plugin first before I can load it, because it needs a callback. So I don't think I can load is as just a global dependency.
There are other ways that I can load it in, like you say as a global and include the callback in the url. But the plugin makes it possible to not have to have the callback.

**Comment by guybedford** [comment]
@happylinks theres many ways of looking at this:

1. Do a normal bundle not an sfx bundle, and use SystemJS and the plugin config in production.
2. Continue to do an sfx bundle, but load it itself with SystemJS in production with the plugin dependency
3. Look at ways of supporting this plugin in builds, posting an issue to the plugin. Because it relies on an external API, that would likely be by assuming some kind of API global to work with, but will be tricky to implement due to this async nature.
