### ISSUE TITLE
Module x is not present when bundling jsPlumb

### ISSUE THREAD

**Issue by matthieu-ravey** [systemjs/builder#495]
I create a new jspm project and I just install jquery and jsplumb. In my main file I import them and console.log something. It works fine in dev workflow, but it does not work once bundled with `jspm bundle-sfx ./app/main.js` . You can find a simple reproduction of this here: https://github.com/matthieu-ravey/jspmjsplumb.

**Comment by guybedford** [comment]
This may be related to https://github.com/systemjs/builder/commit/0c8e88d3596e37c739d713d45b725b37e871eb96, which is being released tomorrow.

**Comment by matthieu-ravey** [comment]
@guybedford thanks i'll try it when it's released

**Comment by matthieu-ravey** [comment]
@guybedford I just tried with jspm 0.16.27 and it's still not working

**Comment by guybedford** [comment]
@matthieu-ravey if you use a normal bundle, it shows that this is jsPlumb itself. The problem is that it has two named AMD defines and is not an anonymous AMD module. We should handle this case better though - it should definitely either not work in the browser, or work for the build.

**Comment by guybedford** [comment]
Actually this is kind of an edge case. SystemJS when loading jsPlumb doesn't actually get the right module value for it as far as I can tell. So actually it isn't loading jsPlumb correctly in the browser as a module, it is loading it as a bundle (allowing it to define names to the registry).

It's difficult to catch the intent here, perhaps the point is that bundles can't be used as dependencies, which should throw in the builder.

**Comment by guybedford** [comment]
This same problem is being tracked under the more general issue https://github.com/systemjs/systemjs/issues/1108.

**Comment by guybedford** [comment]
@matthieu-ravey the workaround would be to define jsPlumb as a CommonJS module so it avoids the AMD bugs.
