### ISSUE TITLE
Expose --keep-fnames UglifyJS option

### ISSUE THREAD

**Issue by mwhite** [systemjs/builder#496]
https://github.com/mishoo/UglifyJS2/blob/master/bin/uglifyjs#L68

This is a very useful option that my code is broken without but I don't want to have to forgo minification.  Would a PR be accepted?

**Comment by guybedford** [comment]
Is this not already captured by the `mangle` option?

**Comment by mwhite** [comment]
Nope, it's an additional boolean option that's only relevant when mangle=true which doesn't mangle function names so code depending on Function.prototype.name works.

I personally don't need it any more, refactored to be explicit (depending on function name is kind of a bad idea).

**Comment by guybedford** [comment]
I'd prefer not to add individual options, unless we create a completely generic options object for all uglify options. I'm open to it, but just trying to keep the API surface area small. Chaining with a custom uglify step is always fine too.
