### ISSUE TITLE
Need to override auto detection

### ISSUE THREAD

**Issue by jkuri** [systemjs/builder#497]
Hi @guybedford, 
I am struggling with some bundle where I want to have some vendor dependency included (moment), my builder config looks like this;
````javascript
var config = {
  baseURL: '.',
  transpiler: 'typescript',
  typescriptOptions: {
    module: 'cjs'
  },
  map: {
    typescript: './node_modules/typescript/lib/typescript.js',
    angular2: path.resolve('node_modules/angular2'),
    rxjs: path.resolve('node_modules/rxjs'),
    moment: path.resolve('node_modules/moment/moment.js')
  },
  paths: {
    '*': '*.js'
  },
  meta: {
    'node_modules/angular2/*': { build: false },
    'node_modules/rxjs/*': { build: false },
    'moment': {
      'format': 'global'
    }
  },
};
````
I am pretty sure what result I want to get because I tried "correcting" auto detected name in generated bundle and then it works properly. Thing is now I get this:
````javascript
System.registerDynamic("node_modules/moment/moment" ...
````
but I want the result to be:
````javascript
System.registerDynamic("moment" ...
````
I understand this is the right result I get, because I set map configuration for `moment` to `path.resolve(node_modules/moment/moment.js')`, but can this be overriden? 
I really read all the documentation before posting this question, at the end tried all combinations with `exports` and `globals` and cannot get the result I want. 
Any help would be appreciated.

**Comment by jkuri** [comment]
Ok, I solved it with this configuration in case anyone will be dealing with similar problem:
````javascript
var config = {
  baseURL: '.',
  transpiler: 'typescript',
  typescriptOptions: {
    module: 'cjs'
  },
  map: {
    typescript: './node_modules/typescript/lib/typescript.js',
    angular2: path.resolve('node_modules/angular2'),
    rxjs: path.resolve('node_modules/rxjs')
  },
  paths: {
    '*': '*.js',
    'moment': 'node_modules/moment/moment.js'
  },
  meta: {
    'node_modules/angular2/*': { build: false },
    'node_modules/rxjs/*': { build: false },
    'moment': {
      'format': 'global'
    }
  },
};
````

**Comment by guybedford** [comment]
Yes exactly, paths configuration forms the canonical namespace.
