### ISSUE TITLE
Loading relative amd module without extension

### ISSUE THREAD

**Issue by n00dl3** [systemjs/builder#499]
When I use the builder I got an error:
>Error: Unable to calculate canonical name to bundle file:///path/to/project/node_modules/crypto-js/core. Ensure that this module sits within the baseURL or a wildcard path config.

I set the `defaultExtension` property to `true` in my package config like so:
```javascript
System.config({
  // or 'traceur' or 'typescript'
  transpiler: "traceur",
  baseURL: "src/js",
  packages: {
    "crypto-js": {
      main: "index.js",
      format: "amd",
      defaultExtension: true
    }
  },
  paths: {
    "crypto-js/*":"./node_modules/crypto-js/*.js"
  }

});
```
crypto-js is an amd package, and I import `"cryptojs/md5"` in my own module, the fact is `"crypto-js/md5"` requires `"crypto-js/core"`, which is required relatively: `require("./core");`
Is there any way to handle that without rewriting the module ?

Note: I also tried to put `"js"` instead of `true` for `defaultExtension` and added a `map` property in package options like that : `map:{ "./core":"./core.js" }` but no change...

**Comment by guybedford** [comment]
Using paths to set extensions is not supported. Try removing the `*.js` part of the path target.

**Comment by n00dl3** [comment]
Really ? I found it [in the docs](https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/loader-config.md) :
>It is also possible to define wildcard paths rules. The most specific rule will be used:
  System.paths['lodash/*'] = '/js/lodash/*.js'

It does not help, anyway...
> \>\>\> Error: ENOENT: no such file or directory, open '/path/to/project/node_modules/crypto-js/md5'
with `"crypto-js/*":"./node_modules/crypto-js/*"` in paths

**Comment by guybedford** [comment]
Thanks, I've updated that example.

Try altering your configuration to:

```javascript
paths: {
  "crypto-js/": "./node_modules/crypto-js/"
},
packages: {
  "crypto-js": {
    defaultExtension: true
  }
}
```

That will make sure the package config catches the paths config. Wildcard paths will probably be deprecated for this folder mapping style in future as it avoids exactly all these catches.

**Comment by n00dl3** [comment]
>\>\> Error: EISDIR: illegal operation on a directory, read

**Comment by n00dl3** [comment]
OK, it works now:
```javascript
System.config({
  // or 'traceur' or 'typescript'
  transpiler: "traceur",
  baseURL: "src/js",
  defaultJSExtensions:false,
  paths: {
    "crypto-js/":"./node_modules/crypto-js/"
  },
  packages: {
    "crypto-js": {
      main: "index.js",
      format: "amd",
      defaultExtension: "js"
    }
  }
});
```
Maybe it's worth having such an example in the docs ?
