### ISSUE TITLE
Calling builder.buildStatic without provided option `browser: true` or `node: true` results in error

### ISSUE THREAD

**Issue by MeoMix** [systemjs/builder#504]
Hey,

I got stuck for several hours :-1:  trying to get `buildStatic` working properly. Eventually, I realized that I needed to define the environment to target.

However, this is in direct conflict with documentation which states: 

> By default builds, like bundles, build for the browser in production

This might be true when using the CLI for bundling, but it is not true when running Builder manually in JS.

I don't know if that's an error or not, but there should probably be some safe guards ensuring the proper options have been provided for environment targets.

Thanks! :balloon:

**Comment by guybedford** [comment]
Ok I've created https://github.com/jspm/jspm-cli/issues/1543 to track this further.

In the builder project itself I think we should have a better message when getting the "exact condition" error, for how to proceed.

**Comment by guybedford** [comment]
I've made a note at the API document page. Will tackle this as part of the documentation process to point to a good source of info for this topic.
