### ISSUE TITLE
Global Static Builds

### ISSUE THREAD

**Issue by g2graman** [systemjs/builder#506]
@guybedford 
I understand that for global static builds it's necessary to specify the globalDeps option but it's not clear what I should set it to. I had previously been getting ` TypeError: Global SFX bundle dependency "D:\Projects\ngPersist\app\angular\app.ts.js" must be configured to an environment global via the globalDeps option.` but am not sure what the value should be set to or if I'm doing something wrong. (I feel like this should be documented somewhere)

I have
```
const gulp = require('gulp'),
    path = require('path'),
    $ = require('gulp-load-plugins')({lazy: true}),
    R = require('ramda'),
    help = require(__dirname + path.sep + 'helpers'),
    join = help.joinChunks;

const Builder = require('systemjs-builder'),
    builderInstance = new Builder(),
    APP_SRC = join([gulp.paths.TS_SRC, gulp.paths.TS_APP])
      || join(['app', 'angular', 'app']),
    APP_DIST = join([gulp.paths.TS_DIST, gulp.paths.TS_APP])
      || join(['dist', 'angular', 'app']);

 let buildOpts = {
    sourceMaps: !!!$.util.env.production,
    lowResSourceMaps: !!!$.util.env.production,
    minify: !!$.util.env.production,
    mangle: !!$.util.env.production,
    format: 'global',
    rollup: true,
    runtime: true,
    globalDeps: {}
  };

  buildOpts.globalDeps[APP_SRC + '.ts.js'] = '';

  let buildOpts = {
    sourceMaps: !!!$.util.env.production,
    lowResSourceMaps: !!!$.util.env.production,
    minify: !!$.util.env.production,
    mangle: !!$.util.env.production,
    format: 'global',
    rollup: true,
    runtime: true,
    globalDeps: {}
  };

  buildOpts.globalDeps[APP_SRC + '.ts.js'] = '';

  gulp.task('jspm', (cb) => {
    builderInstance.reset();
    builderInstance
      .loadConfig(
        gulp.paths.CONFIG_FILE
          || '.' + path.sep + 'jspm.config.js'
      )
      .then(() => {
        builderInstance.buildStatic(
          APP_SRC + '.ts.js',
          APP_DIST + '.js',
          buildOpts
        )
        .then(R.nAry(0, cb)) // call the callback without parameters
        .catch(R.nAry(1, cb)); // call the callback with the error parameter
      })
      .catch(R.nAry(1, cb)); // call the callback with the error parameter
  });
```

The line that reads `buildOpts.globalDeps[APP_SRC + '.ts.js'] = ''`, I am not sure what to set to. I have tried a few things and none of them have worked, though the build seems to complete successfully; I get the final errors when trying to add the js to an html file and view it in the browser.

(Note: I had been using extension `.ts.js` because that's the only extension I've figured out to get working from needing `defaultJSExtensions: true`, and `"defaultExtension": "ts"` for the app, and am using `node` version 5.6.0 for es6 syntax)

**Comment by g2graman** [comment]
It looks like I fixed my problem. Where I had previously provided the path to my `app.ts` file as the first argument to buildStatic before, I just added a package to my `jspm.config.js` and referenced that package name as the first argument to buildStatic

**Comment by guybedford** [comment]
When using jspm for builds, you should use `var Builder = require('jspm').Builder` as that will come with all the correct configuration without needing to manually configure jspm.

**Comment by g2graman** [comment]
Thank you, @guybedford
