### ISSUE TITLE
Ensure that the transpiler is installed separately...

### ISSUE THREAD

**Issue by amenadiel** [systemjs/builder#518]
I was reading the documentation for the Nth time, and noticed a line I never saw before:

> Ensure that the transpiler is installed separately (npm install babel-core here).

Thing is, I never did this step and I never noticed because everything works. What am I missing here? One of my guesses is that, without installing the transpiler, my bundles are still ES6, and they have to do in-browser transpilation.

However, if that was true, and by installing the transpiler I'll now have ES5 bundles, then shouldn't I modify config.js to state that no transpiler is going to be used?

**Comment by guybedford** [comment]
This is for a SystemJS-Builder specific Node workflow and doesn't apply to jspm.
