### ISSUE TITLE
Bundled AMD modules failing test for window.define

### ISSUE THREAD

**Issue by gpoole** [systemjs/builder#519]
In the previous version of SystemJS builder I was using (0.15.6), AMD modules in my static bundle were being wrapped by `$__System.get("@@amd-helpers").createDefine()` and `_removeDefine()`. After updating to a newer version (0.15.10) it seems like this wrapping is no longer happening (at least for my configuration) and now cases like the following fail due to `window.define` being undefined:

```
if (window.define && window.define.amd) {
    define(function() { /* etc */ });
}
```

**Comment by guybedford** [comment]
Yes this was changed to be a locally scoped define over `window.define`. What code is doing this check? This isn't a common pattern at all.

**Comment by gpoole** [comment]
Ah yes that makes sense. It's a bit of code from one of my older RequireJS-based projects, so it's just a weird way I've done it there. I wasn't sure if the global `define` was intentionally not working anymore or just not very common. Thanks!

**Comment by guybedford** [comment]
Sure thanks for the update. I think it's best to let this case fail as it is uncommon, and it's much nicer to not have to be mutating the global all the time.
