### ISSUE TITLE
Instead of remap, have compilers expose their transformers directly

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#52]
This way more advanced analysis can be done allowing for https://github.com/jspm/npm/issues/41.

**Comment by crisptrutski** [comment]
@guybedford skipping this in next release? not sure what it is, and if it's something closable today

**Comment by guybedford** [comment]
Yeah this one's for me to do next release.

**Comment by crisptrutski** [comment]
Ah, just noticed the "current release" tag (though next == pending). Sorry for noise!

**Comment by guybedford** [comment]
This is really a jspm-npm bug, so tracking there rather.
