### ISSUE TITLE
Add support for source directory -> destination directory style bundling

### ISSUE THREAD

**Issue by Bajix** [systemjs/builder#522]
It seems that the SystemJS Builder doesn't give developers much options to build from assets in one folder, into another.

I tried a couple of different approaches to accomplish this, however in the end ended up taking the nuclear approach & monkey patched output to override paths.

Due to how this module canonicalizes ID's, it didn't seem like it was an option to simply set the baseURL towards the destination folder & manually resolve paths via the fetch hook.

Is there a better way of going about this, or otherwise thoughts on changing the API to support an input directory / output directory workflow out of the box?

For reference, here's the solution I'm currently using as a stop gap measure:
https://github.com/Bajix/broccoli-system-builder

**Comment by guybedford** [comment]
What are you looking to achieve with a direvtory -> directory compilation? If you're looking to do single-file compilations of all files in the directory, regardless of their dependencies then look at `builder.compiler`. If you're looking to build an entire directory into a single bundle file, look at wildcard arithmetic.

**Comment by Bajix** [comment]
Source directory to destination directory builds are ideal build systems. That's actually how BroccoliJS works, and it's common in other build workflows.

The [broccoli-system-builder](https://github.com/Bajix/broccoli-system-builder) plugin I mentioned above is simply setting up a builder instance and overriding how files are written. It doesn't setup a build itself, but rather lets the user make a custom build within the callback.

**Comment by Bajix** [comment]
To be clear, here's an example of something I'd like to support:

These two should be equivalent, where the input path is relative to my source base URL, and output relative to my destination base URL:

```js
builder.bundle(path.join(sourceDir, 'foo/bar.js'), path.join(destDir, 'foo/bar.js'));
```

```js
builder.bundle('foo/bar.js', 'foo/bar.js');
```

Right now I'm setting the baseURL relative to the source directory, and then I've monkey patched the writeOutputs function to remap where files are written to be within the destination directory. I really don't want to be reliant on monkey patching here.

**Comment by guybedford** [comment]
@Bajix the two aren't equivalent - the input to `builder.bundle` is in module name space, while the outFile argument is in file system space.

**Comment by guybedford** [comment]
Just let me know if you have any more questions here at all.
