### ISSUE TITLE
Builder cache doesn't handle packageConfigPaths

### ISSUE THREAD

**Issue by harrison** [systemjs/builder#523]
I've set up a test case for using the cache that fails: https://github.com/harrison/jspm-beta

Specific line causing the issue: https://github.com/harrison/jspm-beta/blob/master/builder.js#L23

Relying on fact that `setCache` pulls out compile and trace by reference so the original cache is mutated.

Should be able to reproduce by running:

```
npm install
./node_modules/.bin/jspm install
node watch.js
```

Error:

```
[TypeError: Cannot read property 'a.js' of undefined]
```

I've tried digging around further but haven't got that far:)

**Comment by guybedford** [comment]
I've added a fix for this in https://github.com/systemjs/builder/commit/718ed485b96bc15ecd54ff7b8abb143f59f7015c.

The work around would be to alter https://github.com/harrison/jspm-beta/blob/master/builder.js#L4 to be either a plain object (`{}`) or a cache object of the form - `{ compile: { loads: {}, encodings: {} }, trace: {} }`.

**Comment by harrison** [comment]
@guybedford sweet! That does fix the error with importing `a.js` but fails for `lodash` :(

Added this: https://github.com/harrison/jspm-beta/blob/master/src/app.js#L1
And get this on subsequent builds: `jspm build error [TypeError: Cannot read property 'map' of undefined]`

**Comment by harrison** [comment]
Initially had the lodash error but thought I had narrowed it down further..

**Comment by guybedford** [comment]
@harrison that's due to it not being installed in the config file at https://github.com/harrison/jspm-beta/blob/master/src/jspm.config.js (the baseURL is the default configuration file folder, so package-level jspm.config.js file is being ignored).

**Comment by harrison** [comment]
@guybedford not sure I follow. What am I missing in the config? The initial build completes fine and includes lodash but any subsequent builds with a cache fail.

**Comment by guybedford** [comment]
Ok, thanks this is an issue with the caching process for dynamic package configuration, which actually needs to be architected quite carefully. I will see what I can do here.

**Comment by guybedford** [comment]
I've included a fix here pending release.

**Comment by guybedford** [comment]
Released in 0.15.13.

**Comment by harrison** [comment]
@guybedford amazing!

**Comment by harrison** [comment]
@guybedford when's the next jspm beta release? Have a pr to switch our dashboard over to it :)

**Comment by guybedford** [comment]
@harrison feel free to use the beta in production, it is production ready but it isn't released yet mainly due to waiting on the documentation update.

**Comment by harrison** [comment]
@guybedford planning too:) the current jspm beta has a strict dependency on builder `0.15.11` so was hoping for a jspm bump

**Comment by guybedford** [comment]
Ahh sure, right of course. I'm on contract work this week, but will try and do one when I can.
