### ISSUE TITLE
Production builds plugins don't get NODE_ENV=production from process

### ISSUE THREAD

**Issue by AdamBurgess** [systemjs/builder#526]
I believe this is a bug with builder and not jspm, which is why I'm making it here.

main.js:
```js
import buildEnv from '!build-env.js'
import process from 'process'
console.log(`build env: ${buildEnv}`);
console.log(`runtime env: ${process.env.NODE_ENV}`);
```
build-env.js:
```js
import process from 'process'

export var fetch = _ => '';
export var translate = load => {
    load.metadata.format = 'cjs'
    return `module.exports = '${process.env.NODE_ENV}'`;
}
```

running with `jspm build --node main.js && node build.js`:
```
     Creating the single-file build for main.js...

       !build-env.js
       github:jspm/nodelibs-process@0.2.0-alpha/process-node.js
       main.js

ok   Built into build.js with source maps, unminified as umd.

build env: development
runtime env: production
```
setting `NODE_ENV` manually to `production` before the build also has no effect

**Comment by AdamBurgess** [comment]
in a similar strain, `jspm run main.js` has no way for me to configure NODE_ENV to `production`

**Comment by guybedford** [comment]
In SystemJS, we don't actually support `process.NODE_ENV` at all. This is a CommonJS / Node paradigm. Rather we support it as an optimization in CommonJS files and we support it as an optimization through jspm as well.

The SystemJS way of handling the environment currently is through `System.config({ production: true })`, which can also be seen from `import {production} from '@system-env'`.

Adding the environment flags to `jspm run` like we have for `jspm build` and `jspm bundle` is certainly something that should be done though. I've created an issue for that in https://github.com/jspm/jspm-cli/issues/1621.

Let me know if that answers your question here?

**Comment by guybedford** [comment]
@AdamBurgess just let me know if you have any further questions here at all.
