### ISSUE TITLE
Uglifyjs support sourceMapContents

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#527]
Inspiration to be taken from https://github.com/mishoo/UglifyJS2/blob/master/bin/uglifyjs#L446.

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/builder/pull/562.

**Comment by xiankai** [comment]
Is this fix deployed yet? I've tried doing `jspm dl-loader --latest` to get `systemjs@0.19.28`, but running `jspm bundle-sfx --minify --source-map-contents <source files> bundle.js` still does not produce `sourcesContent`.

Also, is there a way to track what version of builder that systemJS is using?
