### ISSUE TITLE
.buildstatic just outputs the filename - what am I doing wrong?

### ISSUE THREAD

**Issue by darrenshrwd** [systemjs/builder#533]
I've asked a question on SO with 100 bounty:

http://stackoverflow.com/questions/36170705/system-js-builder-buildstatic-just-outputs-the-filename

**Comment by guybedford** [comment]
Can you share the contents of your config.js file? Specifically the baseURL.

**Comment by darrenshrwd** [comment]
Below is my config.js, I am not intending to use typescript **yet** and don't have a compile step as my whole site just has ES5 code at the moment but I needed a transpiler in there to use JSPM or complains about the import statements.

System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "typescript",
  paths: {
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "angular": "npm:angular@1.5.2",
    "typescript": "npm:typescript@1.8.9"
  }
});

**Comment by darrenshrwd** [comment]
Ah do I just need to change the base path to "./"

**Comment by darrenshrwd** [comment]
...Yep that was it. Doh.

**Comment by guybedford** [comment]
Yes a baseURL of `/` means the system root itself.
