### ISSUE TITLE
Exported value not returned when importing bundle

### ISSUE THREAD

**Issue by fdnhkj** [systemjs/builder#536]
Hello,

I am working on angular (1.3) TypeScript projects and starting a new project for which I would like to use ES6 modules, SystemJS and SystemJS-builder (only for js app specific files first - no css, vendors).

Here are the TypeScript compiler options I use :

- target: ES5 (I will not use transpiler but compile directly to ES5)
- module: system

The issue I have is about the promise value returned when doing `System.import` on a bundle generated with systemjs-builder (`builder.bundle`).

#### Development workflow
For development, I use `system.js` file.
During **development**, to import a module I point directly to the entry point of a module, i.e. for following module :

- moduleA
  - entryPoint.ts (with in it `export default angular.module('moduleA');`)
  - other ts files

I would do :

    System.import('moduleA/entryPoint').then(function(moduleA) {
        // and here get default exported value: moduleA.default
    });
Everything is working fine. But then, I have an issue when it comes to the generation of bundles for production environment.

#### Production workflow
For production I am using `system-csp-production.js` file.
##### Using builder.buildStatic
When I generate my concatenated file using 
`builder.buildStatic('moduleA/entryPoint', 'dist/moduleA/bundle.js')`,
and then call `System.import('dist/moduleA/bundle.js')`, I am able to access the export default value via the promise value.

##### Using builder.bundle
However, when I generate my concatenated file using
`builder.bundle('moduleB/entryPoint', 'dist/moduleB/bundle.js')`,
and then call `System.import('dist/moduleB/bundle.js')`, the **promise is returning an empty object** while I was expecting to get the angular module exported in the entry point of that moduleB.

#### Question
Why can't I get exported value by pointing to the file generated with `bundle method` ?

I probably misunderstood the difference between `bundle` and `buildStatic`.
I read about [self-executing-sfx-bundles](https://github.com/systemjs/builder#self-executing-sfx-bundles) but I think that I don't need to make my bundles independent of the SystemJS loader as I am loading `system-csp-production` file in production.

##### Sample repo
I wrote a sample repo to better illustrate my issue :
[https://github.com/fdnhkj/systemjs-builder-bundle-vs-buildStatic](https://github.com/fdnhkj/systemjs-builder-bundle-vs-buildStatic)
In order to run it, you need to execute `npm install && npm start`.
###### Explanation
I wrote:

- a module A for which I generate a concatenated file built with `buildStatic`
- a module B for which I generate a concatenated file built with `bundle`.
Then, I do `System.import` for each of the generated file and `console.log` the promise value. 

Thank you for your help

**Comment by guybedford** [comment]
A bundle is not a module. When you System.import a bundle, the value of the bundle is always an empty module, but the modules inside the bundle will then be in the registry.

So you can do:

```javascript
System.import('dist/moduleA/bundle.js').then(function() {
  return System.import('moduleA/entryPoint').then(function(moduleA) {
  });
});
```

the second System.import will then do no network request, but get the module from the bundle.

You can also use the bundles configuration to skip having to do these nested imports. See https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md#bundle-extension for more info.

**Comment by fdnhkj** [comment]
Thank you @guybedford, really helpful  :+1: !

**Comment by circlingthesun** [comment]
I'm trying to move to JSPM 0.17 beta from 0.16. In my project I create a bundle for each module and its dependencies (one for each route in an angular app). The bundle has the same path as the original module. Before I was able to call `System.import('path/to/module.js')` to import the bundle and it would return the module. Now I'm getting an empty object, even if I import the same path twice. I'm wondering if this is a regression or if I was making use of unintended functionality.

**Comment by guybedford** [comment]
@circlingthesun it would help if you can share a simple test case that demonstrates the problem. It is supported for the bundle module to take the value of the System.register call corresponding to the same name as the bundle itself, but the names would need to normalize to match exactly.

**Comment by circlingthesun** [comment]
@guybedford, I've tried normalization but that raised issues with condition imports in jspm/nodelibs-process. I'll try put together a minimal example of my issue.

**Comment by circlingthesun** [comment]
@guybedford, it appears the problem was a bad bundle configuration that was injected by accident. Thanks for the response.
