### ISSUE TITLE
Error on translate - ES6 code not transpiling

### ISSUE THREAD

**Issue by linnett** [systemjs/builder#539]
I'm trying to transpile a basic main.js file using systemjsbuilder. I ran 'jspm install jquery' as an example. So the file is as basic as this:

```import $ from 'jquery'```.

When I try and compile it using systemjsbuilder in gulp, it throws an error: 

```Error: Error on translate for core/js/main at file:///<userinfo>/src/core/js/main.js
	Error: ENOENT, open '/<userinfo>/src/jspm_packages/npm/babel-core@5.8.38.js'
	    at Error (native)```

My gulp task looks like this:

```
gulp.task('systemjsBuilder', function (cb) {
    // sets the baseURL and loads the configuration file
    var builder = new Builder('./src/', './jspm-config.js');

    builder.bundle('core/js/main', './dist/app.js', {
      minify: true,
      sourceMaps: true
    })
    .then(function() {
        cb();
        console.log('Build complete');
    }).catch(function(err) {
        console.log('Build error');
        console.error(err);
    });
});
```

I took the import out and put in some more simple ES6 in, let a. This threw an error too. Is there something I'm missing?

**Comment by guybedford** [comment]
@linnett jspm builds should always be done through the `var Builder = require('jspm').Builder` API as a direct replacement for `var Builder = require('systemjs-builder')`. This will ensure you get a correctly configured build for jspm.

**Comment by linnett** [comment]
@guybedford thanks for that - the documentation states to use systemjs-builder though - is that just something that needs to be updated?

**Comment by guybedford** [comment]
Yes exactly, can you perhaps point to where in the docs you're referring to?

**Comment by linnett** [comment]
Under "basic use" in the readme file, it states: "var Builder = require('systemjs-builder')" rather than "var Builder = require('jspm').Builder".

**Comment by guybedford** [comment]
Yes that is because SystemJS builder is designed to be used independently of jspm. It's jspm specifically that then documents using the `require('jspm').Builder`. There is actually an issue at https://github.com/systemjs/builder/issues/507 to track when the builder is used the wrong way on a jspm project and provide some kind of warning.
