### ISSUE TITLE
Output to memory

### ISSUE THREAD

**Issue by thepian** [systemjs/builder#54]
I don't see a howto, but hopefully there is a way to output to a memory object rather than a file in the FS. Or perhaps an option to set an output filesystem that could be a memory FS.

**Comment by guybedford** [comment]
This could certainly be an option - providing the source and source map directly when no output file is set.

**Comment by jjbananas** [comment]
I would welcome this idea as well. I'm trying to integrate SystemJS/JSPM into the Rails asset pipeline. I am working around it with my own scripts at the moment but ideally all I need is:

1. Compile a single file (given by module name), including adding `System.register` around it.
2. Get a list of dependencies for that file at the same time.

Currently I have my hacked up a version of the systemjs-builder:index.js file to suit my needs, but it would be great if it was easier/officially supported.
