### ISSUE TITLE
Enable node_modules easy config like browserify

### ISSUE THREAD

**Issue by Alphapage** [systemjs/builder#540]
Hello,

I'm fighting with systemjs builder to use buildStatic and to achieve the same bundle as browserify:
``` 
browserify({ standalone: "test" })
   .transform(babelify)
    .require("./src/entrypoint.js", { entry: true })
    .bundle()
    .on("error", function(err) { console.log("Error: " + err.message) })
    .pipe(fs.createWriteStream("output.js"))
```

Of course, the script needs to require lodash for example which is the problem of systemjs builder because it doesn't seem to understand package.json main field.

It would be great to have a preconfigured options to enable node_modules and include the scripts when necessary.

Any idea on how to achieve this without remapping all node_modules ?

Thanks in advance for your help.

**Comment by guybedford** [comment]
SystemJS builder just follows the same rules as SystemJS itself. So it's best to first focus on ensuring the app can be loaded through SystemJS. Getting lodash to load correctly is then just about setting the right configuration in SystemJS.

If you're frustrated working all this configuration out yourself, then that is what jspm is for, to automate all this configuration creation.
