### ISSUE TITLE
Dependency bundle name starts with 'node_modules/angular2/core', not 'angular2/core'

### ISSUE THREAD

**Issue by allenhwkim** [systemjs/builder#543]
Hi,

First, millions of thanks to systemjs members. I really appreciate your code and effort for this module.

I have a small test repo. https://github.com/jsvalley/ng2-package-seed

All are fine when I  build a systemjs bundle except dependency part.

My small code is this.

import {Pipe} from 'angular2/core';

```
@Pipe({name: 'my'})
export class MyPipe {
  transform(v: string, args: any[]) {
    return 'My ' + v;
  }
}
```

and my builder code, make.js, is the following;
```
var pkg     = require('./package.json');
var path    = require('path');
var Builder = require('systemjs-builder');
var name    = pkg.name;

var builder = new Builder();
var config = {
  baseURL: '.',
  transpiler: 'typescript',
  typescriptOptions: {
    module: 'commonjs'
  },
  map: {
    typescript: './node_modules/typescript/lib/typescript.js',
    angular2: path.resolve('node_modules/angular2'),
    rxjs: path.resolve('node_modules/rxjs')
  },
  paths: {
    '*': '*.ts'
  },
  meta: {
    'node_modules/angular2/*': { build: false },
    'node_modules/rxjs/*': { build: false }
  },
};

builder.config(config);

builder.bundle(
  name, 
  'bundles/' + name + '.js', {
    //minify: true, sourceMaps: true
  }
);
```

When I run `node make.js`, it generate the code successfully, but when I see the output of the file has dependency of 'node_modules/angular2/core', not 'angular2/core' that I expected. Also this incorrect dependency cause 404 error. 

If I manually change it to  'angular2/core', it works fine with my test.html
The output looks like this

```
System.register("src/seed-examples/my.pipe", ["node_modules/angular2/core"], function(exports_1, context_1) {  // <-------- this line --------------
    "use strict";
     ... omitted ....
    }
});
```

I think I am missing very small configuration for systemjs builder, but I couldn't figure out for a week.

If this is not the right place to ask this kind of question, please let me know.

**Comment by guybedford** [comment]
If you use paths configuration for Angular2, then it will output into the bundle as the name you expect:

```javascript
  paths: {
    'angular2/*': path.resolve('node_modules/angular2/*')
  },
```

But that may bring up other issues here.

**Comment by allenhwkim** [comment]
I will try, but what other issue?

**Comment by guybedford** [comment]
If there are other issues, feel free to ask!
