### ISSUE TITLE
ENOENT

### ISSUE THREAD

**Issue by khwerhahn** [systemjs/builder#544]
## Issue Overview
System JS Builder Issue - `ENOENT` error

## Issue Description
I have used this starter together with [featherjs](https://github.com/feathersjs/feathers) and [angular-starter](https://github.com/antonybudianto/angular2-starter), but I cannot get the System.js builder to work. It always throws an `ENOENT` error. For some reason it doesn't find the `main` file and throws an error. When I add the `.js` to it, it throws the next error `cannot find app.component`. The System JS builder is called in the gulp tasks under `tasks/build.js`

I've hit a wall. Could somebody maybe help me find the error. 

## Reproducables
[Repo](https://github.com/khwerhahn/feathersng2)
The app code is hosted in the `client` folder and the build code is hosted in `public`. Everything else stays the same.

**Comment by guybedford** [comment]
Did you mean to post this issue to the starter project repo itself?

**Comment by antonybudianto** [comment]
the issue has been solved in my repo, you can close this @guybedford
