### ISSUE TITLE
Create an already-compiled bundle that's in System.register format

### ISSUE THREAD

**Issue by joeldenning** [systemjs/builder#545]
Searched the docs and the issues for this and found something that may be similar (jspm/jspm-cli#1107) but I don't know what jspm compile was or will be. Would love to hear a way to do this if one already exists.

Basically what I'm hoping to achieve is sort of like an SFX build (pre-compiled js and css), except that it's wrapped in a System.register and may declare some external dependencies. The motivation for it is two-fold. First, performance -- Babel in the browser really increases the size of my bundle and also adds noticeable latency in the js bootstrap. The same can be said for CSS autoprefixer. And second, I'm loading libraries dynamically in the browser, so a normal SFX build won't do. 

I've considered simply creating an SFX bundle and then re-bundling that bundle into a non-sfx System.register bundle, but that doesn't quite do the job since I want to declare external dependencies (large ones that are already loaded that I don't want duplicates of for performance reasons).

Is this similar to what jspm compile is intended to do? If not, what are your thoughts? I'd be willing to contribute to the endeavor even though it might be a considerable amount of work.

**Comment by guybedford** [comment]
SFX builds can declare external dependencies using subtraction. So you can do for example `jspm build app - external-dep-x` and the resulting file will itself be a module. In jspm 0.17 we encourage workflows like this, see for example http://jspm.io/0.17-beta-guide/static-builds-with-rollup-optimization.html.

**Comment by guybedford** [comment]
(of course this all applies equally outside of jspm, using SystemJS builder directly)

**Comment by joeldenning** [comment]
Awesome, just tried that out and it's exactly what I was looking for. This may be the thing that finally gets me to bite the bullet and migrate various projects to jspm@0.17.
