### ISSUE TITLE
Templates not compiled properly

### ISSUE THREAD

**Issue by primavera133** [systemjs/builder#546]
So I have a project that I code in Angular 1.5 (written in Typescript) and that uses Angular-ui-router(0.2.18). I also use JSPM (0.16.32) to set it all up and have a gulp-system that builds it. Locally I use SystemJS module loader to load the separate files but for the QA-server (and eventually production) I use a SFX-build using the jspm.Builder (which uses systemjs builder 0.15.14) and the buildStatic method it provides.

This build works generally fine, but have an issue in one of my modules which has nested routes. The issue boils down to the compilation of the templates where the same compiled template is re-used even where it should be separate ones!

`
import {App} from '../../App';
import '../project/Project';
import {ProjectsDashboardCtrl} from './ProjectsDashboardCtrl';
import {ProjectCardDirective} from './ProjectCardDirective';
import {ProjectSorterDirective} from './ProjectSorterDirective';

const module:ng.IModule = App.module('app.projectsDashboard', []);

module.controller('ProjectsDashboardCtrl', ProjectsDashboardCtrl);

module.directive('projectCard', <any>ProjectCardDirective);
module.directive('projectSorter', <any>ProjectSorterDirective);

module.config(['$stateProvider', ($stateProvider:angular.ui.IStateProvider) => {
  $stateProvider.state('projectsDashboard', {
    url: '/projects',
    views: {
      application: {
        templateUrl: 'src/module/projectsDashboard/view/projectsDashboardActive.html',
        controller: ProjectsDashboardCtrl,
        controllerAs: 'controller'
      }
    }
  }).state('projectsDashboard.active', {
    url: '/active',
    views: {
      projects: {
        templateUrl: 'src/module/projectsDashboard/view/projectsDashboardActive.html'
      }
    }
  }).state('projectsDashboard.cancelled', {
    url: '/cancelled',
    views: {
      projects: {
        templateUrl: 'src/module/projectsDashboard/view/projectsDashboardCancelled.html'
      }
    }
  });
}]);
`

The code in gulp that builds:
`
module.exports = (gulp, config) => () => {
  const path = require('path');
  const Builder = require('jspm').Builder;
  const builder = new Builder();
  const packageJson = require(path.join(config.projectDir, 'package.json'));

  return beginBuild()
    .then(buildSFXNonMin)
    .then(buildSFX)
    .catch((err) => {
      console.log('\n\tBuild Failed\n', err);
      process.exit(1);
    });

  function beginBuild() {
    builder.reset();
    return builder.loadConfig(path.join(config.projectDir, packageJson.jspm.configFile))
  }

  function buildSFXNonMin() {
    const appName = packageJson.name;
    const distFileName = `${appName}.js`;
    const outFile = path.join(config.distDir, distFileName);
    const moduleName = 'app';
    const buildConfig = {
      format: 'global',
      minify: false,
      sourceMaps: true
    };
    return builder.buildStatic(moduleName, outFile, buildConfig);
  }

  function buildSFX() {
    const appName = packageJson.name;
    const distFileName = `${appName}.min.js`;
    const outFile = path.join(config.distDir, distFileName);
    const moduleName = 'app';
    const buildConfig = {
      format: 'global',
      minify: true,
      sourceMaps: true
    };
    return builder.buildStatic(moduleName, outFile, buildConfig);
  }

};
`

So am I correct in assuming it is an issue with SystemJS builder? And do anyone have any clue on what's going on and how to avoid it?

**Comment by primavera133** [comment]
The compiled component looks like this:

define(["require", "exports", '../../App', './ProjectsDashboardCtrl', './ProjectCardDirective', './ProjectSorterDirective', '../project/Project'], function (require, exports, App_1, ProjectsDashboardCtrl_1, ProjectCardDirective_1, ProjectSorterDirective_1) {
    "use strict";
    var module = App_1.App.module('app.projectsDashboard', []);
    module.controller('ProjectsDashboardCtrl', ProjectsDashboardCtrl_1.ProjectsDashboardCtrl);
    module.directive('projectCard', ProjectCardDirective_1.ProjectCardDirective);
    module.directive('projectSorter', ProjectSorterDirective_1.ProjectSorterDirective);
    module.config(['$stateProvider', function ($stateProvider) {
            $stateProvider.state('projectsDashboard', {
                url: '/projects',
                views: {
                    application: {
                        template: '<div class=pistas-projects-dashboard><h1>Select a project</h1><div class=pistas-v-offset--md><tabs data=controller.tabData type=tabs></tabs></div><ui-view name=projects></ui-view></div>',
                        controller: ProjectsDashboardCtrl_1.ProjectsDashboardCtrl,
                        controllerAs: 'controller'
                    }
                }
            }).state('projectsDashboard.active', {
                url: '/active',
                views: {
                    projects: {
                        template: '<div class=pistas-projects-dashboard><h1>Select a project</h1><div class=pistas-v-offset--md><tabs data=controller.tabData type=tabs></tabs></div><ui-view name=projects></ui-view></div>'
                    }
                }
            }).state('projectsDashboard.cancelled', {
                url: '/cancelled',
                views: {
                    projects: {
                        template: '<div class=pistas-projects-dashboard><h1>Select a project</h1><div class=pistas-v-offset--md><tabs data=controller.tabData type=tabs></tabs></div><ui-view name=projects></ui-view></div>'
                    }
                }
            });
        }]);
});
//# sourceMappingURL=ProjectsDashboard.js.map

**Comment by primavera133** [comment]
The compiled component looks like this:

`
define(["require", "exports", '../../App', './ProjectsDashboardCtrl', './ProjectCardDirective', './ProjectSorterDirective', '../project/Project'], function (require, exports, App_1, ProjectsDashboardCtrl_1, ProjectCardDirective_1, ProjectSorterDirective_1) {
    "use strict";
    var module = App_1.App.module('app.projectsDashboard', []);
    module.controller('ProjectsDashboardCtrl', ProjectsDashboardCtrl_1.ProjectsDashboardCtrl);
    module.directive('projectCard', ProjectCardDirective_1.ProjectCardDirective);
    module.directive('projectSorter', ProjectSorterDirective_1.ProjectSorterDirective);
    module.config(['$stateProvider', function ($stateProvider) {
            $stateProvider.state('projectsDashboard', {
                url: '/projects',
                views: {
                    application: {
                        template: '<div class=pistas-projects-dashboard><h1>Select a project</h1><div class=pistas-v-offset--md><tabs data=controller.tabData type=tabs></tabs></div><ui-view name=projects></ui-view></div>',
                        controller: ProjectsDashboardCtrl_1.ProjectsDashboardCtrl,
                        controllerAs: 'controller'
                    }
                }
            }).state('projectsDashboard.active', {
                url: '/active',
                views: {
                    projects: {
                        template: '<div class=pistas-projects-dashboard><h1>Select a project</h1><div class=pistas-v-offset--md><tabs data=controller.tabData type=tabs></tabs></div><ui-view name=projects></ui-view></div>'
                    }
                }
            }).state('projectsDashboard.cancelled', {
                url: '/cancelled',
                views: {
                    projects: {
                        template: '<div class=pistas-projects-dashboard><h1>Select a project</h1><div class=pistas-v-offset--md><tabs data=controller.tabData type=tabs></tabs></div><ui-view name=projects></ui-view></div>'
                    }
                }
            });
        }]);
});
//# sourceMappingURL=ProjectsDashboard.js.map
`

**Comment by guybedford** [comment]
I'm sorry, but it's really important in issues to clearly state your problem succinctly.
