### ISSUE TITLE
Error: Unable to calculate canonical name for map configuration

### ISSUE THREAD

**Issue by rweng** [systemjs/builder#548]
Hi there,

I have the following `system.config.js` with which my application works:

```js
System.config({
    baseURL: 'node_modules',
    packages: {
        'app': {
            defaultExtension: 'js',
            meta: {
                '*.md': {
                    defaultExtension: false,
                    loader: 'systemjs-plugin-md'
                },
                '*.html': {
                    defaultExtension: false,
                    loader: 'systemjs-plugin-text'
                }
            }
        }
    },

    packageConfigPaths: ['./node_modules/*/package.json'],

    map: {
        'app': './app'
    }
});
```

When I try to bundle it with with my entry point, `app/bootstrap.js`, I get the following error:

> [Error: Unable to calculate canonical name to bundle file:///Users/rowe/Code/web/target/dev/app/bootstrap.js. Ensure that this module sits within the baseURL or a wildcard path config.]

The problem is that I cannot change the `map`-configuration for `app` to a path wildcard, because then the package configuration for app is ignored. Any ideas on how to handle this?

Thank you,
Robin

**Comment by guybedford** [comment]
Try adding - 

```
System.config({
  paths: {
    'app/': 'app/'
  }
});
```

and see if that works?

**Comment by rweng** [comment]
That helped, yeah. However, for fully making it work I had to change in my `target/dev` directory and execute the builder there, otherwise I would have to adjust all paths (including the packageConfigPaths). I do this by triggering gulp in a separate process, see [here](https://github.com/rweng/fox-vision/blob/simplify_systemjs/web/gulp/tasks/dist.js#L32). Maybe you have an idea how to improve this without having to remap my system.config.js.

Now there is still a problem remaining and that is that when I run the app with the bundle via `gulp clean dist --backend=fv.arcanio.com`, I get errors that `http://localhost:3001/node_modules/lodash/package.json ` is missing. Seems the builder does not include the `package.json` files. Should the json files even be?

Thanks for your help, Guy!

**Comment by guybedford** [comment]
package.json files will be included in the build if they are required. Just let me know if you still need help with this.
