### ISSUE TITLE
Babel self-contained option

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#55]
We need a builder option to enable the self-contained runtime mode for 6to5.

It should allow a customizable runtime "package name" where to find the 6to5 runtime package.

Then this should be on by default.

**Comment by guybedford** [comment]
This same option could work with Traceur if we get https://github.com/google/traceur-compiler/issues/1667.

**Comment by guybedford** [comment]
This has now been separated from the runtime.

**Comment by chicoxyzzy** [comment]
do you have any recommendations for workaround?

**Comment by guybedford** [comment]
@chicoxyzzy are you looking for self-contained runtime or just "separate runtime"? The separate runtime issue will be worked on this week with some luck.

**Comment by chicoxyzzy** [comment]
I am looking for self-contained runtime

**Comment by gnimmelf** [comment]
Bump, self-contained runtime.

**Comment by guybedford** [comment]
This is supported by setting `babelOptions.optional = ['runtime']`. The next jspm release comes with this feature set by default.
