### ISSUE TITLE
Is there a sample application example that uses the compiled output from systemjs builder?

### ISSUE THREAD

**Issue by akiander** [systemjs/builder#550]
The reason I ask is because we have a large TypeScript/Angular2 web application that works fine when we use systemjs at runtime, but nothing works when we try to pre-build it and run it from the bundle. 

Can you point us at an example that shows what needs to be done once we have successfully compiled the application into a bundle?

**Comment by guybedford** [comment]
I'd suggest following an existing Angular example project if you can here, I don't know the best one to suggest offhand.
