### ISSUE TITLE
How to ignore cdn based system js modules, like that of libraries, while building with system js builder

### ISSUE THREAD

**Issue by devin6391** [systemjs/builder#551]
Hi,
I am making an angular2 project. I am including the angular2 module from CDN and it is not present in my local development system. I have no mapping for angular2 in my config.js too. 
I want to bundle my local system js modules into a single js file. But I cannot do so as my local modules import angular2. I have been trying hard to overcome this but it doesn't work.
I think I am missing something in system js' documentation. Or CDN based modules are not supported while building with system js builder.

**Comment by asapach** [comment]
Try something like this (depending on how you're loading your modules):
```
meta: {
  "angular/*": {
    build: false
  }
}
```

**Comment by devin6391** [comment]
Thanks
