### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by fantaclaus** [systemjs/builder#552]
I try to make a bundle from js files produced by Typescript compiler.

When I use a function with a default value for an argument, SystemJS Builder gives me the error:

```
Build error
{ [Error: Error on instantiate for main.js at file:///D:/test/main.js
	SyntaxError: Unexpected token =
	    at Object.exports.runInThisContext (vm.js:53:16)
	    at SystemJSNodeLoader.loader.instantiate (D:\test\node_modules\systemjs-builder\compilers\amd.js:292:30)
	    at SystemJSNodeLoader.loader.instantiate (D:\test\node_modules\systemjs-builder\compilers\esm.js:54:32)
	    at D:\test\node_modules\systemjs-builder\lib\trace.js:443:25
	    at tryCatcher (D:\test\node_modules\bluebird\js\release\util.js:16:23)
	    at Promise._settlePromiseFromHandler (D:\test\node_modules\bluebird\js\release\promise.js:502:31)
	    at Promise._settlePromise (D:\test\node_modules\bluebird\js\release\promise.js:559:18)
	    at Promise._settlePromise0 (D:\test\node_modules\bluebird\js\release\promise.js:604:10)
	    at Promise._settlePromises (D:\test\node_modules\bluebird\js\release\promise.js:683:18)
	    at Async._drainQueue (D:\test\node_modules\bluebird\js\release\async.js:138:16)
	Evaluating D:/test/main.js] originalErr: [SyntaxError: Unexpected token =] }
```

So, this is the source code:

```ts
import "jquery";

function f(n: number = 1)
{

}
```

It is compiled to:

```js
System.register(["jquery"], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    function f(n = 1) {
    }
    return {
        setters:[
            function (_1) {}],
        execute: function() {
        }
    }
});
```

I use **systemjs-builder@0.15.15**

**Comment by guybedford** [comment]
I guess this is because it can't understand the `function f(n = 1) {}` part with the default function parameter? You may have to add a TypeScript option for it to transpile that.

**Comment by fantaclaus** [comment]
Yes, you're right. But there is no separate option to transpile default parameters.

The only thing I can do is set target to `es5` and TypeScript will transpile it. But at the same time it will stop supporting `async/await` since `es5` target doesn't allow for generators which are used in Typescript's `async/await` polyfill.

There is another way: to set  `target` and `module` options to `es6` and then to use traceur/babel to transpile into `es5` during bundling. But in my case it is not a very good idea since my application is targeted to browsers which support most of `es6` features natively and using of traceur/babel runtime would be an overhead.

SystemJS Builder works fine with many `es6` features (generators, arrow functions, etc). So, it would be nice if it doesn't fail on default parameters.

**Comment by aluanhaddad** [comment]
@fantaclaus This is not an issue with the SystemJS builder, it is a transpiler issue. SystemJS is optimized for use with transpilers, but, as far as I know, it is not handling your 
> (generators, arrow functions, etc)

in any special way. Many cutting edge JavaScript runtimes just happen to support these features.

Also, I don't believe the babel runtime is in anyway required to handle default parameters as they can be statically inserted into callsites.

Also, out of curiosity, what browsers are you targeting? Last time I looked the browser (mainstream) with the richest ES6 support was Edge, and it was at something like 80%.

**Comment by fantaclaus** [comment]
@aluanhaddad I'm targeting Chrome at the first place and other modern browsers. Anyway, sooner or later each modern browser will support es6 at 100% (I hope). So we need a bundler which doesn't crash when it is fed with valid es6 code.

About traceur/babel runtime: it is needed to polyfill classes. My project uses not just default parameters but classes and other es6 features too. So when I use traceur/babel I have to attach its runtime.

**Comment by frankwallis** [comment]
@fantaclaus maybe try running it with ```node --harmony_default_parameters```

**Comment by fantaclaus** [comment]
@frankwallis Wow! It works! Thank you very much!

So it is node itself crashes on default parameters.

@guybedford I didn't expect that SystemJS Builder would execute the code of my app. Is it really necessary? It's strange that a bundler runs client code. Could it be insecure?

**Comment by guybedford** [comment]
We execute because the code returned is in the System.register format, which needs to be executed to get the deps (`System.register([...deps...], ...`). The alternative would be to use a regex to extract the deps out, but that might fail on commented out code so best to stick with it as it is I think as execution is the quickest parsing method.

Since Node will typically always provide the most ES6 features, I don't think this is too much of a limitation.

**Comment by fantaclaus** [comment]
Ok. Thank you for explanation.
