### ISSUE TITLE
builder doesn't support leading "/" notation in paths

### ISSUE THREAD

**Issue by npbenjohnson** [systemjs/builder#554]
Using a leading / on paths to specify files should be loaded from the base of a site works in the browser. With the builder I would expect it to use the base path but it just looks for it at file:///file.js (3 dashes because it doesn't try to resolve the dash)

**Comment by guybedford** [comment]
I understand this is a catch, but SystemJS has no concept of the rootURL, only a baseURL.

Also we treat the client and server equally. That is `/x.js` on the file system really does mean `file:///file.js` as we use file URLs.

We could potentially amend the error message here to be more useful as well.
