### ISSUE TITLE
Builder not applying path remapping to metadata.

### ISSUE THREAD

**Issue by nickvdyck** [systemjs/builder#558]
Hi, we are currently using systemjs and systemjs-builder in combination with npm and `node_modules`. When we serve up our application everything works fine and all mappings to modules in the `node_modules` folder are working correctly. But when we bundle our modules with systemjs-builder, its not applying the given metadata to the module. And this results in the module returning a different object reference than expected. This is apparently due to the metadata not being mapped and systemjs (in browser) just diffing a snapshot of the window object before the module loaded with the window after the module loaded.

Our config file looks a bit like the following (simplified version):
```js
System.config({
    baseURL: '/',
    defaultJSExtensions: true,
    transpiler: 'babel',
    babelOptions: {
        'optional': [
            'runtime'
        ]
    },
    meta: {
        'angular': {
            'format': 'global',
            'exports': 'angular'
        },
        'angular-resource': [
            'angular'
        ],
    },
    map: {
        'angular': 'node_modules/angular/angular',
        'angular-resource': 'node_modules/angular-resource/angular-resource',
        'babel': 'node_modules/babel-core/browser.js',
        'systemjs': 'node_modules/systemjs/dist/system.js',
        'system-polyfills': 'node_modules/systemjs/dist/system-polyfills.js',
        'babel-core': 'node_modules/babel-core',
        'babel-runtime': 'node_modules/babel-runtime',
        'core-js': 'node_modules/babel-runtime/core-js',
        'core-js/library': 'node_modules/babel-runtime/node_modules/core-js/library',
    }
});
```

And we got a nice script to bundle this all up, which kinda looks something like this:
```js
var Builder = require('systemjs-builder');
var builder = new Builder('app', 'app/config.js');

builder.config({
    paths: {
        'node_modules/*': './node_modules/*'
    }
});

builder.bundle('app.js', './dist/app.js', {
    minify      : false,
    sourceMaps  : true,
    mangle      : false
})
.then(function() {
    // console.log('success', arguments);
})
.catch(function (error) {
    console.log('error', error);
});
```

Using the config method of the builder doesn't seem to apply the new mapping to the given metadata. If i put a debugger statement during the build on the following line: https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L4757. The meta variable contains the following values: 
![screen shot 2016-04-18 at 17 34 01](https://cloud.githubusercontent.com/assets/6469315/14611711/8e3901dc-058b-11e6-9989-c3c021fea812.png)

It still assumes that the `node_modules` folder is inside the `app` folder and the correct metadata is not being applied.

Which gives us the following build file. (In there you can see that the prepareGlobal function doesn't have the angular value as the second argument (which it should have as far is I understand)):

```js
System.registerDynamic("node_modules/angular/angular.js", [], false, function($__require, $__exports, $__module) {
  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);
```

The following is a mall repro of the whole case: [builder_repo.tar.gz](https://github.com/systemjs/builder/files/224245/builder_repo.tar.gz). And although this repro may seem a bit weird, it represent a very slimmed down version of what we have setup.

It accepts the following commands:
- `npm run server` : to start up a server
- `npm run build`: to build files into the dist folder

`index.html` contains the dev version and the `index.bundle.html` will serve up the build assets.

If you serve up these pages it will tell you that angular got loaded correctly for the `index.html` page but not for the bundled page.

I'm not sure if this is a weird edge case or wrong config we are using or if this is a bug in systemjs or systemjs-builder. I actually gave up debugging this one.

Your help and feedback is much appreciated!

**Comment by guybedford** [comment]
The issue here is that the build-specific paths setting:

```javascript
builder.config({
    paths: {
        'node_modules/*': './node_modules/*'
    }
});
```

needs to be set _before_ loading the configuration file.

Try:

```javascript
var builder = new Builder('app');

builder.config({
    paths: {
        'node_modules/*': './node_modules/*'
    }
});

builder.loadConfigSync('app/config.js');
```

**Comment by guybedford** [comment]
(I know configuration ordering can be a pain, there's a possible feature in the next SystemJS major to batch configuration calls into an internal configuration queue to avoid these types of issues)

**Comment by nickvdyck** [comment]
Thanks for the quick response, that seems to be working. Although we need to redo a bit of our bundling code. Being able to batch your configuration would be great, and would certainly helped us out. The next SystemJS is that 0.17, and is this api documented somewhere?  I saw the loadConfigSync function while debugging our mess, but is there some extended documentation somewhere or only the readme and systemjs wiki?

**Comment by guybedford** [comment]
Yes the next SystemJS will be 0.20, but that will be much later this year. The builder API docs are lacking yes. This is all on the [roadmap](https://github.com/jspm/project/blob/master/ROADMAP.md) if it helps to know.
