### ISSUE TITLE
Static/SFX build errors in browser when commonjs module exports window.location as default export

### ISSUE THREAD

**Issue by joeldenning** [systemjs/builder#559]
This issue is basically identical to systemjs/systemjs#1192 (fixed with systemjs/systemjs#1193), except the problem is manifested in sfx builds. Basically, IE11 throws an Error if you call `Object.getOwnPropertyDescriptor` on `window.location`.

A popular npm module that does this is [sockjs-client](https://github.com/sockjs/sockjs-client), specifically their [location](https://github.com/sockjs/sockjs-client/blob/master/lib/location.js#L3) module.

I've got a PR coming that should fix this, with code being the same as what I did in systemjs/systemjs#1192

**Comment by guybedford** [comment]
Released in 0.15.16.
