### ISSUE TITLE
Can't bundle whole app in single file

### ISSUE THREAD

**Issue by filipesilva** [systemjs/builder#566]
Heya,

Apologies if the title is a bit vague. I've an Angular 2 app that I'm trying to bundle using SystemJS builder. There's a main entry point (`main.js`) that loads an app package (`app/index.js`), and these have dependencies on Angular 2 and RxJS.

My config looks like this:
```
{
  map: {
    main: 'main.js',
    angular2: 'vendor/angular2',
    rxjs: 'vendor/rxjs',
    'reflect-metadata': 'vendor/reflect-metadata/temp/Reflect.js',
    'zone.js': 'vendor/zone.js/dist/zone.js',
  },
  packages: {
    app: {
      format: 'register',
      defaultExtension: 'js',
      main: 'index'
    },
    angular2: {
      defaultExtension: 'js',
    },
    rxjs: {
      defaultExtension: 'js'
    },
    'angular2-polyfills': {
      format: 'global'
    },
    'reflect-metadata': {
      format: 'global'
    },
    'zone.js': {
      format: 'global'
    }
  }
}
```

Using the following code, I can create 3 bundles (`vendor/vendor.js`, `main.js` and `app/index.js`) that contain the full application, and work correctly. The only catch is that I have to import `vendor/vendor.js` via a script tag.

```
builder.bundle('main - [main] - [app/**/*]', 'vendor/vendor.js')
  .then(() => builder.bundle('main - [app/**/*] - vendor/vendor.js', 'main.js'))
  .then(() => builder.bundle('app - vendor/vendor.js', 'app/index.js'))
```

I was also trying to make a single bundle with everything via the following code:

```
builder.bundle('main', 'dist/main.js')
```

This doesn't seem to work for me. SystemJS still tries to load all individual Angular2 files instead of using the bundle. Am I missing some configuration?

**Comment by guybedford** [comment]
If the first case is working there's no reason the second case shouldn't as well. I guess make sure you're doing things consistently between the two in terms of the production page loading process?

Loading vendor through a script tag does sound the most sensible loading approach for a common bundle. Deferred loading of common bundles is straightforward to do through bundles config, but probably isn't needed here.

**Comment by filipesilva** [comment]
Thanks for the confirmation that it should work @guybedford, I was beginning to doubt my sanity.

I was trying to put up a test repo to show this behaviour, trimming down anything unnecessary, and eventually it just worked. The problem was somewhere in my code all along, but now I have a working copy and will extrapolate from that.

Cheers!

**Comment by nickmkk** [comment]
@filipesilva I have the same issue right now, just curious, did you ever figure out what was causing SystemJS to ignore the bundle and load all files individually?

**Comment by filipesilva** [comment]
@nickmkk I did at the time, while trying to do a simple repro. I don't remember now what I changed though... :/
