### ISSUE TITLE
plugin-css + css-directory = messed up path

### ISSUE THREAD

**Issue by GlurG** [systemjs/builder#572]
I think I have encountered a corner case when it comes to bundling style sheets with JSPM. Here is the relevant part of my config.js:
```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*"
  },

  meta: {
    "boot": {
      "deps": [
        "font-awesome.css!",
        "css/main.css!" // <--- offending line (renaming the "css" directory to "styles/" fixes the problem)
      ]
    },
    ...more meta stuff...
  }

  map: {
    "css": "github:systemjs/plugin-css@0.1.21",
    "font-awesome.css": "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.1/css/font-awesome.css
    ...more map stuff...
  }
```
And the relevant part of my package.json:
```
"jspm": {
    "directories": {
      "baseURL": "client"
    },
    "dependencies": {
      "css": "github:systemjs/plugin-css@^0.1.21",
      "text": "github:systemjs/plugin-text@^0.0.7"
    },
    "devDependencies": {}
  }
```
And my directory structure is basically:

```
package.json
client/config.js
client/boot.js
client/css/main.css
client/css/vendor/...
client/js/...
client/js/vendor/...
```
Upon running `jspm bundle boot bundle.js --skip-source-maps` I encounter the following error:
```
Building the bundle tree for boot...

  boot.js
  github:systemjs/plugin-css@0.1.21/main.css!github:systemjs/plugin-css@0.1.21.js
  js/lib/jquery-plugins.js
  js/lib/notify.js
  js/vendor/formValidation.bootstrap.min.js
  js/vendor/formValidation.min.js
  js/vendor/tracekit.min.js
  styles/vendor/formValidation.min.css!github:systemjs/plugin-css@0.1.21.js

err  Error: CSS Plugin:
  Broken @import declaration of "styles\vendor\formValidation.min.css"
  Broken @import declaration of "jspm_packages\github\systemjs\plugin-css@0.1.21\main.css"
      at SystemJSNodeLoader.exports.bundle (file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/github/systemjs/plugin-css@0.1.21/css-builder.js:76:13)
      at file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/github/systemjs/plugin-css@0.1.21/css.js:89:29
```
My guess is that I have the css plugin installed (via JSPM) which maps the string "css" -> "github:systemjs/plugin-css@0.1.21", so the path to "main.css" ends up being messed up. As I mentioned in the comment above, renaming my directory from "css" -> "styles" solves it.

SystemJS version = 0.19.26
JSPM version = 0.16.33

Just putting it out there in case others have encountered the same problem :)

**Comment by GlurG** [comment]
Somewhat related to the issue above. The bundle generator seems to incorrectly handle the font-awesome.css! case. font-awesome.css! is loaded via the css-plugin (hence the exclamation-mark), which gets referenced incorrectly in the final bundle.js:
```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*"
  },

  meta: {
    "boot": {
      "deps": [
        "font-awesome.css!",
        "styles/main.css!"
      ]
    },
    ...

  map: {
    "font-awesome.css": "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.1/css/font-awesome.css",
    "css": "github:systemjs/plugin-css@0.1.21",
    ...
```
Upon running `jspm bundle boot --skip-source-maps client/bundle.js` the bundle contains the following erreneous path: `System.registerDynamic("boot.js", [..., "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.1/css/font-awesome.css!file:///C:/Projects/spoilstoolbox.com/client/jspm_packages/github/systemjs/plugin-css@0.1.21.js", ...], true, function($__require, exports, module) {`
The css-plugin is referenced with `file:///C:/Projects/spoilstoolbox.com/`...which obviously breaks when I load the bundle.js in the browser.

**Comment by guybedford** [comment]
This is a common problem unfortunately due to the `css` plugin name clashing with the `css` folder name. The fix is to reference the folder `./css/main.css` with a relative path so it distinguishes the namespace, but even that is blocked by https://github.com/systemjs/systemjs/issues/1230, so the best thing is just to do a renaming like this.
