### ISSUE TITLE
Bundled Code Will Not Run

### ISSUE THREAD

**Issue by mattdemps** [systemjs/builder#576]
I have code written in ES6(2015), and the code will transpile on the fly when using System.import() during runtime.  However if I try and bundle/transpile that same code with the same configuration it will not run if included with a script tag (or System.import for that matter), even though SystemJS is loaded first.

I have tried this with both Traceur (including the tracuer-runtime prior to the bundled/transpiled traceur code) and Babel.  Both load up the file and the wrapping transpiled code does run, but the inner functions that I have written do not.

I can bundle up code and have systemjs register all of the modules in that bundle, then when I do a System.import(), any "import" statements referencing one of those modules will work if the newly imported module has not been bundled prior to runtime.

Essentially what I need is the SFX build, but without the SystemJS included (since I will have multiple bundles that load at different times, and only need one instance of SystemJS).

What can I do to get a bundle to act the same as a runtime System.import() ?

**Comment by asapach** [comment]
Maybe this is what you need: [`jspm --inject`](https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md#loading-a-bundle-automatically-inject)

**Comment by mattdemps** [comment]
@asapach Thank you for your reply.  I am not using JSPM at the moment, I am pulling my packages with NPM and bundling for production (thought I will investigate JSPM in the future).  Even though I don't see the benefit of using JSPM over System-Builder in this  instance (since I am not using it as a package manager), a code snippet in the JSPM documentation has helped me realize that I need to load my bundle with a script tag, but then also call `System.import('bundle_key.js')` to fire off the code.

```html
<script src="js/API.js"></script>
<script src="layouts/tier1/js/tier1.js"></script>

<script>
    System.import('tier1.js');
</script>
```
