### ISSUE TITLE
Trouble with conditional loading

### ISSUE THREAD

**Issue by Nehon** [systemjs/builder#577]
Hello,
I fail to have the conditional loading to work with system.buildStatic.
I've been following this documentation : http://jspm.io/0.17-beta-guide/conditional-loading.html
My use case is that I want to switch a configuration file when ever a certain parameter is passed to my build.
I'm working with jspm 0.17 beta with typescript and the typescript plugin

So here is what I have : 
My jspm configuration looks like that
```
SystemJS.config({
  transpiler: "plugin-typescript",
  typescriptOptions: {
    "tsconfig": true
  },
  packages: {
    "app": {
      "main": "main",
      "defaultExtension": "ts",
      "map": {
        "authConfig":{
          "skipConfiguration": "./session/auth.config-travis.ts",
          "~skipConfiguration": "./session/auth.config.ts"
        }
      }
    },

  },

});
```
From my understanding whenever I import "authConfig" system will resolve the path to ./session/auth.config.ts if the skipConfiguration param is not set or false else ./session/auth.config-travis.ts

My import looks like this: 
```
import {authConfig} from "authConfig";
```
**And when I run the app, it actually works.**

Then I want to build the app, and I use buildStatic in a gulp task : 
```
 static bundle(done) {
        let builder = new Builder("./", "jspm.browser.js");

        builder.loadConfig("jspm.config.js")
            .then(() => {
                builder.buildStatic("app", "./.tmp/app.js", { minify: true, skipConfiguration: true, browser:true, sourceMaps: false, runtime:false})
                    .then(() => {return done()})
                    .catch((ex) => {done(new Error(ex));
                });
        });
    }
```
My jspm.browser.js looks like this : 
```
SystemJS.config({
  baseURL: "/",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  }
});

```
this fails with this error : 
Error: TypeError: No resolution found at all for condition app/#:authConfig

I feel the issue is a path issue, but, I can't figure it out.
Your insight would be greatly appreciated.

EDIT: 
Forgot to mention the folder structure of my app :
```
/
   |_app/
      |_session
         |_ here are the ts files using the import and the actual files to import.
   jspm.config.js
   jspm.browser.js
   package.json
   ...
```

**Comment by mazniak** [comment]
I could be wrong but based on my reading of 0.15.16 code support for arbitrary conditions isn't supported? definition of `processTraceOpts()` in `builder.js#332` indicates only "browser", "node" and "production" flags (and their ~ opposites) are set without the ability to define any others.

**Comment by guybedford** [comment]
Arbitrary conditions like you expected have since been implemented - they weren't previously.
