### ISSUE TITLE
API for invalidating cache on changed files? (Sharing Builder instance)

### ISSUE THREAD

**Issue by swernerx** [systemjs/builder#579]
I am using JSPM builder inside Gulp like that:

```js
const jspmBuilder = new jspm.Builder("src", "jspm.config.js")

gulp.task("js:main", function() {
  jspmBuilder.bundle("app/main", "main.bundle.js", jspm_options)
})

gulp.task("watch", [ "build" ], function()
{
  gulp.watch([
    "src/**/*.js"
  ], [ "js:main" ])
})
```

Interestingly there seems to be some file caching in place somewhere inside the builder.

What I experience is the following:

1. First build works fine
2. Following builds based on the gulp watcher are being rebuilded, but using the old file content.

Moving the initialization of the `jspm.Builder` inside the `js:main` task fixes this issue.

I care about good life circle and performance during development of larger applications so I figured that sharing the same builder instance for each build is a good pattern. Interestingly this does not seem to work.

Is there any workaround for can use to tell the `Builder` to invalidate changed files? Or can we make it smarter regarding its built-in caching?

**Comment by swernerx** [comment]
I am using jspm@0.17.0-beta.14. And I am accessing the `Builder` contructor via the `jspm` import:

```js
import jspm from "jspm"
```

**Comment by guybedford** [comment]
You can run `builder.reset()` between builds. This won't clear the cache, but will just mark the cache as needing revalidation from file statting. Yes this needs to be documented!

**Comment by guybedford** [comment]
`builder.invalidate(fileName)` can also be used to invalidated individual files, supporting wildcards as well.

**Comment by swernerx** [comment]
Thanks for sharing the "invalidate" call. That's super awesome and works very good:

https://github.com/sebastian-software/modern-spa-boilerplate/commit/2e7d4742518d4c60fb221326f48d9ae8d74c0fba

I see pretty quick rebuild times:

```
[15:37:13] Changed: src/components/Test.js
[15:37:13] Starting 'js:main'...
[15:37:13] Finished 'js:main' after 164 μs
```

That's much better than the initial runtime:

```
[14:59:54] Starting 'js:main'...
[14:59:54] Finished 'js:main' after 1.28 ms
```

which is super useful for live rebuilding/reloading.

I think I prefer that approach over transpiling in the browser.

**Comment by swernerx** [comment]
Maybe we should close this task and open another one for documenting this useful API.

**Comment by guybedford** [comment]
Sure, I've made a note in the issue at https://github.com/systemjs/builder/issues/250#issuecomment-152299085.
