### ISSUE TITLE
Source map paths are relative to `baseURL`, instead of `outPath`

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#58]
The source map chaining in https://github.com/systemjs/builder/blob/master/compilers/es6.js#L59 seems to work correctly.

But I'm not sure why it isn't failing because the `sources` array contains module names like `file` instead of `file.js`.

Given this, how is Traceur knowing that the original file is `file.js`? Is it from `load.address`? That seems like the wrong assumption to be making?

**Comment by crisptrutski** [comment]
Haven't look at that at all. Is this really a chaining issue though, perhaps I'm misunderstanding but sounds like the issue is with the vanilla traceur sourcemap or the input map (chaining should not generate any source names of its own)

**Comment by guybedford** [comment]
@crisptrutski did you manage to look into this?

**Comment by crisptrutski** [comment]
Took a quick look - those names are coming from `load.name` (https://github.com/systemjs/builder/blob/master/compilers/es6.js#L44). We don't seem to have the base path in scope here (we could work backwards from the name.. hacky). 

Seems we might as well just yank the extension (if any) from the address and just plonk that on. :goat:

**Comment by guybedford** [comment]
Thanks, I'm wondering if I had my test case wrong - it should pick up the original source names from the first source file if chaining source maps being the point.

Would be nice to verify these are working correctly with some more test cases. Including if the original file was compiled from a few separate files into ES6, and then compiled into ES5, those first files should display as individual entries when debugging.

**Comment by crisptrutski** [comment]
Sure - will write specs for `[6to5, traceur]` x `[single, multiple]` source map output cases, given fixture files.

**Comment by guybedford** [comment]
Thanks that would be great.

**Comment by crisptrutski** [comment]
Hijacking this issue for key issue. Will keep "relative to baseURL" as behaviour for in-memory builds

**Comment by guybedford** [comment]
Perfect.
