### ISSUE TITLE
Why renaming SystemJS reference in buildStatic to $__System?

### ISSUE THREAD

**Issue by marcog83** [systemjs/builder#581]
Hi, thanks a lot for your excellent eco system. I started developing es6 thanks to JSPM. 
I tried to push a bit the bundler.
 My goal would be to get a single file that contains all my code. Some code is lazy loaded. As i understood, system.import is the way to load external scripts. When I work with a bundled version of the project everything is fine, but when I try to make a buildStatic things go tricky.
 System.import disappears and I have to wrap system.get into a promise to keep my API async. But my real problem is that I can't figure out how to avoid System to be renamed with $__System. Is it possible in staticBuild? I 've seen that this naming is hardcoded in at least two places :( . By other hand I saw a property in options where I can set the name, bit it's overwritten when the build is static. 

I Hope translation is not so bad.
Marco

**Comment by guybedford** [comment]
When you say `System.import` disappears, what exactly do you mean here? Can you share a short code example to illustrate?

buildStatic is designed to create a module that is completely independent of SystemJS itself. So we don't reference `System` directly in the bundling process but rather a micro loader implementation and hence the renaming.

If you want to be able to use `System.import` inside of a static build, you can do that fine, but you would need to include your own version of SystemJS in the project.

**Comment by guybedford** [comment]
Just let me know if you still need help here.
