### ISSUE TITLE
Loading a bundle automatically ?

### ISSUE THREAD

**Issue by ianjohnspain** [systemjs/builder#583]
Hi,

I was looking jspm bundle command that allows you to use --inject which modifies the config file rather than having to modify and inject a script tag into the html file.

Its documented here https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md

Can this also be done with SystemJS Builder ?

Once I have my bundle or bundles then I wouldn't need to modify my index.html to force loading of the bundles but these can come from the systemjs config file.

Any ideas ?

Thanks

**Comment by guybedford** [comment]
When bundling, `output.modules` contains the list of modules you'd need to use to create a custom bundles config. This is how jspm does injection in just this one line - https://github.com/jspm/jspm-cli/blob/master/lib/bundle.js#L80.

This should certainly be documented though, I've added it to the list at https://github.com/systemjs/builder/issues/250.

**Comment by randalvance** [comment]
@guybedford The code you pointed out is for jspm-cli. It is working for JSPM, but not for system builder. I checked builder.js for system builder and there is no option for `injectConfig` (https://github.com/systemjs/builder/blob/master/lib/builder.js#L592). Can we please reopen this?

**Comment by guybedford** [comment]
@randalvance `injectConfig` is not a SystemJS builder option as SystemJS builder does not write config - it is only an extension to the jspm SystemJS builder extension. To repeat the comment above for how to do a custom injection:

```javascript
builder.bundle('x').then(function(output) {
  var productionSystemJSConfig = {}; 
  productionSystemJSConfig.bundles['path/to/bundle.js'] = output.modules;
  saveCustomConfig(productionSystemJSConfig);
});
```

**Comment by davismj** [comment]
@guybedford since jspm [ignores config and baseURL arguments when bundling](https://github.com/jspm/jspm-cli/blob/master/lib/bundle.js#L26) there's not really a good way to build a bundle out of anything in a different baseURL folder. Do you think it would make sense to add your above code as part of an `inject` option in systemjs-builder? Or support reading baseURL from the config in jspm-cli?

**Comment by guybedford** [comment]
@davismj there are two separate baseURL values in jspm - the baseURL in the System config which is used by the browser, and the baseURL in the package.json directories, which is passed by jspm to SystemJS builder when bundling. These should refer to the same underlying path.

**Comment by davismj** [comment]
Ah, this might be the issue I was having in https://github.com/systemjs/systemjs/issues/1755. Perhaps this is just a documentation issue and I can submit a doc PR?
