### ISSUE TITLE
Build "src" folder into "dist" folder -> baseUrl problem

### ISSUE THREAD

**Issue by meriturva** [systemjs/builder#587]
We have problems building `src` folder with `node_modules` outside.

Just see repo: https://github.com/meriturva/SystemJsBuilder-587

you simple could run tasks `gulp build` and see errors.
The main problem here is that we have `system.config.js` inside `src` because we have this structure on our projects but we have to run builder on the root (where node folder is placed).
I think that it is a problem of builder `baseUrl` but it is really difficult to understand how to use it related to `node_modules` folder outside src.
Any help?
So thanks.
Diego

**Comment by guybedford** [comment]
Can you share the exact error here? Is it "Unable to find canonical name for..."?

If so, when building node_modules you need to ensure that it knows how to name the node_modules since it isn't inside the baseURL.

The way to do this is via paths configuration at build time:

```javascript
config: {
  paths: {
    'node_modules/': '../node_modules' // or whatever this path is
  }
}
```

**Comment by meriturva** [comment]
Thanks for the paths settings....but now i have a problem with `@angular/platform-browser-dynamic/platform_browser_dynamic` and `@angular/core/src/metadata` imports.
Error during `gulp build` command:
```
  originalErr: [Error: Unable to calculate canonical name to bundle file:///H:/Projects/github.com/SystemJsBuilder-587/node_modules/@angular/core/src/metadata. Ensure that this module sits within the baseURL or a wildcard path config.] }
```
Why? the test app is working well with systemjs.config.js on browser.
So thanks!
Diego

**Comment by guybedford** [comment]
If the path above for `node_modules` is configured correctly to `file:///H:/Projects/github.com/SystemJsBuilder-587/node_modules/` (`builder.config({ paths: { 'node_modules/': 'file:///H:/Projects/github.com/SystemJsBuilder-587/node_modules/' } })` is what you're after), then it will be able to calculate the canonical name.

**Comment by meriturva** [comment]
You are right @guybedford , now canonical names are calculated correctly but i have problems on metadata and platform_browser_dynamic class as explained on last post.
I attached here image about error.
Thanks.

![issue](https://cloud.githubusercontent.com/assets/5664195/15313551/4c581b6c-1c0c-11e6-912e-4706926385f5.PNG)

**Comment by guybedford** [comment]
@meriturva if `builder.loader.paths['node_modules/'] == 'file:///D:/Projects/github.com/SystemJsBuilder-587/node_modules/` (which can be verified in the build task), then it is not logically possible to get the error above. If you can confirm that exact equality, that will confirm the issue as either a bug in this invariant, or a configuration issue there that this configuration is not present.

**Comment by guybedford** [comment]
Argh sorry actually there is currently a bug in the trailing `/` form I remember now... stick with the trailing `*` in the paths configuration rather - `paths: { 'node_modules/*': 'file:///D:/Projects/github.com/SystemJsBuilder-587/node_modules/*' }`

**Comment by meriturva** [comment]
Thanks @guybedford but new configuration with trailing `*` dosen't help....i still have problem with package:
`file:///D:/Projects/github.com/SystemJsBuilder-587/node_modules/@angular/core/src/metadata`
i think it is related to name `metadata.js` that it is the same of folder `metadata` inside directory `node_modules\@angular\core\src`. am i right?
Thanks.

**Comment by guybedford** [comment]
@meriturva the canonical name calculation is simply reverse-pathing so no it isn't related to that. I think this may be a windows issue with the conflation of `/` and `\`.

**Comment by guybedford** [comment]
It's not "looking for" `core/src/metadata` it is simply running that through canonicalization. Shouldn't https://github.com/meriturva/SystemJsBuilder-587/blob/master/gulpfile.js#L13 be `'./node_modules/': './node_modules/'` rather?

**Comment by meriturva** [comment]
No @guybedford because the builder is initialize with `baseUrl = "src"` as https://github.com/meriturva/SystemJsBuilder-587/blob/master/gulpfile.js#L10

so i had to indicate `'./node_modules/': '../node_modules/'` 
do i miss something? or may be could be related to the fact that we have `src` on base url and metadata canonicalization has `src` on path but inside angular module?

**Comment by guybedford** [comment]
@meriturva only plain names (`x`) are baseURL relative. `./x` and `../x` will be normalized relative to the `process.cwd()`.

**Comment by meriturva** [comment]
I have change packages with umd files but not RxJs...in some case builder works.
Here the real strange behavior:

https://github.com/meriturva/SystemJsBuilder-587/blob/master/src/systemjs.config.js#L5-L8

If i configure on `systemjs.config.js` RxJs from `npmcdn.com` builder works otherwise (local folder) not.

**Error**:
```
error { [Error: Error tracing ./node_modules/rxjs/Subject.js at file:///H:/Projects/github.com/SystemJsBuilder-587/node_modules/rxjs/Subject.js
        Loading ./node_modules/@angular/core/core.umd.js
        Loading app/main.js
        Unable to calculate canonical name to bundle file:///H:/Projects/github.com/SystemJsBuilder-587/node_modules/rxjs/Observable. Ensure that this module sits within the baseURL or a wildcard path config.]
  originalErr: [Error: Unable to calculate canonical name to bundle file:///H:/Projects/github.com/SystemJsBuilder-587/node_modules/rxjs/Observable. Ensure that this module sits within the baseURL or a wildcard path config.] }
```
I have checked and on Rx `package.json` main is `Rx.js` and it is same file of direct call: `https://npmcdn.com/rxjs@5.0.0-beta.6`

ps: i have updated repo: https://github.com/meriturva/SystemJsBuilder-587
psps: `guld serve` live site works in every case....as usual it is just a builder issue.
psps: i'm on window 10 with node 4.4.4

**So here my thoughts**:
I'm on windows environment, sure webserver npmcdn is linux base.
Class `Subject.js` is loaded correctly (so rxjs module is configured correctly) and we don't have any folder named `subject` on package.
On the same time we have error loading `Observable` just because we have `Observable.js` file and `observable` folder.

What do you think?
Again thanks!
Diego

**Comment by guybedford** [comment]
Setting rxjs from CDN just excludes it as an external. Which is the same as adding `externals: ['rxjs']` option.

**Comment by meriturva** [comment]
Thanks @guybedford it is clear now why it works with http source. I made test in linux environment without success, same error on `Observable` class. I will contact RxJs support and update issue here.

**Comment by guybedford** [comment]
@meriturva no problem, although to reiterate my last answer, using CDN source in a build is identical to configuring that dependency as a build external.

**Comment by meriturva** [comment]
@guybedford i know now....so now for me the problem is that rxjs is not ready with a bundle version (for example current rx.umd.js file miss few WebSocket class) that's why i have to build it.
Anyway i think to give a try to http://rollupjs.org/ (because it is already used by Angular team and it could be really easy for me to integrate it).
Thanks.

**Comment by cristian-eriomenco** [comment]
@meriturva Hi, sorry for offtop, I have exactly same problems with understanding how to reference 'node_modules' from /src/index.html   or  /dist/index.html.   If you could briefly help me to understand why its failing to reference it. I have created a SO question as well: 
http://stackoverflow.com/questions/39293697/angular2-systemjs-approach-to-build-process

similar question:

http://stackoverflow.com/questions/34788209/project-structure-for-a-src-to-dist-folder-using-node-modules

I've spent 5 days on this still could not get any progress. Community on Gitter is also dead :(

**Comment by meriturva** [comment]
@cristian-eriomenco We have just moved to Rollup.

**Comment by cristian-eriomenco** [comment]
@meriturva Ok, so bundling with a "smaller" bundle.js is another viable solution to lazy-loading :). Thanks I'll look into it as well, simply because I could not get my head around a production (non bundling) workflow with systemjs. Community on Gitter and SO is dead-under-graveyard-quiet. Cheers!
