### ISSUE TITLE
Rollup documentation?

### ISSUE THREAD

**Issue by bmayen** [systemjs/builder#590]
I can't find much info on setting up rollup builds. I'm using JSPM and Typescript and I use systemjs-builder directly in my gulp task (via `jspm.Builder`) to output an sfx build. I cannot get rollup to work with this setup. I'm not actually sure if it's expected to work. Not sure if I should be filing that as a bug or if it's just a lack of information on my end.

**Comment by guybedford** [comment]
Rollup is enabled by default, but must be supported by the transpiler plugin. TypeScript rollup support is currently blocked on a TypeScript issue, which is tracking in https://github.com/frankwallis/plugin-typescript/issues/97.
