### ISSUE TITLE
exportName option for global sfx output

### ISSUE THREAD

**Issue by edoardocavazza** [systemjs/builder#591]
Hi,

I'd like to distribute my ES6 class (with its dependencies) as SFX bundle, but it seems that I can define a `globalName` only for modules. 

How can I export the class in order to instantiate it directly instead of calling `MyModule.MyClass`?

Thank you very much!

**Comment by guybedford** [comment]
We don't currently support this but we can certainly add an `exportName` option here.

**Comment by guybedford** [comment]
Exporting the top-level default export has been implemented in https://github.com/systemjs/builder/commit/550e22c46ca1631520442f40c9186479c3d2b441.

**Comment by edoardocavazza** [comment]
Thank you very much, it really works like a charm.

**Comment by guybedford** [comment]
Released in 0.15.17.
