### ISSUE TITLE
Fetch override performance

### ISSUE THREAD

**Issue by bmayen** [systemjs/builder#592]
According to the docs, fetch override should return a string. The example shows a fallback to return a Promise though. Following this example works, but it suffers a ~1s performance hit. Even if all I do is `return fetch(load)`, it's roughly 1s slower than if I don't override at all. Testing this with a very small dependency tree (3 files). Not sure if the hit is significantly more with more files.

**Comment by guybedford** [comment]
So you're saying that by just adding the build option:

```javascript
{
  fetch: function(load, fetch) {
    return fetch(load);
  }
}
```

that is enough to slow down your build by 1s running in Node!?

**Comment by bmayen** [comment]
That's what I'm seeing. I'm on Node v6.1.0. I'll do a more isolated test, separate from the rest of my build system, in case there's something else affecting this.

**Comment by bmayen** [comment]
So, to clarify, I was mistaken when I said it was a small dependency tree. Was testing against the wrong app. In the case of a small app, I'm not seeing any difference. But when run on the example provided by the Angular 2 Quickstart, it's about 1s difference. 

I have caching enabled and subsequent gulp builds are ~200ms with no fetch override. Adding the example provided above adds ~1s to that.

**Comment by guybedford** [comment]
@bmayen I think this is just because adding a custom fetch hook means bypassing the standard fetch cache. A custom fetch hook needs to manually set `load.metadata.timestamp` on the load record for cache matching.

**Comment by guybedford** [comment]
But yes, we should probably ensure the default fetch hook provided here does standard cache metadata automatically...

**Comment by guybedford** [comment]
Included in https://github.com/systemjs/builder/commit/61d75408fa2af1cd5cc97569b28c8fe7cd593b7c.

**Comment by bmayen** [comment]
Thanks!
