### ISSUE TITLE
Minification takes a very long time

### ISSUE THREAD

**Issue by mravey** [systemjs/builder#596]
When bundling and minifying our application with builder it takes a little bit more than 5 minutes to execute the whole process. When we dont minify it it takes only 8 seconds. One idea I had and I tried to implement in systemjs/builder was to minify each file separately before joining them. My very quick code looks like this:

```javascript
if (minify) {
	var uglify = require('uglify-js');

	outputObj.sources = outputObj.sources.map(function(source) {
		try {
			return uglify.minify(source, {fromString: true}).code;
		} catch(e) {
			return source;
		}
	});
}
```

and I've inserted it just before this line https://github.com/systemjs/builder/blob/85b5c671a63e094927d18e166862076544fb8823/lib/output.js#L65 . With this approach the whole process comes down to less than a minute.
What do you think about it ?

**Comment by guybedford** [comment]
Those numbers are really impressive to hear. Yes this is definitely the direction to move in.

The additional benefit is that we can then also cache the minification process with the normal load caching process (`load.sourceMinified = minify(load.source`), which has been tracking for a while at https://github.com/systemjs/builder/issues/209.

**Comment by guybedford** [comment]
The above issue is tracking granular minification and a granular minification cache. Contributions here are very welcome.
