### ISSUE TITLE
How to preserve license comments when minifying?

### ISSUE THREAD

**Issue by Rush** [systemjs/builder#597]
I know that Uglify takes the `comments` option to do this and I tried passing it to my build process in various ways:
```js
    var builder = new jspm.Builder();
    return builder.buildStatic(moduleName,  builtJs, {
      runtime: true,
      sourceMaps: true,
      minify: !options.debug
      comments: true,
      uglify: {
        comments: true
      }
    })
```
But neither seems to work. Can you help?

**Comment by guybedford** [comment]
Note that Traceur does not support any comments, so if building AMD, commonjs or globals (which all run through Traceur), comments must be stripped!

We're gradually moving over all internal transformations to Babel to ensure comments are never removed. Then this actual issue has been tracking for a while in https://github.com/systemjs/builder/issues/329 as well.

**Comment by guybedford** [comment]
This is being tracked in these two issues: https://github.com/systemjs/builder/issues/489, https://github.com/systemjs/builder/issues/329.

**Comment by httpete** [comment]
I can't see the right way to do this. This is the most common workflow, stripping all comments except licenses.
