### ISSUE TITLE
Module exported using System.amdDefine instead of System.registerDynamic

### ISSUE THREAD

**Issue by SonofNun15** [systemjs/builder#598]
My package references `node-uuid` along with other external npm dependencies. Many of the larger dependencies I chose to exclude from bundle using `meta: { dep: { build: false } }`. I did NOT exclude node-uuid because it is a small package and I wanted it to be wrapped inside of my package to reduce the number of peer dependencies. 

In the output, there is not a `System.registerDynamic("node_modules/node-uuid")` entry. Instead, it appears that the export is using:

```
(function() {
var define = System.amdDefine;
(function(_window) {
  'use strict';
  var _rng,

// ... Many lines of code

  if (('undefined' !== typeof module) && module.exports) {
    module.exports = uuid;
  } else if (typeof define === 'function' && define.amd) {
    define("node_modules/node-uuid/uuid", [], function() {
      return uuid;
    });
  } else {
    _previousRoot = _window.uuid;
    uuid.noConflict = function() {
      _window.uuid = _previousRoot;
      return uuid;
    };
    _window.uuid = uuid;
  }
})('undefined' !== typeof window ? window : null);

})();
```

Is SystemJS Builder somehow deciding to use AMD as a format for this export while all of the other modules are exported using the `register` format?

**Comment by guybedford** [comment]
Yes this is how SystemJS builds AMD dependencies, but it shouldn't be an issue though?

The `node-uuid` module was detected as AMD by SystemJS and built as AMD. The only alternative way to interpret it would be as CommonJS instead of AMD by using metadata to enforce that. AMD takes preference over CommonJS in SystemJS though, then you would see the `System.registerDynamic` output for the file.

**Comment by SonofNun15** [comment]
I don't have a problem with AMD strictly speaking, but the issue is that my code that is consuming this built bundle is making a network request for `node-uuid` and getting a 404. So my primary concern is that I want SystemJS to recognize that `node-uuid` is already present and use the loaded version instead of making a AJAX request to retrieve it. `registerDynamic()` definitely works in this case, but amdDefine doesn't appear to?

**Comment by guybedford** [comment]
You can try adding some debugger statements to see if the AMD define path is actually triggering there at all (`else if (typeof define === 'function' && define.amd) { console.log('defining node-uid'); define("node_modules/node-uuid/uuid", [], function() {...`). amdDefine does just behave identically to System.registerDynamic.

**Comment by SonofNun15** [comment]
Good to know. I'll check to see if `define` is getting called. Thanks!

**Comment by SonofNun15** [comment]
Turns out it was an issue with my mapping. Needed to map `'node-uuid': 'node_modules/node-uuid/uuid'`. Thanks so much for the input, it's really helpful to understand how SystemJS processes AMD / CJS for bundling!

**Comment by guybedford** [comment]
Sure, no problem!
