### ISSUE TITLE
How to load multiple files from single bundle?

### ISSUE THREAD

**Issue by oodboo** [systemjs/builder#599]
We would like to bundle angular project files into single vendor.js file as:

        @angular/common
        @angular/compiler
        @angular/core
        @angular/http
        @angular/platform-browser
        @angular/platform-browser-dynamic
        @angular/router
        @angular/testing
        lodash
        rxjs
        -------------------------------> vendor.js

How to load those components from that single file into SystemJS config?

(Although to be honest question is how to bundle them so that it will allow SystemJs to import them in the first place...)
main.js should compiled by tsc and should be run in usual http-server way ... (We do not want to minify of bundle those in dev....)

**Comment by guybedford** [comment]
It's best to follow an existing guide here that shows the correct configuration.
