### ISSUE TITLE
6to5 sfx bundles not normalizing

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#60]
From https://github.com/jspm/jspm-cli/issues/457.

**Comment by SekibOmazic** [comment]
Additional info (maybe it helps):

traceur:
```Javascript
System.register("lib/todo/TodoCtrl", ["lib/todo/TodoItem"], function($__export) {
````

6to5:
```Javascript
System.register("lib/todo/TodoCtrl", ["./TodoItem"], function(_export) {
```

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/builder/commit/3229ce27dc84816f2fadc0f644c2bdbd87fdf072.

**Comment by SekibOmazic** [comment]
:+1:

**Comment by SekibOmazic** [comment]
Not sure if the last commit caused some issues, but freshly built application now reports this:
```Shell
 AssertionError
_6to5: true
actual: false
expected: true
generatedMessage: false
message: "Error loading "lib/app" at http://localhost:8080/lib/app.js↵http://localhost:8080/lib/app.js: did not recognize object of type "File""
name: "AssertionError"
operator: "=="
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: AssertionError
````
This happens in `es6-module-loader.js`line 1177:

```Javascript
/**
* Return f.call(thisArg, x), or if it throws return a rejected promise for
* the thrown exception
*/
function tryCatchReject(f, x, thisArg, next) {
	try {
		next.become(getHandler(f.call(thisArg, x)));  // <---- It breaks here. 
	} catch(e) {
		next.become(new Rejected(e));
	}
}
```

In this case I'm not using `bundle-sfx` option. The index.html looks like this:

```html
    <!-- Use this for development -->
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
        System.import('lib/app').catch(console.error.bind(console));
    </script>

    <!-- Use this for production -->
<!--
    <script src="jspm_packages/traceur-runtime.js"></script>
    <script src="build.js"></script>
-->
```

Building with `traceur` causes no problems.

**Comment by guybedford** [comment]
Can you copy the rest of the stack from the message?

Also, is this running on the master here? Perhaps you need to run `npm install`?

**Comment by SekibOmazic** [comment]
Here only the rest:

```Shell
stack: "AssertionError: http://localhost:8080/lib/app.js: did not recognize object of type "File"↵    at Object.getFieldNames (http://localhost:8080/jspm_packages/6to5.js:2:28297)↵    at visitChildren (http://localhost:8080/jspm_packages/6to5.js:2:5430)↵    at Visitor.PVp.visitWithoutReset (http://localhost:8080/jspm_packages/6to5.js:2:5138)↵    at Visitor.PVp.visit (http://localhost:8080/jspm_packages/6to5.js:2:4660)↵    at Function.transform (http://localhost:8080/jspm_packages/6to5.js:3:24492)↵    at Object.exports.ast.before (http://localhost:8080/jspm_packages/6to5.js:8:19156)↵    at TransformerPass.astRun (http://localhost:8080/jspm_packages/6to5.js:6:24341)↵    at TransformerPass.transform (http://localhost:8080/jspm_packages/6to5.js:6:25382)↵    at http://localhost:8080/jspm_packages/6to5.js:4:16680↵    at arrayEach (http://localhost:8080/jspm_packages/6to5.js:18:8534)"get stack: function () { [native code] }set stack: function () { [native code] }
```

My setup:
```Shell
     Using loader versions:
       es6-module-loader@0.12.0
       systemjs@0.12.1
       6to5@3.3.1
```

I've tried with `npm install` but it didn't help.

**Comment by guybedford** [comment]
If you've updated builder from master, you'll need to run `npm install` inside the SystemJS builder folder. I think you'll find this is a 6to5 dependency issue.

**Comment by SekibOmazic** [comment]
Yes, it looks like 6to5 issue, but I started a fresh new project with `jspm dl-loader --6to5`, then after accepting default options I just added some ES6 code. Since all dependencies have been loaded by `jspm` I expected this to run out of the box - just like before.

My project structure has been made by `jspm` and looks like this:
![screen shot 2015-02-01 at 14 50 47](https://cloud.githubusercontent.com/assets/3735902/5992257/cb6311d6-aa21-11e4-971c-8e4199134f03.png)

So I have no SystemJS builder folder to run `npm install` from. And running it from the root didn't help.

**Comment by guybedford** [comment]
I'd suggest installing jspm again - `npm install -fg jspm`.

**Comment by SekibOmazic** [comment]
Hmm didn't help either. Now I'll just switch back `traceur` because I need to move on. 

Thanks for your help.

**Comment by guybedford** [comment]
@SekibOmazic perhaps see if you can work out if this is happening for a specific module by commenting out imports to narrow down the code that's breaking? It sounds like it may be a 6to5 bug.

**Comment by guybedford** [comment]
@SekibOmazic I've managed to replicate this, thanks looking into it.

**Comment by SekibOmazic** [comment]
@guybedford Cool. I was just trying to narrow it down.

**Comment by guybedford** [comment]
Fixed in 0.7.0.

**Comment by rthor** [comment]
Any news on this? Got this same problem.

**Comment by guybedford** [comment]
Ensure you update jspm and all its dependencies to the latest - SystemJS builder had a regression but it has been resolved.

**Comment by rthor** [comment]
Hmm weird, jspm was latest but probably not some of its dependencies... Works now — Thanks!
