### ISSUE TITLE
can't bundle with plugin-css imports

### ISSUE THREAD

**Issue by michaelmalonenz** [systemjs/builder#600]
As of the current release, I can no longer bundle files that take advantage of plugin-css to import css like:
`import 'mystyles.css!';`

I believe it is due to this change:
https://github.com/systemjs/builder/commit/61d75408fa2af1cd5cc97569b28c8fe7cd593b7c#diff-dde50c51d91de11d407f53423f3baeecL179

where the builder used to wrap the custom fetch in a Promise, and now it expects the loaderFetch to return a Promise, which plugin-css's does not.  I am raising the issue here because it's a change in API, that I'm not sure was intended.

**Comment by michaelmalonenz** [comment]
More information is here:
https://github.com/aurelia/bundler/issues/120

**Comment by guybedford** [comment]
Sure, no problem, added https://github.com/systemjs/builder/commit/e78f0e63d416d3079331a6fb5309574a10d4ba60.

**Comment by michaelmalonenz** [comment]
Thanks - I can confirm this fixes my problem.  Thanks for the speedy response!

**Comment by alexisargyris** [comment]
When can we expect this to be released?

Thanks a lot in advance

**Comment by barefootdeveloper** [comment]
Thanks a lot for finding and fixing this, I was stuck in a scenario where my co-workers couldn't build but I could because npm pulled down .17 and I was still on .16.    For now I locked the package to .16 and everyone is working again.

**Comment by guybedford** [comment]
Released in 0.15.18.

**Comment by barefootdeveloper** [comment]
Thanks Guy!
