### ISSUE TITLE
Could not bundle @angular modules because 'index.js' goes into module name.

### ISSUE THREAD

**Issue by vsDizzy** [systemjs/builder#603]
Hi. I'm trying ti build `@angular.js` bundle containing `core, common, compiler, ...` modules.
See the picture. `index.js` went to module name, which is wrong.
![pic](http://i.imgur.com/6RUmJRX.jpg)

**Comment by guybedford** [comment]
This is actually right, extensions are part of the module name. When running the bundle, ensure the same configuration is present before loading the bundle and everything should work out.

**Comment by guybedford** [comment]
Let me know if you need further help here at all.
