### ISSUE TITLE
packages not overriding packageConfigPaths

### ISSUE THREAD

**Issue by EmanuelEriksson** [systemjs/builder#605]
Hi

Im having problems using firebase with systemJS because its main is the node version of firebase.

Im importing all my modules with packageConfigPaths and trying to override the main for firebase using packages.

```
defaultJSExtensions: true,
packageConfigPaths: [
  '/node_modules/*/package.json'
],
paths: {
        'rxjs/*': '/rxjs/*',
        'app/*': '/app/*',
        '*': '/node_modules/*'
      },
packages: {
  'firebase': {
    configured: true,
    main: './lib/firebase-web'
  }
}
```

But it's not working, the node version is still loaded.

This works when using systemJS-builder.

**Comment by guybedford** [comment]
To debug, this check `Object.keys(System.packages)` to see that `firebase` is properly normalized into `http://site.com/node_modules/firebase` as the package name key.

**Comment by EmanuelEriksson** [comment]
Thank you, it turned out that I wasn't loading the config correctly. This config was never sent to systemJS.
