### ISSUE TITLE
Mismatched sourcesContent

### ISSUE THREAD

**Issue by circlingthesun** [systemjs/builder#607]
When I'm bundling a module that references two `location.js` files (in different directories), a `Mismatched sourcesContent` error is thrown at https://github.com/systemjs/builder/blob/master/lib/sourcemaps.js#L54. It appears this is because`map.sourceRoot` is undefined which results in the `source` variable having no path component. `map.sourceRoot` is only undefined for .js files loaded via plugin-babel inside my local `app` package. Files loaded via the text plugin and js files loaded from external packages are prefixed with their paths. I've included some of the `source` values I've observed below:

```
....
source: za-provinces.js
source: lib/github/bower-packages/bower-jstz@1.0.5/jstz.js
source: lib/github/jspm/nodelibs-process@0.2.0-alpha/process-node.js
source: lib/npm/angular-ui-router@0.2.18/release/angular-ui-router.js
source: home.js
source: lib/npm/angular-ui-router@0.2.18/release/angular-ui-router.js
source: lib/npm/oclazyload@1.0.9/dist/ocLazyLoad.js
source: app/directives/phone-number/phone-number.html
source: phone-number.js
source: app/components/public-root/public-root.html
source: public-root.js
source: app/modals/location-modal.html
...
```

My local packages config is as follows:

```js
packages: {
    "app": {
      "main": "app.js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel"
        }
      }
    }
  }
```

I'm using plugin-babel 0.11, builder 0.15.18, jspm 0.17.0-beta-16.

**Comment by guybedford** [comment]
I guess this is because the `angular-ui-router.js` entry comes up twice. It would be interesting to know why that is as well. Any way you can share an exact test case here for me to look into it further?

**Comment by circlingthesun** [comment]
The problem seems to be fixed with 0.15.18. However, I still see duplicate entries for `angular-ui-router.js` and other files. This appears to happen only for a bundle of common files that I create manually using bundle arithmetic. I do this by adding multiple trees together via `builder.addTrees()` and then removing references (via `delete agregateTree[key];`) that are referenced less than X times. The resulting tree is then bundled.

I've not really had time to create a test case. I'll try find some time for that over the weekend.

**Comment by guybedford** [comment]
Thanks for the follow-up - please do share a further test case if you can.

**Comment by circlingthesun** [comment]
I've looked into it some more and it appears that the references to `angular-ui-router.js` where in separate bundles. So the 2nd issue was a non bug.
