### ISSUE TITLE
builder.config not working anymore since latest release

### ISSUE THREAD

**Issue by micaelmbagira** [systemjs/builder#608]
I am running a the following build task

```
const Builder = require('jspm').Builder;
const builder = new Builder('./', 'jspm.config.js');

function (done) {
  builder.config({
    production: true,
    paths: {
      "github:*": "jspm_packages/github/*",
      "npm:*": "jspm_packages/npm/*"
    },
    packageConfigPaths: [
      'npm:@*/*.json',
      'npm:*.json',
      'github:*/*.json'
    ]
  });
  builder.buildStatic(
    conf.path.src('index.js'),
    conf.path.tmp('index.js')
  ).then(() => done(), done);
}
```
In this case the configuration I add with `builder.config({...})` is not working anymore since last release:
```
import {production} from '@system-env';
console.log(production); // prints undefined
``` 

When i am running the app without building before, it works and logs `false `.

**Comment by guybedford** [comment]
`production: true` should be a build option - `buildStatic('x', { production: true })` the reason for this is that the state of the build is not the same as the state of the builder (the builder itself will just run in a node environment).

There was another conditional bug in https://github.com/systemjs/builder/commit/36b9c7c4d9189fe9f1ca6647538d73ff7da8b84e which may affect this as well, I'm not completely sure though.

**Comment by micaelmbagira** [comment]
Thanks for the explanation. I tried with `production: true` as an option and also tried the https://github.com/systemjs/builder/commit/36b9c7c4d9189fe9f1ca6647538d73ff7da8b84e and it works. I'll wait until the next release then.
