### ISSUE TITLE
Unable to read dependency when using 6to5

### ISSUE THREAD

**Issue by SekibOmazic** [systemjs/builder#61]
`jspm bundle-sfx lib/app`

Output:
```Shell
     Building the single-file sfx bundle for lib/app...

err  Error: Error loading "angular" at file:/Users/sekibomazic/projects/es6/angular-es6-jspm/angular.js
     Error loading "angular" from "lib/app" at file:/Users/sekibomazic/projects/es6/angular-es6-jspm/lib/app.js
     ENOENT, open '/Users/sekibomazic/projects/es6/angular-es6-jspm/angular.js'
```

You can see `app.js` here: https://github.com/SekibOmazic/angular-es6-jspm/blob/master/lib/app.js

My settings:
jspm 0.11.1
es6-module-loader@0.13.0
systemjs@0.13.0
6to5@3.3.2

**Comment by SekibOmazic** [comment]
Related to: https://github.com/jspm/jspm-cli/issues/462

**Comment by guybedford** [comment]
Does this work in the browser ok without using bundle?

**Comment by SekibOmazic** [comment]
Unfortunately not. I think it is the same issue as https://github.com/jspm/jspm-cli/issues/462

Hm, I haven't change the code, just updated `jspm-cli` to v0.11.1

Will try everything from scratch again and give you feedback.

**Comment by guybedford** [comment]
Ok then this is not a builder issue.
