### ISSUE TITLE
Static build fails due to a missing source map file 

### ISSUE THREAD

**Issue by korya** [systemjs/builder#610]
After upgrading to `v0.15.18` I get the following error during build:

```
... [SOME LINES ARE OMMITTED] ...
[11:46:47] 'dist:bundle-app-js' errored after 314 ms
[11:46:47] Error on fetch for vendor:es6-shim.js at file:///Users/korya/dev/embedded_fw/recipes-planitar/survey/build/vendor/es6-shim.js
	Loading app/bootstrap.js
	Error: ENOENT: no such file or directory, open '/Users/korya/dev/embedded_fw/recipes-planitar/survey/build/vendor/es6-shim.map'
    at Error (native)
```

***

Indeed `build/vendor/es6-shim.js` references its source map file in a comment:

```js
...
//# sourceMappingURL=es6-shim.map
```

This files does not exist in `build/vendor` because I don't need it. I bundle my application without source maps.

***

Here is my setup. It **worked fine with `v0.15.13`**.

I'm using the following gulp task to bundle my code:

```js
gulp.task('dist:bundle-app-js', ['build'], (cb) => {
  var builder = new systemjsBuilder('./build', 'config.js');

  return builder.buildStatic('app/bootstrap.js', 'www/bundle.js', {
    runtime: false,
    minify: true,
    mangle: true,
  });
});
```

Contents of `config.js`:

```js
System.config({
  baseURL: '/',
  defaultJSExtensions: true,
  paths: {
    'vendor:*': 'vendor/*',
  },

  map: {
    'es6-shim': 'vendor:es6-shim.js',
    'lodash': 'vendor:lodash.js',
    'jquery': 'vendor:jquery.js',
    'jquery-ui': 'vendor:jquery-ui.js',
    'bootstrap': 'vendor:bootstrap.js',
    'angular': 'vendor:angular.js',
    'angular-cookies': 'vendor:angular-cookies.js',
    'angular-touch': 'vendor:angular-touch',
    'angular-ui-router': 'vendor:angular-ui-router',
    'ui-bootstrap': 'vendor:ui-bootstrap',
    'toastr': 'vendor:toastr',
    'hammer': 'vendor:hammer',
    'propagating': 'vendor:propagating',
  },
});
```

**Comment by korya** [comment]
I tried to explicitly set `sourceMaps` option  to false using:

```js
gulp.task('dist:bundle-app-js', ['build'], (cb) => {
  var builder = new systemjsBuilder('./build', 'config.js');

  return builder.buildStatic('app/bootstrap.js', 'www/bundle.js', {
    runtime: false,
    minify: true,
    mangle: true,
    sourceMaps: false,
  });
});
```

It did not help.

**Comment by korya** [comment]
I believe that is a bug. When `sourceMaps` options is not enabled, I would expect the builder to:
 1. remove any source map related info from the source code
 2. ignore `sourceMappingURL`, and not to try to open it or decode it.

**Comment by korya** [comment]
The issue can be reproduced on `v0.15.17` as well. I could not reproduce it on `v0.15.16` and below.

**Comment by korya** [comment]
I'm not sure what you've done guys, but the issue still exists in `v0.15.19`. Same setup. `v0.15.13` and `v0.15.16` work fine, but `v0.15.19` fails.

It does not matter if I specify the value of `sourceMaps` explicitly to false, or I just omit it (its value should default to false according to the docs), the result is the same -- an error. 

Do you mind to reopen the issue?

**Comment by guybedford** [comment]
This issue has some new fixes on master coming in the next release shortly.
