### ISSUE TITLE
External Angular 2 stylesheets and templates cause 404 errors in browser

### ISSUE THREAD

**Issue by RoxKilly** [systemjs/builder#611]
I'm trying to bundle my Angular 2 rc 1 app with systemjs-builder 0.15.16 `buildStatic` method.  An angular component has a view as well as  one or more stylesheets external to the script. They are referred to within the `@Component` metadata in [one of two ways](https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html)

Using absolute paths:
```
@Component({
  templateUrl: 'app/some.component.html',
  styleUrls:  ['app/some.component.css']
})
```
Using the now recommended relative paths:
```
@Component({
  moduleId: module.id,
  templateUrl: 'some.component.html',
  styleUrls:  ['some.component.css']
})
```
My app uses relative paths, and things have been working fine. Today I decided to use systemjs-builder's `buildStatic`.  The resulting file throws 404 errors whenever there is a relative path because the browser is fetching `localhost/some.component.html` instead of `localhost/app/some.component.html`.  Below is the relevant part of my **gulpfile.js**
```
var appDev = 'dev/';
var appProd = 'app/';
var typescript = require('gulp-typescript');
var tsProject = typescript.createProject('tsconfig.json');
var Builder = require('systemjs-builder');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('build-ts', function () {
    return gulp.src(appDev + '**/*.ts')
        .pipe(sourcemaps.init())
        .pipe(typescript(tsProject))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest(appProd));
});
gulp.task('bundle',['build-ts'], function() {
  
    var builder = new Builder('', './systemjs.config.js');

    return builder
        .buildStatic(appProd + '/main.js', appProd + '/bundle.js', { minify: false, sourceMaps: true})
        .then(function() {
            console.log('Build complete');
        })
        .catch(function(err) {
            console.log('Build error');
            console.log(err);
        });
});
```

With relative paths, if I run just the `build-ts` gulp task and browse the "regular" way, things work. If I run the `bundle` gulp task and try to browse the app using the `bundle.js` file, the 404 errors occur wherever the app tries to load external templates and stylesheets.  Hard-coding absolute paths everywhere seems like a bad idea. What am I missing?

PS: This is cross-posted on [stackoverflow](http://stackoverflow.com/questions/37497635/systemjs-builder-angular-2-component-relative-paths-cause-404-errors)

**Comment by guybedford** [comment]
You're not missing anything - this is kind of a hard area to get the right naming behaviours with.

Try running build static with the `encodeNames: false` build option. This will build in all the paths, but there may well still be issues.

**Comment by RoxKilly** [comment]
Oh my gosh I don't believe it it could really be that simple.  On first try the application ran!  I'll need to test it for a bit but...what difference did that make?

**Comment by armache** [comment]
Same issue.... encodeNames didn't help. Can you see the problem with this code?

const SystemJsBuilder = require('systemjs-builder');
const configPath = './systemjs.config.js';
const builder = new SystemJsBuilder('./', configPath);
builder.loadConfig(configPath)
.then(function () {
    builder.buildStatic('./app/main.js', './dist/bundle.min.js', {
        encodeNames: false
    })
})
.then(function () {
    console.log('bundle built successfully...');
});

**Comment by dicbrus** [comment]
Do we have any progress with this issue? 

Few details:
1) My app is under ./source/app 
and external html file is 
/source/app/something/something.component.html

2) buildStatic WITHOUT 'encodeNames: false' lead to 404 error, 
loading html external fils from root like '/something.component.html'

3) buildStatic WITH 'encodeNames: false'  it also lead to 404 but in a different way:
it tries to load '/source/app/something/something.component.html

everything is working fine when I use SystemJs (without systemjs builder).

Is is the only way to inline html files? Or move to webpack?

P.S. Relative paths are important for aot compilation so ... any ideas?
