### ISSUE TITLE
Package config works on dev, but failed when build

### ISSUE THREAD

**Issue by antonybudianto** [systemjs/builder#613]
Hi, I used SystemJS for module loading and SystemJS Builder for bundling, everything works well when in development, **but when bundling**, I must add [these lines](https://github.com/antonybudianto/angular2-starter/blob/master/src/systemjs.conf.js#L27-L29) to make it work.
I expect https://github.com/antonybudianto/angular2-starter/blob/master/src/systemjs.conf.js#L30 should already do the job since it alone work when module loading. 

Error I get if I didn't add those lines
```bash
error { Error on fetch for src/tmp/app/app.component at file:///Users/antony/Documents/Code/Web/angular2-starter/src/tmp/app/app.component
	Loading src/tmp/app/main.js
	Error: ENOENT: no such file or directory, open '/Users/antony/Documents/Code/Web/angular2-starter/src/tmp/app/app.component'
```

Maybe it's path related problem. or is it expected to have **two** path mapping like that? (one for normal loading, one for building), if I change `src/app` to `app`, then it works correctly without those additional lines.
Any help will be appreciated.

**Comment by antonybudianto** [comment]
Finally get it working by tricking routes on browsersync, now the `systemjs.config.js` look like
```js
    var map = {
        'app': 'src/tmp/app',
        'test': 'src/tmp/test',
        'rxjs': 'n:rxjs',
        '@angular': 'n:@angular',
        'lodash': 'n:lodash'
    };
```

my app structure:
```
src
__app (typescript files)
__tmp (compiled typescript files)
____app (same structure again with app)
__index.html
__systemjs.conf.js
```

is it a correct config for the structure?

**Comment by guybedford** [comment]
You can use `paths` configuration (instead of map) to alter the bundle naming. Paths basically act like alternatives to the baseURL. This is something that will be documented better in future.
