### ISSUE TITLE
Compile#getEncoding() should consider npm-scope package

### ISSUE THREAD

**Issue by jumperchen** [systemjs/builder#615]
According to this line - https://github.com/systemjs/builder/blob/master/lib/compile.js#L46
If the canonical is a [npm-scope package](https://docs.npmjs.com/misc/scope), it won't be encoded.

For example,
```import {MyFunc} from '@myorg/mypackage';```
This will be output as follows:
```
$__System.register("@myorg/mypackage", [], function(exports_1, context_1) {
```
So, it may be possible to check if the canonical contains a slash `/` then it won't be a system module.

**Comment by guybedford** [comment]
Released in 0.15.20.
