### ISSUE TITLE
"bundles" moved on "jspm i"

### ISSUE THREAD

**Issue by amitport** [systemjs/builder#617]
I have a "bundles" section in `jspm.config.js`. When I run `> jspm i ...` the section is moved into `jspm.browser.js`. This is a very surprising side-effect, which I have to revert manually and can't be solved by the solutions suggested in https://github.com/systemjs/builder/issues/45.

**Comment by guybedford** [comment]
Remove `jspm.browser.js` entirely if you'd rather not have bundles in there.

**Comment by amitport** [comment]
I want it, but just for the path part. Specifically, I sometimes want to use different browser file with different paths though bundles stay the same.

**Comment by guybedford** [comment]
That pattern wouldn't be supported then unfortunately as bundles configuration is browser configuration.

**Comment by guybedford** [comment]
Moved to jspm issue https://github.com/jspm/jspm-cli/issues/1896. This may actually be possible.
