### ISSUE TITLE
Question: Bundle not executing after being imported

### ISSUE THREAD

**Issue by markthethomas** [systemjs/builder#618]
Hey all,
Trying to get the builder working w/ an angular 2 app. At the moment, we have it spitting out our bundled app code, but it doesn't execute on the client. We can see that it's imported on the devtools network panel. The code that gets output seems to just be a bunch of calls to `System.registerDynamic`. What are we missing that would cause code not to execute??

calls w/ system.js in index.html that imports main (mapped):

```javascript
System.config({
        baseURL: '/',
      });
      System.import('/system.config.js').then(function() {
        // imports, just doesn't run
        System.import('main');
      }).catch(function(err) {
        console.error(err);
      });
```

Output: 
```javascript
// ...
"bundle";
System.registerDynamic("vendor/@angular/platform-browser-dynamic/src/facade/base_wrapped_exception.js", [], true, function($__require, exports, module) {
  "use strict";
  ;
//...
```

Build step (gulp):
```javascript
const gulp = require('gulp');
const Builder = require('systemjs-builder');

gulp.task('system:build', (done) => {
  let builder = new Builder('./.dev/client');

  builder.config({
    paths: {
      'vendor/*': './node_modules/*',
    },
  });

  builder.loadConfig('./.dev/client/system.config.js')
  .then(() => {
    return builder.bundle('main.js - [app/**/*]', './.dist/client/main.js', {
      minify: false,
    });
  })
  .then(() => {
    return builder.bundle('app/index.js - (app/**/*.js - [app/**/*.js])', './.dist/client/app/index.js', {
      minify: false,
    });
  })
  .then(() => {
    console.log('Build done');
    return done();
  });
});

gulp.task('system:config:dist', () => {
  return gulp.src('./.dev/client/system.config.js')
             .pipe(gulp.dest('./.dist/client'));
});
```

**Comment by guybedford** [comment]
After loading the bundle, the main entry point still needs to be triggered via `System.import('app/index.js')` after loading the bundle. Loading the bundle itself just acts as cache population setting the loader registry cache.

**Comment by Jefftopia** [comment]
@markthethomas I just ran into this issue. Include your bundle via script tag and leave your import statement unchanged. As Guy said, the bundle is just a cache - it won't load anything itself.
