### ISSUE TITLE
6to5 source maps stopped working

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#62]
It seems the sources paths aren't being set correctly anymore unfortunately.

**Comment by crisptrutski** [comment]
WIll look at this tomorrow

**Comment by guybedford** [comment]
Thanks!

**Comment by crisptrutski** [comment]
Did you spot anything specific off about the source paths?

**Comment by guybedford** [comment]
Yes I believe Traceur and 6to5 provide source maps with different base paths - so when I fixed Traceur's source maps I broke 6to5's. I think this base path management should probably be done in the es6 compiler itself to use the same system.

**Comment by guybedford** [comment]
It may be worth reading https://github.com/google/traceur-compiler/pull/1698 which may end up changing things again in Traceur 0.0.84. If necessary we can do a PR to this version rather and I can push a Traceur update through the stack when this fix is published.

**Comment by jmm** [comment]
> Yes I believe Traceur and 6to5 provide source maps with different base paths

What is the "base path" you're referencing?

**Comment by hgl** [comment]
It would be great if builder could embed file source code directly in the map (via the `sourcesContent` property), so that it's completely self contained. No need to battle with correct sources paths any more, they can always be relative to the current directory for example.

**Comment by guybedford** [comment]
@hgl while this is possible, it would be incredibly inefficient since bundles can be large, and all sources would be processed on inspection instead of just the sources being debugged. I'd rather fix any issues around battling with source paths directly.

**Comment by hgl** [comment]
Browsers should have no difficulties handling files sizing even a few mega bits, and most dev tools support searching across all js files, so they already process all sources on inspection.

Another benefit of making source map self contained is that it makes developers lives easier. Imagine you have all source code live in `src` folder, and generate the bundled file at `build` folder. If the source map isn't self contained, you need to point the web server at the parent folder of both `src` and `build` since you want the dev tool to be able to open the source code, and developers have to visit the site at `localhost:3000/build` for example.

With self contained source map, they can just point the web server to `build` and call it a day. No need to make the source code available, and access `localhost:3000` directly.

**Comment by guybedford** [comment]
Sure, it could be useful. Created https://github.com/systemjs/builder/issues/68.

**Comment by jmm** [comment]
@guybedford Did you miss my comment above?

**Comment by guybedford** [comment]
@jmm Traceur used to derive the `sourceRoot` from the input file name based on the baseURL somehow I think? I'm not sure what it's doing now at all. We did try Traceur 0.0.84 and it broke source maps here, so I'm hoping this gets sorted out.

**Comment by jmm** [comment]
@guybedford 

> Traceur used to derive the sourceRoot from the input file name based on the baseURL somehow I think?

You probably know more about what it used to do, but the only `baseURL` I know if in play here is the argument to your `concatenateSourceMaps` function.

> I'm not sure what it's doing now at all.

Here are some of the issues with what it was recently / is doing:

* Was (and maybe still is) treating `sourceRoot` as a local path, misapplying it to input paths (`sourceName`) to generate relative paths for `sources` output, *and* outputting it in the source map.

* Is altering `sourceName` value (an argument to its compile function, which is output in `sources`), apparently based on `outputName` value (an argument to its compile function, which is output as `file`).

* Was automatically generating a `sourceRoot` value from the `outputName` value. As of 0.0.84 you can decline to pass `sourceRoot` and it won't automatically insert one.

> We did try Traceur 0.0.84 and it broke source maps here, so I'm hoping this gets sorted out.

I wouldn't count on traceur's source map handling getting sorted out anytime soon without guidance from informed users.

**Comment by twalker** [comment]
It may be a mis-configuration on my part, but the `sources` paths in the sourcemap are missing the `.js` extension.

Here's the [example app I'm using to test sourcemaps with 6to5](https://github.com/twalker/jspm-6to5-example). And [here is the sourcemap missing the .js extensions](https://github.com/twalker/jspm-6to5-example/blob/master/public/js/dist/app-built.js.map#L1).

I thought this may be a related issue.

I also now realize, that the sourcemap and built file need to be in the same folder as the sourcefiles. So if you look at my example, please ignore that I'm outputting to a `dist` folder.

Thanks for any suggestions, corrections, or fixes.

**Comment by crisptrutski** [comment]
@twalker think the issue is on our side, and had a simple fix (just pushed to master)

Able to cut a builder release myself, but jspm-cli is locked down till @guybedford wakes up in a few hours  - grabbing builder code and linking manually is your best bet you're in a rush to debug your app or something :racehorse:

**Comment by twalker** [comment]
Thank you @crisptrutski .

FWIW, Getting sourcemaps working is the last piece for me to comfortably release a pretty large SPA to production with jspm + SystemJS + 6to5.  Freakishly delightful.

Just to verify, 
Do sourcemaps and bundle files need to live in the `baseURL` in order for the paths to be correct? At least until  #68 is addressed.

Thanks again.

**Comment by crisptrutski** [comment]
@twalker if I understand you correctly, while the paths will technically be correct if building outside the `baseURL`, but #68 will still be needed if those paths escape your web server resources root.

Perhaps this test sums it up: https://github.com/systemjs/builder/blob/d832c3ef35c264796b86765dadf5503d8a498196/test/unit-tests.js#L56-L75
