### ISSUE TITLE
Builder option to prevent evaluation of a plugin during build?

### ISSUE THREAD

**Issue by BenoitZugmeyer** [systemjs/builder#620]
I'm porting a large and complex application to systemjs-builder. We are using a plugin that can't be evaluated in nodejs, because it has some dependencies tied to the DOM. I know the `exports.build = false;` flag to prevent the plugin from being used when building, but it doesn't prevent the evaluation of the plugin code (and its dependencies).

I managed to prevent the plugin evaluation by using a custom `instantiate` method in the builder: https://gist.github.com/BenoitZugmeyer/18e32f9edf8e3c7e508cf82cf23c3c8a but it doesn't look very future-proof.

Is there a better way to prevent the plugin evaluation? maybe a `meta` flag or something?

**Comment by guybedford** [comment]
The way to handle these sorts of cases is to dynamically import the plugin code in the browser environment only. There are various ways of handling this from jspm 0.17 conditionals to a dynamic System.import within the hook itself.

**Comment by BenoitZugmeyer** [comment]
Does loading the plugin dynamically imply loading it separately from the bundle? Is it safe to extend `System.import`? it isn't mentioned in the [polyfill docs](https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/loader-extensions.md)

I'm sorry to bother you with my questions, I like systemjs and the builder a lot, and I'd like to make things right.

**Comment by guybedford** [comment]
In this specific case, it may be advisable to simply remap the plugin for the build itself:

```javascript
builder.config({
  map: {
    'plugin-name': 'plugin-build-exclude.js'
  }
});
```

plugin-build-exclude.js
```javascript
exports.build = false;
```

It would be nicer to just be able to do:

```javascript
builder.config({
  map: {
    'plugin-name': '@empty'
  }
});
```

for the build config ease though. I've added https://github.com/systemjs/builder/commit/5c59fdb57cf5abae41e47a670a47135dc7680c1d to make this easier.

**Comment by BenoitZugmeyer** [comment]
That's awesome, thank you very much!

**Comment by BenoitZugmeyer** [comment]
I just tried your advices but it didn't do what I expected. The first one included the `plugin-build-exclude.js` file in the dist bundle, and the second didn't include a plugin at all.

What I'd like to have is the plugin included in the final bundle, but not evaluated at build time (like the non-plugin modules). In other words, having the behavior of a plugin with `exports.build = false;`, but without evaluating it (so this flag should be in the configuration instead of the module exported values).

In any case, I'll stay with my solution (the exdended Loader in the build script) for now.

**Comment by guybedford** [comment]
The first case is correct, the wrapper should just itself be added as an exclude.
