### ISSUE TITLE
Does buildStatic support exporting global variables?

### ISSUE THREAD

**Issue by arackaf** [systemjs/builder#623]
I'm wanting to publish a static build file, so users can drop a script tag and run.  It's not essential of course, but it's a nice-to-have.  I'm trying to run

```
builder.buildStatic('src/NavBar.js - react', 'dist/NavBarStaticBuild.js', { globalDeps: { 'react': 'React' } })
```

`src/NarBar.js` does `export default NavBar;` but no NarBar variable is added to the global in the static build file (nothing appears to get exported to global, actually).  Am I missing a configuration property, or am I missing the point of buildStatic?

The docs don't say too much about what options buildStatic accepts.  Googling seems to indicate that I'm missing the point of buildStatic, in that exporting global variables is not supported, but I wanted to check here to be sure.

**Comment by guybedford** [comment]
You can set the module format of the output via - `format: 'amd'` or `format: 'umd'` etc. Let me know if that's what you're after here? Yes the docs are incomplete in this area.

**Comment by arackaf** [comment]
The format seems to default to umd, which is exactly what I want.  The problem is, in the `global` path of the UMD, the else here

```
if (typeof define == 'function' && define.amd)
    define(["react"], factory);
  else if (typeof module == 'object' && module.exports && typeof require == 'function')
    module.exports = factory(require("react"));
  else
    factory(React);
```

the result of the factory call isn't *set* to anything.

For example, the React build that comes with the npm install can be plopped into a script tag, resulting in there being a `React` global variable.

Is there a way to configure buildStatic to do the same.

**Comment by guybedford** [comment]
For this you can add the `globalName: 'React'` option.

**Comment by arackaf** [comment]
There it is.  Love the implicit global :-) 

Will you take a pr tonight to add some documentation on this (and also `globalDeps`)???

**Comment by guybedford** [comment]
Sure thanks that would be great!
