### ISSUE TITLE
Inconsistent `map` configuration behavior

### ISSUE THREAD

**Issue by BenoitZugmeyer** [systemjs/builder#625]
Followup of https://github.com/systemjs/builder/issues/620#issuecomment-225877944

* Right now it is impossible to map a plugin to another file via the main `map` configuration entry. The `map` entry in a package is working though.

* Also, mapping paths starting with a "./" never works in the main `map` configuration but works in the packages, and vice versa.

```js
const builder = new SystemJSBuilder();

builder.config({
    packages: {
        [__dirname]: {
            map: {
                // "./src/index.js": "src/index_node.js",   // Works
                // "./src/plugin.js": "src/plugin_node.js", // Works
                // "src/index.js": "src/index_node.js",     // Doesn't work
                // "src/plugin.js": "src/plugin_node.js",   // Doesn't work
            },
        }
    },

    map: {
        // "./src/index.js": "src/index_node.js",   // Doesn't work
        // "./src/plugin.js": "src/plugin_node.js", // Doesn't work
        // "src/index.js": "src/index_node.js",     // Works
        // "src/plugin.js": "src/plugin_node.js",   // Doesn't work
    }
});

builder.bundle('src/index.js', "dist.js")
    .then(() => console.log("End build"))
    .catch((e) => {
        console.log("Error:", e);
        process.exit(1);
    });
```

But maybe it's more a SystemJS issue.

Edit: last systemjs-builder stable and master

**Comment by guybedford** [comment]
All the above are correct. Non-relative package map applies to internal requires like `require('jquery')` within the package. The only one that seems questionable is the global map `src/plugin.js: src/plugin_node.js`. Global map only applies *once* to avoid circularity. So if the plugin is already mapped, that might explain why it isn't triggering.

**Comment by BenoitZugmeyer** [comment]
You sure close issues quickly! From my tests, the plugin isn't mapped at all:

```js
const builder = new SystemJSBuilder();

builder.config({
    map: {
        "src/plugin.js": "src/plugin_node.js",
    }
});

builder.bundle('src/index.js', "dist.js")
    .then(() => console.log("End build"))
    .catch((e) => {
        console.log("Error:", e);
        process.exit(1);
    });
```

With a `src/index.js` looking like this:
```js
require("./foo.js!./plugin.js");
```

Anyway, I'll digg into systemjs to try to understand why.

**Comment by guybedford** [comment]
Issues are for issues, but always happy to continue discussions.

Relative paths (./plugin) do not go through global map, only plain names
(plugin). Use paths configuration to set the plugin to empty then rather
then.

**Comment by BenoitZugmeyer** [comment]
Ok, thank you for the clarification.
