### ISSUE TITLE
Bundle SystemJS and plugins

### ISSUE THREAD

**Issue by edoardocavazza** [systemjs/builder#627]
Hi,

is there a way to bundle the polyfills, the library and some plugins (mainly loaders) in a single file? If yes, how should the config file look like?

Thanks

**Comment by guybedford** [comment]
Certainly, you can concatenate the output of SystemJS builder with the loader, configuration and polyfills. But this would have to be a manual concatenation step through a build tool or otherwise. Eg `cat promise-polyfill.js system.src.js system.config.js built-bundle.js > build.js` sort of thing.
