### ISSUE TITLE
Configure jsx transpilation with SystemJS Builder

### ISSUE THREAD

**Issue by arackaf** [systemjs/builder#629]
I'm having difficulty getting jsx transpilation working.  Config looks like this

```javascript
let builder = new Builder({
    baseURL: './'
});
builder.config({
    map: {
        'plugin-babel': 'node_modules/systemjs-plugin-babel/plugin-babel.js',
        'systemjs-babel-build': 'node_modules/systemjs-plugin-babel/systemjs-babel-node.js',
        'react': 'node_modules/react/dist/react.js',
        'react-dom': 'node_modules/react-dom/dist/react-dom.js',
        'babel-plugin-transform-react-jsx': 'node_modules/babel-plugin-transform-react-jsx/lib/index.js'
    },
    meta:{
        '*.js': {
            babelOptions: {
                es2015: false,
                plugins: ["babel-plugin-transform-react-jsx"]
            }
        }
    },
    transpiler: 'plugin-babel'
});
```

My error looks like this

> Unhandled rejection Error on translate for src/testES6.js at file:///c:/GIT/simple-react-bootstrap-navbar/src/testES6.js
        (SystemJS) Error: ENOENT: no such file or directory, open 'c:\GIT\simple-react-bootstrap-navbar\babel-helper-builder-react-jsx'
            at Error (native)
        Error loading c:/GIT/simple-react-bootstrap-navbar/babel-helper-builder-react-jsx as "babel-helper-builder-react-jsx" from c:/GIT/simple-react-bootstrap-navbar/node_modules/babel-plugin-transform-react-jsx/lib/index.js

Once I can get this working I'd be happy to send up another pr with the documentation updated.

**As a side question** - am I correct in surmising that experimental ES features are not supported by SystemJS Builder?  In other words, if I throw an object spread in the file I'm building, but set `stage2: false;` the whole build fails.  I assume ES features aren't natively supported by SystemJS Builder until they hit stage 4 / get approved?  

The error message is below.

![image](https://cloud.githubusercontent.com/assets/11261266/16106695/4af9e9d2-335c-11e6-8d6e-14e4bf351af7.png)

**Comment by arackaf** [comment]
I think I cracked it.  It looks like babelOptions isn't configured to take the jsx plugin name as a string (at least not without a ton of jspm configuration) but it *is* configured to take the actual jsx plugin itself.  Ie

```
import transpileReact from 'babel-plugin-transform-react-jsx';


let builder = new Builder({
    baseURL: './'
});
builder.config({
    map: {
        'plugin-babel': './node_modules/systemjs-plugin-babel/plugin-babel.js',
        'systemjs-babel-build': './node_modules/systemjs-plugin-babel/systemjs-babel-node.js',
        'react': 'node_modules/react/dist/react.js',
        'react-dom': 'node_modules/react-dom/dist/react-dom.js',
        'babel-plugin-transform-react-jsx': 'node_modules/babel-plugin-transform-react-jsx/lib/index.js'
    },
    meta:{
        '*.js': {
            babelOptions: {
                es2015: false,
                plugins: [transpileReact]
            }
        }
    },
    transpiler: 'plugin-babel'
});
```

Which works like a charm.

Is that the recommended usage?  I'd be happy to add to your docs some more if so.

**Comment by guybedford** [comment]
You need to install the plugin itself with jspm for it to work.

How are you executing the build task itself? Perhaps you want to just use `@node/babel-plugin-transform-react-jsx` as the identifier if you're npm installing the plugin and don't mind losing universal support.

**Comment by arackaf** [comment]
Sorry - I'm not sure I understand what `@node/babel-plugin-transform-react-jsx` means.

I'm not using jspm at all - my build processes are just some custom Node code wherein I make use of systemjs-builder, uglify-js, etc.  Something like https://github.com/arackaf/booklist/blob/master/react-redux/build/build-es6.js

**Comment by guybedford** [comment]
`@node/x` basically means defer to the NodeJS require within SystemJS.

**Comment by arackaf** [comment]
Ah!  I'm sure that'll work - thanks!
