### ISSUE TITLE
Optimized bundling

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#630]
It would be interesting to investigate the ability to generate optimized bundles that hide non-public entry points through static optimizations like the ones we have with Rollup etc.

The entire optimization could run off a single shared sfx core code possibly as well with this method where non-rollup modules are collapsed.

I'm thinking something like `staticOptimize: true / false` as a bundle option where `entryPoints` allow this process to be controlled.

This would provide significant performance improvements for large bundles not needing to individually handle private modules in the public registry.

With a large tree as well, we have lots of data to tell what is likely public or private anyway.

**Comment by guybedford** [comment]
Effectively this is allowing static optimizations from `buildStatic` to happen for private modules within `bundle`.

**Comment by laurentgoudet** [comment]
Can I ask why this has been closed? As a matter of fact this is exactly what I'm after. Bundling is great because SystemJS can still be used to dynamically load bundles/chunks and their dependencies.

**Comment by guybedford** [comment]
These sorts of optimizations are still on the roadmap.

**Comment by marioteik** [comment]
Is this still on roadmap?

**Comment by guybedford** [comment]
See https://rollupjs.org/guide/en#experimental-code-splitting.
