### ISSUE TITLE
Library production workflow

### ISSUE THREAD

**Issue by noelmace** [systemjs/builder#632]
Despite my efforts, I couldn't find any documentation / solution about the "good way" to  make a bundle for librairies projects, and I'm stuck at this point.

My main problem is that when we make a bundle via the SystemJS Builder, there is no such thing as "index / main" file which permit to make exports in the bundle file.

For example : 
* bundle a `core` folder via its index.js file into a `core.js` file which directly make the same exports as in index.js, permitting to do a `import { foo } from 'project/core'` instead of `import { foo } from 'project/core/index'`
* do exactly the same thing, but with only one bundle file (for all the project) at the end

So, this issue could be a documentation request for a library production worflow (like the one at https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md) or a feature request about managing index files exports as bundle's exports or parent folder exports (for larger bundles). I'll change the title depending on your answers.

Here is the related issue on my project : noelmace/angularjs-decorators#2 (which reference the pull requests and demos).

**Comment by noelmace** [comment]
(my bad, the previous referenced issue has no relation to this one)

**Comment by guybedford** [comment]
This is what static bundles (sfx builds) are for (or even Webpack or Rollup, it's irrelevent what tool is used for module compaction), but it has to be done carefully based on which internals and externals should apply.

**Comment by noelmace** [comment]
Thank you very much for the fast answer.

So, if I have :
```
app/

```
foo.js
```
export default let Foo = 42;
``` 
And use :
` jspm bundle-sfx app/module/index.js myModule.js`

I'll get a myModule.js file, and I can import the definitions on index with
` import { Foo } from 'myModule/

**Comment by noelmace** [comment]
Thank you very much for the fast answer. SystemJS and JSPM are a bit new to me, but they are really great.

So, if I have :
```
app/
    moduleA/
        index.js
        foo.js
``` 
core/index.js
```
export Foo from './foo.js';
```
foo.js
```
export default let Foo = 42;
``` 
And use :
` jspm bundle-sfx app/* myProject.js`

I'll get a myProject.js file, and, after a JSPM install, I can import foo with :
` import { Foo } from 'myProject/moduleA'`

without any "bundles" parameter in the systemjs config file ?

Or maybe I'm wrong on the folder structure ... if so, could you tell me what you recommend ?

I'm also not understanding why we need a micro-loader implementation if at the end, we are sure to use our library as a JSPM dependency, so with SystemJS.

**Comment by guybedford** [comment]
You'd need to rather distribute your library as separate files for these types of requires. SFX bundles just turn many modules into one as a compaction, losing the references to the external modules. Bundles themselves are not a distribution format.
