### ISSUE TITLE
Create static builds from npm modules

### ISSUE THREAD

**Issue by arackaf** [systemjs/builder#637]
Does SystemJS builder cover the use case of, essentially, bundling an npm dependency?  

For example, if I npm install foo, but foo doesn't ship with a dist file, is there a SystemJS Builder config option (absent jspm) that would build up that utility through the normal npm lookup process?

I know jspm can do that, obviously.  I'm just wondering if the normal builder is capable.

**Comment by guybedford** [comment]
Unfortunately not, you'd need to install the dependency with jspm and then do a build through jspm, and then bring it back into a new jspm project. Sub-builds are a sort of separate problem... however you do this build doesn't really matter, but it's not a concern of SystemJS Builder.

**Comment by arackaf** [comment]
Thanks much.  

I guess this is enough of an edge that keeping a jspm sandbox separate for me to just pull down needed utils to make static builds wouldn't be that big of a deal at all.
