### ISSUE TITLE
Rollup size bigger than normal bundling?

### ISSUE THREAD

**Issue by antonybudianto** [systemjs/builder#639]
Hi @guybedford , I'd like to ask **if my rollup setup is correct** because I've successfully setup the build step with rollup, but the size is **bigger** (about ~150KB diff)
- with rollup + runtime: true (~990KB) -> using provided es6 version of angular
- without rollup (~752KB) -> using provided bundled version of angular

Repo to reproduce: 
1. https://github.com/antonybudianto/angular2-starter/tree/rollup-systemjs-builder (please use **rollup-systemjs-builder** branch)
2. `npm install` in the project directory and install global gulp cli
4. gulp serve-build --es6 (will compile to es6 code and wait a while until browser popup)
5. It should successfully popup and serve like normal, but the size is bigger than normal bundling 
(try it by removing `runtime: true` in builder config, go to https://github.com/antonybudianto/angular2-starter/blob/rollup-systemjs-builder/src/systemjs.conf.js#L66 and uncomment the code, and comment the esm/index.js one, and try from step-4 again)

Systemjs config file:
https://github.com/antonybudianto/angular2-starter/blob/rollup-systemjs-builder/src/systemjs.conf.js

Systemjs builder config file:
https://github.com/antonybudianto/angular2-starter/blob/rollup-systemjs-builder/config/gulp/config.js#L49

Systemjs builder task:
https://github.com/ngstarter/systemjs-extension/blob/master/index.js#L9

I **expected** at least same or smaller size.
Any help will be appreciated! Thank you!

**Comment by guybedford** [comment]
Did you try setting `rollup: true` in the SystemJS buildStatic options?

**Comment by guybedford** [comment]
Also you can get a report of the rollup optimization by:

```javascript
builder.buildStatic('x').then(function(output) {
  console.log(output.inlineMap);
});
```

which will show what was compacted. By default rollup is disabled as it can sometimes break things.

**Comment by antonybudianto** [comment]
I tried rollup: true but no difference @guybedford

**Comment by guybedford** [comment]
If using TypeScript, are you using the SystemJS TypeScript plugin? Support for Rollup only came with that as of the very latest release. If not using that plugin, you need to ensure you're not converting into System.register with the TypeScript compiler. Again to see if Rollup is actually being used this can be debugged by checking the `output.inlineMap` value.

**Comment by antonybudianto** [comment]
I'm transpiling it to commonjs using gulp-typescript, so I didn't use SystemJS typescript plugin
I'll try outputing the inlineMap value, thanks

**Comment by antonybudianto** [comment]
but I used esm packages from angular https://github.com/antonybudianto/angular2-starter/blob/rollup-systemjs-builder/src/systemjs.conf.js#L69

**Comment by guybedford** [comment]
You must compile into esm from Typescript, TypeScript outputting CommonJS will stop Rollup from being able to apply.

**Comment by antonybudianto** [comment]
Okay, will try that, thanks for help!

**Comment by kudoz83** [comment]
I hate to revive this - but I'm at my wits end here.  Seeing the inlineMap output as`{ }` with `rollup: true`.   I assume this means rollup is not happening?  I'm using ngc to transpile.

"target": "es5",
"module": "es2015",

This is what is advised in angular2 cookbook for rollup compatibility.

**Comment by asapach** [comment]
@kudoz83 please create a separate issue with repro steps

**Comment by kudoz83** [comment]
I'm not suggesting there is an issue (yet) - I'm asking for clarification on a comment made a while ago on this thread.
