### ISSUE TITLE
buildStatic doesn´t need System.import?

### ISSUE THREAD

**Issue by davidanaya** [systemjs/builder#640]
Hi, so this is probably a noob question, but anyway, I created my first bundle for the quickstart tutorial for Angular 2, and I can´t really understand what is happening with my index.html.

So, my bundle is created like this in gulpfile.js
```
gulp.task('bundle:app', () => {
  builder.buildStatic('app/*.js', 'web/app/bundle.app.js')
  .then(function() {
    console.log('Build complete');
  })
  .catch(function(err) {
    console.log('error ' + err);
  })
})
```

Really basic; now when I use this index.html

```
<html>
  <head>
    <title>Angular 2 QuickStart Deploy</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
    <link rel="stylesheet" href="css/styles.css">
    <!-- 1. Load libraries -->
    <!-- Polyfill(s) for older browsers -->
    <script src="lib/shim.min.js"></script>
    <script src="lib/zone.js"></script>
    <script src="lib/Reflect.js"></script>
    <script src="lib/system.src.js"></script>
    <script>
      System.import('app').catch(function(err) { console.error(err); });
    </script>
  </head>
  <!-- 2. Display the application -->
  <body>
    <my-app>Loading...</my-app>
    <!-- application bundle -->
    <script src="app/bundle.app.js"></script>
  </body>
</html>
```

I get an error Unexpected token <, somehow my app is trying to load http://localhost/ois/web/app and can´t find it.

But, if I remove the System.import completely, then it works. So the thing is, I thought that line was really necesary. In stackoverflow someone suggested that this line is not needed when using a bundle. Is that correct? I did not specify any "initial" module to load and bootstrap the application.

Can anyone give me a hint on what is going on?
Thanks!

**Comment by sebasrodriguez** [comment]
@davidanaya you are right, when you build static you don't need the import. That's because you are already giving the starting module when you call 
```
buildStatic("initialFile.js", "out.js")
```

**Comment by davidanaya** [comment]
But in my case I'm not using a single file, actually I could be using something like this 'app/**/*.js', right? so in that case what would be the starting module?

**Comment by zxul767** [comment]
It doesn't matter that you're not using a single file, what the SystemJS builder does is to automatically figure out all files that will be required (i.e. all dependencies, both direct and transitive) starting from your "main" file.

**Comment by davidanaya** [comment]
ok, I get it, thanks!
