### ISSUE TITLE
(SystemJS) No provider for PlatformRef!

### ISSUE THREAD

**Issue by buddyackerman** [systemjs/builder#641]
I get that error when trying to run my App in IE 9 or 10, it works fine in IE 11.  when I drill down into the error I see the following info:

Below is the context property of a error object called originalError
    **context     < Permission denied >**

Within the originalError object there is an injectors property (an array) with on item in it and that item had an error message saying the following.

    **"ReflectiveInjector(providers: [])"**

The following scripts are being loaded in my Index page

`
script src="/Scripts/jquery-2.2.4.min.js"
    script src="/Scripts/jquery-ui-1.11.4.min.js"
    script src="/Scripts/bootstrap.min.js"
    script src="/node_modules/core-js/client/shim.js"
    script src="/node_modules/systemjs/dist/system.src.js"
    script src="/node_modules/zone.js/dist/zone.js"
    script src="/node_modules/reflect-metadata/reflect.js"
    script src="/node_modules/es6-shim/es6-shim.js"
    script src="/node_modules/intl-tel-input/build/js/intlTelInput.js"
    script src="/systemjs.config.js"

    >script<
            System.import('app').catch(function (err) { console.error(err); });
    >/script<
`

My application boot is:

`
import {bootstrap} from '@angular/platform-browser-dynamic';
import {App} from "./app.component";
import { provide } from '@angular/core';
import {APP_ROUTER_PROVIDERS} from "./app.routes";
import {disableDeprecatedForms, provideForms} from '@angular/forms';

bootstrap(App, [APP_ROUTER_PROVIDERS, disableDeprecatedForms(), provideForms()])
    .catch((err: any) => console.error(err));`

**Comment by guybedford** [comment]
Did you manage to make any progress here?

**Comment by buddyackerman** [comment]
No, i haven't really been looking into it as I've been busy just developing the app.
