### ISSUE TITLE
Unusable source maps

### ISSUE THREAD

**Issue by asapach** [systemjs/builder#642]
In #568 we've discussed the validity of produced source maps and I'd like to revisit the topic. I now find it hard to support the code in production without valid and reliable source maps.
I'm using `test/fixtures/sourcemaps-expectations/babel.tree.single.json` as an example here since it's pretty simple. I've got it visualized [here](http://sokra.github.io/source-map-visualization/#base64,ImJ1bmRsZSI7DQooZnVuY3Rpb24oKSB7DQp2YXIgZGVmaW5lID0gU3lzdGVtLmFtZERlZmluZTsNCmRlZmluZSgiYW1kLTIuanMiLCBbXSwgd2luZG93Lm0gPSB7YW1kOiAnMid9KTsNCg0KfSkoKTsNCi8vIyBzb3VyY2VNYXBwaW5nVVJMPW91dHB1dC5qcy5tYXA=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL2ZpeHR1cmVzL3Rlc3QtdHJlZS9hbWQtMi5qcyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7S0FBSyxBQUFDLENBQUMsVUFBUyxDQUFHLEdBQUMsQ0FPYixDQUFBLE1BQUssRUFBRSxFQUFJLEVBQUUsR0FBRSxDQUFHLElBQUUsQ0FBRSxDQVBXLENBT1Q7QUFBQSIsImZpbGUiOiJvdXRwdXQuanMifQ==,DQovKiBhc2RmIA0KDQpkZWZpbmUoeyBhbWQ6IDIgfSk7IC8vID8NCg0KKi8NCg0KZGVmaW5lKHdpbmRvdy5tID0geyBhbWQ6ICcyJyB9KTs=).
You can also paste [this link](https://raw.githubusercontent.com/asapach/builder/9550f78015e759db720daacda889509fe7caa462/test/output/output.js) here to poke around and explore the raw results: https://raygun.com/validatesourcemaps

While the source map seems valid (i.e. there are no offsets that are out of bounds and the source map consumers don't throw any exception), it's clearly *corrupt*. Here I've highlighted (in white on black) a particular segment that makes no sense:
![sourcemap](https://cloud.githubusercontent.com/assets/1755336/16710648/c6c3e852-463e-11e6-8d26-24de116c3792.png)
(I'm using WebStorm here to visualize it better)

Is this something you could narrow down and send upstream to Traceur? I assume it's the Traceur transformers that are causing it.

**Comment by guybedford** [comment]
We use Traceur to do transforms, and there seem to be some strange offsets in the Traceur output.

So I think this is catered for by the issue at https://github.com/systemjs/builder/issues/489.
