### ISSUE TITLE
Symbol.iterator error with Promise.all() in node 6+

### ISSUE THREAD

**Issue by cookiengineer** [systemjs/builder#644]
As systemjs builder is using bluebird and that leads to incompatibility with the native `Promise.all` method. The native Promise.all method uses a `for ... of` loop and therefore requires the Symbol.iterator on the Promises themselves. I don't know if I'm using the API incorrectly, but I'm assuming that multiple bundle() calls can be used within an Array?

```bash
ERROR TypeError: (var)[Symbol.iterator] is not a function
    at Function.all (native)
```

```javascript
gulp.task('build:angular', (oncomplete) => {

    var builder = new Builder({ /* config */ });

    Promise.all([
        builder.bundle('@angular/core', './build/vendor/@angular/core/index.js'),
        builder.bundle('@angular/compiler', './build/vendor/@angular/compiler/index.js'),
        /* and so on ... */

    ]).then(() => {

        gulp
            .src([ './build/vendor/@angular/core/index.js', './build/@angular/compiler/index.js' ])
            .pipe(gulp_concat('build.all.js'))
            .pipe(gulp.dest('./build'))
            .on('end', oncomplete);

    }).catch((err) => {
        console.error(err);
    });

});
```

1) Is the above demo code intended to work that way with native ES6 Promises?

2) If yes, are there any plans to migrate to native ES6 Promises instead of using bluebird to resolve this issue more easily?

**Comment by guybedford** [comment]
It sounds like this is a Bluebird issue if there is an incompatibility between Bluebird and native promises?

Which version of Bluebird are you running here? Have you tried updating it?

**Comment by guybedford** [comment]
Any update here at all?

**Comment by cookiengineer** [comment]
Couldn't find the bug related to bluebird, I was using the 3.3.4 version. So I kind of did the quick solution to use `var Promise = require('bluebird')` and the issue was resolved.

Not sure if this is a good approach, would much more love to see a native Promise API here. But I guess focus is on backwards compatibility with node 5 and lower.

**Comment by grigoreme** [comment]
Did you used ` Promise.all(
      Promise1,
      PromiseN,
    )`??
If yes please add the promises into `[]` like: ` Promise.all([
      Promise1,
      PromiseN,
    ])`

**Comment by nazreen** [comment]
I made the mistake mentioned by @grigoreme above. Putting everything in a single array solved it.
