### ISSUE TITLE
Distinction between static and instance methods

### ISSUE THREAD

**Issue by peterjuras** [systemjs/builder#646]
Hi!

I'm currently using the systemjs builder to create multiple bundle packages for different languages and everything works great. :thumbsup:

One thing that made me curious though, were certain methods that are currently instance methods on the builder object like _addTrees(tree1, tree2)_ and _subtractTrees(tree1, tree2)_.

Since they are instance methods, I assumed that they have a dependency on the builder object itself. This lead me to write code that binds the methods to the builder object, like this:

```js
const builder = new Builder('www', path.join(__dirname, 'www', 'config.js'));
// ...
const localizationSubtree = subtrees.reduce(builder.addTrees.bind(builder));
```

But looking at the [addTrees](https://github.com/systemjs/builder/blob/master/lib/arithmetic.js#L307) function, I found that it is not dependent on the builder object (e.g. no usage of _this_) so it could be a static method, e.g. provided by _Builder_ itself and it would be clearer that there is no need to bind it.

Do you plan on refactoring these methods in the future? Or would you like to leave them this way?

**Comment by aluanhaddad** [comment]
Even so-called static methods do not imply that bind is not needed as they could depend on the state of the class constructor itself. The simplest things to do is to pass a closure. It's a little more verbose but it is also more reliable.

**Comment by peterjuras** [comment]
That's also true, but maybe I have worded my proposal poorly.

If I haven't missed anything, _addTrees_ and _subtractTrees_ are actually pure, so there should be no binding necessary. Maybe these methods could be exported directly by the module (or a different file) so that they can be used without any dependencies.

**Comment by guybedford** [comment]
Yes this was simply an API simplification that it's easier not to have to think about what is static and what isn't and just have a single namespace.
