### ISSUE TITLE
Bundle Angular2 for Lazyloading Components

### ISSUE THREAD

**Issue by Hanfrey** [systemjs/builder#647]
I am trying to bundle my application with systemjs builder. Its a "core" Application which has angular2 in it. The other components are loaded lazily into the core then. At the moment Iam bundle my core, which works, but the other components then get 404 because they are searching for the old paths of angular2.

I want to have the components bundled, but without angular2, the components then are using the one in my core. I tought I am using buildStatic for this? I am only compiling the ts files to js.

Some snippets what I tried:

Building the core which works:

```
gulp.task('bundle:js', function() {
    var builder = new SystemBuilder('dist', './src/systemjs.config.js');
    return builder.buildStatic('app', 'dist/app.js');
});
```
In my index.html I am loading then the app.js file. Which is around 2MB now.

Then the lazy loaded component is searching for: `https://localhost/@angular/router-deprecated` which results in 404.

Now to the "hard" part:

```
   gulp.task('build:static', function () {
  var builder = new SystemBuilder('', './dist/systemjs.config.js');
  builder.buildStatic('dist/start.component.js', 'dist/start.component.static.js', {
    defaultExtension: 'js',
  globalName: 'test'
});
});
```

In the systemjs i have: 
```
meta: {
      '@angular/*': {
        build: false
      }}

```
After this I get an JS file which is around 400kb. So I think there is no angular2 in it?

If I now try to start my application it tells me:

`zone.js:101 GET https://192.168.99.100/@angular/common//bundles/common.umd.js 404 (Not Found)` 

What is my fault? Is this even possible how I am doing it?

Thanks!

**Comment by guybedford** [comment]
This is what bundle is for, buildStatic doesn't share the internal modules with other bundles.

If you ensure the main bundle containing Angular is run through bundle, then it should be able to find the shared angular files fine.

**Comment by Hanfrey** [comment]
I tought i tried that, tried again...working. Thanks

**Comment by smartm0use** [comment]
@Hanfrey can you share your solution or help me about this https://github.com/systemjs/builder/issues/729 ?
