### ISSUE TITLE
Case sensitivity issue 

### ISSUE THREAD

**Issue by rn1d** [systemjs/builder#649]
I'm bundling my application with systemjs-builder. I want to build separate bundles for my dependencies and for my app.

I'm trying to use the arithmetic to achieve this.

For building the dependency bundle, I use an expression based on the [Third-Party Dependency Bundles example](https://github.com/systemjs/builder#example---third-party-dependency-bundles).

```
builder.bundle('app/main.js - [app/**/*]', 
    'app/deps.bundle.js', 
    { minify: true, sourceMaps: true });
```

For building the app bundle, I use the following:
```
builder.bundle('app/main.js - app/deps.bundle.js', 
    'app/app.bundle.js', 
    { minify: true, sourceMaps: true });
```

I found that the `app/deps.bundle.js` includes modules from the app. After some digging and debugging, it looks like the arithmetic is case sensitive and case used in the `import`-s must match the case in directory/filename exactly. 

For instance, if a file imports a module like `./models/vehicle`, while the file path is `./Models/vehicle` (note the capitalized directory name), it is included in the app bundle.

Is the case sensitivity by design?

I think the arithmetic should be case insensitive for this scenario - even with a case-sensitive convention in place, on large projects with multiple developers someone is bound to make a mistake and cause an issue.

I made a simple demo project [here](https://github.com/rn1d/systemjs-builder-casesensitivity) for reproducing the issue.

**Comment by asapach** [comment]
URLs are case-sensitive, so I see no reason why normalization and bundling shouldn't be.

**Comment by rn1d** [comment]
That's a fair argument, I suppose. 

The only counter argument is that many file systems are case insensitive. Node.js also seems to be case insensitive with `require()` statements. Also, TypeScript seems to be fine with case insensitivity. At the very least, it would be convenient if builder would be forgiving, at least when building bundles. 

After some digging, it seems the case sensitive behaviour is because of the implementation in `arithmetic.js` of `systemjs-builder`, not the `systemjs` loader.

Definately an option to make sure the casing is correct, and to adopt strict conventions on this. The project I'm working on is gotten into a bit of a mess - we didn't pay attention to this from the start and the codebase has grown quite large.

**Comment by asapach** [comment]
I would recommend running your code/tests in Karma. It's case-sensitive even on Windows and MacOS. That way you can discover and fix issues early.

**Comment by guybedford** [comment]
SystemJS imports are case sensitive, yes.

**Comment by rn1d** [comment]
Understood! Thanks for the clarifications - much appreciated!
