### ISSUE TITLE
What to do about 3rd party libraries?

### ISSUE THREAD

**Issue by JasonGoemaat** [systemjs/builder#650]
We are using wijmo controls with angular 2.  We want to load their provided bundles separately and not include them in our generated bundles.  How can we do this?  Our config knows nothing about these because they are registered by loading the bundles ahead of the config being used, but the builder throws an error because it can't find them.

**Comment by guybedford** [comment]
You can just load the provided bundles as modules in SystemJS, then either rebuild them folded up into your bundle with standard bundling, or leave them out as externals during bundling.
