### ISSUE TITLE
Builds crawl to a halt when upgrading from 0.15.23 to 0.15.24.

### ISSUE THREAD

**Issue by circlingthesun** [systemjs/builder#663]
I've noticed my builds taking around 10x longer since  upgrading from 0.15.23 to 0.15.24. I've also noticed peak memory consumption is up from 360mb to 920mb. I've had a look at https://github.com/systemjs/builder/compare/0.15.23...0.15.24 but can't notice any obvious cause.

I'm using the jspm bundle command as follows: ```jspm bundle app/app.js```. I've profiled this command with version 0.15.23 and 0.15.24 of builder. You can see there is a hotspot in 0.15.24 that uses 65.0% of ticks where it only uses 5.7% in 0.15.23. I've included the processed traces below.

[0.15.23.txt](https://github.com/systemjs/builder/files/416308/0.15.23.txt)
[0.15.24.txt](https://github.com/systemjs/builder/files/416309/0.15.24.txt)

**Comment by fictitious** [comment]
could that be because global and register transforms were switched from traceur to babel ?

https://github.com/systemjs/builder/commit/b474ee71df9a7a4ddebfdb0d284c12c9794488d7
https://github.com/systemjs/builder/commit/051deb6aab1d0113e77b5a860e6dbbc00c2544ef

**Comment by circlingthesun** [comment]
I'm having a really hard time pin pointing this issue. I can reliably reproduce the slow down when moving from JSPM 0.17.0-beta.24 to 0.17.0-beta.25 which actually corresponds to a move from version 0.15.24 to 0.15.25 of systemjs-builder. However, when I manually install builder 0.15.24 or 0.15.25 in JSPM's node_modules directory, both work fine :/

**Comment by guybedford** [comment]
This sounds like it could have been a consequence of the upgrade to using
Babel over Traceur transforms internally.

**Comment by circlingthesun** [comment]
I was able to reproduce this consistently when upgrading from JSPM 0.17.22 to 0.17.23. I the process if trying to find the exact commit of builder that caused this, NPM's deduping cause some confusion making me a bit making me unsure of what I was reporting. I'll try again and reopen this issue once I regain my confidence in the details.

**Comment by guybedford** [comment]
It seems pretty clear this is a consequence of the move from Traceur to
Babel in the latest landed systemjs prs.

This will be tough to fix - either involving switching back to Tracuer
(which is not really an option as it's not well supported and doesn't
support code comments and has variable source maps support).

The only path forward then is probably to do some performance optimization
work on the Babel-plugin-transform-es2015-modules-systemjs package in Babel
core. That will not be an easy job though!

**Comment by circlingthesun** [comment]
I was unable to reproduce this issue in isolation. It appears to have been a symptom of a specific version of some package I had installed. After I deleted the node_modules directory and reinstalled everything the problem disappeared for all versions of JSPM and SystemJS Builder.
