### ISSUE TITLE
multiple bundles issue

### ISSUE THREAD

**Issue by davidanaya** [systemjs/builder#664]
Hi!

Sorry, probably this is quite simple to achieve, but I'm having some issues and I couldn´t find a clear explanation on how to do it.

I have a simple Angular2 application with the following structure:

```
/app
    /app/shared
    /components/moduleA
    /components/moduleB
    app.component.ts
    app.routing.ts
    app.module.ts
    main.ts
```
    
I have a working configuration with a single bundle, but I want now to have the following:
    common.js: with all required libraries, angular, route,... and also the files in /app/shared and all required to bootstrap the application (app.component.ts, app.routing.ts, app.module.ts and main.ts)
    moduleA.js: everything inside /app/components/moduleA, but no libraries nor common code inside /app/shared
    moduleB.js: everything inside /app/components/moduleB, but no libraries nor common code inside /app/shared 

I'm using this in my gulpfile

```
gulp.task('bundle', () => {
  builder.buildStatic('app/*.js - app/components/**/*.js', 'web/common.js')
  .then(function() {
    console.log('Build complete');
  });

  builder.bundle('app/components/moduleA/**/*.js', 'web/moduleA.js');
  builder.bundle('app/components/moduleB/**/*.js', 'web/moduleB.js');
})
```

But I'm afraid my moduleA and moduleB contain some common stuff and also libraries from angular and route.

What am I doing wrong? Is there any easier way to do this?

Thanks!

**Comment by guybedford** [comment]
Try making the common bundle with 'bundle' not build static. Then you
should be able to add - web/common.js when doing the module bundles.

**Comment by davidanaya** [comment]
Thanks, @guybedford 

I'm confused now. I thought the difference between bundle and buildStatic was that with buildStatic you don´t need the systemjs.config.js anymore in your project.

I changed my gulp to this

```
gulp.task('bundle', () => {
  builder.bundle('app/**/*.js - app/components/**/*.js', 'web/common.js')
  .then(function() {
    console.log('Build complete');
  });

  builder.bundle('app/components/moduleA/**/*.js - web/common.js', 'web/moduleA.js');
  builder.bundle('app/components/moduleB/**/*.js - web/common.js', 'web/moduleB.js');
})
```

but now my common.js has no angular or route libraries inside, and also my /app/share components are missing

The arithmetic operator in 'app/components/moduleA/**/*.js - web/common.js' doesn´t seem to do much, as the common.js doesn´t have any shared components or angular files at all.

**Comment by davidanaya** [comment]
Ok, I managed to get what I wanted. Now my angular2 app does not initiate :( but at least my modules look what I want. 

```
gulp.task('modules', () => {

  // 3rd party
  builder.bundle('app/**/*.js - [app/**/*.js]', 'web/3rdparty.js', { minify: true });

  // commons
  builder.bundle('[app/shared/**/*.js] + [app/*.js]', 'web/common.js');

  // modules
  builder.bundle('[app/components/moduleA/**/*.js]', 'web/moduleA.js');
  builder.bundle('[app/components/medals/**/*.js]', 'web/moduleB.js');
})
```

Still, I'm a bit confused on why this is working like this, so I'd appreciate if someone could clarify.

`builder.bundle('[app/shared/**/*.js] + [app/*.js]', 'web/common.js');`
this contains both js files in /app and also in /app/shared, which is what I want, but why this does not work?
`builder.bundle('[app/**/*.js] - [app/components/**/*.js]', 'web/common.js');`

`builder.bundle('[app/components/moduleA/**/*.js]', 'web/moduleA.js');`
this contains only what is inside /app/components/moduleA, but shouldn´t contain also what is referenced in my /app? I thought I'd need to do this
`builder.bundle('[app/components/moduleA/**/*.js] - web/moduleA.js', 'web/moduleA.js');`
but I don´t.

**Comment by guybedford** [comment]
Perhaps you're wanting to remove the square brackets? Square brackets mean just the modules listed, without square brackets means the module and all its dependencies.
