### ISSUE TITLE
incorrect line mapping in typescript sourcemap

### ISSUE THREAD

**Issue by m-andrei** [systemjs/builder#666]
Hello, i use typescript with typescript-plugin and try to create source-map.  
In my ts file i wrote "debugger" and try to catch it in source map in chrome.
Debug catching properly in correct file but in wrong position it is not some constant offset, in differents files count of lines between correct and incorrect position is different.
tsconfig:
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": true,
    "experimentalDecorators": true,
    "sourceMap": "inline"
  },
  "exclude": [
    "node_modules", "jspm_packages", "bower_components"
  ]
}`
jspmconfig:
  `  transpiler: "plugin-typescript",
  typescriptOptions: {
    "module": "system",
    "noImplicitAny": false,
    "tsconfig": true
  }`
gulp command:
` const Builder = require('systemjs-builder');
    const builder = new Builder();
    const inputPath = path;
    const outputFile = './.tmp/serve/time/file.js';
    const outputOptions = {
      sourceMaps: "inline"
    };
builder.loadConfig('./jspm.prod.config.js')
         .then(function () {
             builder.bundle(inputPath, outputFile, outputOptions)
                 .catch((ex) => cb(new Error(ex)));
         });`

**Comment by guybedford** [comment]
It may be worth posting an issue to the typescript plugin project here rather.
