### ISSUE TITLE
Consider configuration builds

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#67]
As well as building bundles, it would be useful for the ability to build configuration against a trace tree to only include the minimal configuration necessary to operate that trace tree.

**Comment by crisptrutski** [comment]
@guybedford not quite sure what's meant by "to build configuration" here

**Comment by guybedford** [comment]
Outputting just the bare minimum configuration necessary to make the non-sfx bundle work in production. A config file contains all config across all installed modules. Only a subset is needed for a given page in production, so tooling to create these subsets.

**Comment by crisptrutski** [comment]
:+1:

**Comment by whitecolor** [comment]
So you are going to anialize trace and remove from `System.config` unessessry things? Or what do you mean by `build configuration`?

**Comment by guybedford** [comment]
Configuration needs to be included in production - this would generate the bare-minimum necessary configuration for production. That is, just like script is processed, the configuration file would be processed into the production configuration.

**Comment by guybedford** [comment]
Proposal:

```javascript
builder.buildTree(tree, opts).then(function(output) {
  output.config; // the minimal config options needed for this bundle to run (excluding baseURL and paths)
  output.modules; // the list of module names in the bundle (used for populating bundles)
  output.depCache; // as expected
});
```

**Comment by guybedford** [comment]
Actually this is bundling - there is no reason to include depCache.

**Comment by guybedford** [comment]
If we assume that all modules are bundled, one alternative is just to always normalize with bundling, and thus avoid the need for build config entirely. Previously things like versions still made this necessary but it's looking less common. Production-level mappings are no longer possible and have to be provided at the build config stage. Perhaps that makes sense though.

The remaining issue then is just handling dynamic imports and dynamic normalizations within bundle scenarios (`System.import('jquery', __moduleName)`). The thing is, the only way to know we need these configs is through some kind of dynamic tracing layer that can reason about these requests (https://github.com/systemjs/builder/issues/75).

If we assume that there are going to be bundle / non-bundled boundaries, then we need configuration for everything not bundled. The tricky part is if I've built a bundle for some modules, but rely on other modules being loaded separately. One way to do this would be a trace-level configuration generation function - `builder.getConfig(tree)` which outputs just the necessary map config for that specific tree of modules.

**Comment by guybedford** [comment]
The other part of this is how the workflow itself fits together.

We have two main priorities - low-level primatives like `buildTree` and high-level build operations like `optimizeBuild`. Both use cases need to be individually catered for.

Having `config` (effectively just map config) as an output for `buildTree` as above seem to make complete sense for the primitive level (calling `builder.getConfig(tree)` underneath)/

For the higher-level it is still yet to be determined how that use case will work out.

**Comment by guybedford** [comment]
Perhaps call it `builder.getMapConfig` to be clear.

**Comment by guybedford** [comment]
Ok the goal to avoid all this is to attempt config-free builds, with the dynamic tracing layer to determine configuration later on. Let's see how this goes.
