### ISSUE TITLE
Builder cannot find modules imported with "@node/x"

### ISSUE THREAD

**Issue by revov** [systemjs/builder#670]
I am using electron with SystemJS for the client side of my application. Electron modules are imported via `import * from '@node/electron';` as suggested in https://github.com/systemjs/systemjs/issues/1261. Everything works perfectly fine without any additional System configuration.

However, when bundling the application with the builder I get an error: `Cannot find module 'electron'`. Even if I exclude it from the build it seems that the builder still tries to resolve it:
```
meta: {
  '@node/electron': {
    "build": false
  }
},
```
The only thing that worked was mapping the module to `@empty`, but this now breaks the application since SystemJS is no longer able to resolve `@node/electron`.

I am not entirely sure of the magic happening behind using`@node/x` but with the prebuilt version of electron the `electron` module is nowhere to be found in the node_modules folder. So for the modules provided by Electron my understanding is that they come packaged in the prebuilt version, and the provided `require` function that we use in both the main and the renderer processes knows how to find them. So even if we wanted we would not be able to include these modules in a systemjs bundle (and I suspect most people would not want to).

**Comment by guybedford** [comment]
Sure this makes sense... I've included a fix in https://github.com/systemjs/systemjs/commit/85bca84c0f7830d6489e7ebfeb3a4fff4af7c9d0.

**Comment by revov** [comment]
I can confirm the fix is working and properly excluding "@node/x" modules from the build.

**Comment by guybedford** [comment]
Great, this will come through in the next release, not the current patch, but it shouldn't take more than a week or so I expect.

**Comment by guybedford** [comment]
This fix caused some other breaks and had to be replaced with https://github.com/systemjs/systemjs/commit/9f886bb3bd0633616834bbe2f0e326ce4ac05c6f, but this should still work for your use case.

**Comment by guybedford** [comment]
Released in 0.15.31.
