### ISSUE TITLE
Auto optimizations for Bundles

### ISSUE THREAD

**Issue by believer-ufa** [systemjs/builder#671]
Hello all. I [created issue](https://github.com/jspm/jspm-cli/issues/2003) for JSPM a month ago where i talk about this problem. And one of guys linked me to this project.

I have a suggestion about this problem, maybe you find it useful for yourself.

It may be better to transfer all rights about configuring bundles to System.js Builder? Now we have some Bundle arithmetic approaches what gives us ability to add or remove modules from own bundles. But perhaps more correct to provide the *entire process* of assembling bundles to Builder?

Only one thing what needs from users - its a specify a list of modules that you need to create bundles. Mabye, create a some array in System.js configuration for this? :)

And create code in Builder what automatically resolves all conflicts in bundles and removes collisions from its, and etc, etc. [Like in webpack](https://github.com/webpack/docs/wiki/code-splitting#chunk-optimization), as i sayed in my previous issue about this problem. 

If you do everything so that - you will no longer need in bundle arithmetics, i hope.

**Comment by guybedford** [comment]
Making this easier is the general direction things are headed, but it's difficult to prioritize as a single issue. It is possible to build a wrapper around SystemJS Builder that can perform automatic bundle chunking strategies. Projects that do this can certainly make it easier for users to get advanced bundling workflows.

**Comment by aluanhaddad** [comment]
I would be great to see enhancements here, but I love bundle arithmetic.
