### ISSUE TITLE
0.15.26 -> 0.15.27: SyntaxError: node_modules/eyes/lib/eyes.js: Octal literal in strict mode

### ISSUE THREAD

**Issue by asnov** [systemjs/builder#672]
After upgrading from 0.15.26 to 0.15.27 the builder.buildStatic() fails on my project.
I'm using quite old npm package (http://github.com/cloudhead/eyes.js) which uses octal literals inside it's code. I'm using strict mode for my code and "require('eyes')" goes inside it.
Up to 0.15.27 the project compiled successfully.
Is it possible to turn off this checking?
Or could you suggest how I can use legacy third party modules in my code?
Thank you!

**Comment by Muhammad97** [comment]
It may be better to make a fork of the library?
