### ISSUE TITLE
Babel parsing as strict

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#679]
Babel parsing for CJS and AMD modules should default to non-strict.

Does Babel have a flag or option to support this even?

//cc @jrauschenbusch @asapach

**Comment by asapach** [comment]
I think there's an undocumented babel option `sourceType` which defaults to `'module'`, we should probably set it explicitly to `'script'` for `cjs`, `amd` and `global`.

**Comment by asapach** [comment]
Here: https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/options/config.js#L155-L158

**Comment by guybedford** [comment]
Added https://github.com/systemjs/builder/commit/05807f2308423c9c943638f1ec86ed22f5a7b6e7 and https://github.com/systemjs/builder/commit/783b9b545b6a747eba213cf56f742464969719cb.

**Comment by aluanhaddad** [comment]
@guybedford It is worth noting that TypeScript behaves the same way for `amd` and `cjs` targets. The flag to disable this behavior is `noImplicitUseStrict`. 

There was some debate over this in the TypeScript community but the prevailing feeling was, IIRC, that using ES module syntax implied a desire for as similar semantics as possible.

This could be a fairly large breaking change so I'm wondering if the default should remain as it is.

**Comment by guybedford** [comment]
Released in 0.15.31.
