### ISSUE TITLE
The cost of small modules article

### ISSUE THREAD

**Issue by Rush** [systemjs/builder#682]
https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/

How would System.JS compare to those other solutions?

**Comment by dinoboff** [comment]
JSPM build uses rollup on any es6 module, mainly your source code. Most 3rd party packages are distributed in cjs, umd or global module format and will suffer the same issue described in that blog post (as far as I can see in my built output).

`jspm build` print in bold the module rollup did work on.

**Comment by aluanhaddad** [comment]
@dinoboff If you are using jspm, you can, although it may require an override, build directly from the source of most packages instead of their bundles.
