### ISSUE TITLE
Using .minify causes TypeError: global$1.System.import is not a function

### ISSUE THREAD

**Issue by Gillardo** [systemjs/builder#684]
Exactly as the title says...If i build my bundle using the following
```
    return builder.buildStatic('wwwroot/app/main.js', 'wwwroot/dist/bundle.js', { minify: false, sourceMaps: true})
        .then(function() {
            console.log('Build complete');
        })
        .catch(function(err) {
            console.log('Build error');
            console.log(err);
        });
```

I get an exception when i try to load my application saying

> TypeError: global$1.System.import is not a function

If i change my bundling code to use `minify: true` i dont get the error??

Does `minify` actually do something else as well?

**Comment by guybedford** [comment]
Can you share your bundle file output? And also the code that runs `System.import`?
