### ISSUE TITLE
Upgrade from 0.15.30 -> 0.15.31 broke bundler

### ISSUE THREAD

**Issue by crtag** [systemjs/builder#686]
I have rather simple bundle task to create custom Rxjs bundle for my project. 

```
var builder = new Builder('./node_modules');
builder
	.bundle([
		'rxjs/add/**/*.js',
		'rxjs/observable/**/*.js',
		'rxjs/operator/**/*.js',
		'rxjs/scheduler/**/*.js',
		'rxjs/symbol/**/*.js',
		'rxjs/testing/**/*.js',
		'rxjs/util/**/*.js',
		'rxjs/*.js'
	], './bundles/rxjs.min.js', {
		minify: true,
		sourceMaps: true
	})
	.then(function() {
		console.log('Rxjs bundle build complete.'.green);
		process.exitCode = 0;
	})
	.catch(function(err) {
		console.log('Rxjs bundle build error!'.red);
		console.log(err);
		process.exitCode = 1;
	});
```

After upgrading it fails to find any references for *.js files like this:

```
{ [Error: Error on fetch for node_modules/rxjs/add/**/*.js at file:///Users/xxx/node_modules/rxjs/add/**/*.js
	ENOENT: no such file or directory, open '/Users/xxx/node_modules/rxjs/add/**/*.js']
  originalErr: 
   { [Error: ENOENT: no such file or directory, open '/Users/xxx/node_modules/rxjs/add/**/*.js']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/xxx/node_modules/rxjs/add/**/*.js' } }

```

Downgrading the version fixes the problem.

**Comment by guybedford** [comment]
Support for globbing in the array-based bundle syntax was removed.

Try using the expression form rather:

```
.bundle([
        'rxjs/add/**/*.js',
        'rxjs/observable/**/*.js',
        'rxjs/operator/**/*.js',
        'rxjs/scheduler/**/*.js',
        'rxjs/symbol/**/*.js',
        'rxjs/testing/**/*.js',
        'rxjs/util/**/*.js',
        'rxjs/*.js'
    ].join(' + ')
```

**Comment by crtag** [comment]
I will give it a try, but just a few notes. 

- This is a breaking change and not mentioned anywhere - not in release notes, nowhere;
- Using SystemJS and Builder is quite a guess work sometimes due to the way documentation is provided/maintained, and in regards to this update you may consider investing 15 minutes into describing what actually is [] aka module notation and where globs can be used/not used.

I do use SystemJS and Builder and it's my preference over many other because of absence of that "dark magic" which is the essence of other bundlers, but poor docs are really deterring many others who fall then into "dark magic" of things happening beyond reasonable control.

**Comment by crtag** [comment]
Update:
Using ' + ' arithmetics worked well.
