### ISSUE TITLE
buildStatic into multiple files

### ISSUE THREAD

**Issue by PRR24** [systemjs/builder#688]
buildStatic call in its default form is simple and awesome.

As a future request I would like to separate the built bundle file into multiple different physical files by some pattern, either the arithmetics used for bundle(), or more other form, a'ka:
builder.buildStatic("app", "app.bundle.js", {
  modules: [
     'node_modules.bundle.js': ['node_modules/**'],
    ...
  ]
...
});
Result in this specific example would be two files (done_modules.bundle.js and app.bundle.js) that user would include both into index.html in defined order resulting exact same behavior as today using one file.

Thank you.

**Comment by guybedford** [comment]
Separate bundles for buildStatic would likely best be handled via normal bundling approaches. Static optimizations for bundles are something that can be looked into and this will likely happen in due course.
