### ISSUE TITLE
Builder + plugin-babel: redundant sourcemaps 

### ISSUE THREAD

**Issue by sergei-startsev** [systemjs/builder#692]
Hi,
I use SystemJS builder together with [plugin-babel](https://github.com/systemjs/plugin-babel) for building SFX bundles and came across an issue with redundant source maps in case when `sourceMaps` option is turned off for the builder. Here is configuration example:
```javascript
builder.config({
	transpiler: 'plugin-babel',
	map: {
		"plugin-babel": "npm:systemjs-plugin-babel@0.0.14/plugin-babel.js",
		"systemjs-babel-build": "npm:systemjs-plugin-babel@0.0.14/systemjs-babel-node.js"
	}
});
```
and here is the list of options that I use for building static bundles:
```javascript
builder.buildStatic(bootstrap, {
        sourceMaps: false,
	format: "global",
	globalName: "bundle",
	globalDeps: externals
});
```
Sourcemaps are not embedded to the output bundle, but if you look at the resulted output you see that sourcemaps are actually generated:
![sourcemaps](https://cloud.githubusercontent.com/assets/748074/18513156/f8864d3c-7a94-11e6-8b4e-a1ed1f663729.png)
I was under impression that if you turn off sourcemaps in the builder globally, sourcemaps should not be built at all, even if you use `plugin-babel`. @guybedford could you please clarify the expected behavior?

PS. If you need to turn off sourcemaps in `plugin-babel` you could add the following code to your config:

```javascript
meta: {
	'*.js': {
		babelOptions: {
			sourceMaps: false
		}
	}
}
```

**Comment by asapach** [comment]
I would suggest moving this issue to plugin-babel repo.

**Comment by sergei-startsev** [comment]
@guybedford any thoughts regarding it? should I move the issue to [plugin-babel](https://github.com/systemjs/plugin-babel) repo?

**Comment by guybedford** [comment]
Yes this is an issue with `plugin-babel`, and can be fixed by altering `https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L175` to check `traceOpts && traceOpts.sourceMaps || babelOpts.sourceMaps`.
