### ISSUE TITLE
Unexpected token: operator (>) on external dependency written in es6 when bundling with minify

### ISSUE THREAD

**Issue by mribichich** [systemjs/builder#695]
Hi there,

I wanted to let you know that `jspm bundle dist/app/index dist/bundle.js --minify` fails when one of your third party dependencies is written es6.

I'm using: `jspm@0.16.45`

Error: `err  Error: SyntaxError: Unexpected token: operator (>) (line: 60863, col: 101, pos: 2440448)`

the normal uglify-js package doesn't handle es6 modules.

After a while researching and testing, it seems that jspm doesn't transpile dependencies.

So the only solution I found was installing uglify-js harmony branch, whice handles es6 modules.

`npm install mishoo/UglifyJS2#harmony --save-dev`

Is there another way to handle this kind of situation? Can I tell jspm to transpile the dependency or use the minify file that comes with the dependency?

Thanks!

**Comment by aluanhaddad** [comment]
You need to use `meta` configuration to informed jspm that the package needs to be transpiled. If the package is located at `jspm_packages/npm/some-dep` you can configure this with
```javascript
SystemJS.config({
  meta: {
    "some-dep": {
      "*.js": {
        loader: "babel" // or ts or traceur
      }
    }
  }
})
```

**Comment by mribichich** [comment]
alright thanks aluan!
