### ISSUE TITLE
Exclude tests and fixtures from npm package

### ISSUE THREAD

**Issue by exogen** [systemjs/builder#696]
Currently anyone who installs `systemjs-builder` is also getting its tests, which `du` tells me account for ~424K. To improve install time and disk usage, I recommend using `files` or adding `test` to `.npmignore`. It doesn't look like anything under `test/` is used for non-development purposes.

**Comment by guybedford** [comment]
Sure, I've added an npmignore.

**Comment by exogen** [comment]
@guybedford Awesome, thank you!
