### ISSUE TITLE
builder.reset() errors

### ISSUE THREAD

**Issue by lastmjs** [systemjs/builder#699]
I'm using SystemJS to transpile TypeScript to ES5, here is my config:

```
{
    transpiler: 'plugin-babel',
    typescriptOptions: {
        target: 'es6',
        module: 'es6'
    },
    meta: {
        '*.ts': {
            loader: 'ts'
        }
    },
    packages: {
        ts: {
            main: 'plugin.js'
        },
        typescript: {
            main: 'typescript.js',
            meta: {
                'typescript.js': {
                    exports: 'ts'
                }
            }
        }
    },
    map: {
        ts: './node_modules/plugin-typescript/lib/',
        typescript: './node_modules/typescript/lib/',
        'plugin-babel': './node_modules/systemjs-plugin-babel/plugin-babel.js',
        'systemjs-babel-build': './node_modules/systemjs-plugin-babel/systemjs-babel-browser.js'
    }
}
```

I have a small server running to handle bundles. I bundle like so: 

```
builder.reset();
builder.buildStatic(`
        (app/client/components/*/*.ts) +
        (app/client/bower_components/solutia-maxima-components/components/*/*.ts) +
        (app/client/bower_components/view-quiz-component/*.ts) +
        (app/client/bower_components/video-viewer-component/*.ts)
        `, 'app/client/dist/prendus.js', {
        minify: false
    })
```

Calling builder.reset() causes errors such as the following:

```
file:///home/lastmj/development/prendus/prendus-learning-platform/app/client/components/prendus-app/prendus-app.ts:10:10: Unexpected token is

file:///home/lastmj/development/prendus/prendus-learning-platform/app/client/components/prendus-app/prendus-app.ts:10:14: Unexpected token string
```

And many more. It looks like transpiling the TypeScript has something to do with it. I'm trying to get efficient bundles to work, and the cache only reduces my bundling time from ~14 to ~9 seconds. I'm resetting the bundle because of what it says in this issue: https://github.com/systemjs/builder/issues/579

**Comment by asapach** [comment]
```js
    typescriptOptions: {
        target: 'es6',
        module: 'es6'
    }
```
`target` should be `es5`. Builder doesn't understand ES6 without a transpiler.

**Comment by asapach** [comment]
And `module` should be `system`, I believe.

**Comment by lastmjs** [comment]
The builder has been working fine, it's only when I add `builder.reset()`. My setup transpiles TypeScript with es6 modules, async/await, and es6 down to es5.

**Comment by asapach** [comment]
Try doing `.invalidate('*')` instead. I think `.reset()` actually resets config and depending on how you pass configuration it will roll it back to the initial state.

**Comment by lastmjs** [comment]
That doesn't break it! But now that it is invalidating all files, I'm not getting much of a gain in efficiency. How could I pass in the config so that reset would work?

**Comment by lastmjs** [comment]
Calling invalidate on the individual file that changes is working for me, thanks!

**Comment by guybedford** [comment]
It may be an issue with the TypeScript plugin itself if it is not compatible with the `reset` functionality of builder.
