### ISSUE TITLE
Full source maps for builds

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#7]
Support picking up and then re-mapping the source maps from individual files through into the concat build.

**Comment by Rush** [comment]
I feel that input source maps of individual modules are not being passed to the final build (for example I can see the sourceMap tag when viewing sources of modules in chrome), is it a bug or lack of feature?

**Comment by guybedford** [comment]
@Rush good point, created https://github.com/systemjs/builder/issues/297.
