### ISSUE TITLE
Node mysteriously exits during .bundle

### ISSUE THREAD

**Issue by ghempton** [systemjs/builder#701]
We are using the System.js builder API v0.15.32  to create a static bundle of our project (using both node 4.4.7 and 6.6.0). After recently changing some of our project's imports, we notice that the node process exits mysteriously when we are doing a `builder.bundle`. The promise never resolves or rejects and the process exits:

```
 builder.bundle('ourproject/**/*.js', 'bundles/app.js', {
  browser: true,
  production: true,
  minify: true,
  mangle: false,
  sourceMaps: false
}).then(function(output) {
  // this is never reached
}, function(err) {
  // nor is this
});
// ...but the process exits
```

Through a series of `console.log` statements, the offending code has been determined to be contained within `traceExpression` inside `arithmetic.js`.

Unfortunately, our project is quite large and because of the lack of debug output from system.js and the recursive nature of imports, we cannot find a small reproduction of this. In our code, in select files, we can comment out groups of `import` statements and the build will then start succeeding:

```
...
// as long as these are *all* commented the above issue does not happen
// import from 'a.js'
// import from 'b.js'
// import from 'c.js'
```

Any advice on troubleshooting this? There is zero output and `process.on('uncaughtException')` is never triggered. Our temporary solution is going to be selectively loading some modules asynchronously at runtime, but the fact that is happens based on the structure of our imports is concerning.

**Comment by ghempton** [comment]
Additionally, building via jspm has the same behavior:

```
➜  debug-build git:(release-time-3113) ✗ jspm bundle 'app/**/*.js' bundles/app.js
     Building the bundle tree for app/**/*.js...
➜  debug-build git:(release-time-3113) ✗
```

... and no errors and no bundle outputted.

**Comment by guybedford** [comment]
It's difficult to look into this further without a replication, but thanks for managing to track it down this far already.

Were you able to track down which specific promise step within traceExpression is not resolving or rejecting?

**Comment by ghempton** [comment]
I think I was able to get to the bottom of it. See the associated PR which fixes the issue.
