### ISSUE TITLE
can't bundle angular2 with ng2-select

### ISSUE THREAD

**Issue by dicbrus** [systemjs/builder#702]
Hi, 
can't bundle Angular2 app with ng2-select (v.1.1.0)

In systemjs.config.js:

`
  var map = {
    ...
    'ng2-select' : 'node_modules/ng2-select',
  };
  var packages = {
    ...
    'ng2-select': { defaultExtension: 'js', main: 'ng2-select.js'},
};`

In sysjs-builder.js:

`
  builder.config({
    paths: {
      'node_modules/ng2-select' : '/node_modules/ng2-select/',
      'node_modules/ng2-bootstrap' : '/node_modules/ng2-bootstrap/',
      'node_modules/@angular/':'/node_modules/@angular/'
    }
  });`

All app files are located in /source

when I try to build  get:
   { Error: ENOENT: no such file or directory, open 'e:\projects\project_name\node_modules\ng2-select\ng2-select'

Path to ng2-select is correct,

can't understand what is wrong 

Thanx

**Comment by guybedford** [comment]
You need to make sure that the map config is present at the time the package config is applied.

For example:

```javascript
System.config({
  packges: {
    'ng2-select': { main: 'y' } 
  }
});

System.config({
  map: {
    'ng2-select': 'x'
  }
});
```

Will not work, but will work if you swap the order of the `System.config` calls.

**Comment by dicbrus** [comment]
May be my issue is not about ng2-select, generally builder 
don't want to build 

I have system.config map{} and and system.config packages {} in right order (first map and packages after it).

The app starts and works without errors.

The problem, that I can't solve is that
Builder give me fetch errors all the time.

I tried to add 

```
builder.config({
    paths: {
      'node_modules/':'/node_modules/'
    }
});
```

But in this case I get: 
```
{ Error on fetch for node_modules/@angular/core at file:///node_modules/@angular/core
        Loading app/app.module.js
        Error: EISDIR: illegal operation on a directory, read
    at Error (native)
  originalErr:
   { Error: EISDIR: illegal operation on a directory, read
       at Error (native) errno: -4068, code: 'EISDIR', syscall: 'read' } }
```

Really don't understand how to configure builder to make his work :-(

**Comment by guybedford** [comment]
It is best to try and stick to an existing configuration or boilerplate if you can.

**Comment by dicbrus** [comment]
it seems to me, I understand what was the problem. 

Just writing here for smbd who have the same problem.

If your source code is in sub-folder like "src" (or "source").
you shoud initialize builder with:

```var builder = new Builder('.','systemjs-builder.config.js');```

my mistake was:
```var builder = new Builder('./src','systemjs-builder.config.js');```

In the second case it very hard to link all scripts in /node_modules (i didn't succeed to do it really)

Thanks everybody. meanwhile close the issue.
