### ISSUE TITLE
Self-Executing Bundle Entry Point

### ISSUE THREAD

**Issue by jdemeuse1204** [systemjs/builder#707]
I have a Single Page App that uses AMD modules.  I built the modules into a SFX bundle, but I cannot specify the entry point to the bundle.  Can an entry point be set for a SFX Bundle?  The SPA needs to start up with a specific module, using System.import does not work on a SFX Bundle.  I have a test project located here where I recreated my issue:

https://github.com/jdemeuse1204/TestSystemJS/tree/SystemJS-Build

The app needs to start with the main.js module.

The SFX Bundle is called Site.js located at TestSystemJS/App/Site.js.

My Index.cshtml where the site starts is located here: TestSystemJS/Views/Home/Index.cshtml

**Comment by asapach** [comment]
The first argument of `builder.buildStatic()` *is* the entry point.

**Comment by jdemeuse1204** [comment]
Awesome, thanks a million!!  That should do the trick, however, it looks like I have another issue with my static bundle.

Uncaught TypeError: Unexpected anonymous AMD define

I will check my configuration and see if I can find the cause.
