### ISSUE TITLE
Proper settings to bundle Angular 2 Ahead-of-Time Compiler files?

### ISSUE THREAD

**Issue by RoxKilly** [systemjs/builder#712]
I've compiled my `Angular 2` app written in `typescript 2` using the *Ahead-of-Time compilation* instructions on [angular.io](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#compile).  

**main.ts**
```
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

Now I have a lot of `ngfactory.ts` files as well as `.js` files. To tree-shake and bundle, I'm using the simple task below:
```
gulp.task('demo-bundle', function() {
    var builder = new SystemBuilder();

    builder.loadConfig('./systemjs.config.js')
        .then(function(){
            return builder.buildStatic('dev/main.js', 'dist/bundle.js', {
                encodeNames:false,
                mangle: false,
                rollup: true
            });
        })
});
```

The bundling completes without errors, but the app fails in the browser with error:

> Error: No provider for NgZone!

If I change from Ahead-of-time to Just-in-time compilation by bootstrapping with:
```
platformBrowserDynamic().bootstrapModule(AppModule);
```
Then the bundling and the app work as intended.

Any ideas on how to properly bundle the AoT compilation with `buildStatic`? (In tsconfig, `module` is `es2015` but I've also tried `system` and `commonjs`)

`@angular/compiler-cli 0.6.3`, `systemjs-builder 0.15.31`, `systemjs 0.19.39`

**Comment by RoxKilly** [comment]
The trick is to change `Angular` maps in `SystemJS` configuration. Instead of linking to the UMD bundles as the [QuickStart docs](https://angular.io/docs/ts/latest/quickstart.html#!#add-config-files) recommend, link to `index.js` instead.

Before:
```
System.config({
	map: {
	  '@angular/core': 'node_modules/@angular/core/bundles/core.umd.js',
	  '@angular/common': 'node_modules/@angular/common/bundles/common.umd.js',
	  ...
```

After:

```
System.config({
	map: {
	  '@angular/core': 'node_modules/@angular/core/index.js',
	  '@angular/common': 'node_modules/@angular/common/index.js',
	  ...
```

**Comment by tom10271** [comment]
May I have your `typescriptOptions` in the system config? I cannot successfully compile my application into AOT environment.

**Comment by aluanhaddad** [comment]
I feel like this should be documented somewhere. It's a question a lot of folks have.

**Comment by aluanhaddad** [comment]
It is orthogonal to building vs bundling. I would avoid AOT for other reasons (e.g.: it uses an  undocumented, anonymous programming language)

**Comment by tom10271** [comment]
Our team decided not to use SystemJs anymore and moved to Webpack. There are less pain in many aspects. I am sorry to say it but that is the truth. Error message thrown are frightening to us from SystemJs builder all the time. There are lots of people using Webpack there are lots of template to use. We only use system.js for Plunkr to share code to other developers on earth

**Comment by NithinBhargava** [comment]
Hi,

Unfortunately, code examples for ag-Grid in their official site [https://www.ag-grid.com/javascript-grid-data-update/#removing-rows] are built using SystemJS for Just in Time compilation, and SystemJS Builder for AOT bundling.
However, we are using Angular CLI build for the same in our project. Is there any way to convert or use or at least correspondingly map the code files built using SystemJS safely into Angular CLI way of building so that they can be peacefully and effortlessly used for our requirements?

Any quick help in this regard is highly appreciated as the requirement is very urgent!
Best Regards,
Nithin
