### ISSUE TITLE
File not found defined with globs > 0.15.31

### ISSUE THREAD

**Issue by zanettin** [systemjs/builder#717]
Hi

I'm facing following error after upgrading to a version >= 0.15.31. With 0.15.30 all is working well.

```

{ [Error: Error on fetch for app/**/*.js at file:///Users/development/app/**/*.js
        ENOENT: no such file or directory, open '/Users/development/app/**/*.js']
  originalErr: 
   { [Error: ENOENT: no such file or directory, open '/Users/development/app/**/*.js']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/development/app/**/*.js' } }
```

**Comment by guybedford** [comment]
Yes this was an edge case break unfortunately... see https://github.com/systemjs/builder/issues/686.

**Comment by zanettin** [comment]
thanks @guybedford for your quick reply. after changing my importSrc in bundler.bundle from `[app/**/*.js]` to `app/**/*.js` my app crashes again with an error, that rxjs/isNumeric is undefined now. it's been looked up in document root instead of node_modules:

`````
Error on fetch for rxjs/util/isNumeric at file:///Users/development/company/project/rxjs/util/isNumeric
        Loading app/subscription/components/subscription.component.subscription.js
        Loading app/subscription/subscription.module.js
        Loading app/app.module.js
        ENOENT: no such file or directory, open '/Users/development/company/project/rxjs/util/isNumeric'
````

builder config
``````
	const builder 		=	new Builder();
	const inputSrc		=	paths.app.scripts.app;
	const outputSrc		=	paths.app.scripts.compiled + 'app.js';
	const buildOptions	=	{
		sourceMaps 			:	false,
		lowResSourceMaps	:	true,
		minify				:	true,
		mangle				:	false	// todo: activate after final tests
	};

	builder
		.loadConfig(paths.root + '/system.config.js')
		.then(
			() => {

				builder
					.bundle(inputSrc, outputSrc, buildOptions)
					.then(
						() => {
							util.log(util.colors.white.bgGreen('app.js build successful'));
							cb();
						}
					)
					.catch(
						(error) => {
							util.log(util.colors.white.bgRed('app.js build failed'));
							util.log(error);
							cb(new Error(error));
						}
					)

				;

			}

		)

	;
``````

config
``````
System.config({

	// define packages
	packages: {
		'app': {
			defaultExtension	:	'js',
			meta 				: 	{
				'assets/scripts/vendors.js'	:	{ build : false},	// ignore vendors.js on build task
				'assets/scripts/bundles.js'	:	{ build : false},	// ignore bundles.js on build task
				'*.spec.js'					:	{ build : false}	// ignore all spec files on build task
			}
		}
	}
});
``````

as said before, in 0.15.30 it just worked fine

**Comment by guybedford** [comment]
This sounds like a pathing issue, which should be possible to correct ensuring there is a map value present for `rxjs`.
