### ISSUE TITLE
rollup doesn't work together with source-map-contents

### ISSUE THREAD

**Issue by sormy** [systemjs/builder#719]
systemjs-builder@0.15.32

example: https://github.com/sormy/jspm-hot-skeleton
How to reproduce: remove `--skip-rollup` from `package.json` and try to run `npm run build:dev`

Error: Mismatched sourcesContent

**Comment by asapach** [comment]
This has been fixed in #715. Pending release.

**Comment by guybedford** [comment]
Marking as a duplicate of https://github.com/systemjs/builder/issues/678.
