### ISSUE TITLE
no way to pass encodeNames = false to generate debug static build

### ISSUE THREAD

**Issue by sormy** [systemjs/builder#720]
for static builds `encodeNames` is hardcoded to be `true`

Having static development build with easily readable source code is very important to be sure that code is generated well:
- source maps with correct mapping and correct original source code (doesn't work now) 
- with not encoded module name (doesn't work now)
- not minified (works)
- not mangled, not obfuscated (?)

**Comment by guybedford** [comment]
You can pass `encodeNames: false` as a build option. If you're able to describe the issue you're having with source maps it would be great to hear further.

**Comment by sormy** [comment]
In `Builder.prototype.buildStatic()` `encodeNames` value is hardcoded, so there is no way to pass it from jspm command line or via api:

```
var compileOpts = processCompileOpts(opts, { static: true, entryPoints: entryPoints, encodeNames: true });
```

**Comment by guybedford** [comment]
`builder.buildStatic('module', { encodeNames: false })` should work here. If not then that is a bug. That second argument to `processCompileOpts` is just the defaults.

**Comment by guybedford** [comment]
Just let me know if the above isn't working for you here.

**Comment by sormy** [comment]
Yes, i will double check on this week.

**Comment by sormy** [comment]
@guybedford, you are right it works.

PS: For someone who will like to disable encoding names via jspm use: `--skip-encode-names`
