### ISSUE TITLE
systemjs-builder update breaks glob file support

### ISSUE THREAD

**Issue by oreofeolurin** [systemjs/builder#721]
systemjs-builder v0.15.31 no longer supports glob file matching. Using `app/**/*.js` breaks the build, however `app/index.js` works

```
var builder = new Builder('./', './systemjs.config.js');
    builder.bundle(['app/**/*.js'], 'public/bundles/bundle.min.js');
```

this gives ERROR:
```
Build error
{ [Error: Error on fetch for app/**/*.js at file:///c:/Users/****/Projects/example/app/**/*.js
	ENOENT: no such file or directory, open 'c:\Users\****\Projects\example\app\**\*.js']
  originalErr: 
   { [Error: ENOENT: no such file or directory, open 'c:\Users\****\Projects\example\app\**\*.js']
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'c:\\Users\\****\\Projects\\example\\app\\**\\*.js' } }
```

However systemjs-builder v0.15.30 works perfectly

**Comment by guybedford** [comment]
Try `builder.bundle('app/**/*.js', 'public/bundles/bundle.min.js')` instead here. The array input form no longer accepts globs. See also https://github.com/systemjs/builder/issues/686#issuecomment-245247300.

**Comment by oreofeolurin** [comment]
Thanks, it works
