### ISSUE TITLE
Bundle arithmetic not working with "map" config

### ISSUE THREAD

**Issue by cnshenj** [systemjs/builder#725]
Repro: https://github.com/cnshenj/sysbuilder-test
Run `npm install` in root directory, then go to `build` directory and run `node build.js`.

Error:
Unhandled rejection Error on fetch for bar.js at file:///E:/sysbuilder-test/app/bar.js
        Loading index.js
        Error: ENOENT: no such file or directory, open 'E:\sysbuilder-test\app\bar.js'
    at Error (native)

`index - bar` (this is what I prefer and expect) and `index - bar.js` hit the same error.

**Comment by cnshenj** [comment]
Just found out for those modules that will be excluded, they still need to be present to be traced. This has 2 problems:

1. Analyzing modules that will not be included, making the build process longer.
2. For modules that are not present locally, builder still tries to analyze them but will fail to calculate canonical name.

**Comment by guybedford** [comment]
Perhaps try `externals: ['bar']` here instead?

**Comment by cnshenj** [comment]
"externals" solved the problem
