### ISSUE TITLE
Error on fetch for app.module

### ISSUE THREAD

**Issue by smartm0use** [systemjs/builder#728]
Hello, i created the following Gulp file to run 2 tasks: serve and build.
The serve task works with no problems, it runs server on traspiled files that are in the `dist` folder.
Then i would like to make a `build` folder in which it should be the following structure:

    build
        scripts
            vendors.min.js // libraries loaded by index.html
            main.min.js // libraries loaded by systemjs
            app.min.js // concat of all traspiled source files
    favicon.ico
    index.html

Here is my Gulp file: http://pastebin.com/fZc4aHqe

But on "main-bundle" task i get the following error:

    Error on fetch for dist/app/app.module at file:///my-project/dist/app/app.module
    Loading dist/app/main.js
    Error: ENOENT: no such file or directory, open '/my-project/dist/app/app.module'
    at Error (native)

Do you know why i get this?

**Comment by gruppjo** [comment]
Having a similar problem

**Comment by gruppjo** [comment]
Setting the deprecated `defaultJSExtensions` flag worked for me as a quick fix: https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#defaultjsextensions

**Comment by gruppjo** [comment]
Unfortunately the resulting `bundle.js` now has as a problem with dynamic name computing:
`Uncaught TypeError: Module @angular/core not declared as a dependency.` similar to this issue https://github.com/systemjs/builder/issues/669

I'm out of ideas.

**Comment by aluanhaddad** [comment]
It should not be necessary to have 
```js
'map': {  
    app: './app',
    ...
}
```

**Comment by josephserrano15** [comment]
What's the solution?

**Comment by wawyed** [comment]
This is still an issue (SystemJs/Builder 0.16.3) workaround by @gruppjo works.
Why did you close the issue @guybedford ?
