### ISSUE TITLE
Relative paths (or map) not relative to baseURL

### ISSUE THREAD

**Issue by cnshenj** [systemjs/builder#733]
Directory structure:
```
Scripts
|--app
|   |-- main.js
|
|--lib
    |-- foo.js
```

main.js:
```
import * as foo from "foo";
......
```

Config:
```
baseURL: "http://host/Scripts/app",
defaultJSExtensions: true,
map: {
    "foo": "../lib/foo.js"
}
```

SystemJS tries to load `foo.js` from `http://host/lib/foo.js`, instead of `http://host/Scripts/app/../lib/foo.js` (which is `http://host/Scripts/lib/foo.js`). Same directory structure & config works in RequireJS, which calculate relative paths based on `baseURL`

Also tried `paths` instead of `map`, same issue.

**Comment by cnshenj** [comment]
SystemJS Builder has similar issue. If the map of path is relative, but not started with "..", it is located relative to `baseURL`, but when the map or path starts with "..", it is relative to current working directory (`cwd`).

**Comment by guybedford** [comment]
This is how resolution is defined in SystemJS `./x` means baseURI relative, while `x` means baseURL relative.

**Comment by guybedford** [comment]
There is no ability to backtrack below the baseURL because it's supposed to always be a lowest-common path.
