### ISSUE TITLE
Unhandled rejection Error on fetch for core-js/es6/symbol

### ISSUE THREAD

**Issue by Sri276286** [systemjs/builder#738]
Hi,

I have angular2 project with systemjs, systemjs builder, gulp used.

When I am trying to bundle it's throwing an error 

Unhandled rejection Error on fetch for core-js/es6/symbol at file:///C:/srikanth/Project Work/configportal/node_modules/core-js/es6/symbol
        Loading polyfills.js
        Loading main.js
        Error: ENOENT: no such file or directory, open 'C:\srikanth\Project Work\configportal\node_modules\core-js\es6\symbol'
    at Error (native)

My gulp task : 
----------------------

`gulp.task('bundle', () => {
    var builder = new Builder('target/webapp', './target/webapp/system-config.js');
    builder.bundle('main.js', 'target/webapp1/app.min.js');
})`

My main.js : 
-----------------------

```
import './polyfills.js';

import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { environment } from './environments/environment';
import { AppModule } from './app/';

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule);
```

My polyfills.js : 
----------------------------

```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
import 'core-js/es6/reflect';

import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
```

I am sure that error is because of polyfills.js but I need those polyfills to load my application in all browsers.

Help me to fix this or suggest me some alternatives.

**Comment by asapach** [comment]
You need to install `core-js` using jspm in order to use it correctly with systemjs.

**Comment by Sri276286** [comment]
I am already using systemjs-builder.

I am new to jspm.
@asapach Can you please give steps on how can I fix?

**Comment by asapach** [comment]
Here's the guide: http://jspm.io/0.17-beta-guide/index.html

**Comment by Sri276286** [comment]
Do you feel it can't be donw with systemjs and systemjs builder?

**Comment by asapach** [comment]
It can, but you'll need a lot of manual configuration to make typical CommonJS modules work correctly with SystemJS - and jspm does all the hard work for you. Give it a try.

**Comment by Sri276286** [comment]
I have done everything with systemjs and systemjs builder. If I go now for jspm, it will be a total work around. So only I was thinking. 

Can you please tell me the steps of that manual configuration.
