### ISSUE TITLE
Bundle doesn't contain outer *.html templates

### ISSUE THREAD

**Issue by BartoszBaczek** [systemjs/builder#741]
Hello, I am trying to bundle angular2 app (I am using rc4 at the moment) with systemjs-builder.

My gulp task that is responsible for bundling looks like this:

```
gulp.task('bundleApp', () => {
    let builder = new Builder('./../../', 'systemjs.devconfig.js');

    return builder.buildStatic('./../ControlsTD-TS/app/boot.js', './../../dist/app/Assets-TS/lib/bundle.js', { minify: false, mangle: false, sourceMaps: false })
    .then(function () {
      console.log('Bundle is fine');
    })
    .catch(function (err) {
      console.log('Build error');
      console.log(err);
    });
  });

```

As long as it is the only step on my build, app doesn't load neccesary htmls (there is no error during build process). The reason for that is that it doesn't bundle outer html files (the ones that are requested by component via `templateUrl: 'path/to/htmTemplate'` marker.

If all my html templates are requested via `template: '<div>sampleHtml</div>'` it works fine.

Which step in build am I missing? I want a single bundle for my app, that contains both *.js and *.html files.

**Comment by aluanhaddad** [comment]
To get that affect you should use systemjs-plugin-text. 
You can load the files as
```ts
import template from './template.html';
```

If you really want to stick with the template URL approach and you don't mind having one more file you can create a second bundle explicitly containing all of your Angular templates. I haven't tried this with Angular.

Personally I would suggest trying the import approach. You can switch back and forth with fairly trivial regular expression.

**Comment by BartoszBaczek** [comment]
Thanks for your help, I didn't expected that such a feature is not implemented in systemjs-builder, as it is recommended way of bundling angular2 apps. I'll try with regular expressions.

**Comment by aluanhaddad** [comment]
I don't know maybe it is supported, I just don't see how it would work. @guybedford is there some better simpler way to do this?

**Comment by BartoszBaczek** [comment]
I just found [gulp-angular-embed-templates](https://github.com/laxa1986/gulp-angular-embed-templates). It allows to embed templates from separate *.html file into angular2 compononent. I think it might be another solution.
