### ISSUE TITLE
SystemJs Builder is not able to exclude dependency package given in bundler expression

### ISSUE THREAD

**Issue by VivekShah1983** [systemjs/builder#742]
map:{
  package1:npm:package1@1.0.0
  npm:package1@1.0.0{
    package2:npm:package2@1.0.0
  }
}

If I have jspm based sytemjs config as shown above, and i create a bundler expression like below
package1 - package2

It throws error saying package.js is not present.

Can you please guide me how to resolve this issue

**Comment by aluanhaddad** [comment]
What sort of syntax is this?
```js
map:{
    package1: npm:package1@1.0.0
    npm:package1@1.0.0 {
    package2: npm:package2@1.0.0
}
}
```

**Comment by VivekShah1983** [comment]
It is a jspm's systemjs config file. Which is used by jspm to load packages
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "package1": "npm:package1@1.0.0",
    "npm:package1@1.0.0": {
      "package2": "npm:package2@1.0.0"
    }
  }
});
Jspm package manager looks at this config file to loads related javascript
files

Regards,
Vivek Shah

**Comment by aluanhaddad** [comment]
>It is a jspm's systemjs config file. Which is used by jspm to load packages

That one is, the one in the OP is not.

**Comment by aluanhaddad** [comment]
If you are using jspm, import a pre-configured build from the jspm and use that as opposed to systemjs-builder.
```js
const Builder = require('jspm').Builder;
const builder = new Builder();

builder.build('package1 - package2', 'bundle.js')
  .then(console.info.bind(console))
  .catch(console.error.bind(console));
```
