### ISSUE TITLE
Add watch feature

### ISSUE THREAD

**Issue by mavericken** [systemjs/builder#748]
JSPM-CLI build/bundle has a --watch feature, but it is limited to only use the JSPM-CLI.  I feel it would be really helpful if we had an easy way to do this programatically directly with SystemJS builder (with access to the options SystemJS builder API provides).   I believe I have seen lots of people mentioning that they would like this, but I couldn't find an issue specifically requesting it so I made this one.

**Comment by alexisvincent** [comment]
In the meantime, its easy to do this yourself via something like
```js
var chokidar = require('chokidar');

chokidar.watch(process.cwd()).on('all', (event, path) => {
  builder.invalidate(path);
  builder.bundle('app/index.js')
});
```

**Comment by mavericken** [comment]
@alexisvincent Is this functionally equivalent to what `jspm bundle --watch` does?  I never noticed that you could invalidate pieces and re-bundle.  If so, I think we wouldn't really need a watch feature built into systemjs builder.

**Comment by alexisvincent** [comment]
@mavericken Maybe @guybedford can confirm, but yes, I'm pretty sure it is :)

**Comment by guybedford** [comment]
Yes exactly, this project is attempting to stay lower level.
