### ISSUE TITLE
Dynamic Tracing

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#75]
Given a trace object, it would be nice to be able to run a `dynamicTrace` operation on that trace itself.

This would then search through the ASTs for any dynamic calls to `System.import('string' [, {name: 'parent'}])` and create a new trace layer for these (with duplications included).

We can then subtract the static layers from the dynamic layers to get the dynamic bundles.

**Comment by guybedford** [comment]
One could even consider a font or image load within a CSS file loaded through a plugin as part of the dynamic dependency graph. If it was able to share the same place in the graph itself, then we would have a tree covering all assets needed. This tree could then be moved around, operated on etc ala asset graph.

**Comment by guybedford** [comment]
This is now crucial to knowing what config to inject for production as it is the only configuration layer with some luck.

**Comment by Munter** [comment]
Maybe this is a bit easier now with the graph model that I just added into the mix for ordered traversal. Although it is very primitive compared to Assetgraph, mainly caused by the lack of type and relation modelling and no query engine

**Comment by guybedford** [comment]
Keeping this feature undocumented until the API is completely certain.

**Comment by guybedford** [comment]
(Released in 0.14.9)
