### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#76]
From https://github.com/jspm/jspm-cli/issues/507 - blank lines in the build output can contain unnecessary white space.

**Comment by guybedford** [comment]
@mvolkmann do you remember exactly which lines with trailing whitespace were the issue here? I just had a look through and couldn't work out what you were referring to.

**Comment by mvolkmann** [comment]
Here's a DropBox link to a generated file that contains trailing whitespace on blank lines. There are many lines, but the first ones are 25, 47, 71, 75, and 81.

https://www.dropbox.com/s/llwdzd4xafvvpcr/build.js?dl=0

**Comment by guybedford** [comment]
Sure, thanks removed in https://github.com/systemjs/builder/commit/6a9d16a76296ae4ba5b1f95071bb45e05a96a861.
