### ISSUE TITLE
Caching bundle artifacts

### ISSUE THREAD

**Issue by alexisvincent** [systemjs/builder#760]
@guybedford I wrote a wrapper around `builder.bundle(expression, options)`, to cache the actual build assets against the `${expression}#${JSON.stringify(options)}`, the result being, if the builder is run for the same expression and options, the cached asset is returned. And if the builder is already building it, it just hooks into the already bundling asset.

Code can be found [here](https://github.com/alexisvincent/systemjs-tools/blob/master/lib/index.js#L118).

I wanted to know if you wanted me to contribute this back to the builder project itself? If so, let me know and I'll construct a PR.

**Comment by guybedford** [comment]
@alexisvincent this doesn't take into account file changes though, for which the internal build cache is designed?

**Comment by alexisvincent** [comment]
It does :) See [here](https://github.com/alexisvincent/systemjs-tools/blob/master/lib/index.js#L96)

**Comment by guybedford** [comment]
@alexisvincent in systemjs builder, invalidation strings can be unnormalized module names including a wildcard. Also, it is possible to run `builder.reset` which invalidates all paths. When paths are invalidated they are still cached, just statted during the build process to check if the cache should still be used.

**Comment by guybedford** [comment]
Any PR to add new caching behaviour needs to be consistent with the existing behaviour, that's all, so the issue here is how to trace what individual load records a given expression would invalidate.

**Comment by alexisvincent** [comment]
@guybedford I'd make any `PR` consistent + take into account all edge cases. eg. ATM, this also doesn't accept tree's so it would need to do that. Although, I think the cost of determining tree equality would outstrip the benefit of the cache. 

> When paths are invalidated they are still cached, just statted during the build process to check if the cache should still be used.

Currently, when I invalidate a module, I mark the key as invalid. But I might as well delete the internal cached bundle since I don't reuse it ever. Not so sure what you were trying to get across here.

**Comment by guybedford** [comment]
@alexisvincent this doesn't look at first glance like a simple cache addition into core, so I wouldn't want you to waste time on getting consistency when you may be able to maintain something through your own wrapper project much more easily.

**Comment by alexisvincent** [comment]
Sure :) Although I don't think it would be hard to do. I'm pretty certain I don't have race conditions (but do need to double check). The main additions I think would be simply dealing with the `invalidate` cases and reset. And then hashing the tree.

It's a relatively small code addition to the core. But I also don't mind keeping this in my wrapper, it was more just to be able to share the speed improvements back into the core project for everyone else :)

**Comment by guybedford** [comment]
Thanks for suggesting, but I'd be happy to leave this out - it's effectively a top-level cache that is probably best handled by your wrapper.
