### ISSUE TITLE
Promisify code base (to free up execution thread)

### ISSUE THREAD

**Issue by alexisvincent** [systemjs/builder#761]
@guybedford Currently, the `builder` hogs the execution thread. While this is fine for traditional build operations, it makes it difficult if you want to use the `builder` within a larger system. Currently, I have to fork off another process and reinitialize the it, with comms via IPC.

To play nicer with other systems, things that were previously sync need async support. I'm happy to do this work if you sanction it :)

**Comment by asapach** [comment]
I don't think you can improve anything in this area, since builder is mostly async and uses promises all over the place (up to the point that it's hard to debug). The problem is that it's mostly CPU bound, since Babel transforms and source maps operations are sync and blocking.

**Comment by alexisvincent** [comment]
@asapach I'm positive we can at least introduce a few more opportunities for other code to gain control. Thoughts?

**Comment by asapach** [comment]
I guess you could try artificially yielding control via `setImmediate()`/`process.nextTick()` before/after potentially expensive blocking operations, but at the cost of overall build time (i.e. it might make it worse).
We need good benchmarks to make such decisions,

**Comment by alexisvincent** [comment]
@asapach This is what I mean. Just need to get control of the execution thread occasionally so small units of work can be executed.

**Comment by guybedford** [comment]
@alexisvincent a build tool is by definition a CPU-bound process. If building a web server that is also running builds, the standard practice is application separation via a child process or IPC as you say. Even just adding simple clustering to the webserver can likely get you far here as well. I really don't think this is a feature for the builder to integration.

**Comment by alexisvincent** [comment]
@guybedford Fair enough :)
