### ISSUE TITLE
0.16.0 arithmetic expressions not bringing in external dependencies

### ISSUE THREAD

**Issue by ghempton** [systemjs/builder#765]
In previous versions of bundler the following code would include all external dependencies:

```
builder.bundle('app/start.js', { browser: true });
```

However, after upgrading to `0.16.0` no vendor dependencies are included. Moreover, trying to bundle `app/**/*.js - [app/**/*.js ]` results in an empty file.

If I explicitly try and bundle some of the dependencies, they are included:

```
builder.bundle('app/start.js + react', { browser: true });
```

The setup is a relatively standard JSPM setup and the `app` package uses the register format:

```javascript
SystemJS.config({
  paths: {
   "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "app/": "modules/outreach/"
  },
  packages: {
    "app": {
      "format": "system",
      "defaultExtension": "js"
    }
  }
});
```

**Comment by guybedford** [comment]
I just put together a simple test of an `app.js` in System.register format loading react, and bundling that with `jspm bundler app.js --browser` and it seemed to work fine for me here. Perhaps you can share a replication, or instruct me how to get this example to fail?

**Comment by ghempton** [comment]
I was able to create a minimal repro here: https://github.com/ghempton/systemjs-builder-test

Either running `node build.js` or `jspm bundle app/start` produces a bundle without any of the dependencies.

What I have since realized, is that–from experimenting working through other issues–I had replaced `format: "register"` with `format: "system"` (based on the 0.20 release notes which seemed to indicate that they were equivalent). If I change the build script back to the `register` format then it does properly include the dependencies.

**Comment by guybedford** [comment]
@ghempton thanks for the clear replication. Try uninstalling and reinstalling SystemJS builder, to bump the SystemJS version and see if that helps?

**Comment by ghempton** [comment]
This seems to be fixed in the latest version from git. Thanks for jumping on these issues.

**Comment by guybedford** [comment]
Great thanks for confirming.
