### ISSUE TITLE
trace uses 'system' for the format while rollup and compile checks for 'register'

### ISSUE THREAD

**Issue by zenorbi** [systemjs/builder#779]
I'm trying to `buildStatic` a module to `format: "cjs"` and that module has `System.register` format. The builder's trace correctly identifies the module as a `register` format (https://github.com/systemjs/builder/blob/8200f4973faf93d079441cf8edbced3c260c8cc4/lib/trace.js#L576) but it turns it into `system` (presumably for consistency). However other parts of the builder (https://github.com/systemjs/builder/blob/8200f4973faf93d079441cf8edbced3c260c8cc4/lib/compile.js#L466) and (https://github.com/systemjs/builder/blob/37b73424e25e1b2871847108f333bca0431a5c34/lib/rollup.js#L257) uses the `register` name, thus not correctly detecting if the output should use the default export for the output or the whole module.

The result is that if I try to `buildStatic` this:

```js
System.register([], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var hello;
    return {
        setters: [],
        execute: function () {
            hello = "world";
            exports_1("hello", hello);
        }
    };
});
```

and require it using `require("./built-file")` the result is `undefined`.

**Comment by zenorbi** [comment]
I'm willing send in a PR but I need to know which format should be the chosen one, `system` or `register`.

**Comment by guybedford** [comment]
@zenorbi a PR here would be great. The preferred name is `system` at this point.
