### ISSUE TITLE
SystemJS loads bundle but not executes nothing

### ISSUE THREAD

**Issue by tolemac** [systemjs/builder#784]
Hi!, I'm here after two weeks experimenting a strange behivour.

I have a big app using systemjs, angular 4.x, ng2-bootstrap, rxjs, ... to getting crazy :D

The problems appear a day when the app is loading but doesn't ends the load, the scripts files were loaded but the application isn't executed, Angular doesn't start ...

I had been doing changes and I don't know why it didn't work. I tried to disable the bundles and the application works again. Some days later I get the same problem, I'm not sure about the reason but come back to use bundle, touching the system.config.js, ... I'm not sure how it did solve.

Today I have thinking about and I have decided to make a repo and make tests in order to isolate the problem.

It's a simple repo extracted from angular/quickstart. I have added a gulp file to build a bundle and when I have tryed to load it, I get the same problem. The application not start.

This is the repo: https://github.com/tolemac/systemjs-test

Instructions to reproduce: 

````shell
mkdir systemjs-test
cd systemjs-test
git clone https://github.com/tolemac/systemjs-test.git .
npm install
gulp bundle
npm start
````

**Comment by tolemac** [comment]
I have tried to put breakpoints on this code (from index.html):

````javascript
    System.import('main.js') // Breakpoint here
      .then(function (main) {
        console.log("yep", main); // Breakpoint here
      })
      .catch(function (err) {
        console.error(err); // Breakpoint here
      });
````

And debug stops on the first but it doesn't resolve the promise, neither rejects it.

**Comment by tolemac** [comment]
A curious thing:

![image](https://cloud.githubusercontent.com/assets/247167/23929795/b43d96a8-0928-11e7-9aa8-ec0dddf5b04e.png)

The scripts are being loaded as data, like ajax requests ...

**Comment by tolemac** [comment]
It seems to be a issue bundling angular bundles.
I did more test without bundle angular bundles and it works.

At the moment I close this issue.

**Comment by tolemac** [comment]
Well, after very much attempts I could probe that SystemJS don't detect the bundle format when angular bundles are inside...

I have solved the issue changing systemjs.config:

    packages: {
      'bundles/vendor.js': {
        format: "system"
      }
    }

It can see as issue from two sides, then I think I can close that issue.

**Comment by guybedford** [comment]
@tolemac can you share the source code of the bundle you were loading?

**Comment by tolemac** [comment]
Of course @guybedford.

The solution of that issue is on `bundle-format-system` branch:
https://github.com/tolemac/systemjs-test/tree/bundle-format-system

I have just uploaded the `bundles` folder, you can find there `vendor.js` bundle (I have included the minified version as `vendor.min.js` only for your info).

If you comment the package configuration for "bundles/vendor.js", at `system.config.js`,  it doesn't work, if you uncomment it works fine.

You can reproduce it clonning repo, npm install, gulp bundle and npm start.

**Comment by guybedford** [comment]
Thanks @tolemac I've added a fix for the next SystemJS release in https://github.com/systemjs/systemjs/commit/e595fbcf53f32b74a406ae9c015de70875558578.

**Comment by tolemac** [comment]
I am delighted to be able to help where necessary.

Thank you for your dedication to SystemJS.
