### ISSUE TITLE
loadConfigSync vs "globals aren’t defined in NodeJS"

### ISSUE THREAD

**Issue by arty-name** [systemjs/builder#786]
[The release notes for SystemJS 0.20 say](https://github.com/systemjs/systemjs/releases/tag/0.20.0): 

> System and SystemJS globals are no longer defined in NodeJS

With previous version I was running my unit tests in mocha, and tests contained lines like these: 

```javascript
import System from 'systemjs';
import './../../../systemjs.config';
```

The file `systemjs.config.js` contained `System.config({ … })`. 

So after upgrading to SystemJS 0.20 my unit tests in mocha stopped working, throwing a `ReferenceError: System is not defined`. Mocha runs the tests from Node.js, and System stopped being global in Node.js.

I have tried following solutions: 

1) Since not using globals makes sense, I should import System:

```javascript
import System from 'systemjs';
System.config({ … });
```

Result: mocha tests started working, but Builder stopped working with `SyntaxError: Unexpected token import`

2) I could import System with require: 

```javascript
const System = require('systemjs');
System.config({ … });
```

Result: mocha tests work, Builder doesn’t throw SyntaxError, but doesn’t get the configuration, even the `baseUrl`. 

What is the current recommended way to save SystemJS configuration in a file so that it works both for Builder and for ES6 code?

**Comment by guybedford** [comment]
Set global.System yourself if needed. The point is simply not to enforce
this on all Node js use of SystemJS anymore, to enable multi version
compatibility.

**Comment by arty-name** [comment]
Actually I have tried that and it didn’t work either:

```javascript
import System from 'systemjs';
global.System = System;
import './../../../systemjs.config';
```

Wouldn’t it be a nicer solution to support config in JSON format?

**Comment by guybedford** [comment]
@arty-name the above definitely works in CommonJS:

```javascript
global.System = require('systemjs');
require('config.js');
```

Note that in ES module semantics, dependencies are executed before their parents so that probably explains the issue. The same code would have to be written:

```javascript
import System from 'systemjs';
global.System = System;
import('system.config').then(() => {
  // ...
});
```

or even better with top-level await if and when that ever arrives:

```js
import System from 'systemjs';
global.System = System;
await import('system.config');
// ...
```
