### ISSUE TITLE
Error message "ReferenceError: define is not defined" when loading jquery running bundled

### ISSUE THREAD

**Issue by phil-hutchinson** [systemjs/builder#790]
A JavaScript error 'define is not defined" is reported when executing the following code:

	System.registerDynamic("node_modules/jquery/src/exports/amd.js", ["../core"], false, function ($__require, $__exports, $__module) {
		return (function (jQuery) {

			"use strict";

			if ("function" === "function" && true) {
				define("jquery", [], function () {
					return jQuery;
				});
			}
		}).call(this, $__require("../core"));
	});

The define function should be defined by system.src.js, which is previously loaded. When running the app unbundled, the same issue is not encountered.

This seems similar to #1 which was resolved with 0.6.1 of systemjs. I am using 0.19.27 of systemjs, and 0.16.4 of systemjs-builder.

Problem appears related to loading of http://kenwheeler.github.io/slick because removing this control eliminated the issue. It loads jquery as follows:

	(function(factory) {
		'use strict';
		if (typeof define === 'function' && define.amd) {
			define(['jquery'], factory);
		} else if (typeof exports !== 'undefined') {
			module.exports = factory(require('jquery'));
		} else {
			factory(jQuery);
		}

	}(function($) {
		
		// ...ETC...
		
	}));

Within the bundle, that code looks like this:

	(function (factory) {
		'use strict';

		if ('function' === 'function' && true) {
			System.registerDynamic('node_modules/slick-carousel/slick/slick.js', ['jquery'], false, function ($__require, $__exports, $__module) {
				if (typeof factory === 'function') {
					return factory.call(this, $__require('jquery'));
				} else {
					return factory;
				}
			});
		} else if (typeof exports !== 'undefined') {
			module.exports = factory(require('jquery'));
		} else {
			factory(jQuery);
		}
	})(function ($) {	

		// ...ETC...
		
	}));

**Comment by guybedford** [comment]
@phil-hutchinson the problem is that this is the source file for jQuery being loaded, which does contain a nested AMD define so can't be loaded directly in SystemJS. Try setting jquery to `node_modules/jquery/dist/jquery.js` rather in the map configuration.

**Comment by phil-hutchinson** [comment]
@guybedford that did the trick.. not knowing better, we had set the map to node_modules/jquery/src/jquery.js

Thanks so much for your assistance!
