### ISSUE TITLE
Bundle arithmetic

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#80]
jspm provides a bundle arithmetic syntax handled in https://github.com/jspm/jspm-cli/blob/master/lib/bundle.js#L113.

It could be worth implementing this arithmetic as a class method on the builder. `builder.bundleExpression` perhaps?

**Comment by crisptrutski** [comment]
Yeah think it makes sense to bump that functionality up, sits alongside #51.

On a related note - global builder in jspm-cli namespace, worth refactoring to make short lived instances scoped to commands, or is reuse of that code zero?

**Comment by guybedford** [comment]
Great. Can you clarify what you mean?

**Comment by crisptrutski** [comment]
Trash https://github.com/jspm/jspm-cli/blob/master/lib/bundle.js#L20 and create `Builder` instances within exported functions :mag:

**Comment by guybedford** [comment]
Ah right, the class hate! Quite happy to leave the existing structures in place :)
