### ISSUE TITLE
Error bunding 'esnext' async code

### ISSUE THREAD

**Issue by timfish** [systemjs/builder#804]
Previously I was targeting ES5 and using `aurelia-bundler`. I was not minifying as I never got it working. SystemJS was trying to transpile the minified code and stopping when it saw that transpilation was disabled.

Now targeting the latest electron which has native async/await and I can't get bundling working at all.

I'm using these settings:
```json
      "options": {
        "inject": true,
        "minify": false,
        "depCache": false,
        "rev": false,
        "sourceMaps": true,
        "sourceMapContents": true
      }
```
Top of my `config.js`
```javascript
System.config({
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "*": "dist/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  map: {
```

And the TypeScript compiler is targeting:
```json
    "target": "esnext",
    "module": "system",
``` 

SystemJS handles this all fine when running in development and loading all the files individually.

But on bundling I get the following error:
```shell
        (SystemJS) Unexpected identifier
        C:/Users/tim/Documents/some-path/dist/alarms/alarm-list.js!transpiled:45
                        async addAlarm() {
                              ^^^^^^^^
        SyntaxError: Unexpected identifier
```
This is the first `async` that the bundler hits. Does the bundler support bundling async code?

**Comment by aluanhaddad** [comment]
The issue is that you are telling TypeScript _not_ to transform your code. Additionally, you aren't using any of the SystemJS transpilation features. Tell TypeScript to downlevel your emit by specifying `"target": "es5"`

**Comment by timfish** [comment]
I want to target ESnext as chrome supports all these features. ESnext transforms the Typescript code to valid JavaScript which chrome can handle so to say it does no transforms is simply not true. As well as much improved stack traces, and smaller files, performance is significantly better. All I want the bundler to do is concat all the files together using `system` loader so why would I need it to transpile anything? I already have code which runs in latest chrome...

**Comment by aluanhaddad** [comment]
If it supports all of the features in use, then no, you do not need a lower target. SystemJS does not alter `async` functions.

**Comment by timfish** [comment]
Then why is systemjs builder throwing an error when it encounters the async keyword?

**Comment by guybedford** [comment]
@timfish that is likely due to using the SystemJS builder minification option, which still uses the older version of Uglify. There is an issue tracking this at https://github.com/systemjs/builder/issues/726 to use Babili or Uglify ES (I'm probably leaning towards Uglify ES at the moment) and contributions here would be amazing.

**Comment by timfish** [comment]
Thanks @guybedford, I'll close this and we can track it on #726 and I'll add a bug over at aurelia-bundler
