### ISSUE TITLE
SystemJS Builder Tutorial

### ISSUE THREAD

**Issue by alexdelgado** [systemjs/builder#807]
I wanted to use the systemjs builder to bundle some core scripts then dynamically call what I needed on the page but I got so frustrated with the error messages and the lack of debugging capabilities that I pretty much gave up. Other people had similar issues but I couldn't fix the problem.. So my ask is if you could make a small tutorial showing how to get this thing working properly. The closest I found was [Tour of Heros](https://github.com/smmorneau/tour-of-heroes/) but the author has since moved away from systemjs and even there I was running into some issues.

**Comment by HarelM** [comment]
Here is the error messages I get:
```
Build application error
{ [Error: Error on translate for application/application.module.js at file:///D:/Github/IsraelHikingMap/Angular4/IsraelHiking.Web/wwwroot/application/application.module.js
	document is not defined] originalErr: [ReferenceError: document is not defined] }
Build external error
[Error: SyntaxError: Unexpected token: operator (>)]
```
document is not present in file application.module.js and I couldn't understand what I did wrong.
The second error message appears only when trying to minify.
I'm trying to pack both "vendor" and "application" into two files.
Project can be found here if anyone is interested in explaining what I should do with these uninformative error messages...
https://github.com/IsraelHikingMap/Site/
angular4 brnach.

**Comment by Red-3** [comment]
Having similar issues. One of the problems I see is that systemjs tries to be all the things so it's really hard to find out specific things. My challenge is to get systemjs to load an app from bundled files. It  works when the files are unminified but I don't know how to get the bundles in the right format so that the main module is recognized when it's not contained in a main.js but in a bundle.min.js

**Comment by HarelM** [comment]
The above branch is no longer relevant. I moved away from SystemJS.
