### ISSUE TITLE
[HELP] Generate sourcemaps with Typescript and save it with SystemJS

### ISSUE THREAD

**Issue by Sweet-Bob** [systemjs/builder#808]
Hi,

I generate inlineSourcemaps with typescript, i.e sourcemap comment placed in file, and looks like:
//# sourceMappingURL=data:applicat....
I try various combinations of systemjs options: sourceMaps, sourceMapContents, lowResSourceMaps. But all sourcemaps deleted.

Compile typescript & bundle systemjs separate, i.e systemjs get js files on input (which contain sourcemap tags)

Thank you for any help!

**Comment by guybedford** [comment]
Does this happen when using SystemJS builder to generate the bundle here, or is this for direct loading with SystemJS dynamically? There may well be a SystemJS builder issue linked to this already.

**Comment by Sweet-Bob** [comment]
When use systemjs builder, for bundle.

**Comment by guybedford** [comment]
Are you definitely running systemjs builder with the source maps option enabled here?

**Comment by Sweet-Bob** [comment]
Yes, for now i created repo, please look at: [systemjs-sourcemap-test](https://github.com/Sweet-Bob/systemjs-sourcemap-test)

**Comment by aluanhaddad** [comment]
@Sweet-Bob you have a typo
The setting is `sourceMaps` not `sourceMap`
See https://github.com/systemjs/builder#sourcemap-options

**Comment by Sweet-Bob** [comment]
@aluanhaddad ouch ;) thank you!
@guybedford sorry for my inattention, thank you!
