### ISSUE TITLE
build error: Angular 4 on SystemJS with systemjs-builder

### ISSUE THREAD

**Issue by leduong** [systemjs/builder#809]
Dear SystemJS team!

2 days ago, it's work and build test on Travis
![screenshot from 2017-05-26 14-41-25](https://cloud.githubusercontent.com/assets/1042749/26486005/84955c0e-4223-11e7-9463-417b6cec048c.png)

https://travis-ci.org/AngularVN/angular4-seed/jobs/235774520

Now, It's have a major issue, help me
![screenshot from 2017-05-26 14-39-14](https://cloud.githubusercontent.com/assets/1042749/26486011/8899b58e-4223-11e7-8355-1eaa50a6953b.png)

I'm try again with my laptop, it's fail. Maybe it's problem with typescript compiler

ubuntu 16.04 x64
node 6.10.3
npm 3.10.10

https://stackoverflow.com/questions/44196321/build-error-angular-4-on-systemjs-with-systemjs-builder

**Comment by Sweet-Bob** [comment]
I think this is problem of dependencies, someone was updated and crashed everything

**Comment by aluanhaddad** [comment]
These errors are coming from `tsc` the TypeScript compiler. They are not SystemJS related errors.

Regardless, you need to run
```bash
$ typings uninstall --save node
```
and
```bash
$ typings uninstall --save core-js
```

**Comment by leduong** [comment]
Thanks, it's work again
