### ISSUE TITLE
Is there something smaller than System.js when all modules are bundled?

### ISSUE THREAD

**Issue by far-blue** [systemjs/builder#810]
System.js covers all the bases with modules and bundles of modules, pre-loaded and load-on-demand. SFX bundles are exactly the opposite and have everything together in a single statically loaded blob. But there should be something in the middle to cover the common situation of a lib bundle and an app bundle, both loaded on page load and without dynamic loading. More and more sites have multiple Single Page Apps that share a common set of frameworks and then have page-specific code and in this case we really only need the functionality of the SFX-Core loader (3kb) rather than System.js (60kb) but sfx-core is written to wrap all included modules so can't be used with multiple bundles.

Is there something like sfx-core (or a way to use sfx-core) that supports multiple bundles? I wouldn't mind if it was a little bigger than 3kb but System.js is almost as big as Bluebird and bigger than Knockout!

**Comment by far-blue** [comment]
I've put together a suggested approach that appears to work but I've only tested the basics. Comments appreciated on where it may not behave as expected:
https://gist.github.com/far-blue/1db4205adf1cbf18f732a6f2cf2e8b7e

**Comment by guybedford** [comment]
There's a reduced 6KB production loader available in the SystemJS dist/
folder which is designed for this purpose.

**Comment by far-blue** [comment]
I can't find anything that looks right in the dist folder. There's a systemjs-loader.js file in the src folder that's 6k, and another called systemjs-production-loader which is a bit bigger but I can't really tell what they do, what they are for, how they differ or how to use them. The system-production one looks like it could be the src for the 17k minified system-production.js in the dist folder. Is it a drop-in replacement for system.js for when everything is already bundled?

**Comment by far-blue** [comment]
Also, system-production.js in the dist folder appears to be new to the 0.20 releases - would it be compatible with the 0.19 release? JSPM appears to still be on 0.19 release.

**Comment by SerkanSipahi** [comment]
@far-blue 
1.) if you use (well tested in large project) jspm@0.17.0-beta.41 you get systemjs@0.20
2.) Its not really compatible! Follow this => https://github.com/systemjs/systemjs/releases/tag/0.20.0 =>  if you can upgrade to systemjs@0.20

**Comment by far-blue** [comment]
I've not been able to get jspm 0.17.0-beta.41 to work for me I'm afraid. I've logged an issue with jspm :)
