### ISSUE TITLE
Install through npm fails, throws error at "{"shasum":"ac6a8ebbcf"

### ISSUE THREAD

**Issue by nombrekeff** [systemjs/builder#833]
When trying to install with npm `npm install systemjs-builder --save` it throws an error,
yesterday it worked without a problem. Installing from **windows 10**

npm version: **5.3.0**
node version: **v6.11.2**

Error:
```
npm install systemjs-builder --save
npm ERR! Unexpected end of input at 1:30497
npm ERR! ,"text-table":"~0.2.0"},"directories":{},"dist":{"shasum":"ac6a8ebbcf
npm ERR! 
```

**Comment by guybedford** [comment]
This sounds like an npm error. I've tried this on Windows and it seems to be working fine. Perhaps try running `npm cache clear` and installing again. Let me know if you are still seeing this though.

**Comment by amenadiel** [comment]
I've been having problems since last monday when I updated npm. Mostly about "expected sha1-rubbish and instead got sha-512-rubbish". And I'm referring to projects totally unrelated to JSPM.

**Comment by guybedford** [comment]
Glad to hear I'm not on the hook for once :)

**Comment by nombrekeff** [comment]
I've tried again today, without changing nor updating anything, and it seems to be working as expected now. 
I'm going to test a couple of thing and if anything fails I will continue this issue.
Thanks by the way!

**Comment by amenadiel** [comment]
@nombrekeff  if it's solved, please close this issue.

**Comment by nombrekeff** [comment]
Sorry I forgot it was open.
It seems like it is solved. So I will close it.
Thanks!

**Comment by nombrekeff** [comment]
Okey, I think its solved now.
Thanks!
