### ISSUE TITLE
Running the builder in the browser?

### ISSUE THREAD

**Issue by PeterKnight** [systemjs/builder#841]
I was wondering if it is feasible to compile esm modules in the browser and send the compiled output to say the clipboard or a server (not running node)? I'm thinking of ways to create a codepen/jsfiddle like experience where users could develop in a sandbox without setting up node.js locally and configuring config&build files.

**Comment by guybedford** [comment]
This isn't currently supported, but certainly could be.

If you do take a stab at it I'd be happy to accept any PRs.

**Comment by PeterKnight** [comment]
Thanks Guy, might take a stab at this later in the year. Also looked at serverless functions as an alternative to requiring local tooling & configuration.
