### ISSUE TITLE
Builder not transpililng es6?

### ISSUE THREAD

**Issue by gnimmelf** [systemjs/builder#85]
Hi, first attempt at the builder, so maybe very stupid mistake, but it seems that my module's code is not transpiled from es6 syntax to common-js syntax. (The code works fine just using `System.import('app')`.)

gulpfile.js + systemjs-builder:
```
var path = require('path')
var gulp = require('gulp')
var shell = require('shelljs')
var Builder = require('systemjs-builder');
var builder = new Builder();

var output = 'dist/app-bundle.js'
shell.mkdir('-p', path.dirname(output))

gulp.task('build', function() {    
    builder.reset()
    builder.loadConfig('./src/config.js').then(function() {  

        builder.config({ 
            baseURL: '.' 
        });

        return builder.buildSFX('app', output)
    });
})
```

Loading bundle with
```
<script src="src/jspm_packages/system.js"></script>
<script src="src/config.js"></script>     
<script src="dist/app-bundle.js"></script>   
```

Browser console gives:
```
Uncaught SyntaxError: Unexpected reserved word
app-bundle.js:1382
```

app-bundle.js#L1382-1400
```
import m from 'npm:mithril@0.1.30';
export default {
  controller: function() {
    var name = m.prop("Apex");
    return {name: name};
  },
  view: function(ctrl) {
    return [m("h1", ctrl.name() + " says hi!")];
  }
};

System.register("npm:mithril@0.1.30", ["npm:mithril@0.1.30/mithril"], true, function(require, exports, module) {
  var global = System.global,
      __define = global.define;
  global.define = undefined;
  module.exports = require("npm:mithril@0.1.30/mithril");
  global.define = __define;
  return module.exports;
});
```

**Comment by silenceisgolden** [comment]
can confirm, 0.9.0

**Comment by silenceisgolden** [comment]
also can confirm that this happens even with `builder.reset()` removed.

**Comment by guybedford** [comment]
Thanks - can you share a repo I can clone to try this?

**Comment by guybedford** [comment]
Do you have a `transpiler` value set in your config perhaps?

**Comment by silenceisgolden** [comment]
@guybedford using babel, transpiler set to 6to5.

**Comment by silenceisgolden** [comment]
@guybedford you can clone this repo https://github.com/silenceisgolden/builder-probs

**Comment by gnimmelf** [comment]
Yup, 0.9.0 here too, with 6to5.

**Comment by crisptrutski** [comment]
@guybedford cause is here https://github.com/systemjs/builder/blob/1e46a3d07fa0da46ff647c78a6822a95787bebc1/compilers/es6.js#L37

@gnimmelf @silenceisgolden  Need to change transpiler option to `"babel"`.

1. Should probably check for either string to make lives easier.
2. Should display deprecation warning for for '6to5' option.
3. Should warn on unrecognised transpiler options.

**Comment by gnimmelf** [comment]
Oki, building now works, no plaintext `import` statements in the bundle.

Just to recap, if other newbies are in distress:

Builder is now:
```
builder.reset()
builder.loadConfig('./config.js').then(function() {  

    builder.config({ 
        transpiler: 'babel',
        baseURL: '.' 
    });

    return builder.buildSFX('./src/app', output)
});
```

Next then, when not using the bundle, this was the kickoff in my `index.html`:
```
<script>
    System.import('src/app').catch(console.error.bind(console));
</script>
```

Replacing that with the bundle:
```
<script src="/dist/app-bundle.js"></script>
```

All good!

**Comment by guybedford** [comment]
Great glad that sorts it, will make this easier.
