### ISSUE TITLE
injecting dynamic imports

### ISSUE THREAD

**Issue by jschr** [systemjs/builder#87]
I've been trying to tackle porting a project that used requirejs over to systemjs and being new to systemjs I ran into a snag.

Long story short, I'm trying to use the systemjs builder to dynamically create a build file that will inject imports into the main module based on a user request . I was able to accomplish this by hooking into the [onBuildRead](https://github.com/jrburke/r.js/blob/master/build/example.build.js#L544) function in requirejs where my main module file looked something like:

```js
var dep1 = require('dep1')
// other dependencies injected here by build
var otherDeps = {{ depsInjectedByServer }};

// to stuff with otherDeps and otherDeps to sub modules
```

Is there anyway I can accomplish this with systemjs?

I looked at the systemjs plugin api but I don't think it would suffice as I would need to pass along the user parameters to the translate.

Hopefully I explained what I'm doing clear enough. 

Thanks.

**Comment by guybedford** [comment]
It would help if you could clarify the use case a little more here - you're injecting requires into the main entry point based on data in the main entry point?

**Comment by jschr** [comment]
Sure no problem. The project I'm trying to move over to systemjs from requirejs allows users to build little widgets that are composed from many React components. The end product I'm trying to create is a single bundled js file that the user can download. Because I don't want to bundle every single React component in the library I want to be able to dynamically create a build file with only the components selected by the user.

To accomplish this in requirejs, the main entry point was injected with all the requires of the components that were needed and then bundled everything together to produce the single js script.

I'm just experimenting with SystemJS so I'd understand if this isn't in the current scope of the project. However I do enjoy using it :) 

Thanks again.

**Comment by guybedford** [comment]
Ah right I think I see what you mean - you should be able to use the builder arithmetic to generate custom bundles containing what you need. See https://github.com/systemjs/builder#example---exclusion, you could effectively do the same for addition of trees.

Alternatively you could generate the initial main entry point before running builder, containing the imports you need and then run that through the builder perhaps.

**Comment by jschr** [comment]
Appreciate the input. Generating the main entry point before running the builder sounds ideal. Is there a way to pass the builder the file contents as a string rather then a file path for the inital main entry point? Would a plugin be the best way to accomplish that?

**Comment by guybedford** [comment]
@jschr do you want to generate the main entry point because you want all the scripts loaded upfront in the app? How come you don't need this functionality in development though?

**Comment by jschr** [comment]
The functionality is part of the process so it would be needed in dev or production. The end product is allowing users to essentially create there own dashboard. The workflow for the user is:

1. Select some components to import. These are UI components so I plan to generate a live preview. I was thinking I would on-demand load each component via System.import because there could be hundreds of components to choose from.

2. When the user is happy, they will "publish" there dashboard, at which point I will bundle all of the components they selected together into a single script file. This script file could then be downloaded or hosted but the main idea is it should only contain the components needed to render their custom dashboard.

Appreciate you taking the time to help, sorry if this is a bit out of scope!

**Comment by jschr** [comment]
After looking into advanced builder options, it does look like I can modify the the trace tree to either inject the imports directly into the source of the main file before calling buildTree so I might go with that approach. Thanks for your help and your work on this library.
