### ISSUE TITLE
Building in plugins

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#89]
There's a distinction between plugins that remain in production and those that don't.

Currently - `build = false` as an export of the plugin itself means that the plugin does not support build compilation and will be included in production itself.

We should adjust it so that when this option is set, we include the plugin trace in the build.

**Comment by whitecolor** [comment]
So user should be able to have:

1) While developemnt one version of the plugin (that include some special dev features, like for example live reload for the module)
2) While build use another version (include some special bundling code or something)
3) In prodution build I want to include third version (that have only production code)

Is it possible now?

**Comment by guybedford** [comment]
No - this issue is only tracking whether or not to build the plugin itself into the app.

The issues you're talking about can be classed under conditional loading features.

**Comment by guybedford** [comment]
Implemented.
