### ISSUE TITLE
SyntaxError with buildSFX

### ISSUE THREAD

**Issue by thesbros** [systemjs/builder#90]
When I run this code:
```
builder.reset();
builder.loadConfig(paths.root + "public/config.js")
.then(function()
{
	builder.config({baseURL: "app/"});
	return builder.buildSFX("app/index", paths.output + "scripts/build.js", {
		minify: prod,
		sourceMaps: !prod
	});
})
.then(function()
{
	cb();
})
.catch(function(err)
{
	console.log(err);
	cb();
});
```
I get the error:
```[SyntaxError: Error loading "app/index" at file:/Users/USER/PROJECT/app/scripts/index.js
Evaluating app/index
	Unexpected token <]```

Which is caused by having a JSX element in index.js: `React.render(<App />, app[0]);`

`transpiler` is set to `babel` though, and Babel has JSX support so it should be compiling. Running `babel app/scripts/index.js` compiles fine, so it must be a problem with `systemjs-builder` or my configuration.
If I remove the JSX, all other ES6 transpiles correctly.

**Comment by u9520107** [comment]
I am facing this issue as well, builder.trace dies when trying to read files with jsx element syntax.

**Comment by thesbros** [comment]
Any update on this? Should I just run my JS through babel and then into builder for now?

**Comment by guybedford** [comment]
Yes rather use a two-phase compilation process if possible.

**Comment by thesbros** [comment]
If anyone's still having this issue, I fixed it by adding the following to my config.js:
```js
System.config({
  [...]
  "babelOptions": {
    "optional": [
      [...] 
      // fixes JSX compilation
      "reactCompat"
    ]
  },
});
```

**Comment by thesbros** [comment]
Actually that does not work, it uses the pre-0.12 React syntax.
Could you reopen this? It's still a problem.

**Comment by james-s-turner** [comment]
+1 for reopen. I see the same thing using builder.build() as well.

**Comment by guybedford** [comment]
@james-s-turner can you confirm that `builder.loader.transpiler == 'babel'` here?

**Comment by james-s-turner** [comment]
@guybedford My build file is here: https://github.com/james-s-turner/flummox-es6-spike/blob/master/build.js

**Comment by guybedford** [comment]
@james-s-turner check that the file you are loading is being correctly detected as an ES6 module via the presence of module syntax (`import` or `export`). Standard scripts are not by default transpiled in SystemJS.

**Comment by james-s-turner** [comment]
@guybedford  Got it working, my bad . Root problem was that my app is using old systemjs 0.16.11. So downgraded to systemjs-builder 0.10.6 to match and all works nicely. Thanks anyway.
