### ISSUE TITLE
Make tests resilient

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#93]

**Comment by guybedford** [comment]
Ideally we could have static tests that can't change in time - testing by decoding the mappings themselves and being sure they align. Perhaps that is too much to ask though.

**Comment by guybedford** [comment]
Let's also track the "reset expectations" port here, closing https://github.com/systemjs/builder/pull/84.

**Comment by crisptrutski** [comment]
The "automatically update expectations" flag is in. Will look at thinning to at most one "explicit" output test. Like having a fine-tooth comb available to catch things we haven't thought about, for example caught a change in Traceur ASTs that affected performance, even if we move it out of the "npm test" family.

**Comment by guybedford** [comment]
Can you explain how the "automatically update expectations" flag is to be used? Could we add a `scripts` option to the package.json called `npm run test:update-expectations` or something like that?

**Comment by crisptrutski** [comment]
Done
