### ISSUE TITLE
Share output object with bundle hook to allow memory separate css builds

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#94]
Goes with https://github.com/systemjs/plugin-css/issues/15.

**Comment by whitecolor** [comment]
Should be considered that this also referres to other types of bundles, beside css.

**Comment by guybedford** [comment]
The alternative here is simply to allow `opts.styleOutput` as an input object which can be written to by reference.

**Comment by whitecolor** [comment]
@guybedford is this working already `opts.styleOutput`?

**Comment by guybedford** [comment]
@whitecolor I'll be working on this in the CSS plugin after the next jspm release.
