### ISSUE TITLE
Windows testing

### ISSUE THREAD

**Issue by guybedford** [systemjs/builder#95]
@OClement had a Windows issue where paths are being built in of the following form:

`"npm:react-router@0.12.4/C:\Users\O\.jspm\packages\npm\react-router/index"`.

I have no idea how the `.jspm` folder is getting in here.

It would be good to do some testing on Windows to see if we can replicate this build issue at all.

@OClement if you can provide a simple repo that replicates this on Windows that would help a lot too.

**Comment by OClement** [comment]
Will try to recreate one as soon as I can
Thanks

**Comment by richardhallett** [comment]
Hello, coincidentally I stumbled upon this exact problem @OClement is having.

I've created a quick public repo that should hopefully explain, along with reproducible steps in the readme, it is pretty easy to recreate on windows from scratch.

https://github.com/richardhallett/systemjs-issue95

**Comment by OClement** [comment]
@guybedford I've moved my repo to Github and made it public
This is the actual code that fails on Win for me:

https://github.com/OClement/CKWEB_2015

**Comment by guybedford** [comment]
Thanks. Ok sounds like this is more critical then - will do some windows testing asap.

**Comment by guybedford** [comment]
This is fixed now in jspm-npm 0.20.3 (https://github.com/jspm/npm/commit/59cb342820ee41759b712c416ae71531d7e73274). If you run an npm update of jspm it should update to use this version of the endpoint. Do let me know if you spot any other windows issues at all!
