### ISSUE TITLE
"System.baseURL = ..." style configuration doesn't work

### ISSUE THREAD

**Issue by also** [systemjs/builder#98]
Much of the SystemJS [configuration documentation](https://github.com/ModuleLoader/es6-module-loader/wiki/Configuring-the-Loader) suggests configuring system like

```javascript
System.baseURL = '/js/lib/';
System.paths['jquery'] = '//code.jquery.com/jquery-1.10.2.min.js';
```

It isn't possible to use this same configuration in the file passed to `builder.loadConfig()`, because the `System` object isn't a loader, just a shim with a `.config()` method.

This means that after following the SystemJS documentation, you have to rewrite your configuration to work with the builder.

**Comment by guybedford** [comment]
Great point - yes we should support these configuration styles too.

**Comment by guybedford** [comment]
Ok this has been resolved. Thanks for posting.
